mobilecoinfoundation/mobilecoin

mob
This might help the user experience in issues like
https://github.com/mobilecoinofficial/mobilecoin/issues/6
=> Nicer mob behavior (check for docker being installed)

BUILD.md, crypto/box/README.md
This is what I get for not rendering them locally before making PR
=> Fixup markdown rendering in various readme's

crypto/box/README.md
Thanks to @joekottke for suggestion to use markdown footnotes in
the earlier PR comments
=> Improve readme

consensus/service/BUILD.md, consensus/service/README.md
Fixes MC-1311.
Some params are missing from the example consensus command.
=> Update command with missing params

consensus/service/src/bin/main.rs
Signed-off-by: Brian Anderson <andersrb@gmail.com>
=> consensus-service: Fix typo

consensus/service/src/bin/main.rs
Signed-off-by: Brian Anderson <andersrb@gmail.com>
=> consensus-service: Remove some unnecessary clones

jenkins/Jenkinsfile, jenkins/build-pod.yaml, jenkins/packaging-pod.yaml
- Builds cargo binaries
- Sets up sample ledger data for testing
- Initial ground work for adding containers and registry pushes
TODO:
- Actual container assembly
- Kubernetes deployment manifests for a 5 node cluster
=> Initial addition of Jenkins continuous deployment

mcbuild/enclave/src/lib.rs
This ensures the `lib<enclave>.signed.so` artifact ends up being copied to the `target/<profile>` dir if one is created by the build (tested with privkey and generated privkey). This will
=> MC-1333 Ensure the signed enclave ends up in target profile dir #close

mobilecoind/src/bin/main.rs
This PR should solve a bug in `mobilecoind` where it would attempt to download the ledger, fail, and leave an empty ledger db file. On a consecutive run it would then try to open this empty ledger and panic instead of trying to re-bootstrap it.
=> change mobilecoind to try and bootstrap ledger if it exists but empty

jenkins/Jenkinsfile, ops/Dockerfile-bootstrap-tools, ops/Dockerfile-consensus, ops/Dockerfile-mobilecoind, ops/entrypoints/consensus_validator.sh, ops/entrypoints/mobilecoind.sh
- Add Dockerfiles and assembly for mobilecoind, consensus node, and bootstrap-tools
=> Add container builds to Jenkinsfile

mcbuild/enclave/src/lib.rs
And commentary about why they are needed / what they do
=> Add enclave security linker flags to the enclave linker step

consensus/api/proto/blockchain.proto, consensus/api/src/conversions.rs, mcconnection/src/thick.rs, peers/src/connection.rs, transaction/core/src/blockchain/block.rs, transaction/core/src/blockchain/block_contents.rs, transaction/core/src/blockchain/block_id.rs
This is part of the groundwork towards moving LedgerDB contents from Serde to Prost.
=> make Block, BlockID, BlockContentsHash derive Message

transaction/core/src/membership_proofs/mod.rs
=> Fixes a merge conflict

consensus/enclave/measurement/build.rs
This will need to get merged into master, and then to the release branch to fix the deployment.
=> MC-1388 Fix build script to output libconsensus-enclave.signed.so as before.

tools/local-network/README.md, tools/local-network/bootstrap.sh, tools/local-network/local-network.py, tools/local-network/mobilecoind.sh
Also adds a bash header and reduces the size of the bootstrap
=> MC-1229 Updates local network README

mobilecoind/clients/release-packages/v0.2.0/mobilecoin-testnet.sh
This is the startup script that goes into the linux tarball for mobilecoin
=> Add versioned startup script to repo

.circleci/config.yml
Add `cargo doc` generation and include them as a CircleCI [artifact](https://app.circleci.com/pipelines/github/mobilecoinofficial/mobilecoin/679/workflows/8852d130-545b-4524-ab86-c34536d0fb2e/jobs/1191/artifacts).
=> add a build docs step

jenkins/Jenkinsfile
Fixing Python stub generation to reflect the new protobuf organization introduced in #120
=> Update wallet test to reflect new proto locations

mobilecoind/clients/python/blockchain_explorer.py
- Add CLI params for listen port, mobilecoind host and port
- Removes the need for using `flusk run` but that will still work as previously configured
=> Update blockchain_explorer.py to be configurable

testnet-client/src/main.rs
If attestation fails, it can take several seconds for mobilecoind to return from a call `get_network_status()`.
This PR adds a progress indicator to let the user know that the testnet client is busy.
A typical error in the mobilecoind log that causes this looks like:
> 2020-05-08 19:50:20.776795054 UTC ERRO Failed getting last block from mc://node1.test.mobilecoin.com:443/: Operation { error: Attestation(Grpc(RpcFailure(RpcStatus { status: 1-CANCELLED, details: Some("Received http2 header with status:5...
=> add a progress indicator for network status checks

deploy/00-node-grpc-ingress.yaml, deploy/01-node-certificates.yaml
Soundtrack of this PR: [Corporeal by Broadcast](https://www.youtube.com/watch?v=kr2473XpG98)
This update is required for a system-upgrade of `cert-manager` in our CD system.
Updates the Kubernetes CRD API references for `cert-manager`
* None
=> Update cert-manager resource references

Cargo.lock, Cargo.toml, api/src/conversions.rs, mobilecoind-json/Cargo.toml, mobilecoind-json/README.md, mobilecoind-json/src/main.rs
Soundtrack of this PR: [Tell me when to go](https://www.youtube.com/watch?v=2GZbaXdK8Js)
Many workflows involve REST APIs, we'd like to allow our users to not have to learn gRPC. This provides a wrapper around mobilecoind exposing functionality with JSON.
* An initial implementation using Rocket that creates a web server that calls functions in mobilecoind
This does not expose all mobilecoind functionality but is intended as an intended as providing the minimum viable for our users to start integrating into their products.
=> JSON gateway for mobilecoind

consensus/scp/src/slot.rs
Previously, SCP Ballot values were sorted by transaction hash. Now, Ballot values are sorted by the ordering defined by WellformedTxContext, which sorts by fee, and then by transaction hash.
Many of the changes here relate to replacing BTreeSet with HashSet. In the past, a lot of SCP code used sorted sets of TxHash because that matched the ballot ordering. That's no longer the case, so this PR prefers the faster and simpler HashSet data structure.
This was slam tested and performance seems unchanged.
=> 984 sort transactions by fee

mobilecoind-json/src/main.rs
Soundtrack of this PR: [Together](https://www.youtube.com/watch?v=vnfGni4_RlI)
We had requests from people interested in integrating with our REST API for features that show general information about the ledger.
```
$ curl http://localhost:9090/ledger-info
{"block_count":"2142","txo_count":"16425"}
$ curl http://localhost:9090/block-info/235
{"key_image_count":"1","txo_count":"3"}
```
* This was requested functionality, there is potentially more ledger inspection work to be added.
=> Adds functions to REST API for querying ledger stats

consensus/scp/tests/mock_network/mod.rs, consensus/scp/tests/test_cyclic_networks.rs, consensus/scp/tests/test_mesh_networks.rs
Soundtrack of this PR: [Random](https://www.youtube.com/watch?v=K4dx42YzQCE)
This is an incremental PR in the direction of #210.
* adds a struct to store test parameters
* splits out test running logic
* next step is to add in the metamesh network
=> use a struct for SCP test options

LICENSE
=> Includes license for tests

mobilecoind/clients/release-packages/v0.4.0/Dockerfile, mobilecoind/clients/release-packages/v0.4.0/mobilecoin-testnet.sh
Soundtrack of this PR: [Good Morning](https://www.youtube.com/watch?v=J0j3-tmQLjg)
Make sure that scripts we use for distribution and Docker packaging are tracked
* Adds a Dockerfile
* Adds the launch script for testnet v0.4.0
=> Updated script for 0.4.0 and Dockerfile

api/src/conversions.rs
Soundtrack of this PR: https://www.youtube.com/watch?v=nJDpXPVFRUo
Converts between `CompressedRistrettoPublic` and `external::CompressedRistretto`
=> Add some missing conversions for external::CompressedRistretto

Cargo.lock, Cargo.toml
Prost have merged our changes to their repo, but have not yet released a new version. This PR switches us from a private fork we had to the main prost repo.
Grabbing prost from the official repo.
=> switch to original prost repo

consensus/enclave/trusted/Cargo.lock, consensus/enclave/trusted/Cargo.toml
Followup on #249 - I neglected to make the change in the enclave Cargo.toml
Switch to using upstream prost.
=> use main prost repo

ledger/sync/src/ledger_sync_service.rs, sgx/backtrace/src/lib.rs, sgx/backtrace/src/tracing.rs
Soundtrack of this PR: [Human League - Seconds](https://www.youtube.com/watch?v=YshmX_M307M)
The SGX backtrace code needed updating for the new rust.
* Pre-requisite to updating internal code with new rust.
=> FOG-63 Fix asm! usage in backtrace, minor doc update.

watcher/src/watcher_db.rs
Soundtrack of this PR: [My Favorite Mistake](https://www.youtube.com/watch?v=AmIlUKo4dQc)
Ended up in a situation where the previous PR #271 passed CI, built and tested locally, but then when merged to master, failed CI and deployment.
* Fixes build error and cleans up lingering resolved FIXME
=> Fix watcher build

jenkins/Jenkinsfile, jenkins/packaging-pod.yaml
Soundtrack of this PR: [Sun by Caribou](https://www.youtube.com/watch?v=euS2SlC68q8)
Often times, Docker Hub fails with an EOF upon submission, or its possible that Kaniko doesn't build a layer correctly.  Either way, there needs to be a cleanup and retry upon failure.  This change addresses that.
* 3 retry attempts for each Kaniko build/push
=> Update kaniko retries

mobilecoind/src/service.rs, mobilecoind/src/utxo_store.rs
@rjwalters discovered a bug that prevented a re-adding a previously-added monitor in mobilecoind after the monitor has been removed. Investigation revealed that the bug only occurs when a key image related to the monitor has been spent.
* Bug-fix for the add-remove-add monitor scenario
* A unit test that was initially failing and now passing.
I have also validated this works with a simple test script:
```
from mob_client import mob_client
mobilecoin = mob_client("cvm:4444", ssl=False)
sender_account_key = mobilecoin.get_account_key(bytes([2,154,47,57,69,168,246,187,31,181,177,26,84,40,58,64,82,109,40,35,89,36,57,5,241,163,13,184,42,158,89,124]))
sender_monitor_id = mobilecoin.add_monitor(sender_account_key, first_subaddress=0, num_subaddresses=1)
print('added')
input()
balance = …
```
=> mobilecoind: fix bug in monitor removal

mobilecoind-json/README.md, mobilecoind-json/src/main.rs
We added additional functionality to both mobilecoind and mobilecoind-json. This updates the README to describe usage.
* Adds more sample cURL commands to README
=> Update README for mobilecoind-json

consensus/service/README.md, mobilecoind/README.md
Documentation links are broken.
Fixes to documentation links.
None.
=> Fix doc links to generate-sample-ledger

consensus/service/README.md
List rendering is incorrect.
This fixes the numbering of the list such that the next item continues at 8 instead of restarting at 1.
None
=> Fix list markdown in consensus/service/README.md

tools/local-network/local_network.py
It's nice to have a local `mobilecoind` running as part of the local network test script, and it is currently a requirement to have it running for some internal development.
* local network script changed to run a mobilecoind instance
=> add mobilecoind to local network script

account-keys/src/account_keys.rs, account-keys/src/domain_separators.rs, account-keys/src/lib.rs
This is needed by libmobilecoin
Fixes up previous commit
=> Export needed constant from account-keys lib

util/keyfile/src/json_format.rs
=> Fixup code comments in keyfile json_format module per discussion

start-testnet-client.sh
Soundtrack of this PR: [Cemetery Gates](https://www.youtube.com/watch?v=dfXqxjMkyQ4)
The previous version of this script was hard-coded to a specific CSS (sigstruct) file. This PR changes that and uses the contents of production.json to determine the URL of the consensus-enclave.css
* Updates to `start-testnet-client.sh` script
=> Update start-testnet-client CSS download

README.md
=> un-indent watcher node description paragraph

consensus/service/src/byzantine_ledger.rs
Soundtrack of this PR: [Get Free](https://www.youtube.com/watch?v=OI3shBXlqsw)
Refactors send_scp_msg to be  Fn(Msg<TxHash>) instead of  Fn(Option<Msg<TxHash>>). Same functionality, but I think this feels more natural.
=> send_scp_message takes a Msg instead of Option<Msg>

attest/core/src/ias/verify.rs
This PR fixes a serde incompatibility introduced in the fix for MC-1719.
* Reverts the structural changes to `VerificationSignature`.
* Manually implements `prost::Message` for `VerificationSignature`.
* Use `prost` for this serialization instead of `serde`.
=> Fix wire format issue introduced in earlier PR

Cargo.lock, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, transaction/core/src/constants.rs, transaction/core/src/tx.rs, transaction/core/src/validation/validate.rs, transaction/core/test-utils/src/lib.rs, transaction/std/src/transaction_builder.rs
Soundtrack of this PR: [She Blinded Me with Science](https://www.youtube.com/watch?v=V83JR2IoI8k)
More accurate naming and increase minimum fee from 10 pMOB to 10 mMOB. 
* Change BASE_FEE -> MINIMUM_FEE
* Set minimum to 10mMOB
[MC-1733](https://mobilecoin.atlassian.net/browse/MC-1733)
=> BASE_FEE -> MINIMUM_FEE, and increase minimum to 10mMOB

jenkins/Jenkinsfile
The CD configuration currently does not reapply the configurations in the 01*yaml files.
* Reapply any changes found in  the `01*.yaml` files.
=> Update Jenkins to reapply changes in 01* yaml files

mobilecoind-json/README.md, mobilecoind-json/src/bin/main.rs, mobilecoind-json/src/data_types.rs
Soundtrack of this PR: [Double Trouble by Fire Saga](https://www.youtube.com/watch?v=7j9hseLiAys)
The current JSON API does not match the spec and in some cases diverged from the gRPC API in a confusing way. This cleans up a lot of that.
* Split out getting account key from entropy and monitor creation
* Renamed a lot of routes
* Complete the other functions
=> Updates existing JSON API to match spec

consensus/scp/src/node.rs, consensus/scp/src/slot.rs
Soundtrack of this PR: [more Tycho](https://www.youtube.com/watch?v=PRqKCgT0sQA)
It would be nice to test things like ByzantineLedgerWorker by mocking its dependencies, such as ScpNode.
* Generates a mock ScpNode duriing testing via mockall's `automock`.
* Mock ByzantineLedgerWorker's other dependencies.
=> [MC-1806] Automocks ScpNode

Cargo.lock, consensus/service/src/byzantine_ledger/mod.rs, consensus/service/src/byzantine_ledger/worker.rs, peers/Cargo.toml, peers/src/broadcast.rs, peers/src/lib.rs, peers/src/threaded_broadcaster.rs, peers/test-utils/Cargo.toml, peers/test-utils/src/lib.rs
Soundtrack of this PR: [still Tycho](https://www.youtube.com/watch?v=PRqKCgT0sQA)
Yet more incremental progress towards mocking ByzantineLedger's dependencies.
* Adds a Broadcast trait,
* Automocks Broadcast trait,
* ByzantineLedger depends on trait, instead of on the concrete implementation ThreadedBroadcaster,
* Minor cleanup
* Mock ByzantineLedger's other dependencies.
=> [MC-1801] Adds Broadcast trait

attest/core/src/lib.rs, attest/net/src/sim.rs
This should fix attestation failures related to version mismatch.
=> MCC-1703 Bump expected IAS version.

crypto/ake/enclave/src/lib.rs, ledger/sync/src/test_app/main.rs, mobilecoind/src/bin/main.rs
Fixes a bug in master
* `s/INTEL-SA-00233/INTEL-SA-00334/`
=> MCC-1726 Use the correct advisory ID

consensus/enclave/impl/src/lib.rs, consensus/enclave/mock/src/lib.rs
In the change to constant-time Merkle proof validation, we changed the data stored in a TxOutMemebershipProof. Previously, the last element in the proof was the root hash of the Merkle tree used to create the proof, while after the change to constant-time validation, the function compute_implied_merkle_root must be used to obtain the Merkle root hash. Parts of the consensus enclave still assume that the last element of a proof is the root hash, causing occasional panics.
* Consensus enclave uses compute_implied_merkle_root instead of incorrectly assuming that the last element of a proof is the root hash.
=> [MCC-1745] Consensus enclave uses compute_implied_merkle_root

consensus/service/src/client_api_service.rs
We want ClientApiService to provide immediate feedback to clients when they submit a transaction that will be rejected. Previously, ClientApiService implemented some of these checks, but they are redundant with TxManager::is_valid.
* ClientApiService uses TxManager::is_valid
=> [MCC-1766] ClientApiService uses Txmanager::is_valid

attest/core/src/ias/verifier.rs
Currently, we check all the given status verifiers to ensure they all pass, which defeats the purpose. This treats them separately, and says "if any of the status verifiers pass, consider that a pass, and if any of the other verifiers fail, consider that a fail."
* Put all the status verifiers into their own collection, which is evaluated independently.
=> MCC-1790 Fix verifier not doing multiple MRENCLAVE/SIGNER

mobilecoind/clients/python/lib/BUILD.md
This marks the updated PyPi release after #460.
=> improve pypi build documentation

mobilecoind-json/README.md
Update the README with the new b58 codes introduced in #457
=> Update README with b58 in response

.github/dependabot.yml
Matching that of https://github.com/RustCrypto/utils
=> Add dependabot yaml file

tools/release-tests/mirror-json-test.py
We recently updated the mobilecoind-mirror API to match the mobilecoind-json endpoints for the ledger.
* Updates integration test endpoint to match the API
=> Update integration test endpoint for mirror

util/keyfile/src/keygen.rs
The keyfile crate writes default keyfiles and has a function
to read default keyfiles from a directory. However, due to a subtle
sorting issue, the i'th file in the returned vector is not
`account_keys_{i}.json`. This fixes that.
If this was not already causing problems in tests, then I don't think
it will cause a problem to commit this, and it will help the fog
conformance tests which are being developed.
=> Fix a minor issue in mc-util-keyfile crate

mobilecoind/clients/python/jupyter/wallet.ipynb
Now that we have [mobilecoin as a PyPi package](https://pypi.org/project/mobilecoin/), we can update our jupyter notebook accordingly.
* Updates jupyter notebook to use mobilecoin package
[MCC-1896](https://mobilecoin.atlassian.net/browse/MCC-1896)
=> Update jupyter notebook

ledger/distribution/src/main.rs
* `--start-from next` and `--start-from last` should work as documented (but they were mistakenly switched).
* Switch them so that the code matches the documentation.
=> mc-ledger-distribution: Next and Last were incorrectly switched

mobilecoind/clients/python/cli/send_payment.py, mobilecoind/clients/python/lib/mobilecoin/client.py, mobilecoind/clients/python/lib/setup.py, mobilecoind/clients/python/mailchimp/allocate_mobilecoins.py
The last python package update introduced a bug. This PR fixes this and resolves a few other open issues.
* fix parentheses bug `int(api()).status` should have been `int(api().status)`
* [fixes MCC-1939](https://mobilecoin.atlassian.net/browse/MCC-1939) Use library TxStatus enum directly
* [fixes MCC-1941](https://mobilecoin.atlassian.net/browse/MCC-1941) Add MyPy support
=> Python 0.3.3

util/build/enclave/src/lib.rs
Currently, there are three basic steps to build an production enclave:
1. Build an enclave in release mode with IAS/SGX set to PROD/HW.
2. Produce an offline signature over the resulting `consensus-enclave.dat` (GENDATA) file.
3. Bring the GENDATA, PUBKEY, and UNSIGNED pieces back together into a signed enclave
Prior to this patch, performing step 3 on a different day from step 1 would result in a failed build, because a new GENDATA file was created and used during step 3, and the Intel utilities which create this file inject the creation date (YYMMDD) into the file. This PR changes this behavior.
* Only create/work with a new GENDATA file if one was not provided during the build.
=> MCC-2002 Fix construction of signed consensus enclave binary from offline signature

ledger/db/src/lib.rs
* We should have as few panics as possible.
* Removing an unnecessary panic call in ledger db
=> remove unnecessary panic in LedgerDB

Cargo.lock, consensus/enclave/trusted/Cargo.lock, transaction/core/Cargo.toml, transaction/core/src/amount.rs, transaction/core/src/blockchain/mod.rs, transaction/core/src/range_proofs/error.rs, transaction/core/src/ring_signature/error.rs, transaction/core/src/validation/error.rs
Incrementally moving towards replacing failure with displaydoc
=> Replaces failure usages in transaction/core with displaydoc

mobilecoind/clients/python/jupyter/wallet.ipynb
We changed our mobilecoin python package to not unpack grpc objects under the hood, so our jupyter notebook needs to be updated to reflect this.
* Fixes jupyter notebook
[MCC-2020](https://mobilecoin.atlassian.net/browse/MCC-2020)
=> Fix up usage of mobilecoin package

consensus/scp/src/predicates.rs
* Fixes a comment in a unit test
=> [MCC-2003] Comment fix

transaction/core/src/ring_signature/mlsag.rs
Extracts a challenge helper function to avoid duplicate code.
=> [MCC-2042] Extracts a challenge helper function to avoid duplicate code

Cargo.lock, jenkins/Jenkinsfile, mobilecoind/Cargo.toml, mobilecoind/src/bin/main.rs, mobilecoind/src/config.rs
We would like to provide the ability to filter client IP address by country from the client side.
* Adds a country config check at startup for mobilecoind
[MCC-2123](https://mobilecoin.atlassian.net/browse/MCC-2123)
=> Add IP check to config

transaction/std/src/transaction_builder.rs
This PR adds support for providing a separate `PublicAddress` to be used when making the fog hint for the output of a transaction. This allows the recipient of the `TxOut` itself and the public key contained inside the fog hint to be different.
The API added in this PR is intended to be used for transactions outputs addressed to the user creating the transaction, such as in the case of the change output of a transaction. This provides a way to use a single view key for fog while allowing the `TxOut` itself to be addressed to a different account or a different subaddress within the same account.
It should be noted that under normal circumstances, it would be considered griefing to send a transaction with an output that has mismatching recipient/fog hint. However, because only fog ingest …
=> [MCC-2138] Add custom fog hint support to TransactionBuilder

consensus/scp/src/msg.rs, consensus/scp/tests/mock_network/mod.rs, consensus/service/src/byzantine_ledger/worker.rs
* Msg implements fmt::Display. This is idiomatic and removes some "msg.to_display()" boilerplate.
=> [MCC:2046] Msg implements fmt::Display

MAINNET.md
Add a README with MainNet information.
* adds MAINNET.md
=> MainNet README

TERMS-OF-USE.md
Add Terms of Use.
* Add `TERMS-OF-USE.md`
=> Add Terms of Use

MAINNET.md, README.md
Add `MAINNET` and `TERMS-OF-USE` to `README` and `TERMS-OF-USE` to `MAINNET`.
* Adds `MAINNET` to `README`
* Adds `TERMS-OF-USE` to `README`
* Adds `TERMS-OF-USE` to `MAINNET`
=> Update readme and mainnet

Cargo.lock, Cargo.toml, common/Cargo.toml, consensus/enclave/trusted/Cargo.lock, consensus/enclave/trusted/Cargo.toml
https://github.com/slog-rs/slog/commits/master
=> stop patching slog, 2.7 was released containing our patch

mobilecoind/src/sync.rs
It is possible to send TxOuts of value = 0, so we need to be sure mobilecoind supports discovering those.
* A test case for mobilecoind syncing a block with a TxOut of value 0.
=> Ensure support for receiving txos with a value of 0 in mobilecoind

mobilecoind-json/README.md
< The motivation for the changes in this PR. "Currently we...", "This is needed because..." >
* < Additions, removals, fixes, features >
< Ticket status, e.g. "fixes #issue number" > 
* < Out of scope non-goals for this PR >
* < These should be links to tickets. If the tickets do not exist, make them. >
=> Remove stray double quote character

consensus/service/src/byzantine_ledger/worker.rs
This PR more clearly states, and enforces, the invariant that transactions added to the `pending_values` collection must be valid with respect to the current ledger. While transactions are validated when they are received from clients, enforcing the invariant when the transactions are first consumed by the service worker clarifies the intention and prevents potential race conditions where a transaction expires between when it was received from a client and when it was consumed by the worker.
=> Enforces invariant that pending_transactions are valid w.r.t the current ledger

crypto/keys/src/ristretto.rs
=> Make CompressedRistrettoPublic implement FromRandom trait

MAINNET.md, consensus/service/BUILD.md, mobilecoind/README.md
Soundtrack of this PR: [A Walk](https://www.youtube.com/watch?v=mehLx_Fjv_c)
This documentation change is needed to reference upcoming changes needed to handle multiple secure enclaves.
* Documentation changes that reference `production.json` manifest for secure enclave downloads
* Adding new enclaves to the `production.json` file.
=> Update enclave-distribution production.json format

fog/api/proto/report.proto
these comments were incorrect, and caused bugs
=> fix fog report proto comments about the meaning of pubkey expiry

account-keys/slip10/src/lib.rs
Super minor PR to fix a couple capitalization issues in comments.
=> Fix minor capitalization issues in comments

mobilecoind/strategies/accounts.py
=> fix regression

.circleci/config.yml
=> update the docker image used by circleci

attest/core/src/quote.rs, attest/core/src/seal.rs, consensus/service/src/byzantine_ledger/mod.rs, crypto/keys/src/x25519.rs, ledger/db/src/tx_out_store.rs, ledger/sync/src/reqwest_transactions_fetcher.rs, mobilecoind/src/db_crypto.rs, mobilecoind/src/monitor_store.rs, mobilecoind/src/payments.rs, mobilecoind/src/processed_block_store.rs, mobilecoind/src/utxo_store.rs, sgx/build/src/lib.rs, transaction/core/src/membership_proofs/errors.rs, transaction/core/src/membership_proofs/mod.rs, transaction/core/src/ring_signature/rct_bulletproofs.rs, util/build/script/src/utils.rs, util/grpc/src/auth/mod.rs, util/grpc/src/lib.rs, util/host-cert/src/lib.rs, watcher/src/verification_reports_collector.rs, watcher/src/watcher_db.rs
This PR brings over a few changes from my Rust upgrade PR in order to make that one smaller.
* A few small changes that future `clippy` would be complaining about.
=> Backport rust uprev fixes

.circleci/config.yml
< The motivation for the changes in this PR. "Currently we...", "This is needed because..." >
* < Additions, removals, fixes, features >
< Ticket status, e.g. "fixes #issue number" > 
* < Out of scope non-goals for this PR >
* < These should be links to tickets. If the tickets do not exist, make them. >
=> Update Dockerfile version in CI config.'

sgx/report-cache/untrusted/src/lib.rs
Fix typo
Rename `REPORT_REFRESH_INTERNAL` to `REPORT_REFRESH_INTERVAL`
=> Rename REPORT_REFRESH_INTERNAL to REPORT_REFRESH_INTERVAL

CHANGELOG.md
Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=6c-RbGZBnBI)
We're not a punk rock band anymore, we're a new wave band.
* Initial cut of a changelog covering changes to the repository culled from our commits since the currency launch last year.
* Automation
=> MCC-2308 Keeping A ChangeLog

api/proto/external.proto
This is related to grpc bridge project
=> Add go-package option to external.proto

deploy/00-node-grpc-ingress.yaml, jenkins/packaging-pod.yaml, ops/Dockerfile-consensus
SGX upgrades and build-system upgrades were needed.
* Updates to the Dockerfile-consensus for CD
* Updates to the Ingress definitions
* Update Kaniko to latest version
=> Update cd build

mobilecoind/clients/python/blockchain_explorer/requirements.txt
Soundtrack of this PR: [Pipeline](https://www.youtube.com/watch?v=j09C8clJaXo)
Updates to the referenced Python module versions in the `blockchain_explorer` client.
* Update versions of `grpcio`, `grpcio-tools`, and `mobilecoin`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200318484127252/1200539963987635) by [Unito](https://www.unito.io)
=> Update versions for block explorer

transaction/core/src/tx.rs
this function is exercised in the sample paykit, but not in the `transaction-core`
unit tests, until this commit
=> add tests for the `subaddress_matches_tx_out` function in `transaction-core`

fog/ingest/server/src/controller_state.rs
It is reported that when ingest dies (perhaps Azure restarts the VM)
and then is restarted and begins in the idle state, it doesn't publish
any metrics saying that it is in the idle state.
Initially, I thought that we must be missing a line in the worker to
tell it to publish metrics or something, but as I dug into that,
it seems that that is happening in the grpc admin API and the server
does not need to regularly push out metrics actively on its own.
I dug into what is setting the metrics, and it looks that when
the server changes mode, we update the metrics. However, when the
controller state is first initialized, that does not trigger any
metrics to be set. (I.e. we are trying to maintain an invariant
that the controller state value is always published to the metrics,
but that …
=> Fix ingest not publishing metrics #1081

Cargo.lock, Cargo.toml, consensus/enclave/trusted/Cargo.lock, consensus/enclave/trusted/Cargo.toml, fog/ingest/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.toml, fog/ledger/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.toml, fog/view/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.toml
=> Upgrade mbedtls to fix overflow warnings.

fog/test-client/src/config.rs
This was requested by Jason during deployment work
=> Make test client able to take config from ENV

util/grpc/src/lib.rs
Currently, both Error and Critical get forwarded to sentry and cause
sentry alerts. However, most attestation errors are logged at Error
level, as well as other client-triggered "errors" that usually
represent the normal operation of the system.
This commit makes attestation errors and "invalid arg" errors (that
don't necessarily indicate a server problem) logged at debug level.
It makes general "enclave errors" which get mapped to permission denied
normally, logged as warn level only. We should revisit this in the future
and try to break down those error levels in a more granular way.
This commit is a cherry-pick of the commit to 1.1.2 maintenance release
into master branch.
=> Cherry-pick: Use less severe log levels for server errors that aren't usually actionable

util/grpc/src/build_info_service.rs
I noticed this while working on #1349
=> Fix an incorrect reference in BuildInfoService

consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock
this commit was made by doing `cargo update -p siphasher` in all
workespaces
there is a bugfix in that which is relevant to fog
=> update siphasher everywhere

Cargo.lock, Cargo.toml, fog/ingest/client/src/lib.rs, fog/ingest/server/src/controller.rs, fog/ingest/server/src/server.rs, fog/overseer/server/Cargo.toml, fog/overseer/server/LICENSE, fog/overseer/server/README.md, fog/overseer/server/src/bin/main.rs, fog/overseer/server/src/config.rs, fog/overseer/server/src/error.rs, fog/overseer/server/src/lib.rs, fog/overseer/server/src/server.rs, fog/overseer/server/src/service.rs, fog/overseer/server/src/worker.rs, fog/overseer/server/tests/inactive_outstanding_key_idle_does_not_have_key.rs, fog/overseer/server/tests/inactive_outstanding_key_idle_has_key.rs, fog/overseer/server/tests/one_active_node.rs, fog/overseer/server/tests/retired_key_not_outstanding_idles_have_different_keys.rs, fog/overseer/server/tests/retired_key_not_outstanding_idles_have_same_key.rs, fog/overseer/server/tests/utils/mod.rs
This PR contains the core functionality of the Fog Overseer service. The service monitors the active Fog Ingest cluster and makes sure that there is at least one active node. If there is no active node, then it performs the automatic failover logic. This logic is described in detail in the worker.rs documentation. 
Note that this PR contains the core logic: the monitoring logic is in worker.rs and the rest of the files basically just expose that functionality to clients via a Rocket HTTPS server. The tests test 5 different scenarios in an end to end fashion. Note that there are still some key features that need to be implemented before we can deploy this service. Namely, we'll need to implement the following items: 
1. Sentry alerting: in some cases, we need to send alerts to humans when …
=> Implement core Fog Overseer functionality

consensus/enclave/impl/src/lib.rs, fog/overseer/server/src/worker.rs
I introduced a subtle bug in a previous PR, this PR fixes it.
=> use the correct fee_map

transaction/core/src/blockchain/block.rs
We might be adding fields to `Block` or `BlockContents` in the near future, and it is important to ensure that BlockIDs and block contents hashes do not change for existing blocks that do not have the new data added.
This PR adds a simple test to ensure that is the case. It also modifies the `get_block()` method that is used in a few tests to include key images in the generated blocks.
There is some overlap between this and https://github.com/mobilecoinfoundation/mobilecoin/blob/master/transaction/core/tests/digest-test-vectors.rs but I figured this doesn't hurt.
=> include key images in block tests, add test for hash consistency

fog/test-client/src/test_client.rs
As noted in #1367, ops wants us to update the Fog test client so that the test client returns to healthy status more quickly after a failure. Currently, health is re-established after a single failure only once every node in the set completes a successful transfer in succession. 
* Re-establishes test client health after one successful transaction.
* Cleans up the documentation around test client health.
Fixes #1367 
* #1445): Continue improving the test client by making the number of transactions consistent per day.
=> Loosen health time for test client

attest/net/Cargo.toml, attest/net/src/lib.rs, util/telemetry/src/lib.rs
Fixes some issues I found by running `cargo hack check --each-feature`
* Fix an error when mc-util-telemetry is built without the jaeger feature. Follow-up to #1340.
* Add missing `blocking` feature to `reqwest` dependency.
* Bonus cleanup: Move conditional mods into the associated `cfg_if` block.
=> Fix a couple of minor issues

fog/distribution/src/main.rs, tools/fog-local-network/fog_local_network.py
See #1448 for a full description of the problem. 
* Add `..` to `fog_local_network.py` usages of `TARGET_DIR`. This fixes the `file not found` error that results from executing the script as is. 
Fixes #1448
=> Fix fog_local_network.py script

transaction/std/src/memo/authenticated_common.rs, transaction/std/src/memo/authenticated_sender.rs, transaction/std/src/memo/authenticated_sender_with_payment_request_id.rs
Needed to provide more room in the memo since the previous HMAC left 20 bytes of space unused unnecessarily.
Move Hmac to the end.
=> Updating memos to move hmac to the end

tools/enclaver.sh
Soundtrack of this PR: [1ONY - Silk](https://soundcloud.com/1ony/silk)
Make it easier to get MrEnclave hex values for a particular environment like `test.mobilecoin.com`
Added a script `enclaver.sh` which will print enclave values for Consensus, View, Ledger, and Ingest to stdout.
=> Add `tools/enclaver.sh` script to more easily get MrEnclave values in Hex

util/build/sgx/src/env.rs, util/build/sgx/src/lib.rs, util/build/sgx/src/vars.rs
=> Minor cleanup of code to load environment variables.

Cargo.lock, mobilecoind-json/Cargo.toml, util/generate-sample-ledger/Cargo.toml, util/grpc-admin-tool/Cargo.toml, util/grpc-token-generator/Cargo.toml
This seems like it was cargo-culted.
=> Remove spurious serde deps

.github/dependabot.yml
Changed dependabot target group by notifications
=> changed the target for dependabot notifications

consensus/api/proto/consensus_common.proto, consensus/api/src/conversions.rs, transaction/core/src/validation/error.rs, transaction/core/src/validation/validate.rs
Reverts mobilecoinfoundation/mobilecoin#561
=> Revert "[MCC-1994] Adds validate_outputs_are_sorted"

account-keys/src/burn_address.rs
there was a merge race between burn address PR and crypto update
PR
=> fix master build

ledger/db/src/lib.rs, transaction/core/src/mint/config.rs, transaction/core/src/mint/tx.rs, transaction/core/src/mint/validation/common.rs
#1438 got merged to `master`, so I have rebased `feature/minting` and pushed that but did not deal with any issues
=> Small fixes following the confidential-token-id merging

transaction/core/src/ring_signature/rct_bulletproofs.rs
Soundtrack of this PR: [Mr. Dawes Jr.](https://www.youtube.com/watch?v=oL3AijekRYw)
Noticed a comment that remained for the proof of opening while updating the MCIP 
* Removes a leftover comment
=> Remove comment remaining from confidential token id previous work

api/proto/external.proto, transaction/core/src/mint/config.rs, transaction/core/src/mint/tx.rs
As was requested by @garbageslam in a PR comment
=> Improve nonce comment

consensus/api/proto/consensus_client.proto, consensus/api/proto/consensus_common.proto, consensus/service/src/api/client_api_service.rs, consensus/service/src/consensus_service.rs
=> add block-version field to propose tx response

consensus/api/proto/consensus_common.proto, consensus/service/src/api/client_api_service.rs, consensus/service/src/consensus_service.rs
Fixes #1718 (in release 1.2.0 branch)
This is a cherry-pick of https://github.com/mobilecoinfoundation/mobilecoin/pull/1720
=> add block-version field to propose tx response (#1720) (release-1.2.0)

consensus/enclave/impl/src/lib.rs
this breaks the older clients if the fee output doesn't do this
=> make the fee output conform to block version rules

Cargo.lock, fog/ocall_oram_storage/trusted/Cargo.toml, fog/ocall_oram_storage/trusted/README.md, fog/ocall_oram_storage/trusted/src/lib.rs
Cherry picking commit from PR: 
https://github.com/mobilecoinfoundation/mobilecoin/pull/1732
=> add tests for untrusted tampering with data and metadata (#1732)

Cargo.lock, Cargo.toml, ledger/streaming/publisher/Cargo.toml, ledger/streaming/publisher/src/grpc.rs, ledger/streaming/publisher/src/lib.rs, ledger/streaming/publisher/src/test_utils.rs
=> Add GrpcServerSink

account-keys/src/account_keys.rs, account-keys/src/lib.rs, fog/sample-paykit/src/cached_tx_data/mod.rs
This change is described in issue #1787
=> Set change subaddress index to u64::MAX - 1, update sample paykit

account-keys/src/account_keys.rs, account-keys/src/lib.rs, fog/sample-paykit/src/cached_tx_data/mod.rs
=> Set change subaddress index to u64::MAX, update sample paykit

transaction/core/src/blockchain/block_version.rs, transaction/core/src/ring_signature/rct_bulletproofs.rs
this was requested in other PR reviews
closes #1706
=> add feature extended message digest

ledger/db/src/mint_config_store.rs
The `total_mint_limit` field was previously used when we didn't store the entire `MintConfigTx`. But now that we do, there's no need to store it since this is already available in the `MintConfigTx`.
=> remove redundant field

Cargo.lock, android-bindings/Cargo.toml, android-bindings/src/bindings.rs
Adding bindings for Android SDK RTH 1.2.0 release
Updating change subaddress to `u64::MAX - 1`
* android-sdk RTH (See #1606)
* Update change subaddress to `u64::MAX - 1`
=> Android SDK RTH and Change Subaddress Update

consensus/enclave/impl/src/lib.rs
=> Make sure all output token ids are actually configured

mobilecoind-json/tests/integration_test.py, mobilecoind/strategies/drain-accounts.py, mobilecoind/strategies/test_client.py
We'd like to test `mobilecoind-json` as part of our Jenkins CD process, this PR provides a Python script that exercises some of `mobilecoind-json`'s core functionality.
* Get this to run as part of a k8 deployment in `internal`
=> Write an integration test for mobilecoind-json

util/test-helper/src/lib.rs
* Use `lazy_static` to call `get_seeds`
* Use `rand::distributions::Alphanumeric` in `random_string()`
=> Clean up mc-util-test-helper

tools/local-network/local_network.py
to resolve conversation from https://github.com/mobilecoinfoundation/mobilecoin/pull/1943
=> reverting ledger-dist folder to work dir and work dir now in target dir

consensus/enclave/api/src/config.rs, consensus/enclave/api/src/fee_map.rs, consensus/enclave/impl/src/lib.rs, consensus/service/config/src/tokens.rs, consensus/service/src/api/blockchain_api_service.rs, tools/local-network/local_network.py
This cherry-picks https://github.com/mobilecoinfoundation/mobilecoin/pull/1965 to the `candidate-1.2` branch
There were no conflicts
=> Make fee map enforce divisibility by minimum fee. Also check this in enclave impl #(1965)

mobilecoind/src/config.rs
This picks #1996 to master, there were no conflicts
=> add an option to use an ipinfo token (#1996)

consensus/mint-client/src/config.rs, consensus/mint-client/src/printers.rs
Fixes for @remoun 's comments in https://github.com/mobilecoinfoundation/mobilecoin/pull/1993#pullrequestreview-977730258
=> pr review fixes

mobilecoind/strategies/drain-accounts.py
I am not sure if this still needs to be ported to `release/v1.2.0`, we may have gotten through CD now.
But in case it does, here is a PR. There were no conflicts.
---
* make drain accounts script handle defragmentation errors
* make it subtract fee from sending amount after successful defragmentation
* Update mobilecoind/strategies/drain-accounts.py
Co-authored-by: Mike Turner <zaphrod.beeblebrox@gmail.com>
* Update mobilecoind/strategies/drain-accounts.py
Co-authored-by: Mike Turner <zaphrod.beeblebrox@gmail.com>
* Update mobilecoind/strategies/drain-accounts.py
Co-authored-by: Mike Turner <zaphrod.beeblebrox@gmail.com>
* fix indentation
* fix syntax
Co-authored-by: Mike Turner <zaphrod.beeblebrox@gmail.com>
=> make drain accounts script handle defragmentation errors (#2035)

Cargo.lock, mobilecoind-dev-faucet/Cargo.toml, mobilecoind-dev-faucet/README.md, mobilecoind-dev-faucet/src/bin/main.rs, mobilecoind-dev-faucet/src/data_types.rs, mobilecoind-dev-faucet/src/lib.rs, mobilecoind-dev-faucet/src/worker.rs
this enables it to support multiple faucet requests concurrently
=> make the faucet have a background thread that splits tx outs

transaction/core/src/constants.rs
Cherry-pick #2073 to master. there were no conflicts
=> adjust MAX_TOMBSTONE_BLOCKS constant (pick to master)

transaction/std/src/transaction_builder.rs
* add `add_gift_code_output` method that send a gift code TxOut to the gift code reserved sub-address and creates a fog hint for the primary subaddress
* add paragraph to `add_change_output` to describe how to use it for gift code cases
The `add_output_method` assumes to that the fog hint address is the same as the recipients address. In the case of sending funds to oneself at any subaddress other than the primary address, this creates the wrong fog hint and thus doesn't allow you to track your funds via Fog in clients who are using your primary address with Fog. This solves that problem
1. `add_gift_code_output` is very specific and it could technically be refactored to a method that's used for sending to any owned subaddress with a name like `add_reserved_subaddress_output` - is it …
=> Gift code transaction builder support

connection/src/traits.rs, mobilecoind/src/service.rs
we merged before we these comments appeared I think
=> fix Remoun comments from #2060

consensus/enclave/impl/src/lib.rs
this is required because the mint_output function rejects any new
token id if new token ids are not allowed yet, but the fee aggregation
code would sometimes, under load, try to mint a fee output of alternate
token ids, because of privacy considerations in MCIP #25
If not fixed, then if 1.2.0 is started with bv = 0, and has alternate tokens in the `tokens.toml` file, then the consensus nodes will crash if more than one Tx appears in the block.
```
OH NO, WE CRASHED :( thread ByzantineLedgerNodeID(peer1.mc-v1-2-0-without-upgrade.development.mobilecoin.com:443:1af604b8ef998e89b939bffca5731e377122a78bfdd844a1b5e50c7534979321) on /usr/bin/consensus-service
Details: panicked at 'form_block failed: FormBlock("Cannot mint outputs for non-MOB tokens until they are supported")', …
```
=> fix block-version 0 behavior in consensus enclave

transaction/types/src/block_version.rs
Rephrase for succinctness and consistency.
=> Tidy up BlockVersion method docs

start-testnet-client.sh
Fix SIGSTRUCT_URI value, present:
```
pool/a4155a9b69c7a574e478366aca68d3fca5837c93/bf7fa957a6a94acb588851bc8767eca5776c79f4fc2aa6bcb99312c3c386c/consensus-enclave.css
pool/1fba5385d299c3a47485cec3aac85ec395377df3/bf7fa957a6a94acb588851bc8767eca5776c79f4fc2aa6bcb99312c3c386c/ingest-enclave.css
pool/1fba5385d299c3a47485cec3aac85ec395377df3/bf7fa957a6a94acb588851bc8767eca5776c79f4fc2aa6bcb99312c3c386c/ledger-enclave.css
pool/1fba5385d299c3a47485cec3aac85ec395377df3/bf7fa957a6a94acb588851bc8767eca5776c79f4fc2aa6bcb99312c3c386c/view-enclave.css
```
Should be
```
pool/a4155a9b69c7a574e478366aca68d3fca5837c93/bf7fa957a6a94acb588851bc8767eca5776c79f4fc2aa6bcb99312c3c386c/consensus-enclave.css
```
=> Fix start testnet shell

.internal-ci/docker/Dockerfile.fog-test-client, .internal-ci/docker/entrypoints/fog-test-client.sh, .internal-ci/helm/fog-test-client/templates/fog-test-client-deployment.yaml, .internal-ci/helm/fog-test-client/values.yaml, fog/sample-paykit/src/cached_tx_data/mod.rs, fog/sample-paykit/src/error.rs
- Watcher, standalone node_hw operational fixes. (#2266)
- Feature/fix var prefixs test client (#2278)
=> More changes from 1.2.3

Cargo.lock, android-bindings/Cargo.toml, android-bindings/src/bindings.rs
Cherry-picking commits from release 1.2+ branches
This is needed to begin work on SDK release 1.3.0
* 1.3.0 release work
=> Android SDK Merge 1.2+

Cargo.lock, android-bindings/Cargo.toml, android-bindings/src/bindings.rs
Cherry-picking changes from #2303 
This is needed in order to begin work on SDK version 1.3.0
* Upgrade android-sdk to bindings and protobufs 1.3.0-pre0
=> Android merge expose rng

consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs
Fixed a couple of lint issues in mc-consensus-mint-client.
=> mc-consensus-mint-client lint cleanup

tools/local-network/README.md
one thing i've been hearing from multiple people is, the local network py script docu is a bit sparse. i wanted to improve it with a quickstart
=> improve local network docu with a quickstart

libmobilecoin/include/chacha20_rng.h
Need to update from bool to void return type to match rust signature
=> Fix return type for mc_chacha20_rng_free

transaction/std/src/transaction_builder.rs
This attempts to address my comment here: https://github.com/mobilecoinfoundation/mobilecoin/pull/2519#discussion_r970141946
=> attempt to DRY up some code and remove obscure prepare_for_signing

fog/sql_recovery_db/src/test_utils.rs
As described in #2517, the test process is sometimes unable to establish a connection to the PSQL server. The easiest fix for this is to implement retry logic, that will retry failed connections a certain number of times. 
I chose to implement this fix first because it's the simplest and most bang for our buck. The other option is to remove PSQL from the tests and implement a SqlLite or other type of in-memory DB. I spoke with @garbageslam and @eranrund, and they mentioned how they thought through this option when they first implemented this test SQL implementation, and there were some pretty major cons to this approach:
- If we use SqlLite, we'd have to have two separate DB schema / migration paradigms for Diesel.
- A simple in-memory approach (not using SqlLite) would be very diffiult …
=> Add retry logic for test PSQL connections

fog/view/load-test/src/main.rs, ledger/sync/src/test_app/main.rs, mobilecoind/src/config.rs, watcher/src/verification_reports_collector.rs
These appear to be wrong comments left in from the chain-id PR
=> fix some messed up comments

transaction/core/src/ring_ct/rct_bulletproofs.rs
This is a follow-up on #2519 that moves a bunch of code that sits in a helper function to the only place that called that helper function. This makes the code easier to follow.
Nothing was changed under than moving the contents of that function.
=> move code from a helper function that is only used in one place into that one place

.github/workflows/ci.yml
We will fix this as part of #2565 , which is blocking for Block Version 3 release
=> disable mint auditor test for now

consensus/mint-client/src/config.rs
This picks 41ecebe83f3a34d69044698b012c512b3f4f640d to release/v2
=> Pick add check to mint client

attest/api/src/conversions.rs, attest/enclave-api/src/lib.rs
=> Re-apply PR #2463 (was accidentally removed)

attest/ake/src/event.rs, attest/ake/src/shared.rs, attest/ake/src/state.rs, attest/api/src/conversions.rs, attest/enclave-api/src/lib.rs, crypto/noise/src/cipher_state.rs
=> Re-apply PR #2473 (was accidentally removed)

fog/README.md, fog/sql_recovery_db/src/test_utils.rs
Also improved test utility postgres connection error reporting
=> Update fog readme for new mob prompt behavior

fog/sql_recovery_db/cleanup/src/db_cleaner.rs
This PR implements the actual DB "cleanup" logic, which amounts to decommissioning an ingest invocation if it's egress keys are expired.
=> Decommission expired ingest invocations with the cleanup utility

consensus/mint-client/src/bin/main.rs, util/grpc/src/lib.rs
=> make call option utility in mc-util-grpc

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, connection/Cargo.toml, connection/src/traits.rs, consensus/tool/Cargo.toml, consensus/tool/README.md, consensus/tool/src/main.rs
This was motivated by Remoun's comment, #2635
=> add a mc-consensus-tool which can help avoid long sleep in tests

.github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/docker/entrypoints/node_hw.sh, .internal-ci/docker/support/node_hw/bin/wrapper-ledger-distribution.sh, .internal-ci/helm/consensus-node/templates/node-deployment.yaml, .internal-ci/test/mint-auditor-test.sh, .internal-ci/test/mobilecoind-integration-test.sh, .internal-ci/test/mobilecoind-json-integration-test.sh, .internal-ci/util/drain_accounts.sh, consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs
Fix the ability to bootstrap the network from scratch with a 2.x+ version container and charts. Useful for load testing.
- Add optional secrets for initial and fog keys seeds.
- Add MC_START_FROM=zero logic to ledger-distribution.
=> release/v2: [Fixes] CI/CD, chart, container - Fix consensus node bootstrap from scratch. 

tools/fog-local-network/README.md, tools/local-network/README.md, tools/local-network/local_network.py
Updated README in local-network to include optional block-version parameter
Updated README in fog-local-network to include postgresql setup
Updated default block version in local_network.py from 2 to 3
These changes should be made in order to have more complete, up-to-date instructions for running and testing on a local network.
=> Updating local network README files

crypto/digestible/signature/Cargo.toml, crypto/ring-signature/signer/Cargo.toml
=> Fix `Cargo.toml` formatting failing `cargo-sort`

CHANGELOG.md, fog/recovery_db_iface/src/lib.rs, fog/sql_recovery_db/src/lib.rs
follow ups from https://github.com/mobilecoinfoundation/mobilecoin/pull/2707
(I merged a little early, I should have accepted the suggestions and used the [skip-ci] tag)
=> Nits from fog view db fetch pr

CHANGELOG.md, fog/recovery_db_iface/src/lib.rs, fog/sql_recovery_db/src/lib.rs, fog/view/server/src/config.rs, fog/view/server/src/db_fetcher.rs, fog/view/server/src/server.rs, fog/view/server/tests/smoke_tests.rs
This cherry-picks #2707 and #2714 to master
=> Pick fog view db fetch fixes (master)

fog/view/server/src/block_tracker.rs, fog/view/server/src/db_fetcher.rs, fog/view/server/src/server.rs
This PR makes the `BlockTracker` aware of the store's `ShardingStrategy`. This change is cosmetic in that it makes sharding logic cleaner- the sharding strategy now exists in the `BlockTracker`, which is a struct responsible for tracking which blocks have been processed.
=> Update block tracker to use sharding strategy

.github/workflows/mobilecoin-workflow-dev-test.yaml
Small fix to update the CD mint-auditor test to specify the token-fee.
=> release/v2 - CI/CD - Specify fee for mint-auditor test.

.github/workflows/ci.yml, consensus/tool/src/main.rs, mobilecoind/strategies/burn.py
I ran into the minting-and-burning CI test being flaky or just not working, I believe this will make it more reliable.
=> Fixes to mint-and-burn CI to make it more robust

fog/view/enclave/impl/src/lib.rs
Previously we were only setting `highest_processed_block_count` by finding the first response that wasn't fully processed. This PR also sets `highest_processed_block_signature_timestamp` and `last_known_block_count` using this response. It also adds much needed unit test for the `get_block_data` method.
=> Set block-related data more accurately

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml, .internal-ci/test/minting-config-tx-test.sh, .internal-ci/util/generate_minting_keys.sh, .internal-ci/util/generate_tokens_config.sh, .internal-ci/util/tokens.base.json
Change the CD integrations alternate token from 1 to 8192 so we don't conflict with the main/test token id 1 in future testing.
=> master - CI/CD - change testing token to 8192

Cargo.lock, fog/view/server/Cargo.toml, fog/view/server/test-utils/src/lib.rs, fog/view/server/tests/router_smoke_tests.rs
Creates the base set of integration tests for the Fog View Router.
=> Create Fog View Router integration test

Cargo.lock, consensus/enclave/Cargo.toml, consensus/enclave/tests/enclave_api_tests.rs, consensus/enclave/tests/graceful_teardown.rs, consensus/service/src/api/client_api_service.rs, consensus/service/src/api/grpc_error.rs
This pulls out some bug fix and improvement from PR #2670 , which we might redevelop
=> Consensus api Bug fix and testing

transaction/core/src/validation/validate.rs, transaction/core/tests/validation.rs
See [MCIP 57](https://github.com/mobilecoinfoundation/mcips/pull/57) for discussion
=> MCIP 57 update ring uniqueness requirements for SCIs

mobilecoind/src/error.rs, mobilecoind/src/payments.rs
An MVP for having mobilecoind pass along the fee map digest to consensus
when submitting transactions
=> [TOB-5] mobilecoind: plumb fee_map into transaction builder

fog/api/proto/view.proto, fog/api/tests/fog_types.rs, fog/sql_recovery_db/src/lib.rs, fog/types/src/view.rs, fog/view/enclave/impl/src/e_tx_out_store.rs, fog/view/enclave/impl/src/oblivious_utils.rs, fog/view/server/test-utils/src/lib.rs, fog/view/server/tests/smoke_tests.rs
The changes in this PR were submitted in #2803, but got deleted in #2845. Since #2803 was already reviewed, this PR doesn't need review and will be submitted directly. 
=>  Re-submit 2803 

Cargo.lock, account-keys/Cargo.toml, account-keys/src/account_keys.rs, account-keys/src/address_hash.rs, api/proto/external.proto, api/src/convert/signing_data.rs, api/src/convert/unsigned_tx.rs, consensus/enclave/trusted/Cargo.lock, crypto/keys/src/ristretto.rs, crypto/ring-signature/src/ring_signature/key_image.rs, crypto/ring-signature/src/ring_signature/mlsag.rs, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock, transaction/builder/src/signed_contingent_input_builder.rs, transaction/builder/src/test_utils.rs, transaction/builder/src/transaction_builder.rs, transaction/core/src/lib.rs, transaction/core/src/tx.rs, transaction/extra/Cargo.toml, transaction/extra/src/lib.rs, transaction/extra/src/signed_contingent_input.rs, transaction/extra/src/tx_summary_unblinding/data.rs, transaction/extra/src/tx_summary_unblinding/error.rs, transaction/extra/src/tx_summary_unblinding/mod.rs, transaction/extra/src/tx_summary_unblinding/report.rs, transaction/extra/src/tx_summary_unblinding/verifier.rs, transaction/extra/src/unsigned_tx.rs, transaction/extra/tests/verifier.rs, transaction/types/src/amount.rs
Also makes transaction builder able to generate the tx summary unblinding data.
=> add tx-summary unblinding data, streaming verifier, tests

transaction/extra/tests/verifier.rs
This adds tests of the feature/tx-summary-unblinding-data branch
https://github.com/mobilecoinfoundation/mobilecoin/pull/2725
=> Tx summary unblinding tests

.github/workflows/ci.yml, .github/workflows/dependent-repos.yml, .github/workflows/mobilecoin-dev-cd.yaml, .mobconf, CHANGELOG.md, consensus/enclave/build.rs, consensus/enclave/measurement/build.rs, consensus/enclave/trusted/build.rs, consensus/service/BUILD.md, docker/install_sgx.sh, fog/ingest/enclave/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ingest/enclave/trusted/build.rs, fog/ledger/enclave/build.rs, fog/ledger/enclave/measurement/build.rs, fog/ledger/enclave/trusted/build.rs, fog/view/enclave/build.rs, fog/view/enclave/measurement/build.rs, fog/view/enclave/trusted/build.rs, ops/Dockerfile-consensus
- Copy in CHANGELOG updates from 3.0
- Add CHANGELOG items for 4.0
Part of releasing 4.0 is updating the CHANGELOG.
=> Fill in the changelog for 4.0.0

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dispatch-dev-test.yaml
I would like this in the v4.0 branch, but not sure it _must_ go into the v4.0 branch.
- Fix a nit on variable naming.
- Fix the dispatch_workflow call for block version 2/3 testing.  Update for newer json config on minting-config-tx-test.sh
=> fix(ci/cd): fix dispatch test workflow

BRANCHING.md
Add a proposal for handling release branches by merging them
[Rendered Proposal](https://github.com/mobilecoinfoundation/mobilecoin/blob/branching-strategy/BRANCHING.md)
=> proposal: BRANCHING.md [skip-ci]

.internal-ci/helm/consensus-node-config/templates/node-ingress-blocklist-configmap.yaml, .internal-ci/helm/consensus-node-config/values.yaml, .internal-ci/helm/consensus-node/templates/_helpers.tpl, .internal-ci/helm/consensus-node/templates/client-grpc-attest-ingress.yaml, .internal-ci/helm/consensus-node/templates/client-grpc-ingress.yaml, .internal-ci/helm/consensus-node/templates/gateway-ingress.yaml, .internal-ci/helm/consensus-node/templates/peer-grpc-ingress.yaml, .internal-ci/helm/consensus-node/values.yaml, .internal-ci/helm/fog-services-config/templates/fog-ingress-blocklist-configmap.yaml, .internal-ci/helm/fog-services-config/values.yaml, .internal-ci/helm/fog-services/templates/_helpers.tpl, .internal-ci/helm/fog-services/templates/fog-ledger-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-ledger-http-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-report-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-report-http-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-view-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-view-http-ingress.yaml, .internal-ci/helm/fog-services/values.yaml, .internal-ci/helm/mc-core-dev-env-setup/values.yaml
Update helm chart ingress objects to support enabling IP blocklists.
We need to merge these changes up to the master branch and back port them to the release/v3.0 branch.
=> feat: HAProxy Ingress Blocklists

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, core/types/src/account.rs, mobilecoind-dev-faucet/README.md, mobilecoind-dev-faucet/src/bin/main.rs, mobilecoind-dev-faucet/src/lib.rs, mobilecoind-dev-faucet/src/slam/mod.rs, mobilecoind-dev-faucet/src/worker.rs, transaction/signer/Cargo.toml, transaction/signer/README.md, transaction/signer/src/lib.rs, transaction/signer/src/main.rs, transaction/signer/src/traits.rs, transaction/signer/src/types.rs
This merges into master the following changes from release/v4.1:
* minor improvements to faucet worker (https://github.com/mobilecoinfoundation/mobilecoin/pull/3062)
* add transaction signing API and types, offline signer (https://github.com/mobilecoinfoundation/mobilecoin/pull/2926)
=> Merge release/v4.1 to master

fog/view/server/src/fog_view_router_service.rs, mobilecoind/src/service.rs, util/grpc/src/auth/mod.rs
Adds gRPC authentication and chain id checks to FVR streaming API.
=> Add authentication logic to router

common/src/logger/loggers/mod.rs, transaction/builder/src/transaction_builder.rs, transaction/extra/src/signed_contingent_input.rs, util/grpc/src/grpcio_extensions.rs, util/logger-macros/src/lib.rs, util/uri/src/uri.rs
Pull changes from `release/v4.1` to `master`.
Note for reviewers: only commits that were not the result of an existing PR (w/ reviews) need code review. This PR shouldn't have any.
=> Pull changes from `release/v4.1` to `master`

.internal-ci/helm/fog-test-client/README.md, .internal-ci/helm/fog-test-client/scripts/apply-k8s.sh, .internal-ci/helm/fog-test-client/scripts/generate-k8s.sh
Update fog-test-client helper scripts used to launch canary instances.
=> fix: update fog-test-client helper scripts

fog/view/server/src/fog_view_router_server.rs, util/grpc/src/health_service.rs
=> Add logging for readiness check

transaction/extra/src/signed_contingent_input.rs
Update a single comment to add clarification
The comment for the function claims it does something it specifically does not do.
None
=> Update misleading comment

fog/ledger/server/src/db_fetcher.rs, util/grpc/src/health_service.rs
Hopefully fix num_blocks issues
=> Process all blocks but only add ours to ORAM

CHANGELOG.md
- Update 4.1.0 changelog
- Fix links in 4.0.2, 4.0.1 changelogs.
Pre-requisite to releasing 4.1.
=> Update changelog for PRs to 4.1

mobilecoind/strategies/requirements.txt
Updated jedi, parso, traitlets, prompt-toolkit.
Needed to update dependencies to get cd to pass: https://github.com/mobilecoinfoundation/mobilecoin/actions/runs/4505237172/jobs/7930763151
Fixes #3207
=> Update dependencies for cd

ledger/sync/src/ledger_sync/ledger_sync_service.rs, mobilecoind/src/sync.rs, watcher/src/bin/main.rs, watcher/src/verification_reports_collector.rs, watcher/src/watcher.rs
https://github.com/mobilecoinfoundation/mobilecoin/issues/2405
=> Changed log levels
=> Changed log messages
=> Set get block contents max sleep time to 60 seconds
=> Update log messages

watcher/src/watcher.rs
[Issue](https://github.com/mobilecoinfoundation/mobilecoin/issues/2405 ) 
Changed the log level to debug because of https://github.com/mobilecoinfoundation/mobilecoin/issues/2405#issuecomment-1432279302
=> Change log level to debug for watcher

fog/api/proto/view.proto, fog/ledger/test_infra/src/lib.rs, fog/uri/src/lib.rs
Fixes build error introduced by merging router branches.
=> Fix router CI errors

CHANGELOG.md
=> Update changelog for v5.0 release

.github/workflows/refresh-ledger-bootstrap.yaml
* Add a download step to the ledger/watcher refresh, so that we're not downloading the whole blockchain each time
* Make ledger refresh job go faster
* Nothing planned
=> Add a download step to the ledger refersh

.internal-ci/docker/entrypoints/fogingest.sh, .internal-ci/helm/fog-ingest/templates/fog-ingest-statefulset.yaml, .internal-ci/helm/fog-ingest/values.yaml
=> adds dir creation and memory resources

core/types/src/account.rs
=> Add zeroize on drop to core account container types

Cargo.lock, attest/core/src/types/measurement.rs, attest/verifier/Cargo.toml, attest/verifier/config/Cargo.toml, attest/verifier/config/src/lib.rs, attest/verifier/src/ias.rs, attest/verifier/src/lib.rs, attest/verifier/src/status.rs, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock
This provides some of the foundation for #3375 and breaks up the overall change into smaller chunks
=> Add `TrustedMeasurement` `From` impl to `StatusVerifier`

attest/verifier/build.rs
DRY up some of the licate logic for generating x509 certificates in the
`build.rs` of the `mc-attest-verify` crate.
=> Consolidate certificate generation

.internal-ci/helm/fog-services/templates/fog-ledger-fogshardrangegenerator.yaml, .internal-ci/helm/fog-services/templates/fog-view-fogshardrangegenerator.yaml, .internal-ci/helm/fog-services/values.yaml
- Fixes shardOverlap templating to use correct value
- Adds name override to reduce name & label length of shards and routers
- Adds a Delete retention policy to the ledger router and ledger shards PVC cleanup
=> Helm chart upgrades

.github/workflows/ci.yml, .github/workflows/dependent-repos.yml, .github/workflows/mobilecoin-dev-cd.yaml, .mobconf
Update docker image to use one without node, reducing the image size some.
=> Remove nodejs from docker image

.github/workflows/mobilecoin-dispatch-dev-mainnet-fog.yaml, .github/workflows/mobilecoin-dispatch-dev-testnet-fog.yaml
Add ability to "push button" deploy Fog environments in do development wired up for TestNet or MainNet.
=> Add "Deploy Fog" manual actions

.internal-ci/helm/fog-ledger/templates/fog-ledger-fogshardrangegenerator.yaml
Fix the port alignment for the fog-ledger-router grpc-gateway instance.
=> fix ledger http ports

mobilecoind/src/sync.rs
The goal of this is to be able to saturate all CPU cores with view key scanning operations when there is a single monitor, which is a pretty common case. In this case, we need to be able to scan multiple blocks in parallel for a single monitor, when it is many blocks behind.
I don't think this should much change the situation if there are a lot of monitors, since it still doesn't spend that much time working on only one monitor. It's at most like a hundred blocks at a time if you have a lot of cores.
I'm tired of waiting for mobilecoind to sync. :)
=> Improve parallel processing when there is only a single monitor

.internal-ci/helm/fog-ledger/templates/fog-ledger-router-servicemonitor.yaml, .internal-ci/helm/fog-ledger/templates/fog-ledger-store-servicemonitor.yaml, .internal-ci/helm/fog-view/templates/fog-view-router-servicemonitor.yaml, .internal-ci/helm/fog-view/templates/fog-view-store-servicemonitor.yaml
Roll up release/v5.2 - update servicemonitor to add stack labels (#3782)
=> rollup - update servicemonitor to add stack labels (#3782)

Cargo.lock, Cargo.toml, consensus/enclave/trusted/Cargo.lock, consensus/enclave/trusted/Cargo.toml, fog/ingest/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.toml, fog/ledger/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.toml, fog/view/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.toml
Using an updated mbedtls crate version that should allow for building on apple silicon
=> Update mbedtls crate revision

Cargo.lock, fog/block_provider/src/local.rs, fog/ledger/server/Cargo.toml, fog/ledger/server/tests/router_integration.rs, fog/ledger/test_infra/Cargo.toml, fog/ledger/test_infra/src/lib.rs
Previously the router_integration test only verified the `results` field
of the `CheckKeyImagesResponse`. Now the entire structure is verified.
=> Verify all of CheckKeyImagesResponse

.github/workflows/refresh-ledger-bootstrap.yaml, .internal-ci/util/wait-for-mobilecoind.sh
Make the minimum number of signature the sync script looks for a variable so we can set different thresholds for testnet/mainnet.
=> mobilecoind-sync job: make minimum number of signatures a variable

.github/workflows/refresh-ledger-bootstrap.yaml
Update mobilecoind ledger refresh job, swapping out The Long Now Foundation with Fight For the Future.
=> Update ledger refresh with FFtF node

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-bootstrap.yaml
Update the version we bootstrap from to v5.2.3 and set minimum block height for "ready to test" to 6224.
=> CI/CD - v6.0 Update testing base to v5.2.3

tools/k8s-dev/down.sh, tools/k8s-dev/up.sh
Scripts to safely scale down and back up a dev environment, preserving local data while reducing costs. This will leave some resources running, so its better to delete an environment when you're done testing.
=> tools - scripts to scale down/up a dev environment 

.internal-ci/helm/fog-test-client/templates/fog-test-client-deployment.yaml
Wrap the jaeger sidecar in an if statement and statically set the collector endpoint and port.
=> Fix fog-test-client chart jaeger sidecar

mobilecoind/src/service.rs
See https://github.com/mobilecoinfoundation/mobilecoin/issues/3984
=> address potential deadlock in mobilecoind

CHANGELOG.md
Update changelog with changes going into 7.0.0
=> Update changelog for 7.0.0

CHANGELOG.md
Update changelog with integrated release process update.
=> v7.0 - Update Changelog

start-testnet-client.sh, tools/download_sigstruct.sh, tools/release/03-populate-release.sh, tools/release/README.md
Sync release v7.0 changes to main 
- use versioned measurements download (#4042)
=> release/v7.0 to main - use versioned measurements download (#4042)
