tools/fog-local-network/fog_conformance_tests.py, tools/fog-local-network/fog_local_network.py, tools/fog-local-network/local_fog.py, tools/fog-local-network/local_network.py
Some fixes and cleanups I made for #1693, split into a separate PR.
* Symlink `local_network.py` next to `fog_local_network.py` to avoid mucking with sys.modules
* Use absolute paths when executing binaries
* Dedupe `PROJECT_DIR` constants across `tools/*/*.py`
* DRY up target_dir references
=> Clean up Python in tools/fog-local-network

mint-auditor/api/proto/mint_auditor.proto, mint-auditor/src/convert/counters.rs, mint-auditor/src/convert/mod.rs, mint-auditor/src/db.rs, mint-auditor/src/lib.rs, mint-auditor/src/service.rs
We'd like the `mc-mint-auditor` GRPC service to expose all the information it has, in case it needs to get consumed by any external service.
This PRs adds an endpoint for getting the counters, which includes statistics on how many blocks were scanned and number of discrepancies found.
=> Mint auditor exposes counters over GRPC

ledger/streaming/client/src/backfill.rs, ledger/streaming/client/src/lib.rs
=> Add BackfillingStream

Cargo.lock, libmobilecoin/Cargo.toml, libmobilecoin/Makefile, libmobilecoin/include/keys.h, libmobilecoin/include/transaction.h, libmobilecoin/libmobilecoin_cbindgen.h, libmobilecoin/src/common/buffer.rs, libmobilecoin/src/error.rs, libmobilecoin/src/keys.rs, libmobilecoin/src/transaction.rs, libmobilecoin/toolchain-config.env
Soundtrack of this PR: [Scruscru - Chewing Gum (feat. Sunner Soul)](https://youtu.be/79uwXIcuqvI)
iOS Bindings for Recoverable Transaction History (v1.2.0)
* iOS FFI/Bindings needed for the SDK to implement Recoverable Transaction History
* merge in `master` after this PR merges https://github.com/mobilecoinfoundation/mobilecoin/pull/1606
=> Recoverable Transaction History Bindings for iOS - v1.2.0

util/metrics/src/service_metrics.rs
Fog & Consensus outages often happen with not enough early warning nor enough context as to what's happening. Issue #1370 was created to address this. HTTP servers often track HTTP codes (2xx/3xx/4xx) but given FOG uses a lot of GRPC, OPS specified the desire to have GRPC response codes tracked in a similar manner. This PR slightly modifies existing GRPC tracking code to enable tracking response codes.
Upon approval, this tracker will be instrumented to track response codes of FOG services (ingest/server/etc.).
* Cleanup of 
* Cleanup of GRPC metrics documentation
* Track response codes of FOG GRPC methods
=> Add ability to count individual GRPC status codes

tools/dep-compare.py
At current revision it prints things like this
```
➜  mobilecoin git:(dep-compare-tool) ./tools/dep-compare.py
aead: root = {'0.4.1'}, fog_ledger = {'0.4.2'}
aho-corasick: root = {'0.7.10'}, consensus = {'0.7.8'}
aho-corasick: root = {'0.7.10'}, fog_ingest = {'0.7.6'}
aho-corasick: root = {'0.7.10'}, fog_ledger = {'0.7.18'}
aho-corasick: root = {'0.7.10'}, fog_view = {'0.7.6'}
anyhow: root = {'1.0.52'}, consensus = {'1.0.26'}
anyhow: root = {'1.0.52'}, fog_ingest = {'1.0.26'}
anyhow: root = {'1.0.52'}, fog_ledger = {'1.0.26'}
anyhow: root = {'1.0.52'}, fog_view = {'1.0.26'}
atty: root = {'0.2.14'}, fog_ingest = {'0.2.13'}
autocfg: root = {'1.0.0'}, consensus = {'1.0.1'}
autocfg: root = {'1.0.0'}, fog_ingest = {'1.0.1'}
autocfg: root = {'1.0.0'}, fog_ledger = {'1.0.1'}
autocfg: root = …
```
=> add a dep-compare python script

api/proto/external.proto, api/src/convert/mint_config.rs, api/src/convert/validated_mint_config.rs, consensus/mint-client/src/config.rs, consensus/service/src/mint_tx_manager/mod.rs, fog/ledger/test_infra/src/lib.rs, ledger/db/src/error.rs, ledger/db/src/ledger_trait.rs, ledger/db/src/lib.rs, ledger/db/src/mint_config_store.rs, ledger/db/src/mint_tx_store.rs, ledger/db/src/test_utils/mock_ledger.rs, mint-auditor/src/db.rs, transaction/core/src/mint/config.rs, transaction/core/src/mint/validation/config.rs, transaction/core/test-utils/src/mint.rs
Currently, each `MintConfigTx` configures a list of minters via an array of `MintConfig`s. Each `MintConfig` has a mint limit that caps the amount it can mint since the moment it has been applied.
As a secondary safety measure we want to also limit the total amount that can be minted by all `MintConfig`s together that are included in a single `MintConfigTx`.
* Add `total_mint_limit` to `MintConfigTx`, enforce it when trying to select active mint configurations, and add unit tests to verify correct behavior.
* Cleanup some error handling. Previously there existed an error variant `MintLimitExceeded(<new amount>, <limit>)`. That presented a problem, since it is possible that the new amount (which is `previous minted amount + amount we are trying to mint`) would exceed what can be …
=> Total mint limit per MintConfigTx

tools/fog-local-network/fog_local_network.py
fog_local_network.py was missing a comma in one of the shell commands.
This resulted in `-p mc-fog-test-client-p mc-fog-view-server` being
passed on the command line with an error of
`mc-fog-view-server not expected at this time`
minor python script fix
=> Add missing comma for fog_local_networ.py

libmobilecoin/include/transaction.h
Soundtrack of this PR: [Orlann Divo - Onde Anda O Meu Amor](https://youtu.be/fe-PXWEbCGg)
Function parameter types do not match definition.
* update to be correct.
=> Update iOS Bindings Header File Definition - `release-1.2.0`

util/build/info/build.rs
I'm not entirely sure why, but when attempting to build the mc-util-build-info
crate natively on Windows, I hit this error:
```
error: panic message is not a string literal
--> util\build\info\build.rs:40:26
|
40 |         Err(e) => panic!(e),
|                          ^
|
= note: `-D non-fmt-panic` implied by `-D warnings`
= note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
|
40 |         Err(e) => panic!("{}", e),
|                          ^^^^^
help: or use std::panic::panic_any instead
|
40 |         Err(e) => std::panic::panic_any(e),
|                   ^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
error: could not compile `mc-util-build-info`
To learn more, run the command again with --verbose.
warning: build failed, …
```
=> Fix trival format error build issue on native Windows builds.

Cargo.lock, Cargo.toml, consensus/service/Cargo.toml, consensus/service/config/Cargo.toml, consensus/service/config/src/error.rs, consensus/service/config/src/lib.rs, consensus/service/config/src/network.rs, consensus/service/config/src/tokens.rs, consensus/service/src/api/client_api_service.rs, consensus/service/src/bin/main.rs, consensus/service/src/consensus_service.rs, consensus/service/src/lib.rs
We need to make part of the `mc-consensus-service` crate reusable - specifically, for building the master minters admin key signing utility: we are going to need a utility that can parse the `tokens.toml` configuration file and sign some part of it (the master minters configuration). We don't want to utility to have to depend on `mc-consensus-service` since that crate has a lot of dependencies including the ability to build an enclave, and as such the configuration part of it is being separated into its own small crate that can then be re-used.
* Moving consensus service configuration into its own crate
* Some more explicit error handling
=> Move mc-consensus-service configuration into its own crate

util/grpc/src/lib.rs, util/metrics/src/service_metrics.rs
As part of #1370 operations has expressed the desire to be able to profile different gRPC status (and error) codes in a similar way to how HTTP codes are often profiled as 2XX/4XX/5XX, etc. so that errors in FOG & Consensus can be profiled and monitored for early alerts when FOG services become unhealthy. This PR enables Prometheus metrics to be shipped for most gRPC calls in Consensus & FOG.
* Implementation status code tracking in the "send_result" method in the mc-util-grpc lib that most FOG & Consensus grpc calls go through
* gRPC metrics service used by Mobilecoin was ported from a 3rd party with comments not up to MC doc standards. This PR improves them.
=> Monitor gRPC status codes with prometheus

consensus/enclave/api/src/config.rs, consensus/enclave/api/src/fee_map.rs, consensus/enclave/api/src/lib.rs, consensus/enclave/impl/src/constant_time_division.rs, consensus/enclave/impl/src/lib.rs, consensus/enclave/mock/src/lib.rs, consensus/service/src/validators.rs, tools/local-network/local_network.py
```
Make well-formed tx context hold a "priority" instead of fee.
This commit:
* Replaces the fee with priority in WellFormedTxContext
* Makes the enclave compute priority by dividing the fee by
minimum fee / 128, and discarding the remainder.
Dividing the minium fee by 128 first ensures that if e.g.
you pay minimum fee + 1%, that actually increases your
priority, and minimum fee + 2% increases your priority more
than that. Otherwise, minimum fee + 1% and minimum fee + 2%
would get rounded to the same priority value, and there would
be effectively no difference. If we don't dividie minimum fee
by 128 first, then you have to increase your fee in increments
of minimum fee to start actually seeing your transaction happen
faster, which seems like it would be harmful to a fee market
and lead …
```
=> Tx fee priority

consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs, crypto/keys/src/ed25519.rs
`mc-consensus-mint-client` is used to generate and sign `MintConfigTx`s and `MintTx`s. Prior to this PR, this requires having the private key(s) used for signing inside PEM file that is readable by the utility. This PR enables a new flow where the data to be signed (the hash of the tx prefix) can be generated, and then that hash can be signed offline or by an HSM. The produced signature, in hex bytes, can be fed back into the utility to generate a transaction.
Example usage:
1) Generate a hash for a `MintConfigTx`: `mc-consensus-mint-client hash-mint-config-tx --token-id 10 --config 10:1:minting1-public.pem --total-mint-limit 40 --tombstone 123 --nonce 33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333`
2) Take …
=> mc-consensus-mint-client improvements for offline/HSM flows

Cargo.lock, consensus/enclave/impl/src/lib.rs, consensus/service/Cargo.toml, consensus/service/src/byzantine_ledger/mod.rs, consensus/service/src/byzantine_ledger/worker.rs, consensus/service/src/consensus_service.rs, consensus/service/src/tx_manager/mod.rs, consensus/service/src/tx_manager/tx_manager_trait.rs, consensus/service/src/tx_manager/untrusted_interfaces.rs, consensus/service/src/validators.rs
`tx_hashes_to_block` currently lives inside `TxManager`, which is the object that deals with tracking `Tx`s (the original transaction type, as opposed to the newer mint-related transactions). During the work on adding minting this function was repurposed to get a list of values, that are now either a `Tx`, or a `MintTx` or a `MintConfigTx` and then use the consensus enclave to form a block from them.
This is hacky, and gets in the way of follow-up work on `MintTx` verification that we want to do - specifically, we want to have the enclave validate `MintTx`s against active `MintConfigTx`s, which means the active `MintConfigTx` information needs to make its way to the enclave. `TxManager` has no access to that, and while it could be bolted on that is wrong and repurposing the original …
=> Move tx_hashes_to_block out of TxManager

tools/fog-local-network/README.md
Make it easier for users to follow the readme instructions.
* Adds a missing flag in the `tools/fog-local-network/README.md` so that users can just copy and paste the command.
=> Add missing flag in tools/fog-local-network/README.md

fog/ledger/test_infra/src/lib.rs, ledger/db/src/ledger_trait.rs, ledger/db/src/lib.rs, ledger/db/src/mint_config_store.rs, ledger/db/src/test_utils/mock_ledger.rs
We're going to want to add an API endpoint to consensus that exposes the current minting configuration.
As part of that, it would be helpful to include a map of each configured token id and the associated mint config that is in the ledger.
This can be done by iterating over all configured token ids, but having a utility method that just returns a map with all the information that is in the database seems handy.
I built this in a different PR but then realized I don't need it there, however I will need it for the new configuration API endpoint.
* Add `LedgerDB::.get_active_mint_configs_map`
* Remove  method that is no longer used anywhere.
=> Add utility method `get_active_mint_configs_map` to LedgerDB

consensus/api/proto/consensus_common.proto, transaction/core/src/token.rs
this is desired because it prevents a breaking change in the consensus
proto file between 1.2.0 and 1.3.0 which would otherwise occur
The `TokenId` stuff is not active at this revision, but it is used
in the tokens.toml parsing which is used to configure consensus
at this revision, and would be hard to remove.
=> backport TokenId u32 -> u64 change

tools/local-network/send-mobilecoind-txs.sh
Working out mobilecoind based release issues has historically been very much a pain point and done manually. This script which works via mobilecoin-d json attempts to allow transaction testing via mobilecoind in a one command invocation. This alternatively can be used with the test network.
* A script which uses mobilecoind & mobilecoind-json to create payment monitors, import addresses, and start a payment loop (requires funded accounts)
* Allow for slightly more configuration possibly (pending outside opinions)
=> Test transaction automation script for mobilecoind release testing

libmobilecoin/include/transaction.h
Soundtrack of this PR: [Orlann Divo - Onde Anda O Meu Amor](https://youtu.be/fe-PXWEbCGg)
Function parameter types do not match definition.
* update to be correct.
=> Update iOS Bindings Header Definition - `master`

.github/workflows/mobilecoin-dispatch-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-dev-reset.yaml, .github/workflows/mobilecoin-dispatch-dev-test.yaml, .github/workflows/mobilecoin-dispatch-dev-update-consensus.yaml
Workflow_dispatch (manual) workflows must first exist in the default branch.  This PR adds minimum functionality workflow_dispatch definitions so we can run/integrate them with the release branch.
After we get things working with release/v1.2.0 we will start follow up work to catch up with the edge (1.3.x) deployments, charts and surrounding config. 
* `.github/workflows/mobilecoin-dispatch-dev-*` - placeholder workflows.
* Merge full workflows that will soon be integrated into the release/v1.2.0 in to master.
=> GHA CI/CD workflow_dispatch placeholders.

ledger/db/src/test_utils/mock_ledger.rs
As part of current efforts to improve the speed of block consumers and the network as a whole, the need has arisen to benchmark block consumer & streaming components. It's desired to be able to create test blocks with content that simulates blocks seen in production so that a proper benchmark can be made.
This PR adds an extra test method which generates blocks with custom content so that realistic benchmarks can be established.
* Addition of a method to the mock_ledger file which allows developers to create a custom amount of blocks with a custom amount of key_images, txouts per blocks, recipients, and token ids per block.
Used to fulfill the needs of #1798 & upcoming network improvement efforts
=> Create test blocks with custom content

transaction/core/src/validation/mod.rs, transaction/core/src/validation/validate.rs, transaction/core/tests/validation.rs
This works because, when cargo compiles in-line unit tests, they are
compiled into the module of the code under test, but when cargo
compiles integration tests (in tests directory), that is considered
a separate module (effectively a separate crate, just without its
own cargo toml).
This fixes the adapt hack issue because now we no longer need to
compile the `mc-transaction-core` crate in test mode, which also
references the `mc-transaction-core` crate which `mc-ledger-db`
depends on. The types in the test code always refer to the types
in the same version of `mc-transaction-core` that `mc-ledger-db`
is using
(This experiment came out of discussion in #1870 review)
---
This is not the only way we could fix it (remove adapt hack), we could also move validation to its own crate (this was …
=> move validation tests to be an integration test, remove adapt_hack

tools/lint.sh, transaction/core/src/ring_signature/rct_bulletproofs.rs, transaction/std/src/transaction_builder.rs, util/keyfile/src/keygen.rs, util/keyfile/tests/bin-determinism.rs
Add `clippy --all-targets`. Supports #1693
=> Add Clippy check to lint script

android-bindings/src/bindings.rs
Updating change subaddress to `u64::MAX - 1` to conform to [MCIP #36](https://github.com/mobilecoinfoundation/mcips/pull/36)
See also: #1859 
* Update change subaddress to `u64::MAX - 1`
=> Update Change Subaddress Index

mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/payments.rs, mobilecoind/src/service.rs
We'd like to test `mc-mint-auditor` in CD. As part of that, we need a way to generate burn transactions.
This PR adds an API to `mobilecoind` that allows generating such transactions. A burn transaction is a standard MobileCoin transaction that uses the [recently added](https://github.com/mobilecoinfoundation/mobilecoin/pull/1862) `BurnRedemptionMemo` memo for the `TxOut` that gets sent to the burn address.
* The aforementioned new API and tests for it.
* Exercise this in CD together with `mc-mint-auditor`.
=> API for generating burn txs in mobilecoind

Cargo.lock, consensus/enclave/trusted/Cargo.lock
Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=eFTLKWw542g)
Update a bunch of dependencies in prep for the new release.
* Update crossbeam-utils 0.8.5 to 0.8.8
* Update generic-array 0.12.3 to 0.12.4
* Update regex in consensus enclave to 1.5.5
* Update hyper from 0.14.16 to 0.14.18
* Update hyper from 0.12.35 to 0.12.36
* Update rusoto_s3 (and therefore ledger-distribution and it's dependencies)
* Update or replace rocket
* Update opentelemetry-jaeger
* PR against a release candidate branch for 1.2
=> Dependency updates (Part 1)

Cargo.lock, util/telemetry/Cargo.toml
This was needed since we had to upgrade opentelemetry-jaeger's
dependency on thrift, which in turn depended on a broken verison of
ordered-float.
The changes to opentelemetry-jaeger and thrift can be viewed here:
https://github.com/mobilecoinofficial/opentelemetry-rust/commit/1817229c56340bbb4a6dca63c8dfb5154606e5bf
https://github.com/mobilecoinofficial/thrift/commit/9caf65384c5ec50b4988e2fb07b984f275785123
=> Switch to using our fork of opentelemetry.

android-bindings/src/bindings.rs, api/proto/external.proto, api/src/convert/tx.rs, api/src/convert/tx_prefix.rs, consensus/enclave/impl/src/lib.rs, consensus/service/src/validators.rs, fog/distribution/src/main.rs, fog/sample-paykit/src/client.rs, libmobilecoin/src/transaction.rs, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, transaction/core/src/amount/mod.rs, transaction/core/src/tx.rs, transaction/core/src/validation/validate.rs, transaction/core/test-utils/src/lib.rs, transaction/std/src/memo_builder/mod.rs, transaction/std/src/memo_builder/rth_memo_builder.rs, transaction/std/src/transaction_builder.rs
The changes ported here, from (https://github.com/mobilecoinfoundation/mobilecoin/pull/1827) are:
* Rename `token_id` to `fee_token_id` in `TxPrefix`. This avoids a breaking
change between this and 1.3 in the hashes.
* Make `TransactionBuilder::new` take a fee amount instead of a fee token id
This also changes te memo builder trait, so that it will be compatible with
the burn redemption memo builder which we hope to port next.
This also makes `TransactionBuilder::new` possibly return an error.
* Adapt all clients and sdks for `TransactionBuilder::new` changes.
* Adapt all tests for this change
* Bring the  `Amount::new` function which makes the test code nicer.
This does NOT port:
* Any other changes to transaction builder or tx protos
* The change that makes `add_output` take an amount …
=> port a select subset of the changes from mixed transactions for candidate 1.2

mobilecoind-json/tests/integration_test.py
There's no need for 10 subaddresses in this test, and, more importantly this  makes the test compatible with the drain_accounts.py script which also uses 1 subaddress.
This is needed for running this script as part of the Jenkins CD process.
=> Small adjustment to mobilecoind-json test script that makes it compatible with other test scripts

Cargo.lock, android-bindings/src/bindings.rs, fog/sample-paykit/src/cached_tx_data/memo_handler.rs, mobilecoind-json/src/data_types.rs, mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, mobilecoind/strategies/accounts.py, transaction/core/src/tx_error.rs, transaction/std/Cargo.toml, transaction/std/src/lib.rs, transaction/std/src/memo/burn_redemption.rs, transaction/std/src/memo/mod.rs, transaction/std/src/memo_builder/burn_redemption_memo_builder.rs, transaction/std/src/memo_builder/mod.rs, transaction/std/src/transaction_builder.rs, util/keyfile/src/bin/keygen_main.rs, util/keyfile/src/bin/sample_keys_main.rs, util/keyfile/src/config.rs, util/keyfile/src/keygen.rs, util/keyfile/src/lib.rs
This PR cherry-picks a series of PRs in master branch which landed after Mixed transactions, to the candidate 1.2 branch.
It is staged after the PR that moves pieces of Mixed transactions to candidate 1.2 branch.
The PRs that are picked are:
a26b06fea71f783fbb0399b0cca6026d2453b258 "[Initial take on implementing Burn Redemption Memo](https://github.com/mobilecoinfoundation/mobilecoin/commit/a26b06fea71f783fbb0399b0cca6026d2453b258)" (eran)
e4038aabce65e3752780e6dc3fe9a0b487d03bd1"[Update Change Subaddress Index (](https://github.com/mobilecoinfoundation/mobilecoin/commit/e4038aabce65e3752780e6dc3fe9a0b487d03bd1)[#1880](https://github.com/mobilecoinfoundation/mobilecoin/pull/1880)[)](https://github.com/mobilecoinfoundation/mobilecoin/commit/e4038aabce65e3752780e6dc3fe9a0b487d03bd1)" …
=> Port to candidate 1.2

consensus/scp/tests/mock_network/mod.rs, consensus/service/src/consensus_service.rs, util/grpc/src/grpcio_extensions.rs
There were intermittent issues when clients would lose connection to the server. 
* added a default config for server
#1582
=> added extra configuration consensus service serve side.

Cargo.lock, ledger/distribution/Cargo.toml, ledger/distribution/src/main.rs
Effectively a revert of #1435, with a couple of extra changes to improve error output, and fail after 100 attempts to upload a block.
This should fix most of the remaining Dependabot security alerts.
=> Upgrade rusoto_s3 from 0.42 to 0.48.

hooks/pre-commit
Our current CI uses cargo-sort to ensure our Cargo.toml dependencies are sorted. This adds a check for this to the pre-commit githook.
- Update precommit hook to install/use cargo sort.
- Redirect sort output to dev null.
- Do version checks first, then do tests, pipe some junk to /dev/null.
- Don't print "OK" for rustfmt check, version is sufficient.
=> Add cargo-sort to the pre-commit hook

.github/pull_request_template.md
- Remove the "In this PR section", Soundtrack to end
- Comment out the prompts
Right now, the GH CLI will prepend any commits on your branch to the start of an existing PR template. This is slightly irritating because "In this PR" is the *second* section in our template. This PR attempts to make the template easier to use from within the GH CLI by making the existing "fill stuff in here" prompts comments, and removing the "In this PR" section entirely (so the first thing in the PR is that list.)
=> GH-CLI Friendly PR Template

transaction/std/src/lib.rs, transaction/std/src/test_utils.rs, transaction/std/src/transaction_builder.rs
(This is staged after the mixed transactions PR, and prepares for signed contingent input PR)
This is just code movement and should not be changing any functionality
=> Make a transaction-std-test-utils module, to help code reuse

android-bindings/makefile, android-bindings/src/bindings.rs
Refactor Android Bindings Amount to MaskedAmount
Updating Android SDK protobufs
This is needed in order for the name of the Java object to match the name of the Rust struct and avoid confusion caused by the AmountData -> Amount Rust refactor.
=> Amount -> MaskedAmount

Cargo.lock, consensus/enclave/impl/Cargo.toml, consensus/enclave/impl/build.rs, consensus/enclave/trusted/Cargo.lock
Currently, the consensus enclave build script allows passing in the minting trust root public key as hex-encoded bytes of an Ed25519 public key. This is useful, since mainnet builds need a different key than testnet, and testnet needs a different key than the dev networks, and so on. However, there is no convenient way to get these hex-encoded bytes from a PEM private key. It is however trivial to get a PEM public key file (`openssl pkey -pubout`).
As such, the ops team requested that the environment variable configuring the key changes to pointing a PEM file that contains an Ed25519 public key.
=> allow providing minting trust root public key via a PEM file instead hex bytes

android-bindings/src/bindings.rs
Renamed unmask_value to unmask_amount
unmask_amount now returns both unmasked value and unmasked token id
This is needed for the SDK to recover the token ID of a masked amount
Parameterize tx builder for token ID
=> unmask_value -> unmask_amount

api/proto/printable.proto, api/src/convert/mod.rs, api/src/convert/tx_out_gift_code.rs, transaction/core/src/gift_code.rs, transaction/core/src/lib.rs, transaction/core/src/tx_out_gift_code.rs
Add a new protobuf for the gift code message payload which conforms to the new design for gift codes specified in [#MCIP 32](https://github.com/garbageslam/mcips/blob/fog-compatible-gift-codes/text/0032-fog-compatible-gift-codes.md) and rust equivalent object.
A message format needs to be used to communicate that MobileCoin account holder has sent a gift code TxOut with enough information for the receiver to find the TxOut, unmask its amount, and spend the TxOut.
[Add libmobilecoin and android ffis for building gift codes](https://github.com/mobilecoinfoundation/mobilecoin/issues/1945)
[Add mobilecoind codepaths for creating & sending gift codes](https://github.com/mobilecoinfoundation/mobilecoin/issues/1946)
[Update InputCredentials](https://github.com/mobilecoinfoundation/mobilecoin/issu …
=> Add proto schema for GiftCode and rust equivalent object 

Cargo.lock, consensus/mint-client/Cargo.toml, consensus/mint-client/src/bin/main.rs
The `mc-consensus-mint-client` binary could potentially be called by other binaries or shell scripts. If it is used to submit a `MintTx` or `MintConfigTx` to consensus, it might get to the point where the RPC call succeeds but consensus rejects the transaction.
Prior to this PR the only way to tell that this happened is to parse the response that is printed to `stdout`, however that is inconvenient. It is a convention in the UNIX world that processes exit with exitcode 0 upon success, and a different value upon failure.
This PR makes it so that if consensus did reject a transaction, the error code is propagated as an exitcode.
=> mint-client: make the process exitcode reflect transaction status returned from consensus when a transaction is submitted

Cargo.lock, fog/sample-paykit/src/cached_tx_data/memo_handler.rs, transaction/core/src/memo.rs, transaction/std/Cargo.toml, transaction/std/src/memo/gift_code_cancellation.rs, transaction/std/src/memo/gift_code_funding.rs, transaction/std/src/memo/gift_code_sender.rs, transaction/std/src/memo/mod.rs
As a part of [MCIP 32](https://github.com/mobilecoinfoundation/mcips/blob/main/text/0032-fog-compatible-gift-codes.md), 3 new memo types were specified:
| Memo type bytes | Name                                              |
| -----------     | -----------                                       |
| 0x0201          | Gift code funding memo                            |
| 0x0202          | Gift code cancellation memo                       |
| 0x0002          | Gift code sender memo                       |
This pull request implements the memo types for the MCIP.  Specific questions exist about whether the gift code funding memo should involve constant time operations when validating the TxOut hash.
Implementation of the 3 memo types specified in MCIP 32
Addresses work specified in #1735 
* …
=> Gift Code Memos

consensus/enclave/api/src/config.rs, consensus/enclave/api/src/fee_map.rs, consensus/enclave/impl/src/lib.rs, consensus/service/config/src/tokens.rs, consensus/service/src/api/blockchain_api_service.rs, tools/local-network/local_network.py
We determined that, if the minimum fee of a token is not divisible by the global minimum, it can cause an information leakage, because paying the minimum fee for that token does not lead to a priority of 128 like everything else.
There are several possible ways to try to mitigate this, but right now the least disruptive (in terms of changing business logic, and MCIPs) is to enforce this rule in the fee map validation. (And for good measure we check that in the enclave init function.)
This does not cause any problems for any existing currencies like MOB, because the mob minimum fee is 4 * 10^9, and we are only requiring that it is divisible by 2^7, which it is. It is likely that most currencies will have a minimum fee value with > 6 zeroes or so, and so they will easily satisfy this …
=> Make fee map enforce divisibility by minimum fee. Also check this in enclave impl

Cargo.lock, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock, transaction/core/Cargo.toml, transaction/core/src/ring_signature/error.rs, transaction/core/src/ring_signature/rct_bulletproofs.rs, util/zip-exact/Cargo.toml, util/zip-exact/README.md, util/zip-exact/src/lib.rs
This is intended to ease maintenance of the `rct_bulletproofs` module,
since accidentally removing or wrongly implementing a length check
no longer silently leads to transaction elements being skipped.
Fixes #1869
I think this version was less annoying in terms of syntax explosion
=> New attempt at zip_exact utility

connection/src/manager.rs, connection/test-utils/src/lib.rs, ledger/sync/src/network_state/polling_network_state.rs, mobilecoind/src/test_utils.rs, util/uri/src/traits.rs
See #848. 
* Creates and uses `host_and_port_responder_id` method.
* Updates mobilecoind test configuration to test this new feature 
Fixes #848
=> Create ResponderId out of host and port in PollingNetworkState

consensus/service/src/validators.rs, mint-auditor/src/counters.rs, mint-auditor/tests/compile_proto.sh, mint-auditor/tests/integration_test.py, tools/local-network/local_network.py
We'd like to exercise the `mc-mint-auditor` service in the Jenkins CD pipeline (and as a bonus to exercise `mobilecoind`'s burn transactions). This PR adds an integration test that is ran by Jenkins upon deployment to a k8 dev network that connects to the mint auditor and verifies that minting and burning gets properly tracked.
I have the accompanying `internal` PR ready (and passing deployment), I will submit it as an uprev PR once this gets merged.
=> Add a mint auditor integration test to be used in CD.

transaction/core/src/tx.rs
```
Mark fee_token_id as `omit_when = 0`
The fee token id, which is a new field in 1.2, needs to be marked
`omit_when = 0`, otherwise there is no way for clients to be
compatible with 1.1 and 1.2.
This needs to be done whenever we add a numeric field to a proto
that is hashed into the blockchain, otherwise the schema evolution
strategy for hashing doesn't work.
(It really should have been the default for hashing integers,
because it's so easy to miss this,
but it's probably too late to change that now.)
```
=> Mark fee_token_id as `omit_when = 0`

transaction/core/src/tx.rs
The fee token id, which is a new field in 1.2, needs to be marked
`omit_when = 0`, otherwise there is no way for clients to be
compatible with 1.1 and 1.2.
This needs to be done whenever we add a numeric field to a proto
that is hashed into the blockchain, otherwise the schema evolution
strategy for hashing doesn't work.
(It really should have been the default for hashing integers,
because it's so easy to miss this,
but it's probably too late to change that now.)
---
This is a cherry-pick of 19f0aeb8625e865f4ce992b7d40427774ba33936
There were no conflicts
=> Mark fee_token_id as `omit_when = 0` (#1978)

android-bindings/makefile, android-bindings/src/bindings.rs, libmobilecoin/include/transaction.h, libmobilecoin/libmobilecoin_cbindgen.h, libmobilecoin/src/transaction.rs, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, transaction/std/src/lib.rs, transaction/std/src/transaction_builder.rs
* Adding TxOutContext struct to return TxOut, TxOutConfirmationNumber, and a shared secret from transaction builder add_output
* Adding iOS native updates to expose TxOutContext to SDK
* Adding Android native updates to expose TxOutContext to SDK
This is needed for the SDKs to support Moby transaction history
=> TransactionBuilder TxOutContext

consensus/service/src/api/grpc_error.rs
Logging at error causes a sentry alert, and so if a client like
fog distro is in a retry loop submitting transactions and getting
this error, it can blow out our sentry quota
=> make permission denied log level be info

consensus/service/src/api/grpc_error.rs
Logging at error causes a sentry alert, and so if a client like
fog distro is in a retry loop submitting transactions and getting
this error, it can blow out our sentry quota
---
This cherry-picks #1997 from master, there were no conflicts
=> make permission denied log level be info (#1997)

Cargo.lock, consensus/mint-client/Cargo.toml, consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs, consensus/mint-client/src/lib.rs, consensus/mint-client/src/printers.rs, consensus/mint-client/src/tx_file.rs
While planning out potential flows for the minting process, we realized there are some missing features in the minting client that will make it more ergonomic. This PR:
* Makes it so that the `MintConfigTx` and `MintTx` JSON files that are read/written by the utility are now using a unified `TxFile` enum. This guarantees the correct file is passed, and provides a user-friendly error message if the user mixes the two unintentionally. 
* Adds a `Dump` sub-command that prints a human-friendly representation of whats in a given json file. This makes it easier for users to verify they are operating on the file they think they're operating on.
* Adds a `Sign` sub-command that takes a tx file, and a list of signer keys or signatures and appends them to the multisig.
* Allows omitting …
=> Implement some improvements to the `mc-consensus-mint-client` utility

account-keys/src/account_keys.rs, account-keys/src/lib.rs, transaction/core/src/memo.rs, transaction/core/src/tx_error.rs, transaction/std/src/lib.rs, transaction/std/src/memo_builder/gift_code_cancellation_memo_builder.rs, transaction/std/src/memo_builder/gift_code_funding_memo_builder.rs, transaction/std/src/memo_builder/gift_code_sender_memo_builder.rs, transaction/std/src/memo_builder/mod.rs, transaction/std/src/test_utils.rs, transaction/std/src/transaction_builder.rs
Build transaction builders for gift codes. Tracks #1735.
* A transaction builder for each gift code memo type
* Create a protobuf message schema for TxOutGiftCode and relevant conversions in mc-api
* Add a gift code tx path in transaction builder
* Make code paths for libsignal ffis & mobilecoind to use to build gift code transactions
=> Gift Code Memo Builder

ledger/streaming/api/Cargo.toml, ledger/streaming/client/Cargo.toml, ledger/streaming/publisher/Cargo.toml
Complements #1960 for this feature branch.
=> Update ledger/streaming crates to use Rust edition 2021

Cargo.lock, Cargo.toml, consensus/enclave/trusted/Cargo.lock, consensus/enclave/trusted/Cargo.toml, fog/ingest/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.toml, fog/ledger/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.toml, fog/view/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.toml
- Update mbedtls workspace patches to newer tag.
rust-mbedtls was previously using an ancient version of `spin`. This new revision of that repo has been moved to the mobilecoinfoundation GH org, and passes unit tests.
=> Uprev mbedtls to mc-0.5 in foundation repo.

android-bindings/src/bindings.rs, api/src/convert/tx.rs, api/tests/prost.rs, fog/sample-paykit/src/client.rs, libmobilecoin/src/transaction.rs, mobilecoind/src/payments.rs, transaction/std/src/lib.rs, transaction/std/src/memo_builder/burn_redemption_memo_builder.rs, transaction/std/src/memo_builder/gift_code_cancellation_memo_builder.rs, transaction/std/src/memo_builder/gift_code_funding_memo_builder.rs, transaction/std/src/memo_builder/gift_code_sender_memo_builder.rs, transaction/std/src/memo_builder/mod.rs, transaction/std/src/memo_builder/rth_memo_builder.rs, transaction/std/src/reserved_subaddresses.rs, transaction/std/src/signed_contingent_input_builder.rs, transaction/std/src/test_utils.rs, transaction/std/src/transaction_builder.rs
*ReservedDestination renamed to ReservedSubaddresses
ReservedDestination is a struct that resolves reserved subaddresses for a given set of account keys. Its naming has led to some confusion. This rename clarifies the purpose of the struct by.
=> Rename ReservedDestination to ReservedSubaddresses

Cargo.lock, Cargo.toml, admin-http-gateway/Cargo.toml, admin-http-gateway/src/main.rs, consensus/enclave/trusted/Cargo.lock, consensus/enclave/trusted/Cargo.toml, consensus/mint-client/Cargo.toml, consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs, consensus/mint-client/src/lib.rs, consensus/mint-client/src/printers.rs, consensus/mint-client/src/tx_file.rs, consensus/scp/Cargo.toml, consensus/scp/src/slot.rs, consensus/scp/src/utils.rs, fog/ingest/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.toml, fog/ledger/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.toml, fog/overseer/server/Cargo.toml, fog/overseer/server/src/bin/main.rs, fog/view/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.toml, mobilecoind-json/Cargo.toml, mobilecoind-json/src/bin/main.rs
- Bump ed25519
- Bump rayon 
- Bump rocket
- Bump mbedtls
- mint-client improvements
- Remove bigint in favor of primitive-types
=> Cherry-pick updates from master.

mobilecoind/src/bin/main.rs, mobilecoind/src/config.rs
This simplifies the ops aspect of running `mobilecoind`: with this change there doesn't need to be logic on whether to run mobilecoind with the migration flag when the ledger already exists or without it when `mobilecoind` is started for the first time and is bootstrapping the ledger.
=> mobilecoind: only attempt to migrate the ledger if it exists

mobilecoind/strategies/accounts.py
```
We decided that we probably don't have to make it load the old non-b58
pub address file format, because we don't need it to be able to send to
old accounts, only send from old accounts to new accounts. So we didn't
change that.
```
=> Make mobilecoind python able to load both root entropy and mnemonic accounts

android-bindings/src/bindings.rs, api/src/convert/tx.rs, api/tests/prost.rs, consensus/api/src/conversions.rs, consensus/service/src/validators.rs, fog/distribution/src/main.rs, fog/sample-paykit/src/client.rs, libmobilecoin/src/transaction.rs, mobilecoind/src/payments.rs, transaction/core/src/amount/commitment.rs, transaction/core/src/lib.rs, transaction/core/src/ring_signature/error.rs, transaction/core/src/ring_signature/mlsag.rs, transaction/core/src/ring_signature/rct_bulletproofs.rs, transaction/core/src/signed_contingent_input.rs, transaction/core/src/signer/README.md, transaction/core/src/signer/dummy_signer.rs, transaction/core/src/signer/local_signer.rs, transaction/core/src/signer/mod.rs, transaction/core/src/signer/no_keys_ring_signer.rs, transaction/core/src/signer/traits.rs, transaction/core/src/tx.rs, transaction/core/test-utils/src/lib.rs, transaction/std/src/error.rs, transaction/std/src/input_credentials.rs, transaction/std/src/signed_contingent_input_builder.rs, transaction/std/src/test_utils.rs, transaction/std/src/transaction_builder.rs
The goal here is to create a `RingSigner` trait that takes arguments and produces a `RingMLSAG`.
The trait should be an appropriate API for a hardware wallet -- the caller need not have the private spend key, and the callee who does have the private spend key has everything they need to produce a `RingMLSAG` conferring spend authority.
There are fundamentally two changes
* Previously, an `InputSecret`, and an `InputCredentials`, contains the one-time-private key. However, in a hardware wallet world, it's not acceptable to have this on the online machine, since it can be used to spend the `TxOut`.
* Therefore, we changed `InputSecret` so that instead it contains the subaddress index of the true input, and the `RingSigner` has the responsibility for computing the one-time private key. Then, …
=> introduce a ring signer trait and use it

fog/distribution/src/main.rs, fog/test-client/src/config.rs, util/keyfile/src/keygen.rs, util/keyfile/src/lib.rs
this was requested by ops to ease release testing
=> make test-client and fog-distro able to read keyfiles in both formats

fog/distribution/src/main.rs, fog/test-client/src/config.rs, util/keyfile/src/keygen.rs, util/keyfile/src/lib.rs
* make test-client and fog-distro able to read keyfiles in both formats
* clippy
this is a cherrypick of #2019 , there were no conflicts
=> make test-client and fog-distro able to read keyfiles in both formats (#2019)

MAINNET.md, consensus/service/README.md, jenkins/Jenkinsfile, start-testnet-client.sh, tools/fog-local-network/README.md, tools/fog-local-network/fog_local_network.py, tools/fog-local-network/local_fog.py, tools/local-network/local_network.py, tools/local-network/mobilecoind.sh
Previously the local_network script looked in `target/release` for the
binaries.  Now the local_network script will attempt to use the
`CARGO_TARGET_DIR` if it's set.
Also updates associated markdown files so copy and paste of commands
works in docker containers.
The local_network script no longer works without local modification when run from inside of the docker image via `./mob prompt`
=> Update local_network script for new docker target dir

consensus/enclave/measurement/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ledger/enclave/measurement/build.rs, fog/view/enclave/measurement/build.rs
- Increase consensus enclave isv_svn to 4.
- Increase view, ingest, and ledger enclave isv_svn to 3.
This is how MRSIGNER-based validators select minimum supported versions.
=> Bump enclave security versions

hooks/pre-commit
There is a subtle issue where, whenever formatting is necessary,
the `$diff` variable starts with a blank line. This is because
we add things to `$diff` by setting `$diff = $diff\n$next`, so
the first item always sticks a new line in there even though it
is the first one.
(I discovered this first when doing the copyright check work.)
I think this means that when doing a formatting check, we do a
`cargo fmt` call over the entire repo first, then over each individual
file in the diff. It will probably be a lot faster if we don't do
the entire repo first, and only do the individual files of the diff,
which I think was the original intent.
=> fix formatting check in pre-commit

util/keyfile/src/bin/read_pubfile.rs
This is a cherry-pick of https://github.com/mobilecoinfoundation/mobilecoin/pull/2036 to `release/v1.2.0`, there were no conflicts
=> Make the read_pubfile tool able to create b58 encoded files optionally

connection/src/thick.rs, connection/src/traits.rs, fog/enclave_connection/src/error.rs, fog/ingest/server/src/connection_error.rs, peers/src/error.rs
A change introduced in https://github.com/mobilecoinfoundation/mobilecoin/pull/1592 results in clients not re-attesting. This happens because the code in https://github.com/mobilecoinfoundation/mobilecoin/blob/eran/async-reattest-bugfix/connection/src/traits.rs#L53 now only runs of if the async call (e.g. `client_tx_propose_async_opt`) fails to queue a request. If it succeeds, then the actual result returned from the server would only get checked in https://github.com/mobilecoinfoundation/mobilecoin/blob/eran/async-reattest-bugfix/connection/src/thick.rs#L211 and currently that does not handle re-attestation.
Unit tests...
=> fix a regression that prevented clients from re-attesting

connection/src/thick.rs, connection/src/traits.rs, fog/enclave_connection/src/error.rs, fog/ingest/server/src/connection_error.rs, peers/src/error.rs
Cherrypick a fix to `ThickClient`. Without this, re-attestation does not take place.
=> fix a regression that prevented clients from re-attesting (#2038)

mobilecoind/strategies/drain-accounts.py
I am not sure if there's a better way to detect the error than searching for strings in the details, but this currently seems to me like the best available way.
we may backport this to 1.2
additional context:
This is what an insufficient funds error looks like, in release testing:
```
INFO:drain-accounts:82: Time to sync: 3.0057718753814697
INFO:drain-accounts:87: Starting balance prior to transfer: 237500000000000000
Traceback (most recent call last):
File "drain-accounts.py", line 162, in <module>
run_test(stub, amount, src_account.monitor_id, dest, args.max_seconds, args.token_id)
File "drain-accounts.py", line 88, in run_test
tx_resp = stub.SendPayment(
File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
return _end_unary_response_blocking(state, …
```
=> make drain accounts script handle defragmentation errors

mobilecoind-json/tests/integration_test.py
This picks #2043 from release 1.2, there were no conflicts
---
* make mobilecoind-json integration test work with mnemonics
* fix mistakes
* remoun improvement
* derp
* simplify
=> make mobilecoind-json integration test work with root entropy accounts (#2043)

transaction/core/src/memo.rs, transaction/core/src/tx_error.rs, transaction/std/src/memo/gift_code_cancellation.rs, transaction/std/src/memo/gift_code_funding.rs, transaction/std/src/memo/gift_code_sender.rs, transaction/std/src/memo_builder/gift_code_cancellation_memo_builder.rs, transaction/std/src/memo_builder/gift_code_funding_memo_builder.rs, transaction/std/src/memo_builder/gift_code_sender_memo_builder.rs, transaction/std/src/test_utils.rs, transaction/std/src/transaction_builder.rs
* Added fee bytes to gift code memos
* Added methods for setting/extracting fees
* Added extra tests & error checking
It was determined that fees should be added to gift code memos. This PR adds fee bytes to gift code memos and updates tests, checks, and documentation to reflect those changes.
* The fees are tracked in big endian bytes, but the index on the gift code cancellation memo was originally in little endian bytes. Shall we just make the index tracked in big endian bytes as well?
* Add method in transaction builder to allow gift codes to be funded
* Work Remaining in: #1735
=> Add fees to gift code memos

.internal-ci/helm/fog-services/templates/fog-report-deployment.yaml, .internal-ci/helm/fog-services/templates/fog-view-deployment.yaml
Gateways were misconfigured to try and reach their downstream services on the wrong ports.
=> Fix json to grpc gw ports.

android-bindings/src/bindings.rs
Parameterize TransactionBuilder Android bindings for token ID
This is needed in order for the Android SDK to handle multiple different token IDs
=> Parameterize TransactionBuilder for Token ID

transaction/core/src/constants.rs
The rationale for this change is as follows:
* We need to greatly increase the time that mint agents have to complete multisig transactions
* There may also be exchanges doing off-line transaction flows that are impacted by the 100 number
* It's fine to have a limit like this but putting it in the signed enclave makes it extremely difficult to change
* In a 1.2.1 release we can make it so that this max tombstone limit is primarily enforced in the transaction queue rather than in the enclave -- if we don't want to have normal transactions that might wait around for 20,000 blocks, then we can do that in an untrusted side release at our leisure.
Client impact of the change:
A git grep in mobilecoin repo reveals the following consumers:
```
consensus/enclave/impl/src/lib.rs: …
```
=> Adjust max tombstone blocks

consensus/scp/src/test_utils.rs, consensus/scp/tests/mock_network/mod.rs, consensus/service/src/byzantine_ledger/mod.rs, crypto/noise/src/symmetric_state.rs, fog/ingest/enclave/impl/src/rng_store.rs, fog/ledger/connection/src/block.rs, fog/ledger/connection/src/untrusted.rs, fog/ocall_oram_storage/trusted/src/lib.rs, fog/view/enclave/impl/src/e_tx_out_store.rs, peers/test-utils/src/lib.rs, transaction/core/tests/util/mod.rs
* Dedupe `test_node_id` and `test_peer_uri`
* Change `allow(unused)` to the more specific `allow(dead_code)`
* Rearrange some `allow` instances
=> Clean up some test helpers

.github/workflows/mobilecoin-dispatch-mainnet-build.yaml, .github/workflows/mobilecoin-dispatch-testnet-build.yaml
Run testnet/mainnet builds and release from automation with prebuilt and signed enclaves.  This will be a manual run process.
- GitHub actions require a dispatch (manual run) action to be defined in the repo default branch to activate runs. 
- Add placeholder dispatch actions so we can develop/run this automation from another branch.
=> Add placeholders for testnet/mainnet build automation.

watcher/src/watcher.rs
Logging URLs in watcher currently is unnecessarily human-unreadable. `as_str()` makes it human readable to decrease cognitive load of reading logs.
Resolves #2021
=> Instead of logging the URL struct with debug formatting, log it with no formatting since it implements the Display printer

.internal-ci/docker/Dockerfile.node_hw
- Forgot to put the sample-keys.1.1.3 binary to re-hydrate root entropy wallet keys from seeds.  
- After we do the full release we can deprecate these older binaries/methods.
=> build 1.2.0 without an upgrade

fog/ingest/server/src/controller.rs
Soundtrack of this PR: [The Impressions - It's All Right](https://www.youtube.com/watch?v=Y1LLwC7N1h8)
Bringing forward changes which were in progress before moving the fog repo to the unified repo.
* Reduce log level of failure to publish report to DB
Context from [mobilecoinfoundation/fog#147]:
```
Sometimes, we lose connection to the sql DB, and the report server write operation fails.
This should not be logged as an error because it's not actionable and errors get converted to sentry alerts.
```
Fixes [mobilecoinfoundation/fog#147] and [mobilecoinfoundation/mobilecoin#1892].
=> Reduce log level of failure to publish report to DB

libmobilecoin/include/keys.h, libmobilecoin/include/transaction.h, libmobilecoin/libmobilecoin_cbindgen.h, libmobilecoin/src/keys.rs, libmobilecoin/src/transaction.rs
Add getters for shared_secret and root_entropy to LibMobileCoin
Getters are needed for shared_secret, and root_entropy requirements have changed so the removed implementation has been re-added.
[Loose Ends - Lets Wax a Fatty](https://www.youtube.com/watch?v=CBN5c1E8nZI)
=> Add get shared_secret & root_entropy FFIs to LibMobileCoin

android-bindings/src/bindings.rs
Update unmask_amount binding to use the new Amount constructor so the old one can be removed
Between the tagging of the 1.2.0 release in the MobileCoin repo and the android-sdk repo, the Amount constructor signature was changed. A private constructor matching the old signature was added to the SDK for compatibility with the MobileCoin 1.2.0 bindings release. This PR just updates the bindings so that the extra private constructor is no longer needed.
=> Use new TokenId class to create Amount

mobilecoind/src/config.rs
Without this change we get a missing import error upon compilation of `mobilecoind` with `--no-default-features`
=> fix mobilecoind build when the ip-check is not enabled

consensus/enclave/impl/src/lib.rs, consensus/service/src/mint_tx_manager/mod.rs, consensus/service/src/validators.rs, fog/distribution/tests/bootstrap.rs, fog/ingest/enclave/impl/tests/tx_processing.rs, fog/ledger/server/tests/connection.rs, fog/test_infra/src/bin/add_test_block.rs, fog/view/protocol/src/user_private.rs, ledger/db/src/ledger_db.rs, ledger/db/src/test_utils/mock_ledger.rs, mint-auditor/src/db/mod.rs, mint-auditor/src/service.rs, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, mobilecoind/src/test_utils.rs, test-vectors/tx-out-records/build.rs, transaction/core/src/blockchain/block.rs, transaction/core/src/tx.rs, transaction/core/src/tx_error.rs, transaction/core/test-utils/src/lib.rs, transaction/core/tests/digest-test-vectors.rs, transaction/std/src/signed_contingent_input_builder.rs, transaction/std/src/test_utils.rs, transaction/std/src/transaction_builder.rs, util/generate-sample-ledger/src/lib.rs
This makes it easier to make `TxOut` that conform to certain
structural rules, which is important for compatibility testing.
Fixes #1749
This will make it easier to execute #2081
=> Make `TxOut::new` take a block version

Cargo.lock, fog/api/proto/view.proto, fog/uri/src/lib.rs, fog/view/connection/Cargo.toml, fog/view/connection/src/bin/router_client.rs, fog/view/connection/src/fog_view_router_client.rs, fog/view/connection/src/lib.rs, fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/src/fog_view_router_server.rs, fog/view/server/src/fog_view_router_service.rs, fog/view/server/src/lib.rs
This is the first PR in a series of PRs that implement the Fog View Router service as described in the design [doc](https://docs.google.com/document/d/1-ju5efGK6vvuYjxj1pKhfFcpgGlornuxZYvOC-nsbjs/edit?usp=sharing). 
This PR implements the "bare bones" structure of the Fog View Router service, meaning that it defines the gRPC API in a proto file, sets up the canonical MobileCoin server + service gRPC structure, and implements the general shape of the async / future paradigm that will be used by the service when the actual logic is implemented
- This PR address the first item in the #2028 ticket. Future PRs will address each additional item.
=> Implement bare bones FogViewRouterAPI server + client

libmobilecoin/include/transaction.h, libmobilecoin/libmobilecoin_cbindgen.h, libmobilecoin/src/transaction.rs
In libmobilecoin:
* Added transaction builder method for funding gift code outputs
* Added methods for creating gift code memo builders
* Added methods for creating & reading gift code memos
* Added corresponding cbindgen bindings
* FFI method for discovery of gift code TxOuts
* libmobilecoin binding test coverage
Adding these methods adds the ability for the iOS mobile SDK to enable the functionality for TxOut gift codes
* Add Android bindings
* Add mobilecoind gift code support
* Assist full service in supporting TxOut gift codes
* Do end to end testing
=> Add libmobilecoin support for gift codes

android-bindings/src/bindings.rs, android-bindings/src/error.rs
* Added FFI methods for making gift code outputs, memo builders, and retrieving gift code memo data
* Added a few error conversions to error enum
Provide Android SDK with the ability to make gift code transactions, and read/write gift code memos.
* Add mobilecoind support for gift codes
* Support end to end testing
* Support SDK & full service teams in full implementation of TxOut gift codes
=> Android ffi bindings for gift codes

BUILD.md, mob
Like #2027, this change allows external tools, such as rust-analyzer, to run `cargo check` inside the docker environment, improving the development experience for people who can't install the SGX SDK locally.
This approach is more flexible than that in #2027, and no longer hard-codes any specific command.
I believe this approach is reliable under argparse's non-standard argument parsing, but if that proves to not be the case another option could be to take the command line as a single string, potentially requiring the user to escape it.
=> Add a new "cmd" argument to mob prompt

Cargo.lock, android-bindings/lib-wrapper/android-bindings/publish.gradle, common/Cargo.toml, go-grpc-gateway/testing/Cargo.toml, util/cli/Cargo.toml
`mc-util-cli` and `go-grpc-gateway-testing` depend on `mc-*` crates, so use the same version.
Found via the following command: `find . -iname "*.toml" | xargs grep '^version *=' | grep -v 'version = "1.3.0-pre0"'`
With this change, this command no longer yields any results.
=> Update all crate versions to match the current version

Cargo.lock, fog/uri/src/lib.rs, fog/view/enclave/api/Cargo.toml, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/Cargo.toml, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/src/lib.rs, fog/view/server/src/fog_view_router_service.rs
This is the second PR for the Fog View Router project. As described in the design [doc](https://docs.google.com/document/d/1-ju5efGK6vvuYjxj1pKhfFcpgGlornuxZYvOC-nsbjs/edit), the router receives a client query request, decrypts it, and then re-encrypts it for each Fog View Store that it knows about. This PR implements the view enclave API that performs this decryption and re-encryption step. In the next PR, I'll implement the logic that takes the output of this API and creates a MultiViewStoreQuery (see the design doc for the definition of this message)
Addresses the second item in #2028 
- Use the output of the API to create the MultiViewStoreQuery and send it to the Fog View Load Balancers
=> Implement create_multi_view_query_data API for Fog View Router

fog/README.md
Mailto link was broken. Was trying to send to:
- `//support@mobilecoin.foundation` rather than `support@mobilecoin.foundation`
=> Fix mailto link

common/src/logger/mod.rs, crypto/digestible/src/lib.rs, crypto/digestible/test-utils/src/lib.rs, crypto/keys/src/ed25519.rs, crypto/keys/src/lib.rs, crypto/keys/src/ristretto.rs, crypto/keys/src/traits.rs, crypto/keys/src/x25519.rs, crypto/message-cipher/src/lib.rs, crypto/ring-signature/src/ring_signature/mod.rs, crypto/sig/src/lib.rs, libmobilecoin/src/common/mod.rs, libmobilecoin/src/lib.rs, transaction/core/src/amount/mod.rs, transaction/core/src/ring_ct/mod.rs, transaction/core/src/validation/validate.rs, util/ffi/src/lib.rs
Per [Rust style guide](https://doc.rust-lang.org/1.0.0/style/style/imports.html#avoid-use-*,-except-in-tests.): "Avoid `use *`, except  in tests." (i.e. `use super::*`)
=> Clean up `pub use *`

connection/src/error.rs, connection/src/thick.rs, connection/src/traits.rs, fog/enclave_connection/src/error.rs, fog/enclave_connection/src/lib.rs, fog/ingest/server/src/connection_error.rs, peers/src/error.rs
I noticed in testing that fog-distro retries infinitely on report
verification failures, which occur if you are using a slam with bad
sigstruct for the network.
This is partly because slam ignores whether errors are retriable.
But even thick client will retry on all attestation errors, because
the `should_retry` function considers all attestation errors retriable
This commit makes the `should_retry` logic more nuanced. Attestation errors
now also expose `should_retry`. The following errors are now
considered non-retriable, and all others are still retriable.
* Any attestation verification failure (because,
the verifier will be the same next time and the report will be too,
so it has no chance to succeed on retry)
* The responder id construction / uri parsing errors, because, the
uri will …
=> Mark some attestation errors as not retriable

fog/overseer/server/tests/retired_key_not_outstanding_idles_have_same_key.rs
Hopefully this will resolve the intermittent `active_key_is_retired_not_outstanding_new_key_is_set_node_activated` failures.
=> Increase sleep delay for flaky test

attest/core/src/ias/verify.rs, sgx/report-cache/untrusted/src/lib.rs
The current output is unwieldy.
<details>
<summary>Sample output</summary>
Before: `2022-06-10 21:36:16.721963255 UTC DEBG Quote verified by remote attestation service VerificationReport { sig: VerificationSignature([8, 169, 184, 224, 61, 130, 40, 71, 160, 184, 190, 253, 183, 243, 44, 101, 161, 101, 134, 165, 136, 187, 103, 1, 160, 10, 10, 49, 35, 120, 209, 78, 38, 55, 244, 65, 175, 42, 18, 248, 34, 25, 44, 31, 55, 178, 74, 120, 215, 130, 123, 132, 136, 155, 112, 241, 184, 153, 41, 247, 253, 57, 122, 184, 161, 150, 15, 101, 20, 211, 112, 249, 243, 2, 117, 15, 169, 73, 59, 54, 193, 106, 148, 172, 123, 1, 180, 54, 70, 230, 66, 57, 121, 190, 243, 82, 49, 114, 81, 203, 7, 144, 99, 169, 53, 34, 48, 184, 221, 191, 204, 116, 47, 101, 181, 119, 87, 13, 129, 74, 53, 161, 77, 170, 35, 37, 25, 158, …
=> Improve `VerificationReport` rendering in logs

.internal-ci/util/manual_republish_existing_build.sh
If you squash merge your commits and you have `skip ci` somewhere in those messages, we'll skip the build.
So lets take the opportunity to update the manual build script with latest updates.
=> Update manual build and trigger CD build

mobilecoind-dev-faucet/src/data_types.rs, mobilecoind-dev-faucet/src/lib.rs, mobilecoind-dev-faucet/src/worker.rs, mobilecoind-json/src/bin/main.rs, mobilecoind-json/src/data_types.rs, mobilecoind/src/conversions.rs, mobilecoind/src/service.rs
Also support trailing comma in the `build_api` macro. This way future method additions do not need to modify the last line.
=> Cleanup: DRY up references to `mc_mobilecoind_api` with an alias

Cargo.lock, android-bindings/Cargo.toml, android-bindings/lib-wrapper/android-bindings/publish.gradle, android-bindings/src/bindings.rs
Added Android bindings for commitment CRC computation
This PR is needed in order to verify the reconstructed TxOutRecord commitment data
=> Add bindings for CRC computation

.github/workflows/mobilecoin-dev-cd.yaml, .internal-ci/helm/consensus-node/templates/node-deployment.yaml, .internal-ci/helm/fog-ingest/templates/fog-ingest-statefulset.yaml, .internal-ci/helm/fog-services/templates/fog-ledger-statefulset.yaml, .internal-ci/helm/fog-services/templates/fog-report-deployment.yaml, .internal-ci/helm/fog-services/templates/fog-view-deployment.yaml, .internal-ci/helm/fog-services/values.yaml
Fog-view may or may not complete in the 2 hour start up time. Bump the startup wait time to 4 hours.
In addition if we were to loose all the view pods in an envrionment we would be looking at several hours of downtime while view reloads.  To minimize the chance of a single node or availability zone taking down the entire view service, add topology  and anti-affinity rules.
- Anti-affinity rules for view, ingest and consensus to make sure each pod ends up on their own node. Report is stateless and fast to come up. We don't need to constrain it to specific nodes.
- Topology rules to enforce balanced distribution across availability zones.
- LabelsSelectors should enforce rules across the app *and* helm chart version.  This way when we have a new helm release version we don't share the …
=> Longer startup, topology and affinity rules 

Cargo.lock, Cargo.toml, fog/sql_recovery_db/Cargo.toml, mint-auditor/Cargo.toml
Use our fork of `diesel` to statically link `libsqlite3`, to avoid a runtime dependency.
See #2165.
* Statically link `libpq`
=> Statically link SQLite

watcher/src/block_data_store.rs, watcher/src/error.rs, watcher/src/watcher.rs, watcher/src/watcher_db.rs
* Move generic mapping of `lmdb::Error::{KeyExists, NotFound}`  into `impl From<lmdb::Error> for WatcherDBError`
* Replace `Url::from_str(&String::from_utf8(bytes))` with `Url::parse(str::from_utf8(bytes))`, and add a helper to DRY up that invocation.
* Simplify some error propagation
=> Simplify and DRY up some watcher code

consensus/enclave/edl/enclave.edl, fog/ingest/enclave/edl/enclave.edl, fog/ledger/enclave/edl/enclave.edl, fog/view/enclave/edl/enclave.edl
Correctly mark `outbuf_retry_id` as an `[in, out]` parameter.
TODO:
=> Make outbuf_retry_id an in,out parameter, fix init-twice crash.

mob
adds a `--` before the `cmd` arg to enable parser to work correctly
changes args from `REMAINDER` to `+` for consistency
=> fix mob docker command arg

sgx/build/src/conf.rs, sgx/build/src/lib.rs
Move the `Compiling X for {IAS dev,SGX simulation} mode` warnings to where we actually emit those features.
=> Fix premature SGX sim and IAS dev build warnings

fog/api/proto/view.proto, fog/view/server/src/fog_view_service.rs, fog/view/server/src/server.rs
This is the 3rd PR for the Fog View Router project (#2028). The previous PR created an enclave method for the Fog View Router to use to convert client query requests into queries that are encrypted for each Fog View Store. This PR doesn't build directly off the last PR in that it implements the MultiViewStoreQuery API for Fog View Store (the previous PR's work will be used in the subsequent PR to build the MultiViewStoreQueryRequets). 
This PR also implements the API in FogViewService. The logic is fairly straightforward- the multi_view_store_query method takes in a MultiViewStoreQueryRequest, which contains a list of Queries that are encrypted by the Fog View Router for any Fog View Store that it knows about. The method logic proceeds by checking to see if it can decrypt any of these …
=> Implement MultiViewStoreQuery API for Fog View 

mobilecoind/src/bin/main.rs, util/telemetry/src/jaeger.rs, util/telemetry/src/lib.rs
Enabled by setting `env.MC_TELEMETRY` to `1` or `true`.
Previously `mobilecoind` had an opt-out with `MC_TELEMETRY=0`. Now all clients have telemetry disabled by default.
=> Make telemetry opt-in

Cargo.lock, Cargo.toml, blockchain/validators/Cargo.toml, blockchain/validators/src/error.rs, blockchain/validators/src/lib.rs, blockchain/validators/src/metadata/key_range/config.rs, blockchain/validators/src/metadata/key_range/mod.rs, blockchain/validators/src/metadata/key_range/validator.rs, blockchain/validators/src/metadata/mod.rs, blockchain/validators/src/test_utils.rs, crypto/keys/src/ed25519.rs
This PR adds validation for metadata signing keys; #2136 adds AVR validation.
This config can be used to revoke metadata signing keys, when `LedgerDB` calls this as part of its validation before appending blocks.
See [MCIP 43](https://github.com/mobilecoinfoundation/mcips/blob/block-metadata/text/0043-block-metadata.md#signing-key-history) and #2104 for more details.
=> Add a `MetadataValidator` for validating block metadata

account-keys/src/account_keys.rs, account-keys/src/lib.rs, crypto/keys/src/ristretto.rs
Adding ViewAccountKey struct which stores the view_private_key and spend_public_key, which can be used to generate PublicAddresses using a different derivation path than the current implementation in AccountKey
Current:
New:
=> View Account Key

crypto/keys/Cargo.toml
When setting up another repo, I discovered that this crate doesn't
build properly.
```
error[E0425]: cannot find function `encode_config` in crate `base64`
--> mobilecoin/crypto/keys/src/x25519.rs:240:31
|
240 |         let encoded = base64::encode_config(&der, B64_CONFIG);
|                               ^^^^^^^^^^^^^ not found in `base64`
```
This happens because the `base64::encode_config` function is only
exposed when at least the `alloc` feature is selected. This commit
ensures that it is selected whenever this crate is built.
=> fix mc-crypto-keys build

crypto/ake/enclave/src/lib.rs, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/src/lib.rs
The Fog View Router is responsible for taking incoming client requests, forwarding them to Fog View Shards, and then returning these received responses to the client. This PR adds three ake enclave methods (and corresponding view enclave methods) that facilitate this process. 
The first method, `backend_init`, allows an enclave to create a Noise auth request to another enclave that serves as a backend.A backend connection is one in which the current enclave is a client to another enclave. It is not the same as a peer connection, in which the current enclave sends peer messages to another enclave, and it's distinct from a client connection, in which the current enclave services client requests. The `backend_connect` method finishes the Noise connection process, and the …
=> Implement enclave APIs that facilitate Fog View Router dynamic store discovery

Cargo.lock, consensus/enclave/mock/Cargo.toml, consensus/enclave/mock/src/lib.rs, consensus/service/Cargo.toml, consensus/service/src/byzantine_ledger/metadata_provider.rs, consensus/service/src/byzantine_ledger/mod.rs, fog/ingest/server/Cargo.toml, ledger/db/src/ledger_db.rs, ledger/sync/Cargo.toml, ledger/sync/src/ledger_sync/ledger_sync_service.rs, ledger/sync/src/lib.rs, ledger/sync/src/metadata_provider.rs
* Make consensus catch-up mode override the downloaded metadata with its own; mobilecoind propagates the metadata it downloads.
* Re-enable check that requires block metadata from Block Version 3 onward. Partial revert of commit ce9eca0.
This is the last blocker to requiring block metadata, per https://github.com/mobilecoinfoundation/mcips/pull/43
* #2197
=> Handle catch-up mode for consensus and mobilecoind

Cargo.lock, Cargo.toml, util/dump-ledger/Cargo.toml, util/dump-ledger/src/bin/dump_ledger.rs, util/dump-ledger/src/error.rs, util/dump-ledger/src/lib.rs, util/generate-sample-ledger/src/bin/generate_sample_ledger.rs, util/generate-sample-ledger/src/lib.rs
Dumps the blocks in a `LedgerDB` with optional overrides to restrict the range of block indexes, to inspect the blocks in the `LedgerDB`. Supports #2104 and #2197
Also make `generate_sample_ledger` input and output paths configurable.
Sample commands:
```
$ tools/local-network/bootstrap.sh
$ cargo run -p mc-util-generate-sample-ledger -- --output-dir test_ledger --keys-dir target/sample_data/keys --blocks=10 --txs 3
2022-07-13 19:28:43.915690200 UTC INFO Making 600 outputs of 416666000000000000 picoMOB across 20 recipients (3 outputs per recipient, 1 tokens, 10 blocks)., mc.module: mc_util_generate_sample_ledger, mc.src: util/generate-sample-ledger/src/lib.rs:56
2022-07-13 19:29:04.049277200 UTC INFO Wrote LedgerDB to "test_ledger", mc.module: mc_util_generate_sample_ledger, mc.src: …
```
=> Add a utility to dump a LedgerDB as JSON

mob
this env was added as a requirement recently to run the fog unit tests, but it was not added to the mob prompt tool.
=> add missing env to mob prompt invocation

.github/actions/mobilecoin-cache-rust-binaries/action.yaml, .github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/docker/Dockerfile.node_hw, .internal-ci/docker/Dockerfile.runtime-base, .internal-ci/docker/entrypoints/node_hw.sh, .internal-ci/docker/support/node_hw/logstash.conf, .internal-ci/docker/support/node_hw/supervisor/conf.d/logstash.conf, .internal-ci/helm/watcher/templates/watcher-deployment.yaml, .internal-ci/helm/watcher/values.yaml, .internal-ci/util/manual_republish_existing_build.sh
Some of these fixes could be worked around, but the standalone container logging needs to work for our Consensus Node Operator partners.
Operational fixes for pieces that are not part of the core stack or tested in the core CD workflow.
- fix `watcher` helm chart syntax and default image/version selection.
- Fix standalone logging. 
- Move logging tools install out of runtime-base to node_hw. node_hw is the only part our node operators run as a standalone container.
- Fix typo in entrypoint that prevented logging from being enabled.
- Move from filebeat to logstash for opensearch support when running as a stand alone container.
- flags and options for the "manual" build script.
GHA CD fixes 
- Fix binary cache to invalidate on changes to .edl and .cargo/config files.
- Remove consensus …
=> Watcher, standalone node_hw operational fixes.

fog/api/proto/view.proto, fog/uri/src/lib.rs, fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/src/fog_view_router_server.rs, fog/view/server/src/fog_view_router_service.rs, fog/view/server/src/fog_view_service.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/server.rs, fog/view/server/src/shard_responses_processor.rs, fog/view/server/tests/smoke_tests.rs
#2189 implemented dynamic shard component discovery in the Fog Router. @jcape requested that we split the Fog View APIs into two- one for clients and one for fog view router instances. Splitting the API ensures that clients won't be able to hit the MultiViewQuery endpoint that router uses. This change also involves re-adding the `FogViewStoreUri`, which allows to disambiguate the APIs even more.
=> Split Fog View API into Client-facing and Store (Fog Router) APIs

.github/actions/mobilecoin-cache-rust-binaries/action.yaml, .github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/docker/Dockerfile.node_hw, .internal-ci/docker/Dockerfile.runtime-base, .internal-ci/docker/entrypoints/node_hw.sh, .internal-ci/docker/support/node_hw/logstash.conf, .internal-ci/docker/support/node_hw/supervisor/conf.d/logstash.conf, .internal-ci/helm/watcher/templates/watcher-deployment.yaml, .internal-ci/helm/watcher/values.yaml, .internal-ci/util/manual_republish_existing_build.sh
Pull in stuff from #2266 into v2 branch
* add .edl and .cargo/config to cache list
* fix syntax and image/tag for watcher chart
* fix logging and switch from filebeat to logstash for better opensearch support
* add flags and options to manual script
* remove consensus nodes between upgrades - new chart has topology constraints that can confilct with volume constraints
* clean up some node_hw container comments
* Update .internal-ci/util/manual_republish_existing_build.sh
* change CD trigger to release/v*
=> Watcher, standalone node_hw operational fixes. (#2266)

fog/sample-paykit/src/cached_tx_data/mod.rs, fog/sample-paykit/src/error.rs
This should fix a bunch of warnings appearing in the test client when
running on testnet, because we ran it for months before the change subaddres
was changed from 1 to u64::MAX - 1.
=> Make fog sample paykit support (at least, scan) historical change subaddress

Cargo.lock, Cargo.toml, account-keys/Cargo.toml, account-keys/src/account_keys.rs, account-keys/types/Cargo.toml, account-keys/types/src/lib.rs, account-keys/types/src/traits.rs, consensus/enclave/trusted/Cargo.lock, crypto/ring-signature/Cargo.toml, crypto/ring-signature/src/lib.rs, crypto/ring-signature/src/onetime_keys.rs, crypto/ring-signature/src/ring_signature/mod.rs, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock, transaction/core/src/ring_ct/generator_cache.rs, transaction/core/src/ring_ct/mod.rs, transaction/core/src/ring_ct/rct_bulletproofs.rs, transaction/core/src/signed_contingent_input.rs
This implements two changes discussed in a meeting on Wednesday.
This helps to move us closer towards making `mc-crypto-ring-signature` not depends on the `alloc` crate, so that it can be used more easily on a Trezor without requiring the rust standard allocator.
=> Mc crypto ring signature no alloc improvements

mint-auditor/src/db/models/audited_mint.rs, mint-auditor/src/http_api/api_types.rs, mint-auditor/src/http_api/mod.rs, mint-auditor/src/http_api/routes.rs, mint-auditor/src/http_api/service.rs
Add endpoint to list audited mints joined to mint tx and gnosis deposit
Motivation
The frontend for the mint auditor will need this endpoint
Future Work
audited burns endpoint
this is based off of https://github.com/Shramp/mobilecoin/pull/1. it was easier to copy-paste the few changes in that diff than fix the merge conflicts.
=> Add audited mints endpint to mint auditor

mint-auditor/src/db/models/audited_burn.rs, mint-auditor/src/http_api/api_types.rs, mint-auditor/src/http_api/mod.rs, mint-auditor/src/http_api/routes.rs, mint-auditor/src/http_api/service.rs
Add route + service + model for getting a paginated list of audited burns along with corresponding burn txouts and gnosis safe withdrawals. This will be used by the frontend of the mint auditor.
=> Add audited burns endpoint to mint auditor

Cargo.lock, connection/test-utils/src/blockchain.rs, mobilecoind/Cargo.toml, mobilecoind/src/test_utils.rs
Adding the fee map to support MockBlockchainConnections having fees for more than just the MOB token, specified by the test setup.
=> Add FeeMap to MockBlockchainConnection

.github/workflows/mobilecoin-dev-cd.yaml, .internal-ci/util/metadata.sh, CHANGELOG.md
GHA
- move to release/* and semver compatible tags
- Remove the redundant "branch" output and change to using "namespace" in the GHA CD.
metadata.sh
- Rework how the metadata script to support the move to new `release/v2` branch pattern. 
- Clean up script for clearer logic flow.
- Truncate `really-super-extra-there-s-no-way-you-need-this-way-too-long` branch names so we don't exceed the 63 character limit in a lot of K8s identifier values.
We are starting to use similar logic for dynamic testing environments in some of the other MobileCoin projects. Break this functionality out in to it's own discrete GitHub Action for reuse on other projects.
=> [Fixes] CI/CD - Update GHA CD and metadata script to support new release branch patterns

Cargo.lock, android-bindings/Cargo.toml, android-bindings/lib-wrapper/android-bindings/publish.gradle, android-bindings/src/bindings.rs
* Expose McRng to the SDK
* Expose ChaCha20 to the SDK
* Parameterize TransactionBuilder bindings for an RNG from the SDK
These changes are needed in order to have transaction building idempotence at the SDK level. After these changes, the SDK will be able to build the same transaction more than once with the same inputs.
* Merge these and other 1.2.0+ changes into master
=> Android SDK Expose TransactionBuilder RNG

Cargo.lock, crypto/ake/enclave/src/lib.rs, fog/api/proto/view.proto, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/src/lib.rs, fog/view/server/Cargo.toml, fog/view/server/src/fog_view_service.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/shard_responses_processor.rs
This PR uses the oblivious programming methods implemented in #2252 to obliviously collate shard responses for  Fog Router.
=> Collate shard response in constant time (obliviously)

fog/view/server/Cargo.toml, fog/view/server/src/lib.rs, fog/view/server/src/sharding_strategy.rs
As desribed in the [design doc](https://docs.google.com/document/d/1-ju5efGK6vvuYjxj1pKhfFcpgGlornuxZYvOC-nsbjs/edit), each Fog View Store instance is responsible for serving a "shard", i.e. a subset, of the total set of TxOuts. This PR introduces the `trait` that will be used to divide the TxOuts into the subsets. 
- Create an `EpochShardingStrategy` that implements the trait for the epoch sharding strategy.
=> Implement epoch sharding via trait

fog/view/server/src/bin/main.rs, fog/view/server/src/db_fetcher.rs, fog/view/server/src/lib.rs, fog/view/server/src/server.rs, fog/view/server/src/sharding_strategy.rs, fog/view/server/tests/smoke_tests.rs
The previous PR (#2350) created the `EpochShardingStrategy`. This PR uses this concrete sharding strategy to tell Fog View which TxOuts its responsible for. 
- The next PR (#2352) allows for the sharding strategy to be passed as a CLI argument.
=> Use sharding strategy to tell view what blocks to process

fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs
Following @garbageslam's comments in #2351, we need to figure out a way to return the highest block count for which the Fog Router's returned TxOuts are valid. I.e. the client needs to be able to tie their balance to a certain block index.
To accomplish this, I (a) refactored the `blocks_processed` terminology to `blocks_observed` and  (b) we mark a block as observed whenever the db_fetcher sees a block (and doesn't necessarily process it, meaning adds its TxOuts to ORAM). This means that each shard will report that it saw a block even when it might be done processing.
This PR also modifies the enclave response collation code to return the minimum highest observed block index to the client. 
* We may consider adding a "is shard done processing it's blocks" method to the `ShardingStrategy` …
=> Return minimum highest processed block to client

fog/types/src/common.rs, fog/view/server/src/bin/main.rs, fog/view/server/src/config.rs, fog/view/server/src/sharding_strategy.rs, fog/view/server/tests/smoke_tests.rs
This PR allows for the `EpochShardingStrategy` parameters to be passed as CLI Arguments. 
- Implement "readiness" for sharding strategy.
=> Add config option for sharding strategy

consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs
Currently if you want to generate a mint-tx or mint-config-tx file and add one or more signatures to the file using a hardware signing key, you need to call hash-mint-tx or hash-mint-tx-config giving it all of the same params as you used in the generate-mint-tx or generate-mint-config-tx subcommands.
This is redundant, burdensome and error prone. The new hash-tx-file subcommand will output the needed hash reading those parameters from the specified tx-file.
shout out to Adam Corbo (https://github.com/hamburgerguy) for the first draft of this PR.
=> new hash-tx-file subcommand: computes and prints the hash of mint-tx and mint-config-tx files.

Cargo.lock, attest/net/src/ias.rs, attest/verifier/types/Cargo.toml, attest/verifier/types/src/verification.rs, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock
- Implement FromBase64 for VerificationSignature
- Use it in IasClient, not FromHex.
We need to be able to parse responses from IAS.
=> Fix VerificationSignature Parsing Issue

.github/workflows/ci.yml, mint-auditor/README.md, mint-auditor/tests/.gitignore, mint-auditor/tests/compile_proto.sh, tools/local-network/authorize-minters.py
This is useful for two reasons:
* Exercise mint auditor test earlier in case we break it
* Serve as an example for how to get a local network with mints
and burns in it. This is helpful for local testing of bridge stuff.
The work here is two parts:
* There are small differences between how jenkins sets up minting
and how the local network script does.
* The local network script signs a tokens file because this is required
to start the network, but it doesn't authorize any minters, because
it doesn't do anything further once the network starts up.
* Jenkins both creates governors and then uses the governors to
authorize minters.
* The mint auditor integration test requires that minters are ready
to go.
* Therefore, we make a python script (which imports and takes constants
from …
=> put mint auditor integration test in CI

Cargo.lock, libmobilecoin/Cargo.toml, libmobilecoin/include/chacha20_rng.h, libmobilecoin/include/libmobilecoin.h, libmobilecoin/libmobilecoin_cbindgen.h, libmobilecoin/src/chacha20_rng.rs, libmobilecoin/src/common/buffer.rs, libmobilecoin/src/error.rs, libmobilecoin/src/lib.rs
* This PR replaces PR #2383 (this is rebased off master and includes PR feedback updates from #2383
* I still need to validate latest commits with MobileCoin-Swift
* expose ChaCha20Rng for MobileCoin-Swift
To support re-trying transaction submission without violating idempotency, Moby (and other clients) need the ability to re-create identical transaction data via the `prepareTransaction` family of methods on MobileCoinClient.
* Added ability to provide a deterministic RNG to prepareTransaction methods, so the client can re-create the rng state prior to the call, if needed, in order to deterministically re-create identical transaction data.
Pivotal Tracker: [[iOS] Moby Transaction Idempotence](https://www.pivotaltracker.com/story/show/182820695)
=> libmobilecoin changes for MobileCoin-Swift SDK transaction idempotence

libmobilecoin/include/transaction.h, libmobilecoin/libmobilecoin_cbindgen.h, libmobilecoin/src/error.rs, libmobilecoin/src/transaction.rs
- Remove dangerous "unwrap" and Propagate invalid BlockVersionError's up through the FFI
Unwrapping an invalid BlockVersion will cause a rust-panic, this is bad for the SDK. Instead we should propagate an `InvalidInput` error up to the client.
- Merge in Swift Changes
[Nicholas - Lonnies Reprise](https://www.youtube.com/watch?v=bxYRAViC0cc)
=> Propagate Invalid BlockVersion Error Up through FFIs

fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/src/fog_view_router_server.rs
Integration testing revealed that the Fog View Router needs to access the Sgx reports in order to perform attestation. This PR adds the necessary report fetching logic.
=> Add report fetching logic to FVR

fog/api/proto/view.proto, fog/view/server/src/fog_view_service.rs, fog/view/server/src/server.rs, fog/view/server/src/shard_responses_processor.rs, fog/view/server/src/sharding_strategy.rs
This PR implements  the "readiness" check for the `EpochShardingStrategy` (and also adds this functionality to the `ShardingStrategy` trait). This check is needed because a Fog View Store may not be ready to serve TxOuts given a certain sharding strategy. In the case of a  Fog View Store that employs the `EpochShardingStrategy, that store is not ready to serve TxOuts unless 50% of its TxOuts have been loaded.
=> Add readiness API to ShardingStrategy

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dispatch-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .internal-ci/docker/support/node_hw/bin/wrapper-ledger-distribution.sh, .internal-ci/test/fog-test-client.sh, .internal-ci/test/minting-config-tx-test.sh
Add 1.1.3 bv0 -> 2.0.0 bv0 -> 2.0.0 bv2 -> current bv2 -> current bv3 upgrade testing.
- update job names to match upgrade path.
- create block version 3 set of tests
- reduce redundant tests between upgrade stages
- enhance fog-ingest activate/retire to use test_client to advance chain for old ingest retirement (mostly in gha-k8s-toolbox)
- minor fix in wrapper-ledger-distribution.sh to reduce the chance of confusing the state file path (thanks Joe!).
- smarter minting config tx test - wait for chain to advance before moving on.
=> [Added] CI/CD - GHA CD for master part 2

fog/view/server/src/error.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/shard_responses_processor.rs
Previously FVR was constructing the responder IDs ncorrectly: it was a wrapper around the stores' / router's URI. What we need it to be is "<host>:<port>"  which this change introduces.
This error was uncovered during unit testing. What happened is the store's thought responder ids were the url type and the router thought that the responder id was the host:port type.
=> Fix responder ID usage in FVR

attest/ake/src/event.rs, attest/ake/src/shared.rs, attest/ake/src/state.rs, attest/api/proto/attest.proto, attest/api/src/conversions.rs, attest/enclave-api/src/lib.rs
- Add attest::NonceMessage
- Add EnclaveNonceMessage
- Add Ready::decrypt_with_nonce, Ready::encrypt_with_nonce
- Add NoncePlaintext, NonceCiphertext events
- Add relevant transitions
There are some internal use cases for enclave messages with explicit nonces.
- Use these objects in MultiViewStoreQuery
=> Messages for noise protocol exchanges with explicit nonces

attest/ake/src/event.rs, attest/ake/src/shared.rs, attest/ake/src/state.rs, attest/api/proto/attest.proto, attest/api/src/conversions.rs, attest/enclave-api/src/lib.rs
- Replace a bunch of repeated trait impls with macros
This removes a bunch of copy-pasta around attest-enclave-api types with a couple macros.
- Replace EnclaveNonceMessage&lt;S> with EnclaveMessage<NonceSession>
- Update attest-ake to support NonceAuthRequest, NonceAuthResponse
- Update the view store to use the new nonced variants where appropriate
=> Minor DRY cleanups around sessions and auth messages

fog/api/proto/view.proto
The FVR [design](https://docs.google.com/document/d/1-ju5efGK6vvuYjxj1pKhfFcpgGlornuxZYvOC-nsbjs/edit) requires an API that allows us to add shards to FVRs list of known shards on the fly, i.e. without having to restart the router server. This PR adds the gRPC service defintion that will be implemented in the next PR.
* Implement this API
=> Create gRPC FogViewRouterAdminAPI

attest/api/src/conversions.rs, attest/enclave-api/src/lib.rs
- Add NonceAuthRequest
- Add NonceAuthResponse
- Add NonceSession
- Add NonceMessage <=> EnclaveMessage&lt;NonceSession>
- Remove EnclaveNonceMessage
This is part of the explicit nonce work, it creates the types necessary for going into/out of our attest-ake machinery in attest-enclave-api.
- Update attest-ake machinery to use nonce variants.
- Update ake-enclave to support nonce sessions
- Update fog view store to use nonce sessions
=> Add NonceAuthRequest, NonceAuthResponse, NonceSession

.github/workflows/mobilecoin-workflow-dev-reset.yaml
Fix the context for the namespace variable in the delete namespace part of the reset/delete workflow.
=> [Fixed] CI/CD - wrong context for namespace variable in reset/delete workflow

.github/workflows/ci.yml, mint-auditor/tests/integration_test.py
this increases the amount of time the test waits for mobilecoind and the mint auditor to catchup to network activity, and adds a named constant so that this can easily be adjusted in the future
=> increase mint auditor test timeout

.github/workflows/ci.yml, .github/workflows/mobilecoin-dev-cd.yaml, .gitignore, .mobconf, jenkins/build-pod.yaml, mob
Instead of running `mob prompt` as a root container, set up and switch to a matching local user. This should keep the files created in the `mob prompt` matching the local user. 
The builder-installer container now has an entrypoint script that if EXTERNAL_UID is passed in will setup a local user/group and setup the environment so local user should be able to build and test rust/go code.  Sudo has been added so users can sudo up to root with no password if they need elevated access.  The container still runs as the root user but switches down to the non-privileged user by default.
Caveats:
- This will not work from a windows cmd prompt, but should work from a WSL environment.
Changes:
- add `.mob` directory for preserving sccache and rust/cargo home and package cache.
- update `mob` to …
=> [Added] tools - Add mob prompt local user support.

mob
with the current version of the script, I consistently get this error
```
$ ./mob prompt
v0.0.17: Pulling from mobilecoin/builder-install
Digest: sha256:d7aae94cebd3b51b9b499ac47a91a7ddf05987be2f174b8e869d5a7c305106e2
Status: Image is up to date for mobilecoin/builder-install:v0.0.17
docker.io/mobilecoin/builder-install:v0.0.17
Traceback (most recent call last):
File "/home/chris/mobilecoinofficial/mobilecoin3/./mob", line 215, in <module>
username = os.getlogin()
OSError: [Errno 6] No such device or address
```
I am not sure why, I'm just using the MATE Terminal.
Following guidance from stackoverflow
(https://stackoverflow.com/questions/4399617/python-os-getlogin-problem)
I tried the `pwd` version, which worked for me.
However, docs, and that answer, seem to say that this should be …
=> Use getpass package instead of os.getlogin to get username

attest/ake/src/event.rs, attest/ake/src/shared.rs, attest/ake/src/state.rs, crypto/noise/src/cipher_state.rs
- Make NoisePlaintext, NoiseCiphertext wrap Plaintext/Ciphertext.
- Update Ready + NoisePlaintext transition to result in Ready + (Vec, u64)
- Add CipherState::next_nonce() accessor
- Make encrypt_with_nonce return, not take, the nonce.
These changes are intended to prevent (catastrophic key-compromising) nonce reuse by only allowing the noise user to provide a nonce when decrypting. By removing the ability of a noise user to provide the nonce when encrypting, we relieve them of the responsibility for avoiding nonce reuse. In order to do this, we need to provide them the (implicit) nonce that the encryptor used instead.
- Implement AkeEnclave::frontend_accept, port backend to use Nonce-relevant messages.
- Use Nonce-relevant objects for MVSQ messages.
=> Don't expose encryption w/ user-specified nonces, return nonces when encrypting

connection/src/error.rs, connection/src/lib.rs, connection/src/thick.rs, consensus/api/proto/consensus_common.proto, consensus/api/src/conversions.rs, consensus/service/src/api/client_api_service.rs, fog/distribution/src/main.rs, fog/sample-paykit/src/error.rs, mobilecoind-dev-faucet/src/slam/tx_submitter.rs
Note: This PR came out of this discussion on another PR: https://github.com/mobilecoinfoundation/mobilecoin/pull/2484#discussion_r966436661 and also discussion in discord
`TransactionValidationError` is an error type created by `mc-transaction-core` in the validation routines. This is the actual low level error returned by validation, and is marshalled across the consensus enclave boundary when something fails.
`ProposeTxResult` is a protobuf enum defined in the consensus_common.proto file. When a submission happens, but fails due to a transaction validation error, we return a grpc success, but with a nonzero "status code" in the form of `ProposeTxResult`. This is supposed to capture the details of the `TransactionValidationError`. In terms of code, the `ProposeTxResult` type is created …
=> Simplify the situation around ProposeTxResult vs. TransactionValidationError

Cargo.lock, attest/enclave-api/src/error.rs, attest/enclave-api/src/lib.rs, crypto/ake/enclave/Cargo.toml, crypto/ake/enclave/src/lib.rs, fog/view/enclave/Cargo.toml, fog/view/enclave/api/Cargo.toml, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/src/lib.rs, fog/view/server/src/router_request_handler.rs
Add a method to convert a client query into a sealed query and modify `reencrypt_for_backends` to accept a sealed query.
This avoids the issue of repeated decryptions of the client query failing due to the Noise nonce advancing in the decryptor.
Update the fog view router to use the new method(s) in the creation of the `MultiViewStoreQuery` messages.
[Soundtrack of this PR](https://www.youtube.com/watch?v=Pgum6OT_VH8)
=> Sealed messages for clients with backends

Cargo.lock, fog/view/server/Cargo.toml, fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/src/fog_view_router_admin_service.rs, fog/view/server/src/fog_view_router_server.rs, fog/view/server/src/fog_view_router_service.rs, fog/view/server/src/lib.rs, fog/view/server/src/router_admin_service.rs
Adds the "shard management" API ,which allows for Fog View Shards to be added to a Fog View Router on the fly while it's running. This allow us to spin up new shards without having to restart Fog View Router instances.
The next piece of this project is to implement and authorization scheme that only allows authorized clients to add shards to FVR. As discussed on discord, we'll accomplish this by configuring Kubernetes to only expose the API, which is running on it's own host / port, to authorized users. 
RFC: I used a `RwLock` to manage thread access to the shards, but we may consider using a `Mutex`. Let me know what you think.
- During deployment, configure kubernetes to only expose the endpoint to authorized users.
=> Implement shard management API sans auth

api/proto/external.proto
After masked amount v2, MaskedAmounts are always stored in a proto oneof, which their versioning information is derived from. It's generally going to be a bug if a MaskedAmount is not stored in a oneof this way, because the recipient will not be able to infer which version it is.
Brian ran into this when updating full-service. It likely will impact SDKs also.
Fixes #2530
=> Update Receipt proto schema for MaskedAmountV2 changes

api/src/convert/amount.rs
In the previous commit we added a oneof to the Receipt proto. However we didn't add a conversion similar TxOut_one_of_masked_amount.
This is needed because in the proto codegen, each oneof corresponds to a different type tied to the struct it appears in.
=> Add a missing conversion for Receipt_one_of_masked_amount

consensus/mint-client/src/config.rs
The mint client reads from a b58 address when it creates a MintTxPrefix, but it doesn't (before this commit) check if that is actually a fog address. If it is, the fog part will get silently removed, and then the fog user won't find it.
This change makes it give an error message.
=> Add check to mint client to ensure public address doesn't have fog

crypto/rand/src/fallback.rs
It turns out that `ThreadRng` is a wrapper around some `Rc<...>` object, which means it does not implement `Send`. My understanding is that this was done on purpose, so make it impossible to send one thread's RNG to another - since that can mean one of two things:
1. The actual RNG (and its associated state) is moving to a different thread, which deprives the sender thread from having an RNG
2. Sending an RNG doesn't actually send any state, and always uses the current thread, so sending is essentially not doing anything. This is what is achieved by this PR.
Some reasoning behind why this is needed:
First, for a practical reason:  this currently breaks https://github.com/mobilecoinofficial/android-bindings/ because JNI requires objects referenced by the Java side to implement `Send`: …
=> Change McRng to be a ZST that forwards calls to thread_rng()

consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs
=> added hash-tx-file subcommand to print the hash of a mint-tx or mint-config-tx file (#2406)

fog/sample-paykit/src/cached_tx_data/mod.rs
These changes were made in 1.2.3 when test client blew up, but we never migrated them to master.
I am not sure what the original commit was, they came from somewhere in here:
https://github.com/mobilecoinfoundation/mobilecoin/pull/2289/files
This discrepancy was only noticed because git picked up these changes randomly when William tried to cherry-pick something to master.
=> migrate test client fixes to master

Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/recovery_db_iface/Cargo.toml, fog/recovery_db_iface/src/lib.rs, fog/recovery_db_iface/src/types.rs, fog/sql_recovery_db/src/lib.rs, fog/view/enclave/trusted/Cargo.lock
As described in #2337, we'd like to create a tool that cleans up expired egress keys. In effect, this means that we'd like to identify ingest invocations, which are associated with egress keys, that have a `'last_active_at` timestamp before some specified time. 
This PR adds the `RecoveryDb` method and corresponding `SqlRecoveryDb` implementation that allows us to identify expired egress keys.
RFC: This is the first time, to my knowledge, that we are handling diesel / PSQL timestamps and specifying them in the `RecoveryDb` trait, which is `no_std`. I chose to use `chrono::NaiveDateTime` because it's one of the types that `diesel` provides a `ToSql` conversion for AND it doesn't require `std`. Let me know your thoughts.
* Create an executable that uses this method to either print the …
=> Create recovery_db method that queries expired ingest invocations

Cargo.lock, Cargo.toml, fog/sql_recovery_db/cleanup/Cargo.toml, fog/sql_recovery_db/cleanup/src/config.rs, fog/sql_recovery_db/cleanup/src/db_cleaner.rs, fog/sql_recovery_db/cleanup/src/main.rs
This PR creates the executable that cleans up the egress keys. Right now, it only implements the dry run functionality, which prints out the keys to the screen. 
* The next PR will handle the non-dry run scenario, which will make changes to the ingest_invocation table.
=> Create db cleaner executable

attest/enclave-api/src/lib.rs, crypto/ake/enclave/src/lib.rs
- Add `AkeEnclaveState::frontends` to keep track of nonce-session-based sessions
- Plumb new `frontend_accept` and `frontend_close` methods to add/remove elements from it.
Earlier PRs developed a specific session type for explicit nonce sessions, this allows their use by `AkeEnclaveState` to allow backend enclaves to track sessions from frontends.
=> Add inbound frontend connection support crypto-ake-enclave

crypto/ring-signature/Cargo.toml
https://github.com/mobilecoinfoundation/mobilecoin/commit/bf4216551790b05c70a29321e248a8a58b1739b4
In referenced commit, we started using features from rand-core 0.6.4, after dependabot had bumped us to that version.
However, this can break downstream, because we only had 0.6 in the Cargo.toml, so cargo could potentially select 0.6.3 still.
Thanks to Davey for reporting the build breakage.
=> fixup cargo toml

attest/api/src/conversions.rs, attest/enclave-api/src/lib.rs, connection/Cargo.toml, crypto/digestible/signature/Cargo.toml, crypto/ring-signature/signer/Cargo.toml, fog/view/connection/Cargo.toml
Also sort Cargo.toml files due to precommit hook.
There's no reason to expose `get_nonce`, and it could cause some issues, so it's being removed. Without `get_nonce` to contrast against, there's no reason not to call `peek_nonce` just `nonce`.
=> Remove `get_nonce` from NonceSession, rename `peek_nonce`->`nonce`

.github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/docker/entrypoints/node_hw.sh, .internal-ci/docker/support/node_hw/bin/wrapper-ledger-distribution.sh, .internal-ci/helm/consensus-node/templates/node-deployment.yaml
Cherry-pick from release/v2
Fix the ability to bootstrap the network from scratch with a 2.x+ version container and charts. Useful for load testing.
- Add optional secrets for initial and fog keys seeds.
- Add MC_START_FROM=zero logic to ledger-distribution.
=> master: [Fixes] CI/CD, chart, container - Fix consensus node bootstrap from scratch.

attest/api/src/conversions.rs, connection/Cargo.toml, crypto/ake/enclave/src/lib.rs, fog/api/src/conversions.rs, fog/view/connection/Cargo.toml, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/Cargo.toml, fog/view/server/src/router_request_handler.rs
@jcape created new `Nonce`-based structs that allow Fog View Router (FVR) and Fog VIew Stores to communicate with messages that contain the nonce used in the noise protocol that attests the communication. #2549 added support for inbound frontend messages, and this PR adds the support for outbound "backend" messages. 
Note that this PR stops short of modifying the `MultiviewStoreQueryRequest` and `MultiviewStoreQueryResponse`, and instead supplies a blank `attest::Message` for the conversion that the `router_request_handler` uses. The following PR (#2617) implements this change.
RFC: In the `backend_decrypt` method, I use the `peek_nonce` method rather than the `get_nonce` method to decrypt the message from the backend. See comment for more info but could use confirmation that this is …
=> Replace client with nonce paradigm for backends

consensus/api/src/conversions.rs, transaction/core/src/input_rules.rs, transaction/core/tests/input_rules.rs
this was suggested in review of the mcip, and brings the implementation in line with the spec. Previously this was only checked in the SCI validate routine.
It doesn't create a bug in the enclave to omit
this check, but it also simplifies review if we just have one spec for everywhere and enforce it everywhere.
=> fixup to partial fills -- input rules check for zero partial fill change

crypto/ake/enclave/src/lib.rs, fog/api/proto/view.proto, fog/api/src/conversions.rs, fog/view/server/src/fog_view_service.rs, fog/view/server/src/shard_responses_processor.rs, util/telemetry/src/lib.rs
The MultiViewStoreQuery uses `attest::Message` queries but needs to use `attest::NonceMessage` queries now that FVR is using Nonce based sessions.  This PR makes this change but stops short of adding a `query` enclave method that takes a `NonceMessage`. 
NOTE: CI is failing for this PR for reasons that don't seem to be associated with the new functionality. I'm going to investigate this CI failure in parallel, but it shouldn't block this PR. 
- Create a `query` enclave method that takes a `NonceMessage`.
=> Modify MVQ to use NonceMessage

mobilecoind/Cargo.toml, mobilecoind/src/config.rs, tools/local-network/local_network.py
This was the simplest way I could see to turn off default-features only on mobilecoind (thanks Nick!)
=> make `tools/local-network/local-network.py` not do ip checks

Cargo.lock, crypto/ake/enclave/src/lib.rs
Previously, we allocated space for 10,000 `frontends` in `AkeEnclaveState`. This caused an OOM failure when the fog conformance tests ran. After tinkering around with the numbers, I found that an allocation of `1000` frontends works fine, and then I cut that number in half because we should never need more than 300 frontends given our FVR needs.
=> Fix fog conformance OOM failure by reducing `frontends` allocation

crypto/ake/enclave/src/lib.rs
Previously, the `reencrypt_sealed_message_for_backends` method used the sealed client message's channel id in the `EnclaveMessages` sent to the stores from the router.  This is incorrect- the channel id for the specific encryptor should be used because it corresponds to the nonce session between the router and the store.
=> Fix reencrypt

mobilecoind/src/bin/main.rs, util/telemetry/src/jaeger.rs, util/telemetry/src/lib.rs
Make telemetry opt-in, with env.MC_TELEMETRY set to 1 or true.
Currently, running a consensus network without a telemetry configuration causes a *ton* of spurious logs. This PR cherry-picks inverting that situation (makes telemetry off by default, requiring `MC_TELEMETRY=1` to enable).
=> Cherry-pick opt-in telemetry (#2193)

ledger/db/src/error.rs
This may be controversial, but I think this may be a good change to make in this particular case.
The goal is to fix #2666.
A lot of our code takes a path to a `LedgerDb` as a command line argument. Then it calls `LedgerDb::open` on that path and unwraps any errors.
LMDB is a C library, and if it encounters any libc errors these get returned as `lmdb::Error::Other(c_int)`.
If we Display this error, it will call `mdb_strerror`:
https://docs.rs/lmdb-rkv/latest/src/lmdb/error.rs.html#127
http://www.lmdb.tech/doc/group__mdb.html#ga569e66c1e3edc1a6016b86719ee3d098
Which will decide if it is an lmdb error or a libc error, and in the latter case call `strerror` and in the former case do something appropriate for the lmdb error.
If we print this error as `Debug`, it will do none of that, it just …
=> Make mc_ledger_db::Error implement Debug by forwarding to Display

crypto/ake/enclave/src/lib.rs, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/src/lib.rs, fog/view/server/src/fog_view_service.rs
PR #2617 updated the MVQ request and responses to use `attest::NonceMessage`, and modified the Fog View Store API to accept this new MVQ but didn't implement the logic to actually fulfill this nonce-based query. This PR implements this by providing new enclave methods.
=> Create query_backend enclave methods

fog/sql_recovery_db/src/lib.rs
this doesn't happen very often, but when it did happen in testnet, we couldn't figure out why very easily and went database spelunking. we still don't know why, and in the future we want these details logged.
=> improve fog ingest logging when unique constraint is violated

fog/sql_recovery_db/src/lib.rs
this doesn't happen very often, but when it did happen in testnet, we couldn't figure out why very easily and went database spelunking. we still don't know why, and in the future we want these details logged.
(see also https://github.com/mobilecoinfoundation/mobilecoin/pull/2681 which is this PR on master)
=> improve fog ingest logging when unique constraint is violated (release/v2)

transaction/core/src/amount/v2.rs
We decided to do this because we generally use Blake2b for key derivations when it's a one-off hash like this, and we use Sha512 only when we want to use `HKDF`. This brings this more in line with our existing code. MCIP 42 has been updated to reflect this.
=> use Blake2b instead of Sha-512 for amount shared secret derivation

crypto/ake/enclave/src/lib.rs, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/src/lib.rs, fog/view/server/src/fog_view_service.rs
This PR updates Fog View stores to implement nonce based auth that serves as the foundation for FVR <-> Fog View Store communication.
=> Implement nonce based auth for Fog View Store

crypto/ake/enclave/src/lib.rs, fog/view/connection/src/fog_view_router_client.rs, fog/view/enclave/api/src/lib.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/src/lib.rs, fog/view/enclave/trusted/src/lib.rs, fog/view/server/src/fog_view_service.rs
As described in the grpcio [docs](https://docs.rs/grpcio/latest/grpcio/type.ClientDuplexSender.html), a `ClientDuplexSender` needs to be closed before it's dropped. In our case this means we need to close the `request_sender` field before we drop the `FogViewRouterGrpcClient`.
We weren't doing this before and it outputted and error log to the message that said `ERROR: Remote stopped...`. After implementing this call to close upon dropping, the error message is no longer outputted.
=> Close gRPC channel when client is dropped

fog/view/connection/src/fog_view_router_client.rs
The FVR integration tests unwraps a result with the `mc_fog_view_connection::Error`, and this requires that it implement `Debug`.
=> Implement debug for Fog View Router client error

fog/recovery_db_iface/src/lib.rs, fog/sql_recovery_db/src/lib.rs, fog/view/server/src/config.rs, fog/view/server/src/db_fetcher.rs, fog/view/server/src/server.rs, fog/view/server/tests/smoke_tests.rs
These batches have a size which is configurable as a command line parameter.
---
The point of this is that we have been having issues where the network latency to get from fog-view to postgres has been high enough that it becomes the bottleneck for fog-view loading all the data into ORAM, and begins to significantly negatively impact the time to restart fog view. We can make the server more tolerant of that by making it try to load more data at once.
Thanks to James for suggested approach here
=> Make fog-view load blocks from postgres in batches

Cargo.lock, Cargo.toml, fog/view/server/test-utils/Cargo.toml, fog/view/server/test-utils/src/lib.rs
Creates a test util module for the Fog View Router integration tests. Defines a precise drop order for the `RouterTestEnvironmenet` struct, because failure to do so makes the test fail.
* The next PR implements the first Fog View Router test.
=> Create fog view router test utils

.github/workflows/ci.yml, tools/lint.sh
Previously the lint.sh script would always check. Now the script will
attempt to fix and will only check if the `--check` flag is provided.
=> Add `--check` option to rust lint.sh script

consensus/service/config/src/error.rs, consensus/service/config/src/tokens.rs, crypto/multisig/src/lib.rs, transaction/core/src/mint/validation/config.rs
While working on the nested signer set PRs I learned that there will be a need to a method to check that a `SignerSet` satisfies some basic sanity tests. I want to add that method to the existing `SignerSet`, so that when `SignerSetV2` is introduced and the code starts having match statements to operate on either a V1 or V2 signerset, I could do something like this:
```
match signer_set {
V1(signer_set) => signer_set.is_valid(),
V2(signer_set) => signer_set.is_valid(),
}
```
The V2 implementation already has this, and it will be helpful to have this ready on the current implementaiton (and reduce the size of the V2 PR that touches this).
=> Add SignerSet::is_valid

fog/api/proto/view.proto, fog/view/server/src/fog_view_service.rs, fog/view/server/src/sharding_strategy.rs
The highest processed block range was being calculated incorrectly previously. The router's enclave was using the minimum highest processed block from all the stores as the highest processed block that it returned to the client. The stores calculated their highest processed block based on its enclave block tracker that only incremented its processed block count when it added a block to it's enclave. 
This resulted in unexpected behavior because each store returned the highest block that it added to its enclave RATHER than the highest block that it observed (the expected behavior). The new paradigm is as follows: each store will continue returning this number and will now additionally add it's block range. The router will then look at each block range, and find the first time a store …
=> Add block range to MVQ response

.github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml, .internal-ci/test/mint-auditor-test.sh, .internal-ci/test/minting-config-tx-test.sh, .internal-ci/util/generate_minting_keys.sh, .internal-ci/util/generate_tokens_config.sh, .internal-ci/util/tokens.base.json, mint-auditor/tests/integration_test.py
Change the CD integrations alternate token from 1 to 8192 so we don't conflict with the main/test token id 1 in future testing.
=> release/v2 - CI/CD - change testing token to 8192

fog/view/enclave/impl/src/lib.rs
Now that the stores are returning their highest processed block counts in addition the block ranges their responsible for, the router will calculate the highest processed block count for the client by finding the lowest store highest processed block count at which a store has not finished processing its block range. If all block ranges have been processed, it returns the max highest processed block count.
=> Implement new highest processed block count logic

.internal-ci/test/minting-config-tx-test.sh
What this `while` loop is trying to achieve is waiting for a new block to show up.`$block_count` is the current number of blocks, and `$new_block_count` is the new block count. We want to wait as long as  `new_block_count <= block_count`, right now the loop is waiting while 'block_count <= new_block_count', so it actually never waits (since `new_block_count` is initialized to 0).
=> Fix an incorrect comparison

Cargo.lock, util/serial/Cargo.toml, util/serial/src/lib.rs
I added `serde_with` to another crate as part of my work on multisig stuff and noticed there is a newer version with breaking API changes, so I used that as an opportunity to move us to the newer version.
I also added a test case to ensure this is behaving is expected, since the macro order matters (quoting the [manual](https://docs.rs/serde_with/2.0.1/serde_with/guide/serde_as/index.html), `place the #[serde_as] attribute before the #[derive] attribute`).
=> upgrade to serde_with 2.0

.github/dependabot.yml
Currently, the dev-cluster can only build and run tests for a handful of PRs at a time. If dependabot makes 7 PRs at once, this will swamp the cluster, and all engineers will be blocked from iterating on CI for several hours (even if CD is not run).
This change makes dependabot only create PRs for the root workspace at midnight in the pacific timezone.
The other workspaces are assigned to 1 AM in the pacific timezone.
Given that most engineers are in one of the four US continental timezones, this will always be between midnight and 4 AM for most employees, so people won't have to kill the dependabot CI runs manually in order to be productive.
=> add scheduled times and timezones for dependabot PRs

.circleci/config.yml, .github/workflows/mobilecoin-dev-cd.yaml, .internal-ci/docker/Dockerfile.runtime-base, .mobconf, attest/verifier/README.md, consensus/enclave/build.rs, consensus/enclave/measurement/build.rs, consensus/enclave/measurement/src/lib.rs, consensus/enclave/trusted/build.rs, consensus/service/BUILD.md, crypto/ake/enclave/src/lib.rs, docker/install_sgx.sh, fog/ingest/enclave/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ingest/enclave/measurement/src/lib.rs, fog/ingest/enclave/trusted/build.rs, fog/ledger/enclave/build.rs, fog/ledger/enclave/measurement/build.rs, fog/ledger/enclave/measurement/src/lib.rs, fog/ledger/enclave/trusted/build.rs, fog/view/enclave/build.rs, fog/view/enclave/measurement/build.rs, fog/view/enclave/measurement/src/lib.rs, fog/view/enclave/trusted/build.rs, jenkins/build-pod.yaml, mobilecoind/src/config.rs, ops/Dockerfile-consensus
This is a cherry-pick of changes from master to build using SGX 2.17.1 and allow SW_HARDENING_NEEDED results for the INTEL-SA-00657 advisory.
* Cherry-pick previously merged PR from master.
* Update ChangeLog
* Bump Versions
=> Update to SGX 2.17.1, add INTEL-SA-00657 to known advisories list. (#2639)

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-dev-test.yaml, .github/workflows/mobilecoin-dispatch-dev-update-consensus.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-reset.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml, .internal-ci/util/metadata.sh
Make sure that CD is run when we have a PR to master or release/ branches. Skip CI/CD when changes are only to .md files.
- PR to master
- PR to release/
- create a branch with feature/
How to opt out of CI/CD runs:
- add the GHA built in [skip ci] to your commit message.
Changes:
- on.pull_request CD workflow
- move all CD dispatch calls to workflow calls.
- clean up steps that described the workflow calls.
- Add human names to the manual dispatch calls.
- make testing workflow line up with current master.
- remove CD debugging skip filters for now.
- update docker actions to remove deprecated nodejs version warnings
- update metadata to remove deprecated GHA set-output calls
Future Work:
- add more file exclusions
- Add logic to skip just CD or just CI.
=> release/v3.0 - CI/CD - CD on PR

.internal-ci/docker/Dockerfile.runtime-base
Although the SDK version has been updated 2.17.101, there's no runtime library changes, so no new package releases. 
- revert SGX package version to 2.17.100.3-focal1
=> Revert release/v3.0 runtime-base SGX package version.

Cargo.lock, consensus/enclave/api/Cargo.toml, consensus/enclave/api/src/config.rs, consensus/enclave/impl/src/lib.rs
This makes it easier to expand and test the validation criteria as the object evolves. https://github.com/mobilecoinfoundation/mobilecoin/pull/2767/ is going to add some more validation scenarios, and @nick-mobilecoin [pointed out](https://github.com/mobilecoinfoundation/mobilecoin/pull/2767/files#r1004662057) that breaking this out of `enclave_init` would simplify testing (and I agree).
=> Refactor BlockchainConfig validation into the actual object.

.github/workflows/mobilecoin-dev-cd.yaml, .internal-ci/util/metadata.sh
Between the upgrade to docker/metadata-actions@v4 and the deprecation of GHA `set-output::`, something broke multiline outputs between jobs.
- Fix `docker_tag` output
=> V3 - CI/CD - Fix docker tags

consensus/enclave/measurement/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ledger/enclave/measurement/build.rs, fog/view/enclave/measurement/build.rs
We need to bump the enclave security version for new enclave releases.
* Bump enclave svns for consensus, fog ingest, fog view, fog ledger enclaves.
=> Bump enclave security versions.

fog/view/enclave/impl/src/lib.rs
A previous PR added `last_known_block_count` collation, and this one adds `last_known_block_cumulative_txo_count` collation. I also took the opportunity to refactor this into a separate \
method and add unit tests.
=> Calculate last known block txo count and add tests

.internal-ci/util/metadata.sh
Docker tags should be constructed from the `${tag}` value and not the `${version}` value.   
A `v3.0.0` semver "tag" event should make a `v3.0.0-dev` artifact set.  We accidentally made a `v3.0.0` docker tag instead.
=> V3 - CI/CD - fix tags part 2

api/proto/external.proto, api/src/convert/signing_data.rs, transaction/core/src/domain_separators.rs, transaction/core/src/input_rules.rs, transaction/core/src/lib.rs, transaction/core/src/revealed_tx_out.rs, transaction/core/src/ring_ct/mod.rs, transaction/core/src/ring_ct/rct_bulletproofs.rs, transaction/core/src/ring_ct/signing_digest.rs, transaction/core/src/tx.rs, transaction/core/src/tx_summary.rs, transaction/core/src/validation/validate.rs, transaction/extra/src/unsigned_tx.rs, transaction/types/src/block_version.rs
The motivation here is that, hardware wallets like Ledger have an expectation that the device can verify what is the balance change that will result from signing a given transaction and who the outbound money will be paid to.
However, currently we have scoped things so that hardware wallets just are responsible for signing the Ring MLSAG, and they don't see large parts of the Tx, including the TxPrefix.
The only way that the set of outputs is connected to the RingMLSAG is that the TxPrefix is hashed into the "message", which is hashed with more things to produce the "extended_message_digest", which is the 32 byte digest that the RingMLSAG actually signs.
For the hardware wallet to really know what it is signing then, it would have to reproduce the entire extended message digest. The …
=> Add TxSummary object and incorporate it into MLSAG signing digest

.github/workflows/ci.yml, Cargo.lock, api/proto/external.proto, api/src/convert/mint_tx.rs, consensus/api/proto/consensus_client.proto, consensus/api/src/conversions.rs, consensus/enclave/impl/src/lib.rs, consensus/mint-client/Cargo.toml, consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs, consensus/mint-client/src/fog.rs, consensus/mint-client/src/lib.rs, consensus/tool/src/main.rs, fog/sample-paykit/src/cached_tx_data/mod.rs, fog/sample-paykit/src/client.rs, fog/test-client/src/test_client.rs, tools/fog-local-network/local_fog.py, transaction/core/src/mint/tx.rs, transaction/core/src/mint/validation/error.rs, transaction/core/src/mint/validation/tx.rs, transaction/core/test-utils/src/mint.rs, transaction/types/src/block_version.rs
Consensus will now accept a MintTx that includes an encrypted fog hint. This allows that e.g. a cross-chain bridge can be used directly from a phone, and the cross-chain bridge is responsible for figuring out the fog part (and not the mobilecoin consensus network).
=> allow specifying a fog hint when minting

fog/api/proto/view.proto, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/impl/src/types.rs
The `QueryResponse`'s `missed_block_ranges`, `rng_records`, and `decommissioned_ingest_invocations` fields were previously not being collated. This wasn't a huge issue because each store should, in theory, produce the same values for these fields (because they are all supplied by the DB and have nothing to do with the store's sharding strategy). That said, there may be slight variations in these values if different stores experience more intense loads and are slightly behind the DB's most recent values. To cover our bases, this PR takes the union of all these field's values.
=> Collate remaining QueryResponse fields

connection/src/error.rs, consensus/api/proto/consensus_common.proto, consensus/api/src/conversions.rs, consensus/service/src/validators.rs, ledger/db/src/error.rs, ledger/db/src/tx_out_store.rs, transaction/core/src/validation/error.rs
Test client sometimes fails in CD with errors like this:
> 2022-11-01 23:40:23.511798629 UTC CRIT thread main on test_client panicked! panicked at 'Unexpected error SubmitTx(TxRejected(Ledger, "Ledger error: `Index out of bounds: 111964`."))', fog/test-client/src/bin/main.rs:111:23    0:     0x564d793cb0c9 - backtrace::backtrace::trace::he6de28a0cae2390a
https://github.com/mobilecoinfoundation/mobilecoin/actions/runs/3373323306/jobs/5598519127
(After this commit we can actually see the error message: https://github.com/mobilecoinfoundation/mobilecoin/commit/68c6b1afee693b9d1548a266bb247b18278306e9)
I believe that this may be caused by a race condition:
* Fog is reading from one of the consensus nodes, which is ahead of another
* The test client decides that some number of tx outs are in …
=> Retry ledger "index out of bounds" errors

Cargo.lock, Cargo.toml, util/vec-map/Cargo.toml, util/vec-map/README.md, util/vec-map/src/lib.rs
A heapless map type is needed for things like hardware wallets.
This was pulled out of #2725 to ease review.
This was mainly used to do POC work and evaluate how much stack space the TxSummary streaming verifier would actually use. But in the future it could become production code I think, we'll have to see.
=> Add mc-util-vec-map which exposes a heapless map type

api/src/convert/input_ring.rs, api/src/convert/signing_data.rs, api/src/convert/unsigned_tx.rs, transaction/builder/src/transaction_builder.rs
The `build_unsigned` function takes an RNG type parameter but it is not bound to any actual inputs, or used in the function body. So all the callers have to supply a pointless type parameter.
This is a random defect that I saw when developing #2725. Pulling this out to ease review of that.
=> fix unnecessary type parameter in build_unsigned

fog/sample-paykit/src/cached_tx_data/memo_handler.rs, transaction/builder/src/memo_builder/rth_memo_builder.rs, transaction/builder/src/transaction_builder.rs, transaction/core/src/tx_error.rs, transaction/extra/src/lib.rs, transaction/extra/src/memo/authenticated_sender_with_payment_intent_id.rs, transaction/extra/src/memo/destination_with_payment_intent_id.rs, transaction/extra/src/memo/destination_with_payment_request_id.rs, transaction/extra/src/memo/mod.rs
Copied changes from pull #2805 to fix GHA
Adding DestinationWithPaymentRequestIdMemo
Adding SenderWithPaymentIntentIdMemo
Adding DestinationWithPaymentIntentIdMemo
Motivation
This PR implements the changes outlined in https://github.com/mobilecoinfoundation/mcips/pull/54.
The current SenderWithPaymentRequestIdMemo allows the sender of a transaction to inform the recipient that an incoming payment pertains to some prior agreed upon payment request. That recipient can always reconstruct the history of that payment request using the ID in the memo. The new DestinationWithPaymentRequestIdMemo will provide the ability for the sender reconstruct the history of that payment ID as well.
The Sender and DestinationWithPaymentIntentIdMemos allow clients to implement a payment intent flow. This will …
=> Payment Intent and Request ID Memos

transaction/core/src/ring_ct/rct_bulletproofs.rs
This is a change that I wanted to do for a while, that I ended up doing as part of #2725 because it was necessary to do the hw-wallet signing flow appropriately.
Pulling out of #2725 to ease review, this is just code movement and should not be a functional change.
=> Move signing function to SigningData in rct_bulletproofs

transaction/core/src/input_rules.rs, transaction/core/src/tx_summary.rs
There is little downside to this since the TxInSummary is already very small compared to the TxOutSummary, and it allows that in the future we could also send the InputRules to the hardware device and verify them, if we decide that that is helpful.
This was a review comment in MCIP 52 from Ryan
=> Make the TxSummary include a digest of input rules, per discussion

.github/dependabot.yml
Currently every dependabot PR includes a comment about the reference to the non-existing 'blocks-v3.x' tag. This corrects that, and also spreads out the runs on an hourly basis for each of the 6 things that are getting updated.
=> Update dependabot labels, spread out the times from 10p PT to 3a PT

api/proto/external.proto, api/src/convert/tx.rs, consensus/api/proto/consensus_common.proto, consensus/enclave/api/src/config.rs, consensus/enclave/api/src/error.rs, consensus/enclave/impl/src/lib.rs, consensus/enclave/tests/enclave_api_tests.rs, consensus/service/src/api/client_api_service.rs, consensus/service/src/api/grpc_error.rs, fog/sample-paykit/src/client.rs, fog/sample-paykit/src/error.rs, fog/test-client/src/test_client.rs, transaction/builder/src/transaction_builder.rs, transaction/core/src/fee_map.rs, transaction/core/src/tx.rs, transaction/extra/src/unsigned_tx.rs
This is an alternative approach to #2670. The description here is copied
from there.
TOB-MCCT-5 is about a "token id oracle" described by TOB during review of confidential tokens design. The idea is that the consensus enclave fee map can be changed by the untrusted side, by restarting the node. If the attacker controls a node and is able to get the user to submit their Tx once with one fee map, and once with another, then the priority value leaks information about what the token id of the Tx is.
In principle they could do this without the user knowing -- they would restart the node and it would not be able to attest to the peers after changing the fee map, but it could still accept Tx proposals and see the WellFormedTxContext which conatins the priority number. Then they turn the node …
=> [TOB-5] add fee_map_digest to Tx

.github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .internal-ci/util/metadata.sh
Fix docker artifact tag construction on GitHub tag event.
- remove reference to non-existent function
- dedupe setting docker_tag variable
- fix github outputs for multiline docker tags.
This pr is the master version of #2788 (release/v3.0).
=> master - CI/CD - fix tag event docker tag construction

consensus/enclave/measurement/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ledger/enclave/measurement/build.rs, fog/view/enclave/measurement/build.rs
- Bump the enclave security version for all enclaves
In the `release/v3.0` branch, we've bumped the enclave security version to 6/5 for consensus/fog enclaves, respectively. This bumps them one more step beyond that, in preparation for the next release.
- Bump version
- Update ChangeLog
=> Bump enclave svn for next release.

.github/actionlint.yaml, .github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-dev-test.yaml, .github/workflows/mobilecoin-dispatch-dev-update-consensus.yaml, .github/workflows/mobilecoin-workflow-dev-bootstrap.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-reset.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml, .internal-ci/helm/mc-core-dev-env-setup/Chart.yaml, .internal-ci/helm/mc-core-dev-env-setup/values.yaml, .internal-ci/test/mint-auditor-test.sh, .internal-ci/test/minting-config-tx-test.sh, .internal-ci/test/minting-tx-test.sh, .internal-ci/util/generate_dev_values.sh, .internal-ci/util/generate_minting_keys.sh, .internal-ci/util/generate_tokens_config.sh, .internal-ci/util/tokens.base.json
Bootstrap environment from S3/PG backups. Reduce the amount of steps required to deploy and test.
Build out `v1.1.3-dev` environment, initialize ledger, run block_version 0 testing and capture block chain s3 buckets and fog recovery database. 
Backups are located in the development ledger bucket: `mobilecoin.eu.development.chain`
- `/prebuilt/${VERSION}/chain/node[1-3]/`
- `/prebuilt/${VERSION}/sql/fog_recovery.sql`
- Break setup steps into their own reusable workflow (more DRY)
- Use github `environments` feature for name spacing required secrets/configuration values.  (Step towards reusing workflows for alpha/beta/test/main artifact builds and deployments)
- Add bootstrap reusable workflow that will restore from a specified backup in s3.
- Remove all v1.1.3 deployment and testing steps. …
=> release/V3 - CD from backup

fog/api/proto/view.proto, fog/api/tests/fog_types.rs, fog/sql_recovery_db/src/lib.rs, fog/types/src/view.rs, fog/view/enclave/impl/src/e_tx_out_store.rs, fog/view/enclave/impl/src/oblivious_utils.rs, fog/view/server/test-utils/src/lib.rs, fog/view/server/tests/smoke_tests.rs
Previously, we were using the first byte in the `TxOutSearchResult.ciphertext` field to denote the difference in length between the ciphertext's payload and the overall length of the ciphertext. This is confusing because we're using bytes of a field to tell user's how to interpret the field. 
To make the API better, i added a `payload_length` field, which explicitly tells clients (or other portions of the code) how long the payload is. Now they won't need to do arithmetic or logic to interpet the field.
- Update the `TxOutSearchResult` proto to have an optional `ciphertext_padding` which holds the difference in paylaod and ciphertext length. This makes it so clients won't need to update and can continue using the old `ciphertext` field, while also maintainiing obliviousness (the same …
=> Replace ciphertext delta with explicit length field

mob
Building the entire workspace requires ~2GB per core.
Some machines have many cores but a small amount of ram resulting in out
of memory issues. When using `mob prompt` the number of jobs will be
limited based on the physical memory size. Developers can override this
by explicitly setting the `CARGO_BUILD_JOBS` environment variable to the
desired number of jobs `CARGO_BUILD_JOBS=4 ./mob prompt`.
=> `mob prompt`: limit number of cores based on memory

fog/recovery_db_iface/src/lib.rs, fog/sql_recovery_db/src/lib.rs, fog/types/src/common.rs, fog/view/server/src/db_fetcher.rs
I merged `master` into `feature/fog-view-router` and didn't accurately resolve merge conflicts for changes introduced by PR #2708. This PR fixes that merge issue and also updates the `sql_recovery_db` method to use a `BlockRange` (this is not strictly necessary for this PR but thought it was a good and easy cleanup)
=> Make query batch logic compatible with sharding strategy

consensus/enclave/impl/src/lib.rs, transaction/core/test-utils/src/lib.rs, transaction/core/test-utils/src/mint.rs
In #2589 we made it such that `MintTx` and `MintConfigTx` nonces are no longer global, and instead are tracked per token id. This mitigates a potential attack where the attacker uses a nonce that is intended for a different mint, and by that prevent the legitimate mint from going through.
This PR accompanies this change, and allows the enclave to accept identical nonces, as long as they are for different token ids.
=> TOB-4: change enclave to track nonces per token id

.github/dependabot.yml
The motivation for this is, dependabot may under various circumstances decide to rebase and force push all its open branchs. With the current configuration, that can cause 50 PRs to trigger CI all at once, which effectively DOS'es the engineers from using CI.
This change will cut down the number of open dependabot PRs at any point in time by about a factor of 5, so these force push events will cause much less load on the cluster and engineers will not be forced to manually cancel dependabot CI runs to get their work done.
=> Throttle dependabot

consensus/enclave/impl/src/lib.rs
form_block is a critical part of our code, so I felt it is appropriate
to explicitly test out the new nested multisig behavior at that point.
I am aware these tests are long and extremely verbose. There is likely
room for improvement, but I wanted to keep the scope of this PR small.
=> Add enclave form_block tests for nested multisigs to ensure end-to-end block forming behaves as expected.

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .internal-ci/test/minting-config-tx-test.sh, .internal-ci/test/minting-config-tx.json, Cargo.lock, consensus/mint-client/Cargo.toml, consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs, consensus/mint-client/src/lib.rs, consensus/mint-client/src/mint_config_tx_file.rs, tools/local-network/authorize-minters.py
Following a discussion with @holtzman, we reached the conclusion that generating a `MintConfigTx` file prior to signing would be easier if all the parameters for the transaction were self-contained inside a single JSON file.
To get an idea of what this file looks like, take a look [here](https://github.com/mobilecoinfoundation/mobilecoin/blob/eran/nested-signer-mint-config/tools/local-network/authorize-minters.py#L30-L39).
Following this change, this allows either specifying the nonce in the input JSON file, or via `--nonce` or to have it be randomly generated.
In addition, the tombstone block can either be specified in the JSON file, or via `--tombstone`, or queried from a node by using `--tombstone-from-node`.
=> Change mint-client to accept MintConfigTx parameters from a JSON file

common/src/logger/loggers/mod.rs
We'd like to have a way to format our stdout/stderr log messages as JSON strings, this will make it easier for machines to ingest our log messages.
The change proposed here allows switching to JSON output by setting the env var `MC_LOG_JSON=1`.
This fixes #2273
=> Add a way for outputting JSON-formatted log messages to stdout/stderr

consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs
adds check-sig command to mc-consensus-mint-client
The check-sig command lets the operator provide a public key to verify that a signature over a hash was done using the corresponding private key.  Useful for pre-validating mint config and mint transactions, as well as debugging transactions that fail.
This is a replacement for PR #2674 by @sugargoat, updated for the current master commit as well as updating terminology to be consistent with other mc-consensus-mint-client commands.
=> Mint client checksig

.github/workflows/ci.yml, .github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-bootstrap.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-reset.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml
Undo using GitHub Environments feature.  It's nice for organizing the secrets in a clean way, but it just makes a mess of the PR conversation history because of its integration with Deployments. Every action that references an environment creates its own "Deployment" in the pr log.
- fix: `actionlint` errors and warnings from `shellcheck`
- `actionlint` is checking shell code with `shellcheck` in GHA workflows.  This is good, but required some cleanup.
- fix: remove references to `dev` Environment
- fix: check and cleanup `secrets` names
- Just update and remap some var names for better organization
=> master (CI/CD) feat: CD don't use Github Environments

consensus/mint-client/src/bin/main.rs, consensus/mint-client/src/config.rs
added --tombstone-from-node <nodespec> to mc-consensus-mint-client's generate-mint-tx command
When generating a mint-tx file, a tombstone block for the mint-tx needs to be assigned. Previously, we required the user to independently look up the index of the last block of the blockchain, increment that by some amount, and pass it to the command using the --tombstone argument.
This PR adds an optional --tombstone-from-node argument which takes a node spec, asks the node for the current last block index, adds MAX_TOMBSTONE_BLOCKS - 1, and uses that for the mint-tx's tombstone block.
=> mint-client generate-mint-tx can now get tombstone block from consensus

admin-http-gateway/src/main.rs, consensus/service/src/bin/main.rs, fog/distribution/src/main.rs, fog/ingest/server/src/bin/main.rs, fog/ledger/server/src/bin/main.rs, fog/overseer/server/src/bin/main.rs, fog/report/server/src/bin/main.rs, fog/sql_recovery_db/cleanup/src/main.rs, fog/test-client/src/bin/main.rs, fog/view/server/src/bin/main.rs, go-grpc-gateway/testing/src/bin/main.rs, ledger/distribution/src/main.rs, ledger/from-archive/src/main.rs, ledger/migration/src/main.rs, mobilecoind-dev-faucet/src/bin/main.rs, mobilecoind-json/src/bin/main.rs, mobilecoind/src/bin/main.rs, util/grpc-admin-tool/src/bin/main.rs, watcher/src/bin/main.rs
I was handed the following stacktrace:
```
OH NO, WE CRASHED :( thread main on /home/sam/mobilecoin/target/release/mc-admin-http-gateway
Details: panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.4.0/lib.rs:125:13
0:     0x55cb59de1029 - backtrace::backtrace::trace::h636b2a06fc441be5
1:     0x55cb59dcc5b7 - backtrace::capture::Backtrace::new::h4e4c6302f49df649
2:     0x55cb59a1f8b4 - mc_common::panic_handler::setup_panic_handler::{{closure}}::h238b670fdff24b81
3:     0x55cb5a2a3aa6 - std::panicking::rust_panic_with_hook::h9ade200275992b5b
at /rustc/e85edd9a844b523a02dbd89f3c02cd13e4c9fe46/library/std/src/panicking.rs:702:17
4:     0x55cb59e187cb - …
```
=> Initialize the logger before doing other operations, so that if something uses the global logger we do not get a panic

fog/recovery_db_iface/src/types.rs, fog/view/server/src/block_tracker.rs
In #2852, I modified the `smoke_tests` to use the Fog View Router's `FogViewAPI` implementation (i.e. the new `unary` API). This caused the `test_middle_missing_range_with_decommission` to fail at line 828, which checks that the highest processed block count is 15. Instead, the test was producing 5. 
This occurs because the Fog View Server `enclave_block_tracker` doesn't track blocks for the first ingress key because its epoch doesn't account for any of that ingress key's blocks. As such, the `process_block_per_ingress_key` didn't have any entries for the first ingress key. This caused the check on line 159 to always fail, triggering the `else` block and causing the block count to never increment. 
The solution is to just skip over any keys that don't overlap with the shard's epoch.This …
=> Account for epochs in block tracker highest processed block count logic

fog/view/enclave/impl/src/lib.rs, fog/view/enclave/impl/src/types.rs
Previously, we weren't incorporating missed blocks into the shard collation highest processed block count calculation. This means that any missed block would cause the highest processed block count to never increase. This logic accommodates missed blocks, ensuring that they don't impede highest processed block count from incrementing.
=> Incorporate missed blocks into calculation for highest processed block count

Cargo.lock, attest/enclave-api/Cargo.toml, attest/enclave-api/src/error.rs, attest/enclave-api/src/lib.rs, consensus/enclave/trusted/Cargo.lock, crypto/ake/enclave/Cargo.toml, crypto/ake/enclave/src/lib.rs, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock
The "classic" unary Fog View API supports blank `QueryRequest`s. (i.e. a `QueryRequest` without egress keys). When implementing FVR, we decided to not support blank QueryRequests to simplify the Intel sealing logic, but this was a mistake because we forgot that clients should be able to query Fog View without egress keys to get information like highest processed block count etc. 
This change makes the necessary changes to the Intel sealing logic to allow for blank FVR `QueryRequest`s. This PR's logic is tested in the follow up PR that removes the classic Fog View API from fog view service.
=> Fix blank query sealing issue

.github/workflows/mobilecoin-dev-cd.yaml
Small fix for the CD workflow to break up some buggy logic on when to clean up a development deploy. This is technically less DRY, but in my opinion much easier to follow and probably more importantly, should actually work :grin:
=> fix(ci/cd): break out cleanup for cleaner logic

.github/workflows/mobilecoin-dev-cd.yaml
Eliminate v3.x deployment, test, upgrade, test part of the workflow by restoring a previously bootstrapped and tested s3 ledger and fog-recovery database at v3.0.0-dev.
=> feat(ci/cd): CD to bootstrap to v3.0.0

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/helm/consensus-node/templates/client-grpc-attest-ingress.yaml, .internal-ci/helm/consensus-node/values.yaml
Set up rate limits to the client attest endpoint to prevent abusive clients from pushing sessions out of the database.  
20 requests per minute per IP address.
=> feat: rate limit consensus client attest endpoint

fog/api/proto/fog_common.proto, fog/api/proto/ledger.proto, fog/api/proto/view.proto, fog/view/server/src/router_admin_service.rs
- Defines necessary protobuf messages for key image lookups in a Fog ledger router/store system.
- Moves AddShardRequest to fog_common.proto (see #2888)
As part of the ongoing project to improve Fog's scalability and stability, we're working on implementing a system that divides Fog ledger servers into a router (which routes requests from the client to a number of ledger store backends) and many stores (which actually hold relevant ledger data). Currently, only key image look-ups are supported.
* Pulling in the rest of the fog-ledger-router work from [milliec/ledger-router-dev into this branch](https://github.com/mobilecoinfoundation/mobilecoin/tree/milliec/ledger-router-dev) - so enclave API changes, implementation of the new enclave API methods, grpc servers, tests, etc.
=> Pull in protobuf changes from milliec/ledger-router-dev

.github/workflows/ci.yml, .github/workflows/dependent-repos.yml, .github/workflows/mobilecoin-dev-cd.yaml, .mobconf, consensus/enclave/build.rs, consensus/enclave/measurement/build.rs, consensus/enclave/trusted/build.rs, consensus/service/BUILD.md, docker/install_sgx.sh, fog/ingest/enclave/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ingest/enclave/trusted/build.rs, fog/ledger/enclave/build.rs, fog/ledger/enclave/measurement/build.rs, fog/ledger/enclave/trusted/build.rs, fog/view/enclave/build.rs, fog/view/enclave/measurement/build.rs, fog/view/enclave/trusted/build.rs, ops/Dockerfile-consensus
- Update scripts to use SGX SDK 2.18
- Update enclave build scripts to require 2.18 SDK
SGX 2.18 has been recently released, this PR updates our repository to use it.
=> Updates to support SGX 2.18.

.internal-ci/docker/Dockerfile.runtime-base
Bump runtime container packages for SGX 2.18
=> release/4.0 - fix: update sgx runtime packages 2.18

transaction/extra/src/tx_summary_unblinding/verifier.rs
I noticed a random defect in #2725 after we merged it:
* During the call to "add_input", it checks if we actually saw all of the expected outputs and returns an error if not.
* Similarly, during the call to "finalize" it should check if we actually saw all of the expected inputs and return an error if not, but I omitted that check by accident.
This rectifies the situation and doesn't break any tests.
=> fix a minor defect in tx-summary-unblinding-verifier

.github/workflows/mobilecoin-dev-cd.yaml, .internal-ci/docker/Dockerfile.bootstrap-tools, .internal-ci/docker/Dockerfile.fog-ledger, .internal-ci/docker/Dockerfile.fog-test-client, .internal-ci/docker/Dockerfile.fogingest, .internal-ci/docker/Dockerfile.fogreport, .internal-ci/docker/Dockerfile.fogview, .internal-ci/docker/Dockerfile.go-grpc-gateway, .internal-ci/docker/Dockerfile.mobilecoind, .internal-ci/docker/Dockerfile.node_hw, .internal-ci/docker/Dockerfile.runtime-base, .internal-ci/docker/Dockerfile.watcher
- fixes #2941 : Use docker sha tag instead of latest on FROM image for runtime containers.
- fixes #2942 : Run CD on all PRs to make sure graphite branch/merge chains get tested.
=> release/v4.0 - fix:  CD workflow issues #2941 and #2942

Cargo.lock, fog/ledger/enclave/api/src/lib.rs, fog/ledger/enclave/api/src/messages.rs, fog/ledger/enclave/impl/Cargo.toml, fog/ledger/enclave/impl/src/lib.rs, fog/ledger/enclave/src/lib.rs, fog/ledger/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/src/lib.rs, fog/ledger/test_infra/src/lib.rs
- Adds `ledger_store_init()`, `frontend_accept()`, and `ledger_store_connect()` to the Fog ledger enclave API for general use with a fog ledger router/store system
- Adds `check_key_image_store()`, `decrypt_and_seal_query()`, `create_multi_key_image_store_query_data()`, and `collate_shard_query_responses()` to the Fog ledger enclave API, which are currently specific to key-image store queries
- Implements all of the above new API methods, including stub methods for testing. 
- New EnclaveCall variants for the above methods. 
Depends on #2889
As part of the ongoing project to improve Fog's scalability and stability, we're working on implementing a system that divides Fog ledger servers into a router (which routes requests from the client to a number of ledger store backends) and many …
=> Ledger enclave support for router and store

fog/api/proto/ledger.proto, fog/ledger/enclave/api/src/messages.rs, fog/uri/src/lib.rs
Add new URIs for Fog Ledger / Key Image Router and Store.
The new Fog Ledger Router and its Key Image Store require two new URI types to exist, one for admin access to the Fog Ledger Router which can add new shards, and one for Key Image Store which will be communicated with by the router.
I don't think there is any future work for this particular PR.
=> URIs for Fog Ledger Router

fog/api/src/conversions.rs, fog/uri/src/lib.rs
Pull in protobuf object conversion functions for Fog Ledger Router
As part of the Fog Ledger Router project, we need functions to convert from protobuf objects to various Rust objects. This pulls in the changes made to conversions.rs for upstreaming.
The next PR in this series will be the stubs of the APIs added to the Fog Ledger enclave to support the Fog Ledger Router.
=> Protobuf conversion functions for Fog Ledger Router

fog/view/server/src/router_request_handler.rs, fog/view/server/src/shard_responses_processor.rs
Currently, the `router_request_handler` can terminate its request loop if there are still view stores that need to be authenticated. The expected behavior is to: 
(a) Return a success if all the ready shards (see note below0 have returned query_responses
(b) After 3 retries, return an error if some shards returned errors that need to be retried.
This PR accomplishes this by adding shards that return responses with `UNKNOWN` status codes to the `shard_clients_for_retry` field (which it should have been doing before), and only decrementing the retry count if there are no stores that need authentication. 
NOTE: This is slightly different than the Fog Ledger Router implementation because that implementation breaks the loop once the number of `query_responses` equals the number of …
=> Fix shard response processing loop

fog/ledger/server/src/error.rs, fog/ledger/server/src/key_image_router_service.rs, fog/ledger/server/src/lib.rs, fog/ledger/server/src/router_handlers.rs
Implementation of the Key Image Router Service
This is the Key Image Router Service, which does the actual work of querying the Key Image Stores and obliviously collating the responses received.
The Key Image Router Service needs to be hosted inside of a Key Image Router Server, which itself needs to be hosted in the key image router binary. These will both be added in subsequent PRs.
It is known that the Key Image Router Service needs to be enhanced to keep track of the block ranges expected from shards, to guard against the case where a shard is mistakenly backed by a store with a different configured block range. This will also affect the loop termination logic, which (in this PR) assumes that a response from all shards is both necessary and sufficient to address a query.
=> Key Image Router Service

rustfmt.toml
I discovered that running `cargo fmt --all` tries to format Baidu-originated files. We should either format them or ignore them, and it seems like our solution for other Baidu code was to ignore it.
=> dont format Baidu code

tools/local-network/README.md, tools/local-network/local_network.py, tools/local-network/prometheus.yml.template
The purpose of this was to do a local slam with prometheus and compare to the results we get in the cloud.
My results were like this:
So, I did not match the ~100 tx/s that Eran was seeing in the dev networks, but I did get about twice as high as I was getting for a 5 node network locally. (See other results here: https://github.com/mobilecoinfoundation/mobilecoin/pull/2934)
=> Make the local network script support a dense3 network option

Cargo.lock, fog/ledger/enclave/impl/Cargo.toml, fog/ledger/enclave/impl/src/lib.rs, fog/ledger/enclave/impl/src/oblivious_utils.rs
Obliviously collates responses from Key Image Stores, to maintain security properties under the new router/store model.
We want to maintain our security properties even though we are splitting out the Fog Ledger service into a router/store model. In order to do this, we obliviously collate the responses from Key Image Stores in encrypted SGX memory so that an attacker cannot determine which shard a given response came from.
=> Oblivious collation of key image store responses

fog/view/server/src/fog_view_router_service.rs, fog/view/server/src/fog_view_service.rs, fog/view/server/src/router_request_handler.rs, util/grpc/src/lib.rs, util/metrics/src/lib.rs, util/metrics/src/service_metrics.rs
Implements Prometheus metrics for Fog View Router (FVR). Previously, upon receiving a request, the router "opened" a Prometheus metrics session, but it never closed it. This PR closes the session and refactors some underlying util logic for cleanliness.
=> Implement prometheus metrics for FVR

transaction/extra/src/signed_contingent_input.rs
Other error traits implement this and it makes some tests (that I am working on in a separate repository) easier.
=> Derive Eq for SignedContingentInputError

rustfmt.toml
I discovered that running `cargo fmt --all` tries to format Baidu-originated files. We should either format them or ignore them, and it seems like our solution for other Baidu code was to ignore it.
Cherrypick of #2987
=> dont format Baidu code 

fog/view/server/src/fog_view_router_service.rs, fog/view/server/src/router_request_handler.rs, util/telemetry/src/lib.rs
Implements opemtelemtry tracing for Fog View Router. Makes use of `async` opentelemtry tracing primitives to accommodate the router's async code.
=> Implement optelemetry tracing for FVR

.github/workflows/mobilecoin-dev-cd.yaml, tools/lint.sh
We're finding there's a lot of pain in the dynamic environments at the moment.  We don't want to loose the production like deployment testing, but we're going to roll back the CD requirement for new work going towards master branch.
- Limit trigger to PRs with 'release/*' as the base ref
- remove push trigger on main, master, and release/* branch
- change clean up tasks CD to match new triggers.
- Add mobilecoin-cd-complete dummy job that is just successful if the rest of the workflow is successful.  This way we have a "standard" job with a static name we can use for branch protection checks.
=> Remove cd triggers for PRs, main and master branches

.github/workflows/mobilecoin-dev-cd.yaml, tools/lint.sh
Roll up PR ([#3029]) to v4.1
* fix: remove cd triggers for PRs, main, master branches
* fix: lint script to use version and locked cargo-sort install
=> v4.0 to v4.1 roll up - Remove cd triggers for PRs, main and master branches (#3029)

fog/types/src/common.rs, fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/src/fog_view_router_server.rs, fog/view/server/src/fog_view_router_service.rs, fog/view/server/src/router_admin_service.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/shard_responses_processor.rs, fog/view/server/src/sharding_strategy.rs, fog/view/server/test-utils/src/lib.rs, tools/fog-local-network/fog_conformance_tests.py, tools/fog-local-network/fog_local_network.py, tools/fog-local-network/local_fog.py
As described in #2966, the Fog View Router (FVR) has no way of knowing if a shard provides the "correct" block range - i.e. the block range for which it was configured to process. This PR makes FVR aware of the shards' block ranges and throws an error if a shard provides an incorrect block range.
=> Ensure shards provide correct blocks

.github/workflows/mobilecoin-dev-cd.yaml, tools/lint.sh
Roll up PR (#3029 / #3030) to master
* fix: remove cd triggers for PRs, main, master branches
* fix: lint script to use version and locked cargo-sort install
=> v4.1 to master roll up - Remove cd triggers for PRs, main and master branches

api/src/convert/mod.rs, api/src/convert/signed_contingent_input.rs
We need a way to go between the Rust/prost struct and the protobuf version. This is similar to a whole bunch of other conversion code we already have.
=> add SignedContingentInput proto conversion

watcher/src/watcher_db.rs
This makes it easier to expose it over APIs such as in full-service
=> add Clone/serde traits to watcher_db::BlockSignatureData

CHANGELOG.md, mobilecoind-json/src/data_types.rs
I don't think there's a reason not to include it for v1, since this is a new field it should not break existing mobilecoind-json users, they could just ignore it.
=> always include the masked amount version

fog/README.md
This is a simple update to the Fog README to change the Diesel CLI install instructions to specify version 1.4.1. We expect Diesel version 1.* in our migrations, and by default `cargo install` will select a 2.* version of Diesel.
I chose not to explain that in the README and just change the install instructions, but I'd be open to being told I should explain as well. I also chose not to try to port the migrations to 2.*, as I don't really know anything about Diesel currently.
The current instructions have become wrong over time and will confuse new devs on the project.
=> Clarify that `diesel_cli` must be version 1 for Fog migrations to run correctly

Cargo.lock, core/src/lib.rs, core/src/protos.rs, core/src/subaddress.rs, core/types/Cargo.toml, core/types/src/account.rs, core/types/src/keys.rs, core/types/src/markers.rs, crypto/ring-signature/src/onetime_keys.rs
some smol improvements extracted from the ledger adventure branch
- add new `account::ViewAccount`, `keys::{TxOutPublic, TxOutTargetPublic}` types to core
- add `TryFrom<[u8; 32]>` key constructors alongside existing `TryFrom<&[u8; 32]>` impls for `Key` container to smooth over some type constraint challenges 
- passthrough `prost::Message` and `ReprBytes` for `Key` container types to improve compatibility when replacing `RistrettoPublic` and `RistrettoPrivate` types in serializable objects
=> add account::ViewAccount, keys::{TxOutPublic, TxOutTargetPublic} to core, improve prost support for key types

.github/dependabot.yml
- Dependabot PRs request reviews from @mobilecoinfoundation/coredev.
- Remove explicit label selection (will be dependencies,rust).
Github now allows automatic assignment to particular users when a group review is requested. I've turned that on for coredev, which means we can request a review from the group, and group members will be tagged automatically.
Additionally, the blocks-v5.0.0 label isn't really proving useful, so I'd rather just remove it, which means we can revert back to dependabot picking "dependencies" and "rust" labels itself.
[Soundtrack of this PR](https://music.youtube.com/playlist?list=OLAK5uy_k2RFXIfn6MsHK3JpYKtXoOlQ_LVK_ltJo&feature=share)
=> Dependabot reviewers and labels update

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-dev-update-consensus.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml, .internal-ci/util/.shared_functions, .internal-ci/util/generate_dev_values.sh, .internal-ci/util/set_tokens_config_version.sh, tools/lint.sh
Its currently a fiddly process to deploy a main/test signed artifacts to the dev cluster for smoke testing. This improves the process from 1h+ manual effort to 10m of automated "push-button" deployment.
- scripts to detect and set correct signed tokens.json based on version and network tier.
- add option to bootstrap a dispatch deploy from backup.
- update dispatch deploy defaults for v4 release.
- remove need to specify a tokens version.
- add secrets (really configs because the values are not secrets) for testnet/mainnet tokens.json
- add secrets for test/main ias 
This will be promoted to release/v4.1 -> master.
=> release/v4.1 - feat(cd/testing): add ability to manually deploy a test/main network to dev

.github/workflows/ci.yml, mobilecoind-dev-faucet/README.md, mobilecoind-dev-faucet/src/lib.rs, mobilecoind-dev-faucet/src/worker.rs
Jason requested that, the mobilecoind-dev-faucet should not immediately start sending lots of transactions after it is deployed, because that makes some other deployment-related things harder. By default it does that because it wants to have its queue full.
The change we made is:
* The faucet worker now has an "is_active" flag, which if false causes it to skip its loop, and this defaults to false.
* The flag is set to true if `--activate` is passed.
* The flag is set true whenever an HTTP POST occurs (post to get payment from faucet, or to start a slam), whether or not the POST results in a successful operation.
* Docu is updated so that for dev testing it demonstrates `--activate` and the existing documented flows should still work.
* CI is updated to use `--activate`
=> Add an "activate" option for the mobilecoind-dev-faucet

mobilecoind-dev-faucet/src/data_types.rs
this stores the units of the "prepare_time" and "submit_time" in the names of these json elements.
it also computes the average throughput of the slam operation -- total transactions divided by total time. this is a rough approximation to the peak tx/s that should be reasonably accurate for a sustained slam.
this number is obtained programmatically from the tool conducting the slam, rather than by humans looking at graphs, and so doesn't have the fuzziness of people judging lines, which in my mind gives it some merit to be worth reporting.
(not that it should replace the number we normally use)
=> write additional helpful data in the json slam report

transaction/extra/src/signed_contingent_input.rs
It is useful to be able to serialize a `SignedContingentInput` so that it can be stored/sent over various mediums.
=> add serde traits to SignedContingentInput

fog/types/src/view.rs, fog/view/enclave/impl/src/types.rs, fog/view/server/src/block_tracker.rs, fog/view/server/src/config.rs, fog/view/server/src/error.rs, fog/view/server/src/fog_view_service.rs, fog/view/server/src/router_admin_service.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/server.rs, fog/view/server/src/shard_responses_processor.rs, fog/view/server/test-utils/src/lib.rs, fog/view/server/tests/unary_smoke_tests.rs, util/uri/src/uri.rs
When deploying Fog View Router to a local network, we discovered that the router was trying to contact the store via a url with host == `0.0.0.0`. This occurred because the store used its `client_listen_url` to construct the URI that it gave to the router during the auth process. The router was unable to contact the store because it operated on a different host, not the same host as the router.
To fix this, I added a `responder_id` query param to the `FogViewStoreUri`, and the value is the externally addressable responder_id in "{HOST}:{PORT}" format. This enables the router to contact the store running in the same local network on a different machine.
=> Make Fog View Store return externally-addressable URI to Router

fog/view/enclave/impl/src/e_tx_out_store.rs, fog/view/server/tests/streaming_smoke_tests.rs, fog/view/server/tests/unary_smoke_tests.rs
The `test-client` test against the locally deployed FVR was failing because the `e_tx_out_store` code panicked during the payload slice copy from the OMAP-returned value and the default ciphertext- these two slices had different lengths. This length mismatched occurred because the default ciphertext had a `payload_length` the size of the **last** TxOut that was processed by `e_tx_out_store`. 
The issue with this approach is that there are differently-sized TxOuts (e.g. some TxOuts have memos, some don't). In this case, the `payload_length` was being initialized to 188 (corresponding to the length of a non-memo TxOut) and then the OMAP-returned `payload_length` was length 210 (because it corresponded to a memo TxOut). 
To fix this issue, we no longer initialize the `paylaod_length` to the …
=> Fix e_tx_out_store

transaction/builder/src/transaction_builder.rs, transaction/extra/src/signed_contingent_input.rs
This will allow services such as DEQS to send the error over RPC calls.
=> add serde and other useful traits to SignedContingentInputError

util/grpc/src/grpcio_extensions.rs, util/uri/src/uri.rs
It used to be the case (prior to some `grpcio` version bump) that it was easy to get the addresses a GRPC server is listening on after the server is created. That was useful when asked to listen on port 0, which causes the system to bind some random free port number. This is a functionality we often use in tests to avoid hard-coding port numbers.
I'd like to make it possible to reuse the TLS credentials setup code while still making it possible to get the chosen port. The scenario that makes me want it is the following:
1) I have an app object, that amongst other things, creates a GRPC server and configures it to listen on some host:port using a URI passed to it on its initialization (and this [Uri](https://github.com/mobilecoinfoundation/mobilecoin/blob/master/util/uri/src/uri.rs#L30) …
=> Make it possible to access the port a GRPC server is listening on

common/src/logger/loggers/mod.rs, util/logger-macros/src/lib.rs
We currently have a `#[test_with_logger]` macro that makes it convenient to write tests that require a `Logger` instance.
It is useful to have an async version of that, in case we want to test async code.
=> add async_test_with_logger macro

Cargo.lock, fog/view/enclave/impl/Cargo.toml, fog/view/enclave/impl/src/e_tx_out_store.rs, fog/view/enclave/impl/src/lib.rs, fog/view/enclave/trusted/Cargo.lock
###
This PR makes the `e_tx_out_store`'s `find_record` method constant time. This is necessary in order to preserve our obliviousness guraantees.
=> Make find_record constant time

util/build/info/build.rs
Previously `?????` would be returned for an inability to run git and
the git error would be returned for a failure running git, when trying
to determine the git commit during build. Now "unknown" will always be
returned in either failure condition.
The drive for this is to prevent log messages of the form
`"GIT_COMMIT" : "fatal: detected dubious "` which can happen in some CI
systems due to newer git `safe.directory` settings.
=> Use "unknown" for `GIT_COMMIT` failures.

.github/actions/run-mc-tests/action.yml, .github/actions/setup-rust/action.yml
Previously `set-output` was used to propagate values from Github actions
to the Github CI jobs, now the variable `GITHUB_OUTPUT` is used to
propagate these values.
This change was made in response to the deprecation of `set-output` by
github,
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Remove use of `set-output` in GHA CI

tools/local-network/prometheus.yml.template
AFAIK this grafana push stuff, for the local network script, hasn't been used by anyone in a few years, and it requires you to do additional setup in grafana. If you just want to talk to prometheus web interface, you have to comment this out or you get logspam.
I feel like it makes sense to comment this out, and let people put it back if they actually want to push from local network to grafana, but lmk if you'd rather leave it in, not a big deal.
=> This comments out the "grafana push" part of the prometheus yml template

.github/dependabot.yml
- Add dependabot for go-grpc-gateway
- Set coredev + cbeck88 as reviewers
Right now we're not updating any dependencies in go-grpc-gateway, but we should.
=> Add dependabot for go-grpc-gateway

fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/src/sharding_strategy.rs
Allows ops to pass `shard_uri` with a comma delimiter.
=> Make shard uris delimiter be a comma

fog/ledger/server/src/router_handlers.rs, fog/ledger/server/src/router_server.rs, fog/ledger/server/src/router_service.rs
* Implements support for the unary `FogKeyImageApi` on LedgerRouterService.
This should allow for backwards-compatibility with clients still using the unary API. Unary requests for key images made to the key image router should be routed properly.
Test this code path - both directly (if possible) and by a connection to localhost.
=> Fog router support for the unary API

Cargo.lock, util/telemetry/Cargo.toml, util/telemetry/src/jaeger.rs
- Unfork opentelemetry, opentelemetry-jaeger
- Update to version 0.18, 0.17, respectively
- Use the reqwest_rustls_collector_client feature instead of curl-based backend.
This crate was previously pulling in isahc (and eventually openssl-sys). This removes that dependency (and therefore openssl-sys).
=> Unfork opentelmetry, use reqwest backend.

fog/view/server/src/db_fetcher.rs, fog/view/server/src/server.rs
Jason reported that fog view is now declaring itself ready well before the highest-processed-block-count is close to the block height.
In the past, the main bottleneck was loading the data from Postgres, but now it's actually putting the data into ORAM.
In this commit, we refine the readiness criteria, so that both the db fetcher and the enclave loading thread have to run out of work before the server declares itself ready.
=> adjust readiness criteria for fog view

hooks/pre-commit
this has been causing me to put 2022 in a lot of files, and I think others also
=> update year in the expected copyright line in commit hook script

BUILD.md, util/build/sgx/src/env.rs
Many projects submodule mobilecoin.git and do not have it's BUILD.md document which describes how to set these variables.
It frequently happens that newly onboarded developers, or partners like copper, run into a build error that looks like this:
```
Compiling libp2p-plaintext v0.37.0
Compiling libp2p-floodsub v0.40.1
Compiling slog-envlogger v2.2.0
error: failed to run custom build command for `mc-attest-core v4.0.2 (/home/chris/mobilecoinofficial/deqs/mobilecoin/attest/core)`
Caused by:
process didn't exit successfully: `/home/chris/mobilecoinofficial/deqs/target/debug/build/mc-attest-core-fa6d778110b3deb5/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'Could not parse SGX environment: Variable(NotPresent)', mobilecoin/attest/core/build.rs:8:41
note: run …
```
=> give more helpful error messages for SGX_MODE and IAS_MODE settings

.mobconf
Change .mobconf to point to 0.0.23
The current builder image hits permission issues when doing builds, because it can't write to /opt/rustup.
=> Update version of builder image to fix permissions issues in /opt/rustup. New builder image thanks to Jason Greathouse.

util/logger-macros/src/lib.rs
We have a helper macro `#[async_test_with_logger]` that uses [`[tokio::test]`](https://docs.rs/tokio/latest/tokio/attr.test.html) under the hood, and it is useful to be able to pass down attributes to `[tokio::test]`. Specifically, it is useful to have some tests use the multi threaded runtime so that they are more representative of the real world.
=> Allow passing of attributes to the underlying #[tokio::test] macro

Cargo.lock, Cargo.toml, attest/verifier/config/Cargo.toml, attest/verifier/config/README.md, attest/verifier/config/src/lib.rs
Rendered [README](https://github.com/mobilecoinfoundation/mobilecoin/blob/attest-verifier-config-ii/attest/verifier/config/README.md)
This is meant to address comments on PR #3078, and allow that a client can load multiple MRENCLAVE measurements on startup and also apply different sets of hardening advisories to these as appropriate.
The idea is that there is a file named e.g. `trusted-measurements.json` which contains a json schema organizing enclave measurements, their respective lists of mitigated hardening advisories, and what release they are associated to, as well as any additional metadata for setting up MRSIGNER verifiers, if that is desired.
Clients like mobilecoind or full-service can load this on startup to configure their verifiers. SDKs could likely bake this in as a string …
=> make a way to store hardening advisory data with enclave measurements and load it

.github/workflows/ci.yml, .github/workflows/dependent-repos.yml, .github/workflows/mobilecoin-dev-cd.yaml
This is a follow on to c4d01f1fb1509fd0775c68b369e4807c706d4364 which bumped the docker version for mob prompt to the latest image. This change also changes it for the CI/CD workflows, so that everything is on the new image.
=> bump ci docker image version

fog/ledger/server/src/key_image_store_server.rs, fog/ledger/server/src/router_handlers.rs
Pulling in changes discovered by Fog View Router leading to PR #3081. Returning remotely-accessible Responder ID URI from Key Image Stores rather than local bind address.
=> Make Fog Ledger Store return externally-addressable URI to Router

fog/ledger/server/src/bin/router.rs, fog/ledger/server/src/config.rs, fog/ledger/server/src/router_server.rs, fog/ledger/server/tests/connection.rs, fog/ledger/server/tests/router_connection.rs, tools/fog-local-network/fog_conformance_tests.py, tools/fog-local-network/fog_local_network.py, tools/fog-local-network/local_fog.py
Fog Local Network and Fog Conformance are two of our most comprehensive Fog tests. It's important that they exercise the binaries we intend to actually deploy, which, in the near future, will be the Fog Ledger Router version. This PR ports those tests to exercise the Ledger Router.
In the future, the Ledger Router should be exercised with multiple stores (#3160). Also, the streaming API should be used instead of (or in addition to) the unary API (#3161).
=> Port fog local network and conformance tests to use ledger router

hooks/pre-commit
this avoids annoying copyright nonsense when moving commits from master to release/v4.1, (2023 vs 2022)
=> make the pre-commit hook check the year itself

mob, mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/payments.rs, mobilecoind/src/service.rs
This adds support for swap proposals and SCIs to mobilecoind.
This is meant to help test the deqs project, which is hard if there is not some wallet software that can incorporate SCIs or make swap proposals.
=> Mobilecoind scis

mobilecoind/src/payments.rs, mobilecoind/src/service.rs
The `SignedContingentInputBuilder` does not know the TxOut global
indices of the ring elements, they usually aren't supplied to it
unless merkle proofs of membership were supplied to it.
It usually ends up setting `tx_out_global_indices` to a list of zeroes.
Then the originator is supposed to set these correctly,
and it falls to the counterparty to find proofs of membership.
I forgot to do this in `generate_swap_impl`, so `mobilecoind` was
leaving `tx_out_global_indices` with an incorrect setting. This
commit fixes it and adds a test.
this bug was introduced a few days ago here: https://github.com/mobilecoinfoundation/mobilecoin/pull/3212
=> mobilecoind: fix a bug in swap generation

Cargo.lock
- Revert Cargo.lock to 3236e2ac814bb6d947af96bd027c8668d8ff8c36
- Update spin to 0.9.6 (0.9.5 was yanked yesterday)
- Re-run cargo-check to pickup changes from release/v4.1
Don't downgrade a bunch of crates which were updated in master but not in 4.1.
=> Revert cargo.lock to the previous revision in master.

hooks/pre-commit
It frequently happens that I modify a file but the copyright line is wrong (from last year). Then the hook inserts a new copyright line, instead of fixing the old one, and I go back and fix it manually.
I have done this enough that I would rather make the tool fix the copyright line.
I can use `git commit -n` but it feels dirty and sometimes I need both formatting and copyright fixes.
=> make the copyright hook smarter

Cargo.lock, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock, transaction/core/Cargo.toml, transaction/core/src/input_rules.rs, util/u64-ratio/README.md, util/u64-ratio/src/lib.rs
This extends the changes in #3214 around DRY'ing up the u64 / u128 arithmetic stuff.
I don't think we should merge this in release/v4.1 since we can't modify the enclave in 4.1 anyways, I think we should just do this in master later. But this at least shows the direction of the U64Ratio stuff.
=> make transaction core input rules validation use U64Ratio

fog/sample-paykit/src/cached_tx_data/memo_handler.rs, transaction/builder/src/lib.rs, transaction/builder/src/memo_builder/defragmentation_memo_builder.rs, transaction/builder/src/memo_builder/mod.rs, transaction/builder/src/transaction_builder.rs, transaction/core/src/tx_error.rs, transaction/extra/src/lib.rs, transaction/extra/src/memo/defragmentation.rs, transaction/extra/src/memo/mod.rs
* Added DefragmentationMemoBuilder
* Added DefragmentationMemo
This PR implements changes outlined in [MCIP #61](https://github.com/mobilecoinfoundation/mcips/pull/61).
[MCIP #61](https://github.com/mobilecoinfoundation/mcips/pull/61) proposes a new memo type: the defragmentation memo. This memo type is used to denote defragmentation transactions. It also includes an ID field that can be used to easily group together multiple rounds of one defragmentation session together for the purpose of reporting total paid in fees and total amount defragmented. The full implementation details and rationale for defragmentation memos can be found [here](https://github.com/dolanbernard/mcips/blob/defrag-memo/text/0061-defrag-memos.md).
=> Defragmentation Memos

crypto/keys/src/lib.rs
This type is already exposed in public APIs of RistrettoPublic and various conversions, but it is not actually exported from the crate, so there is no way for downstream to name the type.
This commit re-exports the type at crate level, which is already part of the public API anyways.
=> expose Schnorrkel Error from mc-crypto-keys

fog/ledger/server/src/router_handlers.rs, fog/ledger/server/src/router_service.rs
Adds optelemetry tracing calls to router_handlers.rs and router_service.rs. 
For all of the reasons metrics tracking is useful in general, we've needed to implement optelemmetry metrics for the Fog Ledger Router. This is modeled after a similar pull request, #2979 for Fog View Router.
\* Since this pull request is, for the most part, a simple copying-over of work from #2979 from the Fog View Router to the Fog Ledger Router, no finer-grained metrics specific to the Fog Ledger Router are present yet. In particular, these metrics do not differentiate between key-image requests and other types of request such as merkle proofs and block service. Optelemmetry calls in those preexisting services probably already cover this, but it might be worth double-checking.  
\* There is no testing in …
=> Optelemetry tracing for FLR

sgx/urts/src/panic.rs
Most of the time when an enclave panics, particularly during local development, the process dies with a hard abort before slog gets a chance to flush it's buffer.
This commit makes it emit the panic message on STDERR first, using eprintln, which means it will be in an OS buffer before the process ends. We continue to write it as well as to slog, which writes to STDOUT.
I see no reason not to do this, it's a massive quality of life improvement for anyone actually working on enclave-impl's.
Without this patch, 100% of the time i do not get panic messages from the enclave, and just a core dumped (aborted) message.
=> fix enclave panic reporting so that it always shows the error

Cargo.lock, common/Cargo.toml, common/src/logger/loggers/mod.rs, common/src/logger/mod.rs
- Remove `slog-gelf`
- Update `tokio` and friends to 1.25 (and similarly newer versions)
This removes `slog-gelf`, which in turn has a build-time dependency on the known-vulnerable `remove_dir_all`, and updates `tokio` and friends to a more modern version.
=> Update tokio, remove slog-gelf

Cargo.lock, util/b58-decoder/Cargo.toml, util/b58-decoder/src/bin/main.rs
Provide a helper to compute the hash for a public address, to facilitate spot-checking RTH and T3 entries.
Sample output:
```
B58 decoded successfully to a PrintableWrapper with a PublicAddress
View public key: ec4836064f75a531074e304d3bd37d0c3bd2f2a657d8318208c86d3f152e9c05
Spend public key: 22dd62976a5963d14c382e75c26d15a7a96088f77998186fb187884282bd7331
Fog report URL: fog://fog.prod.mobilecoinww.com
Fog report id: 
Fog authority sig: c4d4c09752c323217f64848b39babde7b34fa9df22fe9bdcd7a07fc54e7eff0c278ed743f879cf019d53336d4595285914f818933998b47f00783f2dfe671180
Validated: PublicAddress { view_public_key: RistrettoPublic(ec4836064f75a531074e304d3bd37d0c3bd2f2a657d8318208c86d3f152e9c05), spend_public_key: RistrettoPublic(22dd62976a5963d14c382e75c26d15a7a96088f77998186fb187884282bd7331), …
```
=> Extend b58-decoder to print public address hashes

crypto/keys/Cargo.toml
https://github.com/mobilecoinfoundation/mobilecoin/blob/master/crypto/keys/src/ed25519.rs#L40-L41 gates a `use` statement for the `mc_util_serial` crate behind the `serde` feature, but the `serde` feature as currently configured in this crate's `Cargo.toml` does not include the `mc_util_serial` crate when enabled.
=> include necessary optional dep when the serde feature is enabled

consensus/service/src/api/client_api_service.rs
* Adds a field, `tx_proposal_failures` to `ClientSessionTracking`
* Implements the method `fail_tx_proposal()` on `ClientSessionTracking`
* Invokes `session.fail_tx_proposal(now)` when a tx proposal is found to be invalid.
This will be used to track how many failed tx proposals have been sent recently, so that bad connections can be dropped, to prevent attacks and harmful behavior from buggy clients. See: https://github.com/mobilecoinfoundation/mobilecoin/issues/2977
* Actually drop clients
* Prometheus metrics related to this system.
* Code to determine if a particular client / IP address needs to be blocked temporarily or indefinitely.
=> Track failed tx proposals in consensus

mobilecoind/src/payments.rs
i'm finding that sometimes it fails with attestation permission denied errors otherwise
---
feel free to leave comments about how you would like this to be more configurable or use exponential backoff or something, let's decide exactly how it should work during review
=> add retries to mobilecoind when it submits transactions

docker/rust-toolchain, util/build/sgx/src/config.rs
Previously the rust-toolchain file was using the legacy one line toolchain version format from https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file. Now the rust-toolchain file uses toml format and updates the nightly version to the last nightly that contained 1.68.
Dependabot has been updated to only read the toml format of the rust-toolchain file.
Keeping the changes targeted on the dependabot fix, the rust-toolchain file was not renamed to the newer `rust-toolchain.toml`.
The nightly version was bumped to the last nightly that was 1.68. This was to bring in the https/sparse crates.io logic that came in 1.68 which dependabot relies on for 1.68 toolchain versions. This was only moved a little to minimize other clippy and format changes that might be needed.
For reference …
=> Update rust-toolchain to toml format

fog/ingest/server/src/lib.rs, fog/ledger/server/src/lib.rs, fog/report/server/src/lib.rs, fog/view/server/src/lib.rs
[Issue](https://github.com/mobilecoinfoundation/mobilecoin/issues/3281)
This issue was because fog service names were same for OpMetrics and ServiceMetrics. 
Consensus service has different names for the two metrics. 
This PR edits fog service names to be consistent with "consensus_service" in Prometheus.
=> Prometheus edit service names

.internal-ci/helm/fog-services/templates/fog-ledger-rollout-cr.yaml, .internal-ci/helm/fog-services/templates/fog-view-rollout-cr.yaml
The DeepDerivative [function](https://github.com/kubernetes/apimachinery/blob/9652184382609030b58bb40ab009eb0c45b56219/third_party/forked/golang/reflect/deep_equal.go#L424) we use to check if an update is required, doesn't play nicely with default ints that are none-zero or none-pointers. Other default work fine as documented
=> adds successThreshold and timeoutSeconds

.internal-ci/helm/fog-services/templates/fog-view-rollout-cr.yaml
* Move duplicate `CLIENT_AUTH_TOKEN_SECRET` reference out of store, and into router.
* While this didnt cause any issues, it would have removed CLIENT_AUTH from the `fog-view-router` if enabled
* None
=> Move CLIENT_AUTH_TOKEN_SECRET to correct location in view router

fog/api/proto/ledger.proto, fog/ledger/server/src/key_image_service.rs, fog/ledger/server/src/router_handlers.rs
Preserve Prost decode errors from key image store
The Key Image Store is not preserving any Prost decode errors, instead reporting them as Authentication errors. This leads to a continuous thrash from the Fog Ledger Router as it thinks it's hitting a different store every time.
We shouldn't be having Prost decode errors, so we still need to figure that out, but this is an OK first step.
Also, the router might want some kind of "this is getting ridiculous" timeout if it thinks it's hit, say, a thousand unique stores.
=> Preserve Prost decode errors from key image store

.github/workflows/refresh-ledger-bootstrap.yaml, .internal-ci/util/wait-for-mobilecoind.sh
Add GHA daily cron job to refresh pre-loaded mobilecoind ledger and watcher database files saved to Azure Blob Storage accounts.
Tested here: https://github.com/mobilecoinfoundation/mobilecoin/actions/runs/4873525064
This keeps the ledger/watcher dbs fresh for #3348
=> Add GHA job to save ledger/watcher DB files to azure blob storage

fog/ledger/server/src/router_admin_service.rs, fog/ledger/server/src/router_handlers.rs, fog/ledger/server/src/router_server.rs, fog/view/server/src/bin/router.rs, fog/view/server/src/router_admin_service.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/shard_responses_processor.rs, fog/view/server/test-utils/src/lib.rs
We are seeing errors in the Fog Ledger to Key Image Store connection which relate to keepalive pings. We believe this is because the load balancers acting as "shards" cannot handle gRPC keepalive messages the way they would need to. Since we control both sides of the connection, we can just disable keepalives for these internal messages which should hopefully fix the issues we're having.
=> Disable keepalives for Ledger to Store communications in Fog

Cargo.lock, fog/view/load-test/Cargo.toml, fog/view/load-test/src/main.rs
Here's example output against testnet (at version 4.1) right now:
I tried running it wtih several settings for the number of threads, and number of search keys per request.
```
chris@0c3432ad3654:/tmp/mobilenode$ ./target/docker/release/fog-view-load-test --view-uri fog-view://fog.test.mobilecoin.com
{ requests per second: 0.9999198644222255, errors per second: 0, avg latency (seconds) 0.131 }
{ requests per second: 7.997252791718241, errors per second: 0, avg latency (seconds) 0.134 }
{ requests per second: 3.999508924296239, errors per second: 0, avg latency (seconds) 0.23 }
{ requests per second: 2.998778999150032, errors per second: 0, avg latency (seconds) 0.133 }
{ requests per second: 6.999309133192008, errors per second: 0, avg latency (seconds) 0.244 }
{ requests per second: …
```
=> update fog-view load test to report more useful metrics and actually work

consensus/enclave/measurement/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ledger/enclave/measurement/build.rs, fog/view/enclave/measurement/build.rs
Bumping the enclave security versions (ISVSVN) for the 5.0 release
=> Bump enclave security version numbers for release

mobilecoind-json/src/data_types.rs
We have an automated job to upload synchronized mobilecoind ledger/watcher databases to an Azure Blob Store. Right now we can only track the ledger db status.  This enhances mobilecoind-json to include signature information so we can track the watcher db status.
- This is a cherry-pick of  work eranrund's work to the release/v5.0 branch.
=> feat: add block signatures to mobilecoind-json output.

.github/workflows/refresh-ledger-bootstrap.yaml
We have a :chicken: :egg: issue with this job.  We need features in the 5.0.2 release for this job, but it looks for the "latest" release.  
We're going to disable this scheduled job for now and make it a manual run until we get 5.x released and running. 
Re-enable this daily job with better logic for determining when the watcher db is up to date.
=> disable ledger sync cronjob until after 5.0.2 release

.github/workflows/refresh-ledger-bootstrap.yaml, .internal-ci/util/wait-for-mobilecoind.sh
This PR adds logic to the ledger refresh job to wait for the mobilecoind watcher process to finish syncing.
=> fix: add logic to wait for signatures (watcher db) to finish syncing

.internal-ci/helm/fog-services/templates/fog-ledger-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-ledger-http-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-report-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-report-http-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-view-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-view-http-ingress.yaml, .internal-ci/helm/fog-services/values.yaml, CHANGELOG.md
Since view/ledger deployments take a long time to load, add `ingress.enabled=(true|false)` option to the chart so we can launch a set of services and allow them to load without serving traffic to them.
=> feat: (helm) add ingress switch to fog-services for blue/green style deployments.

Cargo.lock, blockchain/types/src/block_id.rs, light-client/verifier/Cargo.toml, light-client/verifier/src/trusted_validator_set.rs, light-client/verifier/src/verifier.rs
This should allow constructing the `LightVerifierClient` from a JSON blob. I imagine the verifier configuration would be a JSON file that is loaded by the Axelar node and relayer, and this should make it possible.
=> Add serde traits to light client

Cargo.lock, Cargo.toml, consensus/scp/types/src/quorum_set.rs, light-client/cli/Cargo.toml, light-client/cli/src/bin/main.rs, light-client/verifier/Cargo.toml, light-client/verifier/src/config.rs, light-client/verifier/src/lib.rs
It's very likely we're going to standardize a light client verifier configuration file to be used by whoever needs the light client verifier. This file is likely going to be JSON, and ideally it should be human readable and easy to edit/modify.
consensus-service, in its `network.toml` configuration file, represents the message signing keys as DER bytes that are then base64 encoded, e.g.:
```
...
"broadcast_peers": [
"mcp://peer1.alpha.development.mobilecoin.com:443/?consensus-msg-key=MCowBQYDK2VwAyEARGQCx0PP9ZDIDFwSq6PPtKSIi2M4pTGdjkPgzKo7LKs=",
"mcp://peer2.alpha.development.mobilecoin.com:443/?consensus-msg-key=MCowBQYDK2VwAyEA8QeMmzauY4bYixH3WG-pd43xaOUvbqOtPcS4vzUVLtI="
],
...
```
This is also the format we use in https://mobilecoin.org/trusted-nodes/
I figured it would be ideal if …
=> add a light client cli utility and make some configuration more human-friendly

Cargo.lock, attest/verifier/config/Cargo.toml, attest/verifier/config/README.md, attest/verifier/config/src/lib.rs
~The underlying implementation of
`mc-attest-verifier-config::TrustedMeasurementSet` has been changed to
no longer support a dedicated config advisory entry.~ The config advisories have been kept. After further investigation it feels like an unnecessary breaking change to remove them.
The creation of a verifier from the `TrustedMeasurementSet` has 
been removed.
`mc-attest-verifier-config::StatusVerifierConfig` has been renamed to
`mc-attest-verifier-config::TrustedMeasurement`
Preparation of a common type to use for trusted measurements. In order for clients to support EPID and DCAP attestation they need to lose knowledge of the verifier implementation and instead pass the trusted measurement values to functionality that can determine how to attest the enclave based on the format of the …
=> Create common measurement types for attestation

blockchain/test-utils/src/lib.rs, fog/load_testing/src/bin/ingest.rs
These are some fixes to the fog ingest load testing binary which I made in the course of trying to use it to collect stats on how quickly fog-ingest can load TxOs.
This has not been used in a few years to my knowledge, but perhaps it could become part of regular testing or the technical committee report or something.
=> Fog ingest load test fixups

Cargo.lock, ledger/sync/Cargo.toml, light-client/cli/Cargo.toml, light-client/cli/src/bin/main.rs, light-client/verifier/src/error.rs, light-client/verifier/src/verifier.rs
Small iteration on the light-client-cli tool to retrieve stored blocks from S3 and store them inside a protobuf, while also verifying fetched blocks.
This lets me take the protobuf and use it for testing in my go bindings endeavor.
=> light-client-cli: add command to fetch archive blocks and verify them

Cargo.lock, blockchain/types/src/block_id.rs, light-client/cli/Cargo.toml, light-client/cli/src/bin/main.rs, light-client/verifier/Cargo.toml, light-client/verifier/src/config.rs
This changes the light client config JSON to use hex notation for block ids instead of a byte array. It also switches to using a parallel iterator when fetching blocks using the CLI tool, making it faster to run.
=> small improvements to light client

.dockerignore, .internal-ci/helm/watcher/templates/watcher-backup-scripts.yaml, .internal-ci/helm/watcher/templates/watcher-backup-volume.yaml, .internal-ci/helm/watcher/templates/watcher-deployment.yaml
- Update watcher backup process to only fire off once per day.
- Backup sidecar to use infra image so we have aws and mdb tools available.
- Fix backup script to use mdb tools to gracefully copy lmdb files.
- remove /target from .dockerignore (can't build docker containers/find binaries if we're just ignoring the default build dir)
AVR Watcher backup storage is a large infra expense.  This will continue to grow while we work on integrating AVRs into the chain.  In the mean time, we discussed and we're going to scale back the granularity and duplication of data. Complete backups will still continue to be available, we're just moving the timing from hourly to daily.
Note: since we're not changing binaries, I don't believe another 5.0.x release is necessary.  We will out-of-band build and …
=> fix (chart): watcher backups

Cargo.lock, light-client/cli/Cargo.toml, light-client/cli/src/bin/main.rs
This PR implements two changes in the light client CLI utility that makes it more friendly when used in the context of the cosmwasm work I am doing outside of this repo.
The changes are:
1) We can now pass known trusted block ids to `GenerateConfig`. This is useful since I want to trust some old knopwn block(s) that contain burn transactions - I can easily find them on https://auditor.mobilecoin.foundation/ and then go to the block explorer to get their ids.
2) Allow specifying the file format outputted by `FetchBlocks`. Previously it was outputting a protobuf-encoded `ArchiveBlocks`. Unfortunately we do not currently have a `prost` version of this, so using it in the cosmwasm realm is impossible without adding that (and all the associated conversions to go between that and …
=> Minor improvements to light-client-cli

attest/enclave-api/src/lib.rs
The `NewEReportResponse` doesn't appear to have ever been used as such
it is being removed.
=> Remove unused `NewEReportResponse`

.github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/helm/fog-services/templates/fog-ledger-fogshardrangegenerator.yaml, .internal-ci/helm/fog-services/templates/fog-view-fogshardrangegenerator.yaml, .internal-ci/helm/fog-services/values.yaml, fog/test-client/src/bin/main.rs, fog/test-client/src/config.rs, fog/test-client/src/test_client.rs, util/parse/src/lib.rs
Since we found out that we can't scale fog-stores by adding more replicas (routers don't load-balance), This redesigns the fog-router/stores into "stacks". Each router has a dedicated set of stores with 1 replica. We run multiple stacks to provide availability and more capacity.
Also included is a change to fog-test-client to make the polling interval configurable.  The previous default of 50ms was a bit aggressive, considering we were measuring the result in 1s buckets.
=> fix (helm): Fog routers deployed in stacks.

fog/ledger/server/src/router_handlers.rs, fog/ledger/server/src/sharding_strategy.rs, fog/sample-paykit/src/cached_tx_data/mod.rs, fog/view/server/src/fog_view_service.rs, fog/view/server/src/router_request_handler.rs, fog/view/server/src/shard_responses_processor.rs, fog/view/server/src/sharding_strategy.rs
View stores assumed a 50% overlap on shards and required half the shard total range to be loaded before returning data to routers. Having a full 50% overlap is resource heavy. This change will makes sure at least 1 block is loaded but will allow for smaller or no overlap configurations. 
- Add some debug logging for view router/store behavior troubleshooting.
- Change logic for returning NOT_READY or SUCCESS to router.
- Revisit logic for when to start serving responses to router.
- This NOT_READY/SERVING behavior should set the gRPC Health Check endpoint, which will enable/disable routing to stores on the k8s/system level.
=> fix (view-router): shardng strategy should not assume 50% overlap

Cargo.lock, attest/net/src/sim.rs, attest/verifier/Cargo.toml, attest/verifier/build.rs, attest/verifier/src/ias.rs, attest/verifier/src/lib.rs, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock
Previously the sim signing certificates used RSA keys. Now they use
ECDSA keys. Changing to ECDSA allows for re-use with DCAP quote signing
which happen to use ECDSA signatures
=> Change sim signing certs to use ECDSA

.cargo/config, tools/lint.sh, util/build/enclave/src/lib.rs
The "-D warnings" is only enforced during clippy or lint runs. If one
pushes to CI or runs `tools/lint.sh` the warnings will show up as
errors.
=> Remove "-D warnings" for development builds

attest/verifier/build.rs, attest/verifier/data/sim/.gitignore
The logic for (re)generating sim files has been re-worked to make it
easier to add the generation of more sim files.
This is _smaller_ refactor to prepare for the need to generate more sim files.
=> Refactor logic for generating sim files in `mc-attest-verifier`

Cargo.lock, attest/untrusted/Cargo.toml, attest/untrusted/src/sim.rs, attest/verifier/build.rs
The quote signing certificates from `mc-attest-verifier` that are
created for `sgx-sim` now provide the necessar DCAP SGX OID extensions
in the leaf certificate.
=> Add OID extensions to simulated signing certificates

attest/verifier/src/dcap.rs
When an enclave is built for debug, a bit is set in the `Attributes`.
The DCAP verifier now checks for this bit being set when it shouldn't
be.
=> Add verification of Debug bit off for release enclaves

.internal-ci/docker/Dockerfile.dcap-runtime-base, .internal-ci/docker/support/sgx_default_qcnl_azure.conf
Adds a runtime base Dockerfile to be used in DCAP deployments.
=> Add DCAP runtime base Dockerfile

.internal-ci/helm/fog-ingest/templates/fog-ingest-statefulset.yaml
Bump startup probe to 300 attempts (3000 seconds) to compensate for long lmdb bootstrap download at initial container startup.
=> fix: (helm) bump fog-Ingest startup probe

.github/workflows/mobilecoin-workflow-dev-deploy.yaml, .internal-ci/docker/Dockerfile.fog-ledger, .internal-ci/docker/Dockerfile.fogingest, .internal-ci/docker/Dockerfile.mobilecoind, .internal-ci/docker/entrypoints/fog-ledger.sh, .internal-ci/docker/entrypoints/fogingest.sh, .internal-ci/docker/entrypoints/mobilecoind.sh, .internal-ci/docker/support/ledger-download.sh, .internal-ci/helm/mobilecoind/templates/mobilecoind-deployment.yaml, .internal-ci/helm/mobilecoind/values.yaml
We download the lmdb database from block storage to a temporary location so we don't end up with a corrupted database in case the start up process is interrupted.  The problem is moving the files from /tmp to the data volume was taking longer than the original curl. 
Download to the same volume/filesystem, then the `mv` is just changing pointers rather than transferring GBs of data.
Bonus:
- consolidate logic into 1 script used by the 3 containers. 
- clean up paths for external installed binaries.
=> fix: (docker) download lmdb bootstrap files to same volume as destination

fog/ledger/server/src/bin/router.rs
* Use regular `get_identity` calls to monitor health of Fog Ledger enclave
There is an issue that is likely in the enclave code that is causing the enclave to crash in rare cases. This should be fixed, but when this crash happens, the enclave never recovers. This PR adds a simple check to ensure the enclave is running and makes sure it gets restarted if it isn't. While the root cause of the issue is also important, it is very rare and difficult to re-create. The fact that there is no recovery from this is also a problem. This PR fixes the fact that there is no recovery from the enclave either crashing completely or not being in a healthy state.
Monitor network logs for this error. Figure out what the cause of this particular crash is and fix it.
=> Add health check for ledger enclave

.internal-ci/docker/entrypoints/node_hw.sh
The backup process of the `/ledger/data.mdb` file is well-intended (backup happens before running an `mc-ledger-migration`) but adds about 8 minutes to the node startup.  The ledger migration itself is very stable, and in a worst-case scenario (corruption, failure, etc), we can remove the `/ledger/data.mdb` file, restart the node, and the node will rebuild its own ledger (with its own signatures) from its own S3 bucket.
This PR removes the backup process of that file.
* Investigate if there IS a way to backup the `/ledger/data.mdb` file out-of-process and without blocking startup.
=> node_hw.sh

attest/untrusted/src/sim.rs, attest/verifier/types/src/verification.rs
The `DcapEvidence` now contains a member `report_data`, which holds
`EnclaveReportDataContents`. This allows the `DcapEvidence` to provide
the report data used by clients for things like public key identities.
=> Add `EnclaveReportDataContents` to `DcapEvidence`

Cargo.lock, attest/ake/src/event.rs, attest/ake/src/initiator.rs, attest/ake/src/lib.rs, attest/ake/src/state.rs, watcher/Cargo.toml, watcher/src/verification_reports_collector.rs
A new state `UnverifiedReport` as been added to the attest key exchange
state machine. The `UnverifiedReport` allows clients like watcher to
get the attestation report from the key exchange handshake without
requiring the report to pass verification. This is useful when the
client doesn't know or need to know the identity of the enclave.
=> Add UnverifiedReport state for attestation

enclave-boundary/src/untrusted.rs, fog/ledger/server/src/bin/router.rs
* Removed ledger enclave check
* Added check for result of enclave calls to panic on all fatal errors
Any time an enclave encounters a non-recoverable error, panic the untrusted code to force a restart.
=> Panic on Enclave Fatal Error

Cargo.lock, api/Cargo.toml, api/proto/external.proto, api/src/convert/enclave_report_data_contents.rs, api/src/convert/mod.rs, attest/verifier/src/dcap.rs, attest/verifier/types/src/verification.rs, consensus/enclave/mock/src/lib.rs, crypto/ake/enclave/src/lib.rs, fog/ledger/test_infra/src/lib.rs
The `EnclaveReportDataContents` is a member of `DcapEvidence` which will
need to be part of `BlockMetadataContents` which derives `Digestible`.
In order to support this future need a `Digestible` implementation has
been added to the `EnclaveReportDataContents`.
Also add `EnclaveReportDataContents` to the external protobufs. To
accomodate the need of it being part of the `BlockMetadataContents` in
the protobufs.
=> Add `Digestible` impl to `EnclaveReportDataContents`

tools/lint.sh
Previously clippy would run twice on the root workspace.
Now the root workspace is only linted once.
=> Update lint script to lint root workspace once

Cargo.lock, attest/api/proto/attest.proto, attest/verifier/types/Cargo.toml, attest/verifier/types/build.rs, attest/verifier/types/src/convert.rs, attest/verifier/types/src/convert/collateral.rs, attest/verifier/types/src/convert/quote3.rs, attest/verifier/types/src/lib.rs, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock
Add prost implementations for `Quote3` and `Collateral`. The
implementations are done in this repository instead of
`mc-sgx-dcap-types` to prevent having to publish proto files from the
`mc-stx-***` crates.
The `prost::Message` implementations use `prost-build` and a `*.proto`
file, which deviates from other `prost::Message` implementations in the
repository. The reasons for this deviation are:
- Prevent changing `Quote3` and `Collateral` to use `Option<T>`
fields. `Option<T>` or defaults need to be implemented to work
directly with `::prost::Message`.
- Ensure that the `::prost::Message` implementations use the same tags
as the gRPCio protobuf implementations.
=> Add prost implementations for `Quote3` and `Collateral`

attest/verifier/types/src/convert/enclave_report_data_contents.rs, attest/verifier/types/src/verification.rs
Previously the `Digestible` implementation was on the
`EnclaveReportDataContents`. Now the `Digestible` implementation is on
the `prost::EnclaveReportDataContents`. This is because the prost
version is what will be needed in the `BlockMetadataContents` which
requires `Digestible` on all decedents.
=> Move `Digestible` implementation to `prost::EnclaveReportDataContents`

Cargo.lock, attest/api/src/convert/collateral.rs, attest/api/src/convert/dcap_evidence.rs, attest/untrusted/Cargo.toml, attest/untrusted/src/hw.rs, attest/untrusted/src/sim.rs, attest/verifier/types/src/convert/collateral.rs, attest/verifier/types/src/convert/dcap_evidence.rs
The previous implementation of `DcapQuotingEnclave::collateral()` only
supported `sgx-sim` builds. Adding in the logic for hw builds requires
that the `DcapQuotingEnclave::collateral()` be fallible since it could
be fallible on a real system.
=> Update `DcapQuotingEnclave::collateral()` to be fallible

Cargo.lock, api/proto/blockchain.proto, api/src/convert/block_metadata.rs, blockchain/test-utils/src/lib.rs, blockchain/types/Cargo.toml, blockchain/types/src/block_metadata.rs, blockchain/types/src/lib.rs, consensus/service/src/byzantine_ledger/metadata_provider.rs, consensus/service/src/byzantine_ledger/mod.rs, consensus/service/src/byzantine_ledger/worker.rs, light-client/relayer/tests/block_processing.rs, light-client/verifier/src/trusted_validator_set.rs, mobilecoind/src/service.rs, transaction/types/src/block_version.rs
Previously the `BlockchainMetadata` contained a filed
`VerificationReport`. With DCAP there is a new type of attestation
evidence `DcapEvidence`. The `BlockchainMetadata` has been updated to
take an `AttestationEvidence` which is a oneof the older
`VerificationReport` or the newer `DcapEvidence`
=> Add `AttestationEvidence` to `BlockchainMetadata`

attest/verifier/src/ias.rs, attest/verifier/src/lib.rs, sgx/report-cache/untrusted/src/lib.rs
Previously the `mc-attest-verifier::Error::Verification` type wrapped a
`VerificationReportData`. Now it wraps a `String` type. This allows for
a more generic interface to provide back the error from attempting to
verify the legacy `VerificationReportData` or the newer `DcapEvidence`.
Verification of the newer `DcapEvidence` provides a string output that
more clearly states where verification failed and as such passing back
the evidence itself isn't very beneficial.
=> Chant type of `mc-attest-verifier::Error::Verification`

api/src/convert/collateral.rs, api/src/convert/dcap_evidence.rs, api/src/convert/enclave_report_data_contents.rs, attest/untrusted/src/sim.rs, attest/verifier/src/dcap.rs, attest/verifier/types/src/convert/collateral.rs, attest/verifier/types/src/convert/dcap_evidence.rs, attest/verifier/types/src/convert/enclave_report_data_contents.rs, attest/verifier/types/src/convert/quote3.rs
Previously some of the `From` implementations for `DcapEvidence` and
its substructs converted from moved instances. This resulted in
unecessary clones by consumers of the API. Now the `From`
implementations for `DcapEvidence` and its substructs convert from
references.
=> Use references in `From` impl for `DcapEvidence`

Cargo.lock, fog/ingest/report/Cargo.toml, fog/ingest/report/src/lib.rs, fog/report/resolver/src/lib.rs
Previously the `FogResolver` created a `Verifier` and kept that around.
Now the `FogResolver` keeps a `Vec<TrustedIdentity>` and creates a
verifier as needed. This is to allow the `FogResolver` to better handle
EPID vs DCAP attestation.
=> Change `FogResolver` to keep `Vec<TrustedIdentity>`

Cargo.lock, attest/untrusted/Cargo.toml, attest/untrusted/src/sim.rs, attest/verifier/Cargo.toml, attest/verifier/src/dcap.rs
The `VerificationMessage` allows one to pretty print the result of a
failure to verify.
=> Add `VerificationMessage` to `DcapVerifier`

api/src/convert/collateral.rs, api/src/convert/dcap_evidence.rs, api/src/convert/enclave_report_data_contents.rs, api/src/convert/mod.rs, api/src/convert/quote3.rs
Previously some conversions in `mc-api` that were from protobuf types to
prost types were implemented as `TryFrom`. Now these conversions are
implemented as `From`. This allows for a more ergonomic API preventing
callers from having to check for errors that really shouldn't happen in
this conversion step.
=> `From` instead of `TryFrom` for proto to prost

attest/verifier/src/dcap.rs
* Make time optional for dcap verification
Time is not available in no-std environments. If time is not available, time validation for certs cannot occur and will be skipped.
=> Make time optional for dcap verification

crypto/ake/enclave/Cargo.toml, crypto/hashes/Cargo.toml, fog/ingest/server/test-utils/Cargo.toml, fog/ledger/test_infra/Cargo.toml, sgx/compat/Cargo.toml, sgx/sync/Cargo.toml, tools/lint.sh, util/serial/Cargo.toml
By default `cargo sort` will *always* re-write every `Cargo.toml` file
it processes. This causes the build system to see the files changed and
results in re-compiling unnecessarily. Now `cargo sort` will only update
a file if it deviates from the desired sorting order.
On my machine this took a no-op lint from 45 seconds down to 25 seconds
=> Limit `cargo sort` to only modify incorrect files.

.github/workflows/mobilecoin-dispatch-dev-testnet-fog.yaml
Add a valid "placeholder" job in the default (master) branch so we can develop a process for deploying a fog environment that points to TestNet consensus in a feature branch.
=> feat: add placeholder job for deploying a testnet fog on development cluster

.github/workflows/refresh-ledger-bootstrap.yaml
Job is currently failing due to 5.0.2 being pulled at some point.  Bump the mobilecoind release version to 5.0.8.
=> fix: ledger bootstrap job - bump release version to 5.0.8

Cargo.lock, attest/core/src/lib.rs, attest/verifier/types/Cargo.toml, attest/verifier/types/src/lib.rs, attest/verifier/types/src/verification.rs
Previously `EvidenceMessage` was a proxy to decode the `EvidenceKind`
enum. This resulted in clients needing to first attempt to decode as
`EvidenceMessage` and then fall back to `VerificationReport`. Now the
logic of decoding `VerificationReport` versus `DcapEvidence` is wrapped
in the `Message` implementation of `EvidenceKind`.
=> Implement `Message` for  `EvidenceKind`

attest/ake/src/event.rs, attest/ake/src/initiator.rs, attest/ake/src/lib.rs, watcher/src/attestation_evidence_collector.rs, watcher/src/bin/db-dump.rs, watcher/src/bin/main.rs, watcher/src/lib.rs, watcher/src/watcher_db.rs
Previously `mc-watcher` used "verification report" or similar to refer
to the `VerificationReport`. With the anticipated use of `DcapEvidence`
`mc-watcher` has been updated to use a more generic term of "attestation
evidence" where appropriate.
I was making changes to watcher to support handling `DcapEvidence` and it seemed that many places where `verification_report` (or similar) was used would be ambiguous to future maintainers. This renaming may be a bit aggressive or perhaps we should completely avoid it as this PR is larger than ideal.
=> Use general term "attestation evidence" in watcher

Cargo.lock, watcher/Cargo.toml, watcher/src/attestation_evidence_collector.rs, watcher/src/bin/db-dump.rs, watcher/src/watcher_db.rs
Previously watcher would only work with `VerificationReport`s. Now
watcher will work with `EvidenceKind` allowing it to work with both the
legacy `VerificationReport` and the newer `DcapEvidence`.
=> Update watcher to handle `EvidenceKind`

.github/workflows/mobilecoin-dispatch-dev-mainnet-fog.yaml
Working on a manual (dispatch) action to deploy a fog instance that uses mainnet consensus. This is a placeholder action in the default branch so we can develop in a feature branch.
=> feat: add placeholder for manual mainnet on dev cluster deploy

account-keys/src/account_keys.rs, common/src/node_id.rs, connection/src/sync.rs, connection/src/thick.rs, connection/test-utils/src/blockchain.rs, connection/test-utils/src/user_tx.rs, crypto/keys/src/ristretto.rs, fog/enclave_connection/src/lib.rs, fog/ingest/server/src/connection.rs, peers/src/connection.rs, peers/test-utils/src/lib.rs, util/ffi/src/ffi_ref_ptr.rs, util/repr-bytes/src/lib.rs
For types that implement `Ord` the `PartialOrd` now redirects to the
`Ord` implementations to ensure they are consistent.
This addresses a clippy lint coming in a newer rust version,
https://rust-lang.github.io/rust-clippy/master/index.html#/non_canonical_partial_ord_impl
Also fixes some non canonical `Clone` implementation from https://rust-lang.github.io/rust-clippy/master/index.html#/non_canonical_clone_impl
=> Use canonical `PartialOrd`

attest/verifier/src/ias.rs, attest/verifier/src/status.rs, consensus/enclave/api/src/lib.rs, crypto/box/src/versioned.rs, crypto/keys/src/ed25519.rs, crypto/message-cipher/src/aes_impl.rs, crypto/message-cipher/src/traits.rs, fog/ingest/enclave/src/lib.rs, fog/kex_rng/src/versioned/buffered.rs, fog/ledger/enclave/src/lib.rs, fog/overseer/server/src/worker.rs, fog/view/enclave/src/ecall.rs, ledger/db/src/mint_config_store.rs, mobilecoind/src/db_crypto.rs, test-vectors/memos/build.rs, util/repr-bytes/src/lib.rs, util/serial/src/lib.rs
Newer clippy versions will warn if the test module is not the last one
in the file,
https://rust-lang.github.io/rust-clippy/master/index.html#/items_after_test_module
Also update some comment formatting for newer `cargo fmt` behavior.
=> Place test modules at end of files

consensus/enclave/impl/src/lib.rs, consensus/enclave/tests/enclave_api_tests.rs, consensus/service/src/byzantine_ledger/mod.rs, consensus/service/src/byzantine_ledger/worker.rs, fog/ingest/server/src/controller.rs, fog/ledger/server/tests/router_connection.rs, fog/ledger/server/tests/router_integration.rs, fog/test-client/src/test_client.rs, ledger/db/src/test_utils/mod.rs, mobilecoind-json/src/data_types.rs, mobilecoind/src/conversions.rs, transaction/core/tests/util/mod.rs, transaction/core/tests/validation.rs
The removal of mutable references that don't need to be mutable is to
address the coming clippy lint of
https://rust-lang.github.io/rust-clippy/master/index.html#/needless_pass_by_ref_mut
=> Remove use of `&mut` that didn't mutate

consensus/scp/src/slot.rs, consensus/service/src/byzantine_ledger/pending_values.rs, consensus/service/src/byzantine_ledger/worker.rs, fog/distribution/src/main.rs, fog/ledger/server/tests/router_connection.rs, fog/ledger/test_infra/src/lib.rs, fog/sample-paykit/src/cached_tx_data/mod.rs, fog/test_infra/src/mock_users.rs, ledger/sync/src/ledger_sync/ledger_sync_service.rs, mobilecoind/src/payments.rs, sgx/sync/src/mutex.rs, transaction/builder/src/input_credentials.rs
Some other minor clippy changes
- use slices for temporary locals instead of vec![].
- use `let _` instead of drop() on copy types.
- Be explicit when creating a slice of type Range
=> Remove uneeded use of `into_iter()`

consensus/enclave/trusted/Cargo.toml, fog/ingest/enclave/trusted/Cargo.toml, fog/ledger/enclave/trusted/Cargo.toml, fog/view/enclave/trusted/Cargo.toml, sgx/alloc/Cargo.toml, sgx/build/Cargo.toml, sgx/compat-edl/Cargo.toml, sgx/compat/Cargo.toml, sgx/css-dump/Cargo.toml, sgx/css/Cargo.toml, sgx/debug-edl/Cargo.toml, sgx/debug/Cargo.toml, sgx/enclave-id/Cargo.toml, sgx/panic-edl/Cargo.toml, sgx/panic/Cargo.toml, sgx/report-cache/api/Cargo.toml, sgx/report-cache/untrusted/Cargo.toml, sgx/service/Cargo.toml, sgx/slog-edl/Cargo.toml, sgx/slog/Cargo.toml, sgx/sync/Cargo.toml, sgx/types/Cargo.toml, sgx/urts/Cargo.toml
Previously the rust version was bumped in the root workspace, but it was
missed for the enclave crates.
=> Update the rust version in the enclave crates

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .internal-ci/helm/fog-report/.helmignore, .internal-ci/helm/fog-report/Chart.yaml, .internal-ci/helm/fog-report/README.md, .internal-ci/helm/fog-report/templates/_helpers.tpl, .internal-ci/helm/fog-report/templates/fog-report-configmap.yaml, .internal-ci/helm/fog-report/templates/fog-report-deployment.yaml, .internal-ci/helm/fog-report/templates/fog-report-grpc-ingress.yaml, .internal-ci/helm/fog-report/templates/fog-report-http-ingress.yaml, .internal-ci/helm/fog-report/templates/fog-report-service.yaml, .internal-ci/helm/fog-report/templates/fog-report-servicmonitor.yaml, .internal-ci/helm/fog-report/templates/fog-report-tls-certificate.yaml, .internal-ci/helm/fog-report/templates/supervisord-admin-configmap.yaml, .internal-ci/helm/fog-report/templates/supervisord-daemon-configmap.yaml, .internal-ci/helm/fog-report/templates/supervisord-fog-report-configmap.yaml, .internal-ci/helm/fog-report/values.yaml, .internal-ci/helm/fog-services-config/templates/fog-report-configmap.yaml, .internal-ci/helm/fog-services-config/values.yaml, .internal-ci/helm/fog-services/templates/fog-report-grpc-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-report-http-ingress.yaml, .internal-ci/helm/fog-services/templates/fog-report-service.yaml, .internal-ci/helm/fog-services/templates/fog-report-servicmonitor.yaml, .internal-ci/helm/fog-services/values.yaml, .internal-ci/util/generate_origin_data.sh
- Break out fog-report chart from fog-services monolith.
- Update GHA and integration tests to support multiple fog-report instances.
We need to be able to build fog instances that have multiple copies of fog-report, fog-view-router and fog-ledger-router with appropriate ingress and secret alignment.
=> Fog-Report - Helm chart improvements for consolidating fog instances.

Cargo.lock, Cargo.toml
The android bindings try to stay n'sync with the MobileCoin repo, but in this case the MobileCoin repo was back on mbedtls. mbedtls was updated to hold back CMake to ensure crosscompiling kept working. We burnt about 2 days debugging building android bindings against the MobileCoin repo, I fixed the issue in May, but forgot to come back and update the MobileCoin repo for future me :(.
=> Update patched mbedtls version

mobilecoind/src/service.rs
When checking that a b58 address is valid, if the code cannot be parsed, that should be considered an invalid argument error rather than an internal error.
Improving this to return the right error code helps users of this API handle errors correctly themselves, since internal errors are often considered retriable but an invalid argument is not.
=> Fix an error code returned by mobilecoind

mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/database.rs, mobilecoind/src/service.rs, mobilecoind/src/utxo_store.rs
Currently, there is no easy way to get all of the unspent tx outs associated to a given monitor id. This is a very normal thing to want to do if you are managing a wallet with many subaddresses, because you have no way to subscribe to updates when payments come in, so you would like to be able to poll for them efficiently.
The GetUnspentTxOutList API call exists, but it only allows you to search for UTXOs one subaddress and token id at a time.
You can use the GetProcessedBlock API call, which allows you to be more efficient because it's not tied to a single subaddress or token id, but it still creates a lot of extra work on the caller side, because now you have to think about blocks and keep track of a cursor as you advance through the chain.
There are other things about this API that are …
=> Add a GetAllUnspentTxOuts API call to mobilecoind

sgx/urts/src/panic.rs
The enclave panic message is passed to a logger that doesn't work with newlines. In order to keep the contents of the panic message from the enclave a space is used to separate the "Enclave panic:" prefix and the actual message.
=> Remove newlines from enclave panic message

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-bootstrap.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .internal-ci/test/check-env-status.sh
- bump the bootstrap tags.
- allow restore of "alpha" (now v5.1.1-dev) history
- simplify the bootstrap options.  No need to support versions older than 5.0
=> update gha workflow to restore alpha/v5.1.1-dev

consensus/scp/tests/mock_network/mod.rs
For the single node mesh and cycle SCP network tests if the main thread doesn't sleep then it will be constantly fighting the node for the lock on shared data. Making the main thread wait 1 millisecond between polls allows the tests to finish in under 5 seconds, where before they would timeout at 8 minutes.
=> Add sleep to main thread of mock network

.internal-ci/helm/fog-ledger/values.yaml, fog/ledger/server/src/bin/router.rs, fog/ledger/server/src/config.rs, fog/ledger/server/tests/router_connection.rs, fog/ledger/server/tests/router_integration.rs
Previously the fog ledger router allocated 30MB of OMAP. This was a hold over from when fog ledger router was fog ledger. Only the key image stores need OMAP and fog ledger router does not need OMAP.
=> Remove fog ledger router omap

crypto/ake/enclave/src/lib.rs
Previously the enclaves would reserve memory for 10_000 backend
connections. An enclave would never need that many connections as it
represents each shard that a router would connect to. This value has
been reduced to 100, which reduces enclave static startup memory from
~32MB to ~320KB.
=> Reduce the static startup memory of enclaves

fog/view/server/src/bin/router.rs, fog/view/server/src/config.rs, fog/view/server/test-utils/src/lib.rs
Previously the fog view router allocated 30MB of OMAP. This was a hold over from when fog view router was fog view. Only the view stores need OMAP and fog view router does not need OMAP.
=> Remove fog view router omap

fog/test-client/src/test_client.rs
This adds opentelemetry spans for the tx building and submission parts, resulting in a trace that looks like this:
=> add trace spans for tx building and sending

fog/report/types/src/lib.rs, fog/sql_recovery_db/Cargo.toml, fog/sql_recovery_db/src/lib.rs
Previously `AttestationEvidenceOneOf` was used in sql recovery db. This
prevented decoding the legacy EPID based fog reports. Now `EvidenceKind`
is used which allows the decoding of legacy EPID fog reports.
=> Use `EvidenceKind` in sql recovery db

fog/enclave_connection/src/error.rs, fog/ledger/connection/src/block.rs, fog/ledger/connection/src/key_image.rs, fog/ledger/connection/src/merkle_proof.rs, fog/ledger/connection/src/router_client.rs, fog/ledger/connection/src/untrusted.rs, fog/sample-paykit/src/cached_tx_data/mod.rs, fog/view/protocol/src/polling.rs
While trying to figure out why the testnet fog-test-client is taking much more time than my local machine to do a balance check on the same account I ran into an issue where I was seeing `message size too large` errors returned from fog-view. 
I've also been looking into why old accounts with many TxOuts take longer to do a balance check even after the initial slow-but-expected sync.
This let me to dig deeper, and this PR is a collection of improvements I made along the way:
1. Make the GRPC `RESOURCE_EXHAUSTED` error, which is the error you get when the server is trying to send you too large of a reply, non-retriable. This is due to the assumption that retrying the same request will result in the same reply.
2. Add a bunch of `trace_time!` logs to client GRPC calls so that I can have …
=> Various improvements to fog-test-client

sgx/urts/src/panic.rs
This reverts commit 2392fcbadcd13c0c23d381cc06400e456371872f. The enclaves aren't meant to change for the 5.2 release, reverting this change helps to keep the compiled version of the enclaves the same as those from the 5.1.0 release.
=> Revert enclave change

.internal-ci/helm/fog-ledger/values.yaml
Moving to a remote mobilecoind configuration reduces the memory needs on each router/store instance. We may be able to schedule more pods per node with a reduced memory footprint.
=> reduce ledger router/store k8s memory requests

fog/ingest/server/src/bin/main.rs, fog/ingest/server/src/config.rs, fog/ingest/server/src/server.rs, fog/ingest/server/src/worker.rs, fog/ingest/server/test-utils/src/lib.rs, fog/ledger/server/src/config.rs, fog/ledger/server/src/db_fetcher.rs, fog/ledger/server/src/key_image_store_server.rs, fog/ledger/server/tests/router_connection.rs, fog/ledger/server/tests/router_integration.rs, fog/ledger/server/tests/store.rs
When deploying the centralized mobilecoind configuration to testnet it appears we are overwhelming the single mobilecoind instance there by polling it from ~18 different services at a 10ms interval. This backs off the default polling duration to 250ms and also makes it configurable.
=> make fog ingest/ledger poll time configurable

fog/ledger/server/src/db_fetcher.rs
Previously each the fog ledger shard would fetch *all* blocks even though they only needed a subset of blocks. Now only the subset of blocks the shard is responsible is fetched.
=> Optimize ledger shard block fetching

fog/ledger/server/src/db_fetcher.rs
In a7b70f620bc4c8959629978247002d100af85b45 the ledger stores were optimized to fetch only the blocks they needed. This caused an error during collation where the minimum of the known blocks are past back to clients. This resulted in only being able to provide the blocks from the lowest shard to the clients. Now shards will continue to poll for the latest block allowing for all shards to be accounted for when collating the response.
=> Fix ledger stores not updating latest block info

.github/workflows/mobilecoin-dev-cd.yaml, .internal-ci/docker/Dockerfile.bootstrap-tools, .internal-ci/helm/fog-ingest/values.yaml, fog/ingest/server/src/config.rs
- Make fog-ingest pub key expiry default to 10 
- (secondary) add fog-view-load-test to the toolbox container for future testing.
=> defaults for pubkey expire

.internal-ci/helm/fog-ledger/templates/fog-ledger-router-servicemonitor.yaml, .internal-ci/helm/fog-ledger/templates/fog-ledger-store-servicemonitor.yaml, .internal-ci/helm/fog-view/templates/fog-view-router-servicemonitor.yaml, .internal-ci/helm/fog-view/templates/fog-view-store-servicemonitor.yaml
Add stack label to Prometheus metrics so we can use it average metrics for things like block_height across stacks to find the overall state of the system.
=> update servicemonitor to add stack labels

mobilecoind/src/service.rs
Previously, mobilecoind returned a GRPC INVALID_ARGUMENT error when certain calls were made to the ledger database and the data requested wasn't found. 
NOT_FOUND is a more correct error code in such cases, and is required for correct behavior of the new remote-mobilecoind fog `BlockProvider` (see https://github.com/mobilecoinfoundation/mobilecoin/blob/feature/bugfix-ledger-notfound-err-code/fog/block_provider/src/error.rs#L38-L39 and https://github.com/mobilecoinfoundation/mobilecoin/blob/feature/bugfix-ledger-notfound-err-code/fog/ledger/server/src/merkle_proof_service.rs#L156)
To verify this results in the expected behavior I hacked together a client that calls `get_outputs` on the fog merkleproof service. Prior to this change, I got this result:
```
Rpc(RpcFailure(RpcStatus { code: …
```
=> bugfix: mobilecoind should return a grpc NOT_FOUND error code when ledger data is not found

Cargo.lock, api/Cargo.toml, attest/ake/Cargo.toml, attest/api/Cargo.toml, attest/core/Cargo.toml, attest/untrusted/Cargo.toml, attest/verifier/Cargo.toml, attest/verifier/config/Cargo.toml, attest/verifier/types/Cargo.toml, consensus/enclave/trusted/Cargo.lock, fog/ingest/enclave/trusted/Cargo.lock, fog/ledger/enclave/trusted/Cargo.lock, fog/view/enclave/trusted/Cargo.lock, sgx/css/Cargo.toml, sgx/report-cache/api/Cargo.toml, sgx/report-cache/untrusted/Cargo.toml, sgx/types/Cargo.toml
Previously the enclave builds would vary between build runs. This was
due to `HashSet` being used during a code generation step. Now the
enclave builds are reproducible.
=> Fix reproducible enclave builds

consensus/enclave/measurement/build.rs, fog/ingest/enclave/measurement/build.rs, fog/ledger/enclave/measurement/build.rs, fog/view/enclave/measurement/build.rs, util/build/enclave/src/lib.rs
Moving the enclaves into the same build directory reduces compilation
times on this developer's machine from 7m45s to 6m31s. Which is ~15%
improvement. It also reduces the build directory from 76GiB to 71GiB.
=> Move the enclaves into the same build directory

Cargo.lock
It looks like when the update to `syn` and `mockall` were integrated
they happened to overlap slightly and it wasn't noticed until run in
`main`.
=> Fix cargo lock versions

.github/workflows/ci.yml, tools/fog-local-network/requirements.txt
Previously the CI runs would start the postgres service inside of the container doing tests. This would result in intermittent failures when postgres wasn't able to start up. Now a service container is used for postgres as described in https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers.
=> Use postgres service in gh actions

.github/workflows/ci.yml
The new CI runners can handle linking with all available threads, there is no reason to limit them to 4.
This takes the times for the build only jobs from 18min to 9min
=> Remove 4 core restriction on CI builds

attest/verifier/build.rs, attest/verifier/src/lib.rs
Previously the sim enclave signing certificates were in the source
directory and used a random key. This caused issues with incremental
builds and at timing issues where the enclaves were in the process of
creating a certificate while the untrusted code was too. This resulted
in attestation errors due to signature mismatches, which would force
someone to rebuild again. Now the sim signing certificates are in the
build directory and use a common default seed.
=> Move sim certificates to build directory

mobilecoind/src/payments.rs
without this, we hit an error in "select_utxos_for_optimization"
=> mobilecoind: fix optimization tx's when using nonzero token ids

.github/actionlint.yaml, .github/workflows/android-bindings-dispatch.yml, .github/workflows/ci.yml, .github/workflows/dependent-repos.yml, .github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-dev-mainnet-fog.yaml, .github/workflows/mobilecoin-dispatch-dev-testnet-fog.yaml, .github/workflows/mobilecoin-dispatch-mainnet-build.yaml, .github/workflows/mobilecoin-dispatch-testnet-build.yaml, .github/workflows/mobilecoin-workflow-dev-bootstrap.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-reset.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml, .github/workflows/refresh-ledger-bootstrap.yaml, .internal-ci/util/generate_dev_values-v5.1.sh
Update all actions to use gha-runner-scale-set labels.  GH devs have decided that 1 long label is better that a list of capabilities and selectors :neutral_face: 
Additionally fix actionlint issue and remove unnecessary IAS configuration.
=> use gha-runner-scale-sets

.github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-dev-update-consensus.yaml, .internal-ci/README.md, .internal-ci/helm/consensus-node-config/values.yaml, .internal-ci/helm/fog-ledger/values.yaml, .internal-ci/helm/fog-view/values.yaml
Setting good defaults for the release. 
- Block version set to `4`
- Set the scale up `exceedBlockHeightBy` to `0` to work around ledger store reporting 0 when no blocks in the latest store.
=> Set block_version to 4 and exceed by to 0 in charts.

crypto/keys/src/ristretto.rs, mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/conversions.rs, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, transaction/builder/src/signed_contingent_input_builder.rs, transaction/builder/src/test_utils.rs, transaction/builder/src/transaction_builder.rs
This can be used to create a relatively easy to use idempotence strategy for mobilecoind payments.
From a vendor or an exchange's point of view, it's really nice if you can have an "idempotence key" in an API that sends money somewhere. Here idempotence means, if I make this request, and retry in case of connection failures, there's no way that it can lead to a payment being sent twice.
For example, in mobilecoind, there is a `SendPayment` API which is meant to be the easiest way to send money to a public address. However, there is no idempotence key on this API, and so if I make the request, then due to connectivity issues, the response is not delivered, but the request was handled successfully, a retry will cause a new payment to be sent, with new UTXOs selected. So in realistic …
=> Add support for setting tx private key in tx builder, expose in mobilecoind api

transaction/signer/src/types.rs
The external transaction signer data types includes a 32 byte `AccountId` which is typically conveyed in JSON and other external code as a 64 digit hex string.  It is useful to be able to create an AccountId from such a representation.
* this PR adds a `From<String>` implementation for `AccountId` allowing an object to be instantiated from a 64 character hex string.
=> impl TryFrom<String> trait for AccountId

.github/actionlint.yaml, .github/workflows/android-bindings-dispatch.yml, .github/workflows/ci.yml, .github/workflows/dependent-repos.yml, .github/workflows/mobilecoin-dev-cd.yaml, .github/workflows/mobilecoin-dev-delete.yaml, .github/workflows/mobilecoin-dispatch-dev-deploy.yaml, .github/workflows/mobilecoin-dispatch-mainnet-build.yaml, .github/workflows/mobilecoin-dispatch-testnet-build.yaml, .github/workflows/mobilecoin-workflow-dev-bootstrap.yaml, .github/workflows/mobilecoin-workflow-dev-deploy.yaml, .github/workflows/mobilecoin-workflow-dev-reset.yaml, .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, .github/workflows/mobilecoin-workflow-dev-test.yaml, .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml
Update dev deploy workflow to restore v5 alpha network at 5946 block height for testing.  Adding to release 5.2 branch just in case we need to make any patches before 6.0 is released in main. 
Will PR similar changes to release/v6.0. Not going directly to 6.0 with this change since current v6.0 charts and workflows won't be compatible with v5 artifacts and testing process.
=> Updated dev deploy workflow for release/v5.2

mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/lib.rs, mobilecoind/src/payments.rs, mobilecoind/src/service.rs, mobilecoind/src/transaction_memo.rs
Right now `mobilecoind` does not include memos in transactions it generates (except burn redemption transactions). `full-service`, Sentz, and some other clients already include these memos and it would be better of `mobilecoind` includes them as well.
I opted to build this in a way that defaults to including the RTH memos unless the user explicitly does not want them. This is in line with `full-service` and other clients behavior, and simplifies upgrading since existing `mobilecoind` users will not need to change anything to start including the memos.
=> mobilecoind: include RTH memos by default and allow customizing them if desired

Cargo.lock, fog/ledger/enclave/api/src/lib.rs, fog/ledger/enclave/impl/Cargo.toml, fog/ledger/enclave/impl/src/lib.rs, fog/ledger/enclave/trusted/Cargo.lock, fog/ledger/server/src/db_fetcher.rs, fog/ledger/server/src/key_image_service.rs, fog/ledger/server/src/lib.rs, fog/ledger/server/tests/router_integration.rs, fog/ledger/server/tests/store.rs
Previously when a fog ledger store was spun up prior to the block chain
having blocks in its block range it would return back 0 for the block
number. This resulted in the collated response having 0 for the total
number of blocks. Now stores will respond back with the range of
blocks that they have processed and the collation logic will combine the
overlapping ranges to come up with the highest available block count.
=> Fix fog ledger router returning incorrect block number

.internal-ci/helm/fog-ingest/values.yaml, .internal-ci/helm/fog-ledger/values.yaml
Two changes to the included helm charts.
- fog-ledger - set `exceedBlockHeightBy` to scale new stores before we hit the block boundary.
- fog-ingest - set annotation to make sure the cluster autoscaler doesn't reclaim VMs running fog-ingest and evict the pods (loosing keys)
=> helm - set exceed by for ledger, keep ingest from being evicted by accident

Cargo.lock
Bumping rustls from 0.21.7 to 0.21.11 to mitigate, https://rustsec.org/advisories/RUSTSEC-2024-0336
Unfortunately due to `mc-ledger-distribution` using rusoto it is still using a version of rustls that is susceptible to RUSTSEC-2024-0336
```
cargo tree -i -p rustls@0.20.7
rustls v0.20.7
├── hyper-rustls v0.23.2
│   └── rusoto_core v0.48.0
│       ├── mc-ledger-distribution v6.0.0 (/Users/nick/git/mobilecoin/ledger/distribution)
│       └── rusoto_s3 v0.48.0
│           └── mc-ledger-distribution v6.0.0 (/Users/nick/git/mobilecoin/ledger/distribution)
└── tokio-rustls v0.23.4
└── hyper-rustls v0.23.2 (*)
```
rusoto is unmaintained and we should probably look at moving toward https://github.com/awslabs/aws-sdk-rust
=> Bump rustls form 0.21.7 to 0.21.11

.internal-ci/helm/consensus-node/templates/node-deployment.yaml, .internal-ci/helm/consensus-node/values.yaml
Make the consensus node startupProbe wait longer (more cycles) and  make the threshold configurable.
=> make consensus node startupProbe configurable

ledger/from-archive/src/config.rs, ledger/from-archive/src/main.rs
Previously mc-ledger-from-archive would always create a new ledger from
the origin block. Now mc-ledger-from-archive will update a pre-existing
ledger database.
=> Allow ledger from archive to update a ledger database

Cargo.lock, ledger/distribution/Cargo.toml, ledger/distribution/src/main.rs, tools/local-network/local_network.py
Previously ledger distribution required an argument and potentially a
state file in order to know what block to start uploading from. Now
ledger distribution will look at the current local ledger database and
walk back from the highest block finding which block has not been
uploaded yet.
=> Change ledger distribution start block logic

attest/verifier/config/Cargo.toml, connection/test-utils/Cargo.toml, crypto/digestible/derive/test/Cargo.toml, crypto/memo-mac/Cargo.toml, light-client/relayer/Cargo.toml, transaction/core/test-utils/Cargo.toml, transaction/summary/Cargo.toml
Previously some of the MobileCoin crates were missing the license entry
in their Cargo.toml file. Now all the crates have the license specified.
=> Add missing license call outs in crates

.internal-ci/docker/entrypoints/node_hw.sh, .internal-ci/docker/support/node_hw/bin/wrapper-ledger-distribution.sh, .internal-ci/helm/consensus-node/templates/node-configmap.yaml, .internal-ci/helm/consensus-node/values.yaml
It can take a long time to pull down and populate the consensus lmdb from S3.  This adds an option to the container entrypoint scripts to just run ledger-from-archive in a loop and populate the local db without bringing consensus online.
in standalone container: set `MC_LEDGER_FROM_ARCHIVE_ONLY` to any value 
or 
in helm: `--set node.config.ledgerFromArchiveOnly="true"` 
- add MC_LEDGER_FROM_ARCHIVE_ONLY option
- remove old ledger-distribution `zero,next,last` logic
=> option to warm up local consensus database.

util/grpc/Cargo.toml, util/metrics/Cargo.toml, util/metrics/src/lib.rs
Previously service metrics were always available from `mc-util-metrics.
This resulted in crates like mc-sgx-report-cache-untrusted depending on
grpcio. Now service metrics are behind the feature `service_metrics` and
crates need to opt in to use it.
=> Put service metrics behind a feature

.github/workflows/refresh-ledger-bootstrap.yaml
- update mobilecoind ledger bootstrap to use v6.0.1
- remove old partner uploads.
=> update mcd version and remove partner uploads

.internal-ci/README.md
- Remove old link to helm charts. This bucket was never actually used and has been deleted for a while.
- Clean up some unused git message documentation.
=> remove old charts link

.github/workflows/refresh-ledger-bootstrap.yaml
Ledger Bootstrap Sync job has been failing since we added the ignite node. 
Update the peer list for the mobilecoind process and add a slack message that triggers on failure.
=> Ledger Bootstrap Sync Job - update mainnet peers, add slack message on failure

.github/workflows/mobilecoin-workflow-dev-setup-environment.yaml, fog/view/server/src/config.rs, fog/view/server/src/db_fetcher.rs, fog/view/server/src/server.rs, fog/view/server/test-utils/src/lib.rs
Make fog-view database polling interval configurable. 
Before this change 1 view-store generated about 300 postgresql transactions/s in development.
After this change 1 view-store generated about 150 postgresql transactions/s in development.
Moving from default of 100ms to 250ms reduced number of transactions/s by just over half.  
- add `MC_DB_POLLING_INTERVAL_MS` env var for fog-view-store
- add pg_stat_statements lib to the dev postgres install.
- fix a couple of minor comment typos.
Investigate view queries.  Look in to only doing update queries on stores with incomplete block ranges.
=> fog-view poll timing

.internal-ci/helm/fog-ledger/templates/_helpers.tpl, .internal-ci/helm/fog-ledger/values.yaml, .internal-ci/helm/fog-view/templates/_helpers.tpl, .internal-ci/helm/fog-view/values.yaml
Right now ledger and view cookie salts are regenerated on every deploy. This means clients may be routed to different backends, requiring new attestation when we change deployment parameters and scale services.  
This change allows us to optionally set a static value for those cookie generation salts.
=> static ingress cookie salt values

mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/service.rs
We needed to have the ability to do view key matching on some txo data and we are already running `mobilecoind`, so instead of having to link in a lot of the mobilecoin Rust code, we added an endpoint to `mobilecoind` to do this.
We're using it and can confirm it works, and we also added a unit test for it.
Thanks!
=> mobilecoind: add tx_out_view_key_match api

mobilecoind/api/proto/mobilecoind_api.proto, mobilecoind/src/service.rs
see PR #4016 from @eranrund:
>We needed to have the ability to do view key matching on some txo data and we are already running mobilecoind, so instead of having to link in a lot of the mobilecoin Rust code, we added an endpoint to mobilecoind to do this.
>
> We're using it and can confirm it works, and we also added a unit test for it.
We merged #4016 into a side branch of release/6.1 in our main repo so that it could receive a full scan by CI/CD via this PR before merging into the release/6.1 branch.
=> mobilecoind: add tx_out_view_key_match api (#4016)

start-testnet-client.sh, tools/download_sigstruct.sh, tools/release/03-populate-release.sh, tools/release/README.md
- use the versioned production.json instead of assuming latest is correct.
- minor clean up and fixes with release readme and script helpers
=> use versioned measurements download
