.circleci/config.yml

This PR makes a few changes to the CircleCI build:
- It adds a new job to run `cargo build` and not just `cargo test`. That should ensure everything builds appropriately.
- It adds back the git dirty check that wasn't properly being called.
- It DRYs the `Enclave_private.pem` file generation.
- It moves the lint and cache upload to the new build task since that one is much faster than the tests one.

CircleCI build improvements

---

transaction/core/src/amount.rs
transaction/core/src/constants.rs
transaction/std/src/transaction_builder.rs
util/generate-sample-ledger/src/lib.rs

This removes remaining mention of tinyMOB as a denomination of mobilecoin, and updates comments to refer to picoMOB.

TinyMOB --> PicoMOB

---

consensus/api/proto/external.proto
consensus/api/src/conversions.rs
consensus/enclave/api/src/lib.rs
consensus/enclave/impl/src/lib.rs
mobilecoind/src/service.rs
transaction/core/src/tx.rs
transaction/core/src/validation/validate.rs
transaction/std/src/transaction_builder.rs

Previously, the tombstone_block was not signed by the transaction signature, meaning that an attacker could potentially modify it.
This ensures that the tombstone_block is included in the prefix, which gets signed.

Moves tombstone_block from Tx to TxPrefix

---

BUILD.md
README.md

This tries to reduce detail in README.md, and move that detail to a root-level BUILD.md. That detail is also expanded upon, to try to give a comprehensive overview of build environment, build configuration, and the enclave-related aspects

Improvements to build instructions in README.md

---

transaction/std/src/transaction_builder.rs

Just an extra unit test or two.

Unit tests that TransactionBuilder returns error if value is not conserved

---

consensus/api/src/conversions.rs
transaction/core/src/amount.rs
transaction/core/src/commitment.rs
transaction/core/src/compressed_commitment.rs
transaction/core/src/lib.rs
transaction/core/src/ring_signature/mlsag.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/core/src/tx.rs
transaction/core/src/validation/validate.rs
transaction/std/src/transaction_builder.rs

Previously, Amount.commitment was a RistrettoPoint (type aliased as "Commitment'), while the rest of the transaction members are CompressedRistretto. Using RistrettoPoint in Amount causes unnecessary compress and decompress operations. For example, computing the hash, digest, serialization, or deserialization of a Tx involves compressing the Amount commitment for each ring element and transaction output.
This PR adds the newtypes Commitment and CompressedCommitment, and updates Amount to use CompressedCommitment. This should prevent most of the unnecessary compress/decompress operations related to Amount.
This also changes SignatureRctBulletproof's sign and verify methods to take one-time addresses and amount commitments in compressed form (CompressedRistrettoPublic and …

Amount and signatures use CompressedRistretto

---

consensus/api/src/conversions.rs
transaction/core/src/ring_signature/curve_scalar.rs
transaction/core/src/ring_signature/mlsag.rs

RingMLSAG derives Message instead of manually implementing it.

RingMLSAG derives Message

---

consensus/service/src/byzantine_ledger.rs
ledger/sync/src/ledger_sync_error.rs
ledger/sync/src/ledger_sync_service.rs

add exponential delays when attempting to catchup in order to prevent excess retries / flooding

---

consensus/api/src/conversions.rs
consensus/enclave/impl/src/lib.rs
ledger/db/src/tx_out_store.rs
mobilecoind/src/conversions.rs
transaction/core/src/amount.rs
transaction/core/src/proptest_fixtures.rs
transaction/core/src/range_proofs/mod.rs
transaction/core/src/ring_signature/mlsag.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/core/src/tx.rs
transaction/std/src/transaction_builder.rs

The main change here is removing the type alias "Blinding", and letting Amount::new take the blinding as a plain old Scalar. 
I think this removes an irritating layer of indirection ("Blinding is a type alias for CurveScalar which is a Prost-friendly wrapper for Scalar") in several places where a Prost-friendly type is not required, like in the non-public methods of Amount.

Minor cleanup for Amount

---

util/encodings/src/base64.rs

Import is mistakenly using `failure::_core` instead of `core`. This PR fixes that.

Fix import of `core` module

---

transaction/core/src/lib.rs

`view_key` is already of type `&RistrettoPrivate`, which is the type `compute_shared_secret` accepts as a parameter, therefore `view_key` doesn't need to be ref'd.

[Minor] Fix double ref

---

transaction/core/src/ring_signature/mlsag.rs

A scalar is "canonical" if it is less than the group order. Enforcing that scalars are canonical removes the possibility that a different scalar that is equivalent mod group order could be substituted in the signature.
As far as I know, our codebase only creates canonical scalars, so this check makes that "happy path" the only path.

Checks that scalars in RingMLSAG are canonical

---

testnet-client/src/main.rs

Entropy is jargon that we can hide from our users. This substitutes the term "master key". 
The mac os terminal defaults to 80 character width, so this additionally breaks up some of the longer printed lines.

Change testnet-client prompt language to reference "master key"

---

README.md
TESTNET.md

This adds a simple link to the main README and adds a new file `TESTNET.md` with instructions on how to participate.

add testnet instructions

---

consensus/api/proto/external.proto
consensus/api/src/conversions.rs
consensus/enclave/impl/src/lib.rs
ledger/db/src/tx_out_store.rs
mobilecoind/src/conversions.rs
transaction/core/src/amount.rs
transaction/core/src/proptest_fixtures.rs
transaction/core/src/tx.rs

The Amount blinding is now derived from the output shared secret, which allows us to remove the `masked_blinding` field in Amount.

MC-1330 Removes masked_blinding from Amount

---

ledger/db/src/lib.rs
ledger/db/src/test_utils/mock_ledger.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
mobilecoind/src/sync.rs
transaction/core/src/onetime_keys.rs
transaction/core/src/ring_signature/key_image.rs
transaction/core/src/ring_signature/mlsag.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/std/src/transaction_builder.rs
util/generate-sample-ledger/src/lib.rs

Replaces some "compute_key_image" functions with KeyImage::from. I think this makes it easier to figure out how to use KeyImage by reading key_image.rs .

KeyImage cleanup

---

Cargo.lock
testnet-client/Cargo.toml
testnet-client/src/main.rs

Uses the chrono crate to display the system time when checking balance.
Adjusts some approximately centered text.
Updates send prompt based on user feedback

add timestamps to balance check display

---

mobilecoind/clients/python/mob_client.py

The `mob_client.generate_tx()` function in `mob_client.py` isn't passing the `tombstone` parameter through to the grpc call. This PR fixes that.

Fix usage of tombstone parameter in mob_client.py

---

Cargo.lock
ledger/db/Cargo.toml
ledger/db/src/error.rs
ledger/db/src/lib.rs

Prior to this PR, `LedgerDB` would store a serialized `BlockContents` object for each block. This contains redundant data, as key images and TxOuts are already stored separately. The change proposed here removes this redundancy, effectively achieving almost x2 size reduction in stored ledger size.
**This is a breaking change as it changes the ledger LMDB format**.

More efficient BlockContents storage in LedgerDB

---

testnet-client/src/main.rs

If someone who has experienced the timeout messages can run this for awhile and see if it helps, that would be useful.

use default timeout/keepalive settings when connecting to mobilecoind

---

transaction/core/src/amount.rs
transaction/core/src/domain_separators.rs
transaction/core/src/lib.rs
transaction/core/src/membership_proofs/mod.rs
transaction/core/src/ring_signature/mlsag.rs

Collects domain separator tags into a central place so that they can be standardized, documented, etc.
This PR moves the existing domain separators. Other PRs will add more where needed.

MC-539 Transaction domain separator tags

---

transaction/core/src/constants.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/validation/validate.rs
transaction/std/src/transaction_builder.rs

Previously, signing a transaction with 16 inputs and 16 outputs (the max currently allowed) would fail.

Increases BulletproofGens party_size to allow large transactions

---

crypto/keys/src/ed25519.rs
mobilecoind/src/test_utils.rs
mobilecoind/src/utxo_store.rs
util/keyfile/src/keygen.rs
util/keyfile/src/lib.rs
util/keyfile/tests/bin-determinism.rs

…  to prevent leaking the temporary directory (or more accurately, to prevent it from being cleaned up when it goes out of scope).

Switch from TempDir::into_path to TempDir::path

---

ledger/db/src/lib.rs

Another incremental step at making the ledger db contents be backed by protos.
** This is a breaking change as it changes the ledger format **

LedgerDB: Store `Block` as proto-encoded instead of cbor-encoded

---

connection/test-utils/src/blockchain.rs
ledger/sync/src/ledger_sync_service_thread.rs
ledger/sync/src/network_state_trait.rs
ledger/sync/src/polling_network_state.rs
ledger/sync/src/scp_network_state.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/bin/main.rs
mobilecoind/src/service.rs
mobilecoind/src/test_utils.rs
testnet-client/src/main.rs

This PR does the following:
* Modify `ledger_sync::*NetworkState` objects to expose the highest block index the network currently agrees on.
* Change`ledger_sync::LedgerSync*` objects to accept a network state wrapped in `Arc<Mutex<>>`, allowing it to be shared and be used by other consumers.
* Building on these changes, introduce a new `GetNetworkStatus` API to mobilecoind.
* Change the test client to take this new information into account.
The end result is that if it takes time to sync the ledger, users would have more visibility to that and not just see a 0 balance.

Improve client experience during ledger catchup

---

consensus/api/src/conversions.rs
crypto/keys/src/ed25519.rs
ledger/db/src/lib.rs
transaction/core/src/blockchain/block_signature.rs

Another incremental step at making the ledger db contents be backed by protos.
Sadly this involves ugly wrappers.
**This is a breaking change as it changes the ledger format.**

LedgerDB: Store `BlockSignature` as proto-encoded instead of cbor-encoded 

---

consensus/api/src/conversions.rs
consensus/service/src/validators.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
mobilecoind/src/sync.rs
transaction/core/src/account_keys.rs
transaction/core/src/onetime_keys.rs
transaction/core/test-utils/src/lib.rs
transaction/std/src/transaction_builder.rs

- Updates PublicAddress docs to refer to subaddresses
- Unit tests that private subaddress keys agree with public subaddress keys.
- Removes redundant math in AccountKey.subaddress()

AccountKey cleanup

---

consensus/api/src/conversions.rs
consensus/service/src/validators.rs
transaction/core/src/constants.rs
transaction/core/src/ring_signature/error.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/core/src/tx.rs
transaction/core/src/validation/error.rs
transaction/core/src/validation/mod.rs
transaction/core/src/validation/validate.rs
transaction/std/src/transaction_builder.rs

The fee is known to be a 64-bit number, so it is not necessary to include it in the range proof. This reduces* the range proof size and validation time.
*We aggregate proofs for 1,2,4,8,16.. values, "rounding up" to the next power of 2. For certain transactions, including the fee in the range proof bumps things up to the next power of 2.

MC-1340 Removes fee output from range proof, finer-grained errors

---

ledger/db/src/error.rs
ledger/db/src/lib.rs
ledger/db/src/metadata.rs
ledger/db/src/tx_out_store.rs
tools/local-network/bootstrap.sh

This PR:
* Changes TxOutStore and key images storage to encode using Prost instead of serializing using Serde. This makes the entire ledger lmdb file contents be protobufs, so it could be read by other implementations, and fields could easily be added as long as the tag numbers do not conflict.
* It also adds a new database that stores a u64 version number, and the crate version string that created the database. My hope is that when we introduce breaking changes we would be able to write code that looks at these version numbers and perform migrations / alert the user about the incompatibility. This would rely on us remembering to update this code when we make breaking changes. It would've been nice if this could happen automatically, but I couldn't figure out reasonable way to do it (for …

More serde->prost changes in Ledger + introducing metadata versioning storage

---

Cargo.lock
consensus/api/proto/consensus_peer.proto
consensus/service/src/peer_api_service.rs
peers/src/connection.rs
peers/src/sync.rs
peers/src/threaded_broadcaster.rs
peers/src/traits.rs
peers/test-utils/Cargo.toml
peers/test-utils/src/lib.rs

Fixes MC-1356.
Currently, peers receive an invalid argument gRPC error when sending consensus messages to a peer who does not know of them. However, it is expected that when a node is first joining the network, no other peers have added them to the `known_peers` section of the network.toml.
This change introduces a response type that allows for specifying the non-error case that the node is not yet known.

Add rpc response type to allow unknown peers without error

---

consensus/api/proto/blockchain.proto
ledger/distribution/src/main.rs
ledger/sync/src/reqwest_transactions_fetcher.rs

This PR uses protobuf's [oneof](https://developers.google.com/protocol-buffers/docs/proto3#oneof) to add future-compatibility to our S3 block proto message.

Add versioning to S3Block

---

consensus/api/proto/blockchain.proto
consensus/api/src/conversions.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/src/lib.rs
consensus/service/src/blockchain_api_service.rs
ledger/db/src/lib.rs
ledger/db/src/test_utils/mock_ledger.rs
ledger/sync/src/ledger_sync_service.rs
ledger/sync/src/test_app/main.rs
mobilecoind/src/service.rs
mobilecoind/src/test_utils.rs
transaction/core/src/blockchain/block.rs
transaction/core/test-utils/src/lib.rs
transaction/core/tests/blockchain.rs
util/generate-sample-ledger/src/lib.rs

This will greatly simplify some post-processing stuff that happens
to the blockchain, it will mean that a bunch of services that
we have don't have to process the entire blockchain in order to
get these counts, which will become important when the blockchain
gets big.

Add cumulative txo count to the block header

---

common/src/responder_id.rs
consensus/api/proto/consensus_peer.proto
consensus/service/src/peer_api_service.rs
peers/src/connection.rs

Previously `ResponderId` was passed over grpc as a serde-serialized object, but we could simplify that and pass it as the string that it is (and that's unlikely to change any time soon or at all). This PR takes care of that.

simplify ResponderId implementation

---

mobilecoind/src/service.rs
transaction/std/src/transaction_builder.rs

TransactionBuilder should be misuse-resistant. Here, TransactionBuilder sorts the transaction outputs so that patterns in client code, like always adding a change output last, do not leak into submitted transactions.
Also updates mobilecoind unit tests which assumed that the change output was the last output in the transaction.

MC-511 TransactionBuilder sorts outputs by public key

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/database.rs
mobilecoind/src/monitor_store.rs
mobilecoind/src/service.rs
mobilecoind/src/sync.rs
mobilecoind/src/test_utils.rs

This PR adds an optional user-provided name that can be associated with each monitor mobilecoind has. This allows user to give their monitors friendly names, and they can later locate them by querying the list of monitors and matching by name.

mobilecoind: add optional monitor name

---

consensus/enclave/src/lib.rs

This removes the gonzo `unwrap_or_else(|_e| panic!("unhelpful message"))` in favor of `expect()`.

MC-1404 Improve consensus enclave startup debugging #in-review

---

transaction/core/src/account_keys.rs
transaction/core/src/constants.rs
transaction/core/src/domain_separators.rs
transaction/core/src/tx.rs

Adds a domain separator tag to the subaddress hashes, and updates the Fee account keys.
This changes all subaddresses, which breaks compatibility with the existing ledger.

MC-1378 Subaddress hash functions use domain separator

---

mobilecoind/src/service.rs
tools/local-network/bootstrap.sh

This PR fixes a few small issues:
- It changes the local-network bootstrap shell script to create 20 accounts instead of 10 so that the balance held by each account can be represented in a `u64`.
- It gets rid of janky logic that prevents recompilation of the relevant binaries - bootstrapping doesn't happen often and this logic is more likely to bite someone than to provide useful value (case in point: I failed at bootstrapping a correct ledger until it occurred to me that the binaries are just old ones, from a previous commit).
- It changes `mobilecoind`'s `GetBalance` API to error if the balance does not fit in a `u64`.

Bootstrap fixes

---

jenkins/Jenkinsfile

Generating more accounts with 100tx (and then throwing away the unused keys) so that test_client doesn't run into the u64 error message.

Change test ledger generation for smaller balances

---

testnet-client/src/main.rs

This PR changes our preferred display units to the following:
|min|max|unit|
|-|-|-|
| 0 | 999 pMOB  | pMOB |
| 0.001 µMOB | 999.999 µMOB  | µMOB  |
| 0.001 MOB | 999.999 MOB  | MOB |
| 1 kMOB | max  | kMOB |

prefer MOB units in testnet client

---

hooks/pre-push

When we set up mobilecoin repo, some engineers wanted that we prevent
new branches from being created for pull requests in the main repo
itself, they want everyone to use forks, and this makes some tools
work better.
Initially we tried to make github itself reject such pushes but
it was found that there is no way to do it.
Instead, this pre-push hook can be installed locally to prevent
accidentally pushing to origin, and suggest pushing to fork and
opening a PR from your fork instead.

Add a pre-push hook, prevents accidentally pushing branches to origin

---

transaction/core/src/domain_separators.rs
transaction/core/src/onetime_keys.rs
transaction/core/src/ring_signature/key_image.rs
transaction/core/src/ring_signature/mlsag.rs

Adds domain-separated hash_to_point and hash_to_scalar functions. Domain separation is the main goal here, but the new functions also simplify using the "right" hash function in various parts of the code that need these.

MC-1396 Domain-separated hash_to_point and hash_to_scalar functions

---

consensus/service/src/tx_manager.rs

The combine function should be deterministic across all nodes. Currently, a node would omit a TxHash while combining if it it has not cached the corresponding Tx, which would be a non-deterministic deviation from the protocol.
Unclear if that actually happens in practice, so this PR elevates the log message from `info` to `error`.

MC-1447 Upgrades log message from info to error

---

common/Cargo.toml

`mc-crypto-rand` is listed as a `dependency` and a `dev-dependency` in the `mc-common` crate. This PR removes the duplicate entry from the `dev-dependency` section.

Remove duplicate dev-dependency in mc-common crate

---

common/src/lib.rs

Running `cargo test -p mc-common` results in a compile error on account of `no_std` being set when the `log` feature isn't enabled. This PR changes the conditional for `no_std` to include whether we're running tests or not.

Fix mc-common tests without features

---

Cargo.lock
util/generate-sample-ledger/Cargo.toml

The `mc-common` crate isn't being used in the `generate-sample-ledger` crate. This PR removes the dependency.

Remove mc-common dependency from generate-sample-ledger

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

The 2 patches in our [cmake-rs fork](https://github.com/mobilecoinofficial/cmake-rs/commits/93ff3a1b1ffcb5c43b924362d95c96762f23454e) (see https://github.com/alexcrichton/cmake-rs/pull/86 and https://github.com/alexcrichton/cmake-rs/issues/87) have been merged/fixed upstream and a new version has been published (see https://github.com/alexcrichton/cmake-rs/issues/87). This PR removes reference to our fork and updates to the new version (`0.1.43`).

Remove cmake-rs fork and update to 0.1.43

---

attest/core/src/ias/verify.rs
common/src/logger/mod.rs
common/src/lru.rs
consensus/enclave/trusted/src/lib.rs
mobilecoind/src/monitor_store.rs
sgx/build/src/conf.rs
sgx/types/src/types.rs

Recent rust compiles warns about unnecessary parenthesis.

Fix compiler warnings

---

util/keyfile/src/keygen.rs

Currently, the keyfile test management requires files to be named account_keys_0.json, account_keys_1.json, etc, and to start at 0. This change allows keyfiles to be named arbitrarily.

Do not prescribe keyfile names

---

Cargo.lock
attest/core/Cargo.toml
attest/net/Cargo.toml
consensus/enclave/impl/Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml
util/build/enclave/Cargo.toml

This pulls in https://github.com/mobilecoinofficial/rust-mbedtls/commit/8cac1fd1b9c521efb742a1014471e8563b2d6426 which is needed for Android compilation on Mac.

bump mbedtls version to mc-0.3 in order to address an Android compilation issue

---

Cargo.lock
Cargo.toml
util/repr-bytes/Cargo.toml
util/repr-bytes/README.md
util/repr-bytes/src/lib.rs

We currently have a lot of code that is like manually grabbing
`prost::encoding::*;` and using it to create custom serializations
with prost.
This is a hazard, because that is not part of the public-facing
interface of prost and it is not documented. It also changes
periodically as upstream refactors the library. The only reason
these symbols are publicly visible at all is that there is no way
that `prost-derive` can function if the proc-macro generated code
cannot access these symbols. When we grab `prost::encodings::*;`
it is creating a maintanence hazard that will make it very hard
ever to uprev prost again.
In the past, every cryptographic primitive that went into `prost`
or `serde` required custom bindings code, which was very long.
ReprBytes32 was a quick stopgap to prevent the code …

Move ReprBytes32 to its own crate and generalize it

---

consensus/service/src/peer_api_service.rs

Soundtrack of this PR: [https://www.youtube.com/watch?v=C7K0rInwDR4](what I happen to be listening to right now)
MC-1055 specifies we should reject consensus messages that do not verify at the RPC entry point, but this is already taking place: 
https://github.com/mobilecoinofficial/mobilecoin/commit/e98a65a323c25919efcab3dfa5bb4db22da3745b#diff-d6a3701358007ab768cdea687051b1bdR273
https://github.com/mobilecoinofficial/mobilecoin/blob/e98a65a323c25919efcab3dfa5bb4db22da3745b/peers/src/consensus_msg.rs#L51-L58
The code also has a FIXME comment that says `Additional verification for quorum set members that public key matches expected`, how ever we moved to a world where the node id is this public key, so if the public key is changed it will no longer be part of our quorum set and we wont act …

remove no longer relevant comment

---

transaction/core/src/ring_signature/mlsag.rs

Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=JTEFKFiXSx4)
Signature validation should reject CompressedRistretto points that don't canonically encode a Ristretto point. Roughly, the canonical points are the nice prime-ordered group that Ristretto provides us with, and the non-canonical ones are everything else.
Unit tests that MLSAG signature verification rejects a signature with a non-canonical Key Image, and returns the correct Error type.

[MC-1475] Unit test that MLSAG signature validation fails if a key image fails to decompress

---

mob

This allows the .mobconf to contain Dockerfile-version so that
the tool can be used in a repo that doesn't contain Dockerfile
or Dockerfile-version files.

Sync mob tool with internal version

---

mobilecoind/clients/python/blockchain_explorer/requirements.txt
mobilecoind/clients/python/pizzamob_leaderboard/requirements.txt

Soundtrack of this PR: [Spinning Away by Eno & Cale](https://www.youtube.com/watch?v=-INeMspNSQ0)
These changes are necessary for the pizzamob and blockchain explorer clients to run as advertised.
* Adds `grpcio` and `grpcio-tools` to the `requirements.txt` files.

Missing gRPC libraries in the python clients

---

mobilecoind/clients/python/Wallet.ipynb

Soundtrack of this PR: [Hazey](https://www.youtube.com/watch?v=nOHEuhJf7nA)
A previous change to the organization of the python clients dir resulted in the Wallet.ipynb no longer running.
* Fixes the Wallet.ipynb by adding a sys path append to add the mob_client dir.

Fix wallet example

---

crypto/keys/src/ristretto.rs

This will allows some code back end services, to be
simplified a little bit, there are a couple places where I am
using try_from to convert from &[u8;32] into this object, even
though the conversion cannot fail.
Soundtrack of this PR: https://www.youtube.com/watch?v=vwfO6tT1ZnU&t=12s

Make CompressedRistrettoPublic implement From<&[u8;32]>

---

mobilecoind/src/service.rs
testnet-client/src/main.rs
util/b58-payloads/src/payloads.rs

Soundtrack of this PR: https://www.youtube.com/watch?v=sVReXN2sFck
Before this commit, a b58 payload with invalid ristretto curvepoints
will cause the application to panic. This is wrong, we should not
panic when deserialization fails.
This commit changes the b58 payloads so that they don't implement
From, which assumes the conversion cannot fail. Instead they
implement TryFrom, and makes sites that were using this
use either TryFrom or TryInto.

Dont panic on ristretto decompression errors

---

api/src/conversions.rs
consensus/service/src/validators.rs
mobilecoind/src/payments.rs
transaction/core/src/validation/validate.rs
transaction/core/test-utils/src/lib.rs
transaction/std/src/input_credentials.rs
transaction/std/src/transaction_builder.rs

Soundtrack of this PR: [April 26, 1992](https://www.youtube.com/watch?v=qi8KJ0boov8&t=91s)
Sorting ring elements prevents the ordering from leaking any information about the true input. 
* InputCredentials sorts the ring elements (instead of randomly shuffling them)
* validate.rs checks that each ring is sorted.

[MC-1470] Ring elements must be sorted

---

Cargo.lock
consensus/enclave/measurement/Cargo.toml
consensus/enclave/measurement/build.rs
util/build/enclave/src/lib.rs
util/build/sgx/src/sign.rs

[Soundtrack of this PR](https://www.youtube.com/watch?v=rFBnlO46xUk)
Right now, all builds require the SGX SDK to be installed, even if they are simply injecting a CSS file.
- Update `mc_util_build_sgx::SgxSign` to just take a `target_arch` on construction.
- Update `mc_util_build_enclave::Builder` to just take the required SGX version.
- Update `mc_util_build_enclave::Builder` to delay hitting pkg-config until actually needed.

Fix CSS-injected builds of mc-mobilecoind when SGX SDK not installed.

---

consensus/api/proto/consensus_common.proto
consensus/api/src/conversions.rs
consensus/enclave/api/src/lib.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/src/lib.rs
consensus/service/src/client_api_service.rs
consensus/service/src/test_utils/mod.rs
consensus/service/src/tx_manager.rs
consensus/service/src/validators.rs
ledger/db/Cargo.toml
ledger/db/src/error.rs
ledger/db/src/ledger_trait.rs
ledger/db/src/lib.rs
ledger/db/src/metadata.rs
ledger/db/src/test_utils/mock_ledger.rs
ledger/db/src/tx_out_store.rs
transaction/core/src/tx.rs
transaction/core/src/validation/error.rs
transaction/core/src/validation/validate.rs

Soundtrack of this PR: [whats currently playing in my room](https://soundcloud.com/doobdoob/doob-moloch-du-sollst-nicht-gehen-310318?in=doobdoob/sets/doob-slow)
We use a TxOut's public key as a unique identifier for the TxOut in numerous places, but up until now have not enforced its uniqueness. Well-behaved clients should never generate the same key twice, but it is a good idea to enforce this behavior in consensus.
* Adding a new TxOut-by-public-key LMDB store
* Changing validation logic across ledger db and consensus to deny having duplicate TxOut public keys.
* For the first time, adding code to gracefully migrate existing LedgerDBs so that this update is painless for live networks.
This has been deployed and slammed successfully with no noticeable performance implications. This does …

Disallow duplicate TxOut public keys

---

Cargo.lock
util/uri/Cargo.toml
util/uri/src/traits.rs
util/uri/src/uri.rs

Soundtrack of this PR: https://www.youtube.com/watch?v=gjEqMt15MKc
The cause for this was, I get "unknown scheme" errors but I don't
know what the expected scheme was, so it makes it hard to debug.
I want it to hold &'static str and tell me what it wanted to see.
This retains the goal of keeping errors having the `'static` property.

Improve mc-uri error reporting and port to displaydoc

---

mobilecoind-json/src/main.rs

Soundtrack of this PR: [Get Back](https://www.youtube.com/watch?v=IKJqecxswCA)
A couple of outstanding requests from our partners for the REST API 
* GET for the list of current monitors
* GET for details about a block 
```
$ curl localhost:9090/monitors -d '{"entropy": "706db549844bc7b5c8328368d4b8276e9aa03a26ac02474d54aa99b7c3369e2e", "first_subaddress": 0, "num_subaddresses": 10}' -X POST -H 'Content-Type: application/json'
{"monitor_id":"5bb9c1a387029f16ded2c8c2f5a942c6ccb1a70f822684372b6b95a8c26750c7"}
$ curl localhost:9090/monitors
{"monitor_id":["5bb9c1a387029f16ded2c8c2f5a942c6ccb1a70f822684372b6b95a8c26750c7"]}
$ curl localhost:9090/block-details/5
{"block_id":"e5f20951896206e88e3df25bf4191381ac197f756ef4fcc713686b5644c87476","version":0,"parent_id":"fe6f53c07aa35c051a40c8afd8e493 …
```

Adds additional REST functions for monitor list and block details

---

api/proto/external.proto
api/src/conversions.rs
mobilecoind/api/proto/mobilecoind_api.proto

The external.proto TxOut was listed as RistrettoPublic but its actually
CompressedRistretto. This fix necessitated adding an extra conversion
and changing one mobilecoind_api type.

Fix external.proto TxOut key types

---

util/b58-payloads/src/payloads.rs

Soundtrack of this PR: [Mr Postman](https://www.youtube.com/watch?v=425GpjTSlS4)
For some potential workflows we'd like a way to specify a URL for a user to submit their public address 
* Defines a payload for a b58 encoding of an "address request" which is just URL
* Tests round-trip encoding and decoding
* Integrate into APIs

Encoding for address requests, right now just a URL to POST to

---

consensus/service/BUILD.md
docker/install_sgx.sh

Signed-off-by: Brian Anderson <andersrb@gmail.com>
The SGX build instructions are out of date with the docker script.
Update BUILD.md to use the same drivers, SDK, and packages as the Dockerfile.
Note that the number of recommended APT packages is reduced. I don't know the significance of this, as I just copied the list from install_sgx.sh.
I have run all these commands before performing a successful build. It was not on a fresh machine though.

Update SGX build instructions per Docker script

---

mobilecoind-json/src/main.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

Soundtrack of this PR: [Postal Service -- Such Great Heights](https://www.youtube.com/watch?v=0wrsZog8qXg)
Previously we added the address request payload, this adds it to mobilecoind and the REST API
* adds a gRPC call to generate a b58 code for an address request
* adds a REST call to wrap the gRPC call 
```
$ curl localhost:9090/address-request -X POST -d '{"url": "https://example.com"}' -H 'Content-Type: application/json'
{"request_code":"4mppAGCtx4xn42C36Ck7gGnAoGbdJceYBH6k"}
```

Adds address request code to mobilecoind and REST API

---

consensus/service/src/blockchain_api_service.rs
ledger/db/src/lib.rs
mobilecoind/src/service.rs
mobilecoind/src/test_utils.rs
transaction/core/test-utils/src/lib.rs

LedgerDB should ensure only valid blocks are written, as an extra safety measurement. Non-origin blocks that lack key images are invalid and that should be enforced.
`append_block` enforces non-zero number of key images for non-origin blocks.

MC-1335: LedgerDB should reject non-origin blocks that do not contain key images

---

common/Cargo.toml

Soundtrack of this PR: [Sahalé - Nlreb Mra Alrrih (Playing With The Wind)](https://soundcloud.com/sahaleprods/sahale-nlreb-mra-alrrih-playing-with-the-wind)
`mc-util-serial/std` must be enabled whenever `serde/std` is enabled, even if `serde/std` is enabled by a third-party dependency. Currently `mc-common/loggers` enables multiple dependencies (`sentry`, `slog-gelf`, and `slog-json`) that all enable `serde/std`. This causes a compile error for any crate that depends on `mc-common/loggers` without something in the dependency tree also enabling `mc-util-serial/std`. Since `mc-common/loggers` is the crate that introduces these dependencies, it should also enable `mc-util-serial/std` for correctness.
* Enables `mc-util-serial/std` for `mc-common/loggers`
* Removes redundant `serde/std` from …

Enable mc-common/std for mc-common/loggers

---

mobilecoind/clients/python/blockchain_explorer/blockchain_explorer.py
tools/local-network/local-network.py
watcher/src/watcher.rs
watcher/src/watcher_db.rs

While working on block timestamps I discovered a few issues:
1) The `watcher` crate was keeping track of last synced block indexes, but defaulting to zero - which is incorrect since block index 0 also needs to be synced. Without the fixes here, the watcher was taking 100% CPU attempting to constantly get new blocks even if everything was synced.
2) `local-network` had a small bug that caused it to fail if nodes take a bit too long to copy the ledger database from the bootstrap one.
3) `block_explorer.py` had a confusing line at the top that caused me to waste some time trying to figure out why changing it is not getting the desired effect.
Fixes for the above issues. Issues 2 and 3 are trivial. For the `watcher` bug I opted to change how `watcher` stores its state. The `last_synced` …

watcher bugfix: properly keep track of last synced block indexes (and some other bugfixes)

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
mobilecoind/Cargo.toml
transaction/core/Cargo.toml

Soundtrack of this PR: https://soundcloud.com/johnny-blue/johnny-blue-anthropos-stream-2020
`byteorder` was replaced by builtin functionality, and there is a lingering unused dependency on it.
Removing said dependency.

remove unused dependency on byteorder

---

.gitignore
api/proto/blockchain.proto
api/src/conversions.rs
consensus/service/src/tx_manager.rs
mobilecoind/clients/python/blockchain_explorer/blockchain_explorer.py
mobilecoind/clients/python/blockchain_explorer/static/css/lofi.css
mobilecoind/clients/python/blockchain_explorer/templates/block.html
transaction/core/src/blockchain/block_signature.rs
watcher/src/watcher_db.rs

Soundtrack of this PR: [Techno](https://soundcloud.com/adambeyer/dcr515-drumcode-radio-live-adam-beyer-studio-mix-recorded-in-ibiza)
We want to have an approximate estimation for when blocks were formed. This PR adds that.
* Change to `BlockSignature` to also include an optional timestamp, represented as seconds since unix epoch that is filled in by untrusted consensus service immediately after forming a block. This change is backwards compatible.
* A change to the block explorer that shows the timestamps on a block page:
* A fix to `watcher` to use constant-size keys. This fix is not backwards compatible.

MC-1567: include approximate signing time in BlockSignature

---

consensus/service/src/config.rs

Soundtrack of this PR: [Moontide Theory](https://youtu.be/ZFI7xoIHt-Q)
Adds a unit test I made to check my understanding of what kind of string is expected by `keypair_from_bytes`

Adds unit test for keypair_from_bytes

---

jenkins/Jenkinsfile

Soundtrack of this PR: [Kick Out The Jams](https://www.youtube.com/watch?v=8XhQRFO4M7A)
The current continuous deployment process will clobber any already-running deployment, thus failing tests and deployment.  This locks the deploy and test process so that deployment and testing can run to completion.
* Additional stage to lock the deploy and test stages
* Build status notification

Add lock to deploy and test, slack notification

---

tools/local-network/README.md
tools/local-network/local_network.py

Soundtrack of this PR: [generic house music](https://soundcloud.com/guy-j/guy-j-echos-12062020)
For some internal work we want to be able to reuse code inside the local network Python script. In order to be able to import it, it needs to match the Python naming conventions.
* Rename `local-network.py` to `local_network.py`
* Some minor structural changes to allow the entry point (`__main__` stuff) to be reused.

rename local-network.py to local_network.py so that it could be imported as a python module

---

mobilecoind/src/payments.rs
transaction/core/src/domain_separators.rs
transaction/core/src/lib.rs
transaction/core/src/tx.rs
transaction/std/src/transaction_builder.rs

Soundtrack of this PR: [https://www.youtube.com/watch?v=Clo0U1BMR5I](My God by Pusha T)
We want to be able to send something to a transaction recipient that demonstrates that we have some secret knowledge that only the creator of the transaction would know.  It doesn't actually prove that we created the transaction, but its close enough for our use case.
* Add TxOutConfirmationNumber and corresponding domain separator
* Create and return it from TransactionBuilder::add_output
fixes #FOG-98
* Integrate confirmation number into sdk and mobilecoind

Implement confirmation number

---

util/uri/src/lib.rs
util/uri/src/uri.rs

This is the result of discussion and redesign / rescoping of
https://github.com/mobilecoinofficial/mobilecoin/pull/206
Soundtrack of this PR: https://www.youtube.com/watch?v=Grrx2IHHIn8
We have decided not to do shard-id right now, and to store things like signature
as struct members in public address. This redevelops and greatly reduces scope of
https://github.com/mobilecoinofficial/mobilecoin/pull/206
and moves some code out of the public repo so that we can iterate more easily.
Renames FogClientUri to FogUri, which is shorter and unambiguous, and will cause me have to inspect and make code changes at any place that was using FogClientUri, which is what I want so that I can make it use the right thing.
- Make fog_authority_fingerprint part of account key
- Make …

Rename FogClientUri to FogUri, move Fog-ledger-uri to internal

---

transaction/core/src/tx.rs
transaction/std/src/transaction_builder.rs

The initial TxOutConfirmationNumber PR was pushed out quickly so that clients could start using it.  But there were a couple of small items in the review comments that were promised in an add-on PR.  This PR will satisfy those review comments.
* Change TxOutConfirmationNumber::new() to TxOutConfirmationNumber::from() since the latter is more canonical Rust
* Add a unit test that verifies the return from TxBuilder::add_output is the same as would be calculated from the shared_secret directly
This change completes FOG-98.
This is the final piece of this work.

Change confirmation ::new to ::from and add a unit test

---

Cargo.lock
api/proto/external.proto
api/src/conversions.rs
consensus/enclave/impl/src/lib.rs
mobilecoind-json/src/main.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
transaction/core/src/account_keys.rs
transaction/std/src/identity.rs
transaction/std/src/transaction_builder.rs
util/b58-payloads/Cargo.toml
util/b58-payloads/src/error.rs
util/b58-payloads/src/payloads.rs
util/keyfile/src/lib.rs
util/test-helper/src/known_accounts.rs
util/uri/src/uri.rs

Soundtrack of this PR: https://www.youtube.com/watch?v=gHUBYt1oPio
We must make some changes where we add some fields to account key and public address.
We need to incorporate the fog authority key fingerprint and the user's signature over that fingerprint,
in order to establish a complete chain of trust back to Bob whenever Alice wants to use a fog report
to send money to Bob.
In earlier discussion we considered encoding this as query parameters in fog-url, but that was only
to avoid making any changes to the b58-encoding. The b58-encoding has changed a lot since then
and has become much simpler to update.
We also should add version numbers to account keys / public addresses soon if we want to have that
for release. Otherwise it will be difficult or impossible to change the meaning of …

New fields in account keys and public addresses

---

api/proto/external.proto
api/src/conversions.rs
mobilecoind/api/proto/mobilecoind_api.proto

Soundtrack of this PR: https://www.youtube.com/watch?v=q_7l0ozbHVA
Generally, we should not use RistrettoPublic in serialized types,
we should try to use CompressedRistretto, because decompressing
a ristretto point requires elliptic curve operations and is pretty
slow. In early performance profiling, consensus spent most of its
time doing this, and that is why we created the CompressedRistretto
type.
The protobuf type external.RistrettoPublic is actually identical
to external.CompressedRistretto, we don't need both, and we should
discourage people from using RistrettoPublic in their serialized
structs.
Remove `external.RistrettoPublic`
Fixup mobilecoind_api.
Turns out we have enough conversions on external.CompressedRistretto
now that no code changes are required.
Fog-125

Remove external.RistrettoPublic, replace with CompressedRistretto

---

consensus/scp/src/core_types.rs
consensus/scp/src/quorum_set.rs
consensus/scp/src/test_utils.rs

QuorumSet equality is incorrect in existing code.
* Fix equality by comparing quorum set members in sorted order

QuorumSetMember ordering should not matter

---

api/proto/external.proto
api/src/conversions.rs

The sender of a transaction has a need for a well-established way to notify the intended recipient to expect an incoming `TxOut` in a way that is verifiable, at least in part, by the recipient.
This `Receipt` structure provides the recipient with the following:
* The public key of the expected `TxOut`. Because `TxOut` public keys are unique in the ledger, this will uniquely identify the `TxOut`.
* The confirmation number of the `TxOut`, which can be used by the recipient of the `TxOut` to confirm that the `TxOut` is indeed intended for them, and to provide evidence that the other party is the sender, or at least knew the shared secret of the `TxOut`.
* The tombstone block of the `Tx` that produced the `TxOut`. One intended use-caes of `Receipt` is to represent a `TxOut` that is not yet in …

[MC-1604] Add Receipt to external.proto

---

crypto/digestible/src/lib.rs

Soundtrack of this PR: https://soundcloud.com/change-underground/sets/flow-sessions-10-1
The digestible crate used `unsafe` to mark a trait that is risky to implement correctly, however that is not a good use of `unsafe` since the code is actually safe.
Removing the `unsafe` markers.

remove incorrect use of unsafe

---

api/proto/external.proto
api/src/conversions.rs
mobilecoind-json/src/main.rs
mobilecoind/src/service.rs
transaction/core/src/account_keys.rs
util/b58-payloads/src/payloads.rs

Soundtrack of this PR: https://www.youtube.com/watch?v=ktwlN_ocL-o
The term "fog_report_key" is ambiguous with actual cryptographic keys,
this is just an id / label string. In discussion it was proposed to rename it
to an id instead.
Rename the `fog_report_key` field to `fog_report_id`

Rename fog_report_key to fog_report_id, per discussion

---

util/url-encoding/README.md
util/url-encoding/src/payment_request.rs

Soundtrack of this PR: https://www.youtube.com/watch?v=MbXWrmQW-OE
Add tests that show what happens when there are unicode characters in the memo, this concern was raised in discussion,
before this commit we were only testing for roundtrip integrity.
The test shows that percent-encoding is used on the unicode codepoints, which is what I expect based on the spec here: https://url.spec.whatwg.org/#urlencoded-serializing
Add an extra test case for mob ulr, fixup out of date examples in readme

Add tests that show what happens when there are unicode characters in memo

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/conversions.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
transaction/core/src/tx.rs

Soundtrack of this PR: [https://www.youtube.com/watch?v=o2dbcH1DsLo](Receipts)
We recently added confirmation numbers to TransactionBuilder which allow a sender to prove that they created a particular transaction. We need to expose this functionality in mobilecoind. This first PR returns the confirmation numbers as part of the receipt.
* Adds confirmation number list to the TxProposal struct
* Returns confirmation numbers as of the recipient transaction receipt
* Call to validate confirmation numbers
* Add all this to the REST API

Return confirmation numbers with receipts in mobilecoind

---

watcher/src/watcher.rs
watcher/src/watcher_db.rs

Soundtrack of this PR: [Good as Hell](https://www.youtube.com/watch?v=vuq-VAiW9kw)
Currently, the WatcherDB keeps a vector of src_urls that it is watching. This is unnecessary, and introduces a dependency for other services who may want to operate the WatcherDB in read-only mode, e.g. to get timestamps.
* Removes src_urls from WatcherDB
Required for [Fog-130](https://mobilecoin.atlassian.net/browse/FOG-130)

WatcherDB should not require src urls

---

mobilecoind/src/service.rs
util/b58-payloads/src/payloads.rs

Recent changes to the b58 code scheme were not backwards compatible. This breaking change needs to be coordinated with our release schedule.
Even if we decide not to use the b58 codes in the SDK work, there's no reason to break backwards compatibility in the test client.
* move new fields to version 4
* actually verify the test vectors by comparison to calculation in javascript
* do this right! Separate serialization from encoding and use protobuf

new fog fields require a new payload version for backwards compatibilty

---

transaction/core/src/tx.rs
transaction/std/src/transaction_builder.rs

Soundtrack of this PR: [One Tree Hill](https://www.youtube.com/watch?v=WfKhVV-7lxI)
(because I'm in Auckland)
The actual logic for using confirmation numbers is currently only in a test, this moves it to a method of TxOutConfirmationNumber so it can be easily called elsewhere.
* Additional method for validating confirmation numbers
* Updates transaction_builder test to use this new method
* Add calls to this for mobilecoind

Encapsulates the validation function for TxOutConfirmationNumber

---

mobilecoind/src/service.rs
util/b58-payloads/src/payloads.rs

Due to a lack of rebase, #256 does not pass tests and prevents further work on the repo until it is fixed.
This reverts commit 69f59b33e4597aee2789ff7a5f88c66cd727d08e.
* Reopen and rebase #256 with the necessary fixes.

Revert "add v4 request payload for backwards compatibility (#256)"

---

Cargo.toml
attest/core/build.rs
consensus/enclave/trusted/Cargo.toml

#253 had to workaround Cargo's build feature unification annoyance (`build-dependencies` features plaguing the actual package's dependencies) by gating stuff on the `std` feature. Since upgrading Rust, we can now use the new resolver (see https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#resolver).
* Switch us to the new resolver. I have confirmed this solves the issue in #253.

enable resolver = "2"

---

Cargo.lock
Cargo.toml
ledger/db/Cargo.toml
mobilecoind/Cargo.toml
mobilecoind/src/monitor_store.rs
mobilecoind/src/utxo_store.rs
watcher/Cargo.toml
watcher/src/watcher_db.rs

The old `lmdb` crate we were using (https://github.com/danburkert/lmdb-rs) appears to no longer be maintained, and has some bugs that affect us (such as https://github.com/danburkert/lmdb-rs/issues/58). Mozilla are maintaining their own [fork](https://github.com/mozilla/lmdb-rs) which addresses the bugs we ran into.
* Switching every use of the old crate with the new crate.
* The bugfix we need has not been released to crates.io yet, so we are getting the crate straight from git. Once its released we should remove the override to use the released version.

Switch to using Mozilla's lmdb fork

---

Cargo.lock
mobilecoind-json/src/main.rs
mobilecoind/api/Cargo.toml
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs
mobilecoind/src/test_utils.rs
testnet-client/src/main.rs

Soundtrack of this PR: [Return of the Mack](https://www.youtube.com/watch?v=uB1D9wWxd2w)
The last mobilecoind PR added confirmation numbers to return receipts. This PR allows `GetTxStatusAsReceiver` to validate the confirmation numbers given a `monitor_id`. I have made the check optional for flexibility, if no `monitor_id` is given the check remains the same as before.
* Adds an optional `monitor_id` to `GetTxStatusAsReceiverRequest` to provide private view key
* Checks that at a confirmation number is valid for a given tx_pubkey and private view key
* Adds an additional return status `InvalidConfirmationNumber`
* Add this functionality to the REST API

Validate confirmation numbers in mobilecoind tx_status

---

attest/core/Cargo.toml
attest/core/src/error.rs
attest/core/src/ias/verify.rs
attest/net/src/sim.rs
consensus/service/src/consensus_service.rs

We want to add some metrics around report timestamps. For that we need to be able to get a usable timestamp object. This PR adds a utility method for the timestamp parsing, in order to save us from duplicating this code anywhere timestamp parsing is required.
Adding `parse_timestamp` to `VerificationReportData`.
* Adding metrics that use the timestamp :)

add a convenience method for parsing VerificationReportData timestamp

---

mobilecoind/src/service.rs
util/b58-payloads/src/payloads.rs
util/url-encoding/tests/comparison.rs

Recent changes to the b58 code scheme were not backwards compatible. This PR restores backwards compatibility and fixes the merge race introduced in reverted PR #256
* move new fields to version 4

add v4 payment requests

---

Cargo.lock
watcher/Cargo.toml
watcher/src/watcher_db.rs

Soundtrack of this PR: [Who Can Say](https://www.youtube.com/watch?v=gMlby1X98wU)
Currently, the watcher's "get last synced block" functionality requires src_urls as input, as it was only called by the WatcherSyncThread, who has the list of URLs that need syncing. This allows the watcher to be restarted with a different set of URLs. However, we are now also using the watcher in a context that does not have the list of URLs, so this PR adds a method that returns the highest synced block for all URLs present in the DB.
* Adds "get_highest_synced_block" and test
* Refactors duplicate code to helper method
Required for (FOG-130](https://mobilecoin.atlassian.net/browse/FOG-130) and (FOG-135](https://mobilecoin.atlassian.net/browse/FOG-135)

Watcher: Highest synced based on urls in DB

---

consensus/scp/src/msg.rs
consensus/scp/src/predicates.rs
consensus/scp/src/quorum_set.rs
consensus/scp/src/slot.rs
consensus/scp/tests/mock_network/mod.rs
ledger/sync/src/ledger_sync_service.rs
ledger/sync/src/network_state_trait.rs
ledger/sync/src/polling_network_state.rs
ledger/sync/src/scp_network_state.rs

Soundtrack of this PR: [LSO](https://soundcloud.com/lazysyruporchestra/take-the-long-way-home-remix)
The collections provided in `mc_common` were selected for use in the enclave. We've fallen into a habit of using them in places where the `std::collections` would be fine.
* change scp and ledger/sync to use std's HashSet and HashMap

prefer std::{HashSet, HashMap} to mc_common

---

ledger/db/src/ledger_trait.rs
ledger/db/src/lib.rs
ledger/db/src/metadata.rs
ledger/db/src/test_utils/mock_ledger.rs

Soundtrack of this PR: [King Crimson - Red](https://open.spotify.com/album/13dGZzRzFoejmyVXAbTPAH?si=kIdv2XtaSPm93OCCfRSQ7g)
We'd like to be able to tell which block a certain TxOut belongs to, mainly for having access to signature and timestamp data. Currently, there is no way to do that.
* Add a new database to `LedgerDB` that keeps a mapping of TxOut global index -> Block number.
* Add code to migrate existing LedgerDBs, so that they can be continued to be used without having to recreate them.

Block num by tx out index

---

consensus/enclave/trusted/.cargo/config

This adds the consensus enclave cargo config file to turn on lvi load hardening.
* Copy the top-level cargo config to the enclave to enable LVI load hardening via compiler flags.
* Updating other repositories to do the same.

MC-1626 Add cargo config to trusted enclave for options

---

mobilecoind-json/src/main.rs

Soundtrack of this PR: [Be Kind](https://www.youtube.com/watch?v=ePao0cTGG-o&list=PLDIoUOhQQPlU2NpvlGKTsQRoCMHTUCLMf)
WIP: Documentation should be updated to explain this functionality
The JSON API is a simple wrapper for the mobilecoind API. We recently added receiver receipt confirmation number to mobilecoind, this exposes it in the JSON wrapper.
* /transfer returns a set of receiver receipts with confirmation numbers
* an additional endpoint that checks receipts for individual TxOuts

Adds receiver receipts and confirmation number checking to JSON API

---

mobilecoind/clients/python/mob_client/mob_client.py

Soundtrack of this PR: [Trust in me](https://www.youtube.com/watch?v=fZY8jUuEzJQ)
Some of our scripts need to check if mobilecoind is fully synchronized with the network
```
In [1]: from mob_client import mob_client                                                                                                 
In [2]: cli = mob_client("localhost:4444", False)                                                                                         
In [3]: cli.get_network_status()                                                                                                          
Out[3]: (2278, 2278, False)
```

Adds get_network_status() to mob_client.py

---

consensus/enclave/trusted/.cargo/config

Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=xwhBRJStz7w)
Additional work is needed to turn on LVI mitigations in the consensus enclave.
* Revert #270, consensus enclave cargo config, pending successful build cycle on an actual network.
* Make this stuff go.

MC-1626 Remove trusted enclave cargo config

---

ledger/db/src/error.rs

A ticket (MC-1649) was submitted for the following error:
`2020-07-08 17:11:08.542491691 UTC ERRO lmdb error: Other(2) , mc.app: mobilecoind, mc.module: mc_ledger_db::error, mc.src: ledger/db/src/error.rs:62`
However, this isn't actually a problem - it happens when the database doesn't exist which is a legitimate case that is properly handled by the application that printed this log message. There's no need for it, and it can be surfaced to the user as part of standardized error handling. We don't globally log error messages in other places and there's no need for this to exist here either.
* Removal of the confusing log message.

remove confusing log message

---

util/generate-sample-ledger/README.md

The instructions here are not quite right.
Firstly, the `--num` parameter no longer exists, and seems to have a reasonable default, so I removed it.
Secondly, the `ledger` directory _does_ exist, so `mkdir ledger` will fail. It seems like something is a bit wonky here because `ledger` contains source code, and the end result of following these instructions is to create a database in that directory. I'm not sure how to reconcile that, so I just updated the instructions to reflect what happens.
Make instructions reflect current master.
None.

Fix instructions for generate-sample-ledger

---

consensus/service/src/consensus_service.rs
consensus/service/src/counters.rs

We'd like to know the age of the SGX attestation report. This has been requested by one of our partners.
* A new Prometheus gauge that reports the timestamp of the report.
* Periodic refreshing of the report.

Add SGX report timestamp metric to consensus service

---

.cargo/config
Cargo.lock
consensus/enclave/api/src/lib.rs
consensus/enclave/impl/Cargo.toml
consensus/enclave/impl/build.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/measurement/build.rs
consensus/enclave/mock/src/lib.rs
consensus/enclave/src/lib.rs
consensus/enclave/trusted/.cargo/config
consensus/enclave/trusted/Cargo.lock
consensus/service/src/bin/main.rs
util/build/enclave/src/lib.rs
util/build/script/src/cargo_build.rs
util/build/script/src/env.rs
util/build/sgx/src/edger8r.rs

Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=n4RjJKxsamQ)
With #270, the LVI mitigations were never deployed, and failed to build in release mode. This fixes those issues and runs with LVI hardening enabled, at noticeable (-25%) reduction in tx/s.
* Bakes the compile-time features into a string array in the enclave impl, and outputs them as a `Vec<String>` via `enclave_init()`, and logs them.
* Adds the necessary hardening features to the enclave builder.
* Adds warnings and CPU selection to the measurement builder.
* Adds a "-vv" logging to the cargo invocation (this will be hidden if "-vv" is not also provided at the top-level)

MC-1626 Log target features of enclave, enable LVI mitigations for enclave builds #in-review

---

util/b58-payloads/src/payloads.rs

* Fixes minor typo in `RequestPayload` doc comment

Fix typo in RequestPayload comment

---

tools/local-network/local_network.py

While attempting to fix some internal tools I tried using the watcher database too early. It takes mobilecoind a few seconds to get to the point it creates it. Since this logic is likely to repeat itself, I figured the correct place for waiting for it is right after it's started.
* A loop that waits until the watcher db has been created on disk.

wait for mobilecoind to start

---

consensus/api/proto/consensus_common.proto
consensus/api/src/conversions.rs
transaction/core/src/validation/error.rs
transaction/core/src/validation/validate.rs
transaction/std/src/input_credentials.rs
transaction/std/src/transaction_builder.rs

Soundtrack of this PR: https://soundcloud.com/yaron-sobel/set-425
Enforcing transaction inputs to be sorted  prevents the ordering of inputs within a transaction from leaking information, for example, if a client always adds larger-valued inputs before smaller-valued inputs.
This fixes MC-1472 and MC-1473.
* `TransactionBuilder` changed to sort inputs when constructing the `Tx`.
* Enclave validation code changed to enforce this new requirement.

Sorted tx inputs

---

crypto/sig/src/lib.rs

libmobilecoin is using this constant from schnorrkel directly, i would like to export it through mc-crypto-sig interface instead

Export a needed constant from mc-crypto-sig

---

api/src/conversions.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/database.rs
mobilecoind/src/error.rs
mobilecoind/src/lib.rs
mobilecoind/src/processed_block_store.rs
mobilecoind/src/service.rs
mobilecoind/src/subaddress_store.rs
watcher/src/watcher_db.rs

To ease potential integrations the need for an API that exposes view-scanned transactions on a per-block was brought up. This PR adds an API endpoint and associated plumbing to `mobilecoind` to support that.
* A new `GetProcessedBlock` API endpoint for `mobilecoind` and the associated `ProcessedBlockStore` that stores the backing data.
* Add this to `mobilecoind-json`.

Mobilecoind processed block

---

Cargo.lock
mobilecoind-json/Cargo.toml
mobilecoind-json/src/main.rs

* `mobilecoind-json` exposes a bunch of the `mobilecoind` API as a JSON API over HTTP. #300 added a new and useful API call that we'd like to expose as well.
* The new `/processed-block/` endpoint.
* Cleanup of `mobilecoind-json` dependencies so that it could be built without caring about an enclave (since there's no need for it to care).

add processed block endpoint to mobilecoind-json

---

mobilecoind-json/src/main.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/database.rs
mobilecoind/src/processed_block_store.rs
mobilecoind/src/service.rs
mobilecoind/src/utxo_store.rs

We received a request to have mobilecoind support reporting of both the received transactions per block (which it already did) as well as ones that were successfully spent. This PR addresses that request.
* Adding a new `direction` field to `ProcessedTxOut`, indicating whether a given entry has been received at the queried block or confirmed spent (via key image matching).
* Update the `mobilecoind-json` utility to support the new API.

mobilecoind ProcessedTxOut direction field

---

.circleci/config.yml
.gitignore
Brewfile

The TestNet-client is built for macOS as part of the release process. This means it should be under test to avoid unintentional regressions.
* Adds a CircleCI job to build the project on macOS
fixes #MC-1557

[MC-1557] Add building on macOS to CI

---

mobilecoind/src/bin/main.rs
watcher/src/bin/main.rs
watcher/src/error.rs
watcher/src/watcher.rs
watcher/src/watcher_db.rs

* The functionality of the watcher db is tightly coupled with the list of URLs being polled by a given `mobilecoind` instance (or standalone `watcher` instance). Code that reads data from the watcher database needs to be aware which URLs are being polled, so that it can only take data from them into account. This is particularly important for some timestamp code such as the work done in #304 
* Add a configuration database to `WatcherDB` that stores the list of "active" URLs. This is updated when the watcher database is opened.
* The watcher database can now be opened either in read-only mode (used by processes needed read-only access to watched data), or in read-write mode (when it is used to update the data, such as from `mobilecoind`). When opened in rw mode, the list of URLs is passed …

Watcherdb configured URL storage

---

Cargo.lock
account-keys/src/account_keys.rs
account-keys/src/identity.rs
consensus/enclave/trusted/Cargo.lock
crypto/keys/src/ristretto.rs
transaction/core/Cargo.toml
transaction/core/src/ring_signature/curve_scalar.rs
transaction/core/src/ring_signature/mlsag.rs
transaction/std/Cargo.toml
transaction/std/src/input_credentials.rs

* In order to reduce the risk of potential secrets leakage, it is a good idea to zero the memory they are stored in when they are no longer needed.
* Changes to signature generation code, transaction builder, account identity and root entropy that result in the sensitive parts being automatically zeroed when they go out of scope.

Zeroize some select secrets

---

Cargo.lock
mobilecoind-json/Cargo.toml
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind-json/src/lib.rs

Soundtrack of this PR: [Playing with a new toy](https://soundcloud.com/eranrund/quarantine-6)
We're going to be building a bridge/mirror thing that forwards some data from mobilecoind into an external host, similar to what https://github.com/BeamMW/Beam-Mirror-Wallet/ does. Since this new piece of software will expose a JSON API, we'd like to reuse the same JSON data types that are used in `mobilecoind-json`. The PR makes that possible.
* Splitting `mobilecoind-json` into a library and a binary.
* Adding a bunch of `From` impls to convert from protobuf-generated structs to the JSON-serializable ones.
* Impl `TryFrom`s to convert from the JSON-deserialiazable structs to the protobuf-generated structs. This requires a bit more effort due to the possibility of failures to parse the received …

Make mobilecoind-json data types reusable

---

consensus/scp/play/src/main.rs
consensus/scp/src/node.rs
consensus/scp/src/scp_log.rs
consensus/scp/src/slot.rs
consensus/scp/tests/mock_network/mod.rs
consensus/service/src/byzantine_ledger.rs

Soundtrack of this PR: [Paid](https://www.youtube.com/watch?v=Df4vDfYxTRk)
Previously, Node and Slot both validated nominated values and filtered out stale or redundant incoming messages, which is confusing and maybe inefficient. This PR makes Slot primarily responsible for "doing the right thing" with proposed values and incoming messages.
This has been slam tested, and seems to have identical performance.

Remove redundant filtering and validation from Node

---

consensus/service/README.md

#288 correctly points out the example in the README is missing a required field in the `network.toml` example.
* Adding the missing field and fixing a typo

add missing tx_source_urls to consensus service README (fix #288)

---

watcher/src/watcher_db.rs

Soundtrack of this PR: [Working on a Dream](https://www.youtube.com/watch?v=R3ZMfPXgd_M)
u64::MAX is used as a sentinel value for key image results, and if passed to the watcher to get a timestamp, should be treated as OutOfBounds.
* Adds u64::MAX to IndexOutOfBounds evaluation.
* Adds case to test
[FOG-131](https://mobilecoin.atlassian.net/browse/FOG-131)

Watcher: u64::MAX is also OutOfBounds

---

tools/local-network/local_network.py

Changes to the `Watcher` reveal a little typo in the local network script that prevents mobilecoind from starting.
* Remove the unnecessary line.

remove unnecessary --tx-source-url

---

.circleci/config.yml

Homebrew recently shipped with a bug that causes a crash when running `brew bundle`. They've since fixed the bug, but the CircleCI macOS image currently comes pre-installed with the older version of Homebrew that includes the bug.
The issue can be seen here: https://app.circleci.com/pipelines/github/mobilecoinofficial/mobilecoin/1714/workflows/537a2357-c4ed-4428-a25b-7543ae89e322/jobs/3303/parallel-runs/0/steps/0-103
In order to get around this, this PR adds the command `brew update` so that Homebrew gets updated before running `brew bundle`.
This issue has more info: https://github.com/Homebrew/homebrew-bundle/issues/751
Note: the `--preinstall` flag is specified, since it is recommended in the issue to do so, as it is faster.
* Adds a command to update Homebrew in CI
* Eventually, once …

Update Homebrew in CI

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
consensus/scp/play/Cargo.toml
ledger/from-archive/Cargo.toml
mobilecoind-json/Cargo.toml
mobilecoind-mirror/Cargo.toml
util/repr-bytes/Cargo.toml

All of our crates' versions should be 0.5.0. That was not the case before this PR.
* Fixing some crates version to be 0.5.0

fix incorrect versions in a few crates

---

consensus/scp/src/lib.rs
consensus/scp/src/node.rs
consensus/scp/src/scp_log.rs
consensus/scp/src/slot.rs
consensus/scp/src/slot_state.rs
consensus/scp/viewer/.gitignore
consensus/scp/viewer/README.md
consensus/scp/viewer/requirements.txt
consensus/scp/viewer/templates/slot.html
consensus/scp/viewer/viewer.py

Soundtrack of this PR: https://www.youtube.com/watch?v=gVbQrn5BoA4
Yesterday during one of my attempts at running #247 locally the network stopped processing transactions, and ballot numbers were increasing without completing. At that point I believe it would've been useful for me to see the state of each scp `Slot` for all of the nodes to try and make sense as to why they are not moving to externalize a slot. This PR is an attempt at providing a solution for this debugging challenge.
* We already have code that writes each processed message a node goes through in a given slot to a file that can then be looked at. This PR adds a per-slot file that contains all the state inside a given `Slot`. Hopefully this would help with understanding network stalls in the future.
* In addition to the …

SCP Slot State debugging

---

api/proto/external.proto
transaction/core/src/amount.rs

(1) Using variable size fields in transaction data means that the
protobuf size reflects something about the numbers in the data,
or which transaction it is, even in encrypted form.
(2) This data is uniformly distributed 64 bit numbers, but the varint
encoding is optimized for small numbers, and is less efficient for
uniformly distributed u64's than the fixed64 encoding. It pays on the
representation size of the large u64's to make the small u64 values
have a shorter representation. But that isn't beneficial for this
data.

Used fixed64 in transaction amount

---

.circleci/config.yml
util/build/enclave/src/lib.rs

Cargo build caches build artifacts so that successive invocations won't rebuild the parts of the code that haven't changed. Currently our project is experiencing spurious rebuilds even when nothing has changed. This leads to slower development cycles.
On top of the spurious rebuilds, the build is also experience build non-determinism. Crate feature selection doesn't appear to be consistent across multiple successive builds under certain circumstances (e.g. when building more than a single package at a time). This is a problem because it means that we might be encountering bugs related to incorrect feature configuration. This also has the potential to mask bugs for the same reason.
This PR addresses several of the issues causing spurious rebuilds and build non-determinism:
* …

Build determinism in CI

---

.circleci/config.yml

CircleCI has a feature that allows a project to display test results in the Tests tab for a given CI run. We're reporting our test results, but not doing so in the way that CircleCI expects. This PR addresses that, as well as a number of edge cases that cause the tests to not be fully reported.
* Calls `store_test_results` with the directory containing the tests results, instead of the test result file itself. See https://support.circleci.com/hc/en-us/articles/360021624194-Test-summary-troubleshooting
* Ensures that test results get converted to junit format on test failure (the bash script that runs the tests is configured with `-e`, so curly brackets have been added to make sure the command for converting gets executed prior to bash exiting the script early)
* Version printing of …

Test reporting in CI

---

consensus/service/src/byzantine_ledger.rs
ledger/sync/src/ledger_sync_service.rs

We currently have two noisy log messages:
The first one happens once a minute as ByzantineLedger tries to perform catch up. If the network has been upgraded to a new version and a node wasn't, that node is going to stay behind indefinitely. Since the code will keep retrying once a minute, there's no reason for this to reach Sentry.
The second one is an intermittent failure when trying to fetch transactions from S3. Since the code that tries to fetches them retries fetching until it succeeds (or a timeout is exceeded), there's no need to treat these intermittent failures as errors. It's nice to know they happen, but they should not find their way to Sentry.
221336-f66f1e00-d587-11ea-8218-ecb96d91811c.png)
* Downgrading a noisy log messages from error to info and warning based on their …

downgrade noisy log message

---

api/proto/external.proto
transaction/core/src/amount.rs

This reverts commit ec42f1008f9aa45c3db85b2404369a4a5157cdd4.
This avoids a breaking ledger change which would be annoying to deal with right now

Revert "Used fixed64 in transaction amount (#333)"

---

Cargo.lock
util/keyfile/Cargo.toml
util/keyfile/src/bin/sample_keys_main.rs
util/keyfile/src/keygen.rs

Soundtrack of this PR: [Dark Trance Cello](https://www.youtube.com/watch?v=5FT5jodwq6U)
We added additional fog params to the Account Key, and this PR plumbs them into our CD tools.
* Updates mc-util-keyfile sample-keys to take fog params as configs and write keyfiles with this data.
[FOG-138](https://mobilecoin.atlassian.net/browse/FOG-138)

Add fog params to account key generation

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
crypto/digestible/Cargo.toml
crypto/keys/Cargo.toml
crypto/keys/src/ed25519.rs

This moves off of our patched ed25519-dalek
In developing this PR I learned the following things:
- `digest` trait is used as an API among an enormous number of our crates,
and mixing `digest 0.8` and `digest 0.9` generally breaks the build
- Many RustCrypto crates are already on `digest 0.9` but `curve25519-dalek` ecosystem is still on `digest 0.8`
- We will likely have to pin things to versions that use `digest 0.8` until `curve25519-dalek` uprevs their version of digest

fixup ed25519-dalek version

---

consensus/scp/src/scp_log.rs
consensus/service/src/byzantine_ledger.rs

#327 added a feature that logs the slot current slot state for each slot to a file. However, there was no limit on how many of these files could be written. This would eventually result in taking a significant amount of disk space on the nodes for no good reason. There's likely not going to be a need to look at old slot states for debugging purposes.
* Change the code that writes these state files to limit to the last 10 slots.

limit number of slot state files to prevent directory from growing indefinitely

---

Cargo.lock
consensus/service/Cargo.toml
consensus/service/src/counters.rs
ledger/db/Cargo.toml
ledger/db/src/lib.rs
ledger/db/src/metrics.rs
util/grpc/Cargo.toml
util/metered-channel/Cargo.toml
util/metrics/Cargo.toml
util/metrics/src/lib.rs

MC-1726 requested a Prometheus gauge for ledger db size. Currently, ledger-related metrics are managed by the users of LedgerDB that write to it (ByzantineLedger, LedgerSyncService) and the metrics are duplicated between the two:
https://github.com/mobilecoinofficial/mobilecoin/blob/c5746954ed453483069bbf63f80019da0145dec1/consensus/service/src/byzantine_ledger.rs#L761-L764
https://github.com/mobilecoinofficial/mobilecoin/blob/c5746954ed453483069bbf63f80019da0145dec1/ledger/sync/src/ledger_sync_service.rs#L316-L321
There is even a TODO item that refers to an old, non-existent ticket to unify them.
I took the opportunity of adding a new metric to address this duplication.
* New metrics built-in into LedgerDB. This is how they show up in Prometheus:
``` …
```

LedgerDB metrics rework

---

Cargo.lock
Cargo.toml
ledger/db/Cargo.toml
ledger/db/src/lib.rs
ledger/db/src/tx_out_store.rs
ledger/migration/Cargo.toml
ledger/migration/src/main.rs

We want to move away from automatic implicit migrations when opening LedgerDBs to an explicit step taken by an operator. This prevents having to deal with race conditions that could occur if two processes attempt to open the database at the exact same time. It also allows to keep all the migration-specific code in a centralized place, and not bloat LedgerDB with it.
* Moving the migration code out from `mc-ledger-db` into a new `mc-ledger-migration` tool.
* Integrate this into our build and k8 flow. I will reach out to @joekottke to plan this.

Move migrations code outside of mc-ledger-db into a dedicated mc-ledger-migration tool.

---

transaction/core/src/fog_hint.rs

Soundtrack of this PR: [Walk Like an Egyptian](https://www.youtube.com/watch?v=Cv6tuzHUuuk)
In order to make the ingest loop constant time, we need a constant time decrypt function for the fog hint.  We can't really do this now, due to limitations in the aes-gcm library (https://github.com/RustCrypto/AEADs/issues/184).  I have a PR against aes-gcm that will allow us to do so (https://github.com/RustCrypto/AEADs/pull/188), but there is no guarantee that it will be merged.  We may have to carry a fork of aes-gcm, but that can wait for the future.  This PR will allow us to move forwards, which is good enough for now.
* Adds a FogHint::ct_decrypt function, which returns a (FogHint, bool)
This will help make progress on FOG-96 and FOG-97.
* Use this code in the ingest enclave impl
* Make a …

Add a basic constant time FogHint::ct_decrypt function

---

ledger/sync/src/ledger_sync_service_thread.rs

As we've grown the testnet initial download times have increased to about 30 mins. This reduces them to close to 10 mins. I attempted larger sizes but found the testnet client would take longer to start up and was subjectively a worse experience. 
* Increase MAX_BLOCKS_PER_SYNC_ITERATION to 100
* Possibly make this a parameter or do more performance tuning

Increases the S3 block sync size to increase performance

---

ledger/migration/src/main.rs

Our logger logs messages asynchronously. Annoyingly, there is no way to delay program termination until all log messages have ben processed. This PR adds the standard practice hack we have for dealing with this.
* Add a magic sleep

Give logger a second to flush any pending messages.

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

`serde_cbor` currently uses serde in such a way that it fails to compile if the `serde_cbor/std` feature is not enabled but `serde/std` is. The error is:
```
error[E0277]: the trait bound `error::Error: std::error::Error` is not satisfied
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_cbor-0.11.1/src/de.rs:781:18
|
781 |     type Error = Error;
|                  ^^^^^ the trait `std::error::Error` is not implemented for `error::Error`
```
This issue has been fixed in https://github.com/pyfisch/cbor/pull/198, but the maintainer of serde_cbor is no longer merging PRs (see https://github.com/pyfisch/cbor/issues/179#issuecomment-654071549).
A fork has been created that fixes https://github.com/pyfisch/cbor/pull/198, located here: …

[MC-1766] Use mobilecoinofficial/serde_cbor fork

---

Cargo.lock
consensus/enclave/api/src/lib.rs
consensus/service/Cargo.toml
consensus/service/src/byzantine_ledger.rs
consensus/service/src/client_api_service.rs
consensus/service/src/consensus_service.rs
consensus/service/src/peer_api_service.rs
consensus/service/src/tx_manager.rs
consensus/service/src/validators.rs

Several layers of the consensus service contain complex dependencies that make them difficult to test. It is also difficult to create test inputs that exercise particular code paths, because the inputs must be compatible with those complex dependencies. It would be nice if some of those dependencies could be mocked...
This PR focuses on TxManager and using mocks for testing:
* Creates a TxManager trait and updates things that use TxManager to use Box\<TxManager\>,
* Uses `mockall` to make TxManager easily mockable,
* Mocks the ConsensusEnclave trait,
* Adds unit tests for TxManagerImpl, which involve mocking TxManagerImpl's dependencies
* Use MockTxManager when testing things like ByzantineLedger.
* Use mockall's `auotmock` to create mocks in other places, instead of manually defining …

TxManager traits, mocks, and tests

---

Cargo.lock
consensus/scp/Cargo.toml
consensus/scp/src/slot.rs

* Uses the `hashset!` and `btreeset!` macros from the `maplit` crate to replace a number of clumsy declarations like `BTreeSet::from_iter(vec![x, y, z])` with the more concise `btreeset!{ x, y, z}`.

Slot uses hashset! btreeset! macros

---

Cargo.lock
Cargo.toml
common/Cargo.toml
common/README.md
common/src/lib.rs
common/src/logger/mod.rs
consensus/enclave/Cargo.toml
consensus/enclave/impl/src/lib.rs
consensus/enclave/src/lib.rs
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml
consensus/enclave/trusted/src/lib.rs
consensus/service/Cargo.toml
sgx/slog/Cargo.toml
sgx/slog/build.rs
sgx/slog/src/common.rs
sgx/slog/src/lib.rs
sgx/slog/src/trusted.rs
sgx/urts/Cargo.toml
sgx/urts/src/eprintln.rs
sgx/urts/src/lib.rs
sgx/urts/src/panic.rs
sgx/urts/src/slog.rs

When we planned out the way that we build enclaves, one of the main
questions was "how do we unit test the mission critical code that
lives in enclaves". We split this logic into `_impl` crates that
can compile as std, without having any sgx-only bits inside them.
Currently, none of these crates support logging, because the
`mc-common::logger` module is std-only. We built an `mc-sgx-slog`
interface which sends slog structures logs over an OCALL to untrusted
to be logged on the global logger. But because this code was
enclave-specific, there was no way to actually use this in the
enclave/impl crates without breaking the tests. And so `mc-sgx-slog`
has been basically unused. None of the `_impl` crates use it, and none
of the tests even use the `[test_with_logger]` functionality, because …

Make slog actually work inside of sgx enclave/impl crates

---

Cargo.lock
consensus/scp/Cargo.toml
consensus/scp/src/core_types.rs
consensus/scp/src/node.rs
consensus/scp/src/scp_log.rs
consensus/scp/src/slot.rs

Currently, it has been difficult to test Node because some of its behavior requires carefully-constructed SCP messages which it passes to Slot. It would be easier to test if Slot could be mocked.
* Creates a Slot trait, and uses automock to generate mocks for testing.
* Adds some simple unit tests to Node that show mocking in action.
This PR leaves several parts of Node untested because those parts are likely to change soon.

Trait and Mock for Slot

---

sgx/urts/src/backtrace/mod.rs
sgx/urts/src/eprintln.rs
sgx/urts/src/panic.rs
sgx/urts/src/slog.rs

This follows up on review comments from: https://github.com/mobilecoinofficial/mobilecoin/pull/358

fixup `unsafe` status of extern "C" function signatures in sgx-urts

---

ops/Dockerfile-consensus
ops/entrypoints/consensus_validator.sh

Soundtrack of this PR: [Revelate](https://www.youtube.com/watch?v=jCyFMnhP_94)
The current Dockerfile and entrypoint for the consensus validator does not include the `mc-ledger-migration` tool to handle automatic ledger upgrades on startup.  This fixes that.
* Add `mc-ledger-migration` to the Dockerfile and in the `consensus_validator.sh` entrypoint script.

Add ledger-migration to entrypoint and Dockerfile

---

consensus/service/src/byzantine_ledger/mod.rs
consensus/service/src/byzantine_ledger/worker.rs
consensus/service/src/client_api_service.rs
consensus/service/src/consensus_service.rs
consensus/service/src/peer_api_service.rs
consensus/service/src/tx_manager.rs

Soundtrack of this PR: [Tycho](https://www.youtube.com/watch?v=dKh1yvmZpgU)
Components are easier to test if they have fewer sub-components. Previously, TxManager held a Ledger instance, but only used it in one place to query for the previous block.
* Removes the Ledger instance from TxManager
* TxManager::tx_hashes_to_block now takes a `parent_block` instead of querying the ledger for it.
* This is incremental progress towards simplifying and testing TxManager and the things that use TxManager.

Remove Ledger from TxManager

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
crypto/message-cipher/Cargo.toml
crypto/noise/Cargo.toml
util/repr-bytes/Cargo.toml

The build is breaking on CI sporadically and it might have something to do with repr-bytes depending on a different version of generic-array then the rest of the project.
* Change generic-array deps to all be 0.12
* Remove unnecessary default-features = fasle
* Upgrade all of the things so we could use generic-array 0.14.

downgrade generic-array to 0.12

---

account-keys/Cargo.toml
consensus/scp/Cargo.toml
crypto/keys/Cargo.toml
mobilecoind/Cargo.toml
transaction/core/Cargo.toml

This fixes a compilation error that occurs as a result of the `mc-crypto-keys`, `mc-account-keys`, `mc-consensus-scp`, `mc-mobilecoind`, and `mc-transaction-core` crates using the `Digestible` derive proc-macro without enabling `mc-crypto-digestible/derive`.
This issue is masked by cargo feature unification, such that this feature is sometimes enabled and sometimes not, depending on what other crates are being included (and what build configuration is being built) for a particular cargo invocation.
An example of this compilation error ([from this CI build](https://app.circleci.com/pipelines/github/mobilecoinofficial/mobilecoin/1901/workflows/f504d01a-e159-44aa-b449-2543f1a89bfc/jobs/3839/parallel-runs/0/steps/0-110)):
```
error[E0599]: no method named `digest` found for struct …
```

Enable mc-crypto-digestible/derive when using Digestible derive

---

ledger/sync/src/reqwest_transactions_fetcher.rs
mobilecoind/README.md
mobilecoind/src/bin/main.rs
mobilecoind/src/config.rs
mobilecoind/src/error.rs
mobilecoind/src/payments.rs

We'd like to support construction of transactions on an airgapped machine, in case someone wants to take that extra measure of protecting their sensitive keys.
* Changes to allow `mobilecoind` to run in "offline mode". In offline mode, `mobilecoind` does not attempt to sync the ledger or communicate with any peers. When the `--offline` command line argument is passed, `mobilecoind` would allow omitting the `--peer` and `--tx-source-url` arguments.
If someone wants to construct a transaction on a machine that does not have internet access, they would need to perform the following steps:
1) Copy a recent copy of the ledger database into the airgapped machine. The copied ledger should include TxOuts that are spendable by the user.
2) Run `mobilecoind` on the airgapped machine: `MC_LOG=trace …

Mobilecoind offline transactions

---

.cargo/config
consensus/enclave/measurement/build.rs
util/build/enclave/src/lib.rs

SHA2 instructions are not available on the platforms we currently have Kubernetes running, and there's no way to remove that other than by hard-code changes. This removes most of the hard-coding (it does keep LVI mitigations), and simply copies target features enabled for the untrusted build into the enclave build.
* Remove SHA target feature where it exists (not supported on our platform yet)
* Copy target features from untrusted into enclave build's RUSTFLAGS.
* Remove explicit skylake from individual enclave build.

MC-1814 Enclave target features inheritance. #in-review

---

consensus/api/proto/consensus_peer.proto
consensus/service/src/peer_api_service.rs
consensus/service/src/tx_manager.rs
peers/src/connection.rs
peers/src/error.rs

@mfaulk and me discovered a bug in which a node would repeatedly try to resolve missing tx hashes from a peer, even if the peer does not have them in its cache. Each attempt takes about 15 seconds due to unnecessary retries, and this happens for each SCP message that refers to the missing hashes.
A scenario in which hashes would be missing is if a peer restarted mid-slot. The local node would have a bunch of queued up SCP messages from before the peer restarted, and when it gets to processing them it will repeatedly attempt to `FetchTxs` from this peer, even though it will never succeed. This effectively results in the node falling back for a long duration of time.
Ideally, the code that fetches txs should be able to learn which hashes are futile and stop trying them, ignoring the SCP …

Detailed missing tx hashes error

---

transaction/core/src/membership_proofs/mod.rs
transaction/core/src/range.rs
transaction/core/src/validation/validate.rs

Soundtrack of this PR: [Numbers](https://www.youtube.com/watch?v=4YPiCeLwh5o)
Merkle proofs use a Range data structure to define a range [a,b] of indices, where the length or the range is b - a + 1. If a > b, this can cause a subtraction underflow.
* Changes Range's `len` and `ord` to allow ranges [a,b] where a > b.
* Adds checks in validation that reject a Merkle proof if it contains a range [a,b] where a > b.

[MC-1784] Subtraction underflow in Range::len

---

api/proto/external.proto
transaction/core/src/amount.rs

This is needed in some backend services, because serialized TxOut
objects will then have a fixed size, and so we won't leak anything
about them through the size of the buffer representing them.
This is a replay of mobilecoin #333, which was reverted in #336
due to concerns that it would break testnet compatibility unless
we made a way to migrate the ledger. The idea we had was that
we would do it right before launch once we were no longer making
testnet releases.

Redo change to make Amount proto object have a fixed size

---

mobilecoind/src/service.rs

We'd like clients to be able to enter either a payment request code or a public address. This PR interprets either case and determines the best thing to do.
* Allows `read_request_code` to take a plain public address, which is interpreted as a payment request with no amount and no memo

Interpret public addresses as request codes

---

consensus/service/src/byzantine_ledger/mod.rs
consensus/service/src/byzantine_ledger/worker.rs
consensus/service/src/client_api_service.rs
consensus/service/src/consensus_service.rs
consensus/service/src/peer_api_service.rs
consensus/service/src/tx_manager/mod.rs
consensus/service/src/tx_manager/tx_manager_trait.rs
peers/Cargo.toml
peers/src/broadcast.rs
peers/src/lib.rs

Soundtrack of this PR: [Royals](https://www.youtube.com/watch?v=nlcIKh6sBtc)
ByzantineLedger currently has a single, large unit test that traces the "happy path" of a node reaching consensus on a single slot. We don't yet have unit test coverage for failure modes, catch-up, or broadcast.
* ByzantineLedger depend on the TxManager trait, instead of a concrete implementation. This will help with testing failure modes.
* Creates a simple unit test that uses the autogenerated mock for TxManager. This is mostly a proof-of-concept that sets up the pattern for further tests.
* Extracts some common setup code that will probably get reused in multiple unit tests.
* https://mobilecoin.atlassian.net/browse/MCC-480
* https://mobilecoin.atlassian.net/browse/MCC-486
* …

[MCC-1694] ByzantineLedger uses TxManager trait

---

Cargo.lock
consensus/service/src/byzantine_ledger/mod.rs
consensus/service/src/byzantine_ledger/worker.rs
ledger/db/Cargo.toml
ledger/db/src/ledger_trait.rs
ledger/db/src/lib.rs
ledger/db/src/test_utils/mock_ledger.rs
ledger/from-archive/src/main.rs
ledger/sync/src/ledger_sync_service_thread.rs

The Ledger trait / LedgerDB are used by a lot of things, which makes those things tedious to test.
* A few tweaks to the Ledger trait so that it is compatible with automock.
* Use MockLedger in unit tests.

[MCC-1700] Mocks Ledger trait

---

consensus/service/src/validators.rs
ledger/db/src/lib.rs
ledger/db/src/test_utils/mock_ledger.rs
mobilecoind/src/payments.rs
mobilecoind/src/test_utils.rs
transaction/core/src/blockchain/block.rs
transaction/core/src/tx.rs
transaction/core/test-utils/src/lib.rs
transaction/std/src/transaction_builder.rs
util/generate-sample-ledger/src/lib.rs

* Removes unused `_rng` argument in TxOut::new

[MCC-1701] Removes unused `_rng` from TxOut::new

---

consensus/service/src/byzantine_ledger/worker.rs
peers/src/connection.rs
peers/src/error.rs

@mfaulk and me discovered a bug in which a node would repeatedly try to resolve missing tx hashes from a peer, even if the peer does not have them in its cache. Each attempt takes about 15 seconds due to unnecessary retries, and this happens for each SCP message that refers to the missing hashes.
For example, a potential scenario in which hashes would be missing is if a peer restarted mid-slot. The local node would have a bunch of queued up SCP messages from before the peer restarted, and when it gets to processing them it will repeatedly attempt to FetchTxs from this peer, even though it will never succeed. This effectively results in the node falling back for a long duration of time.
* A small change that prevents nodes from retrying to fetch txs that have been reported as unavailable …

Dont keep trying to fetch unavailable transactions

---

consensus/service/src/consensus_service.rs

Fix bug which encounters overflow if peer block height is behind current block height when calculating "blocks behind."
* Fixes bug described above
[MCC-1705](https://mobilecoin.atlassian.net/browse/MCC-1705)

MCC-1705: Fix subtraction overflow for blocks behind

---

Cargo.lock
attest/ake/Cargo.toml
attest/ake/src/initiator.rs
attest/ake/src/responder.rs
consensus/enclave/trusted/Cargo.lock

The last remaining use of serde in our external wire formats is the IAS reports transmitted as Noise payloads during key exchange.
* Change the encoding of the `VerificationReport` structure to use the derived `prost::Message`.
* Replacing untrusted-to-enclave use of serde with protobuf.

MCC-1702 Protobuf serialization of IAS reports used in kex

---

api/proto/external.proto
api/src/conversions.rs
consensus/enclave/impl/src/lib.rs
ledger/db/src/tx_out_store.rs
mobilecoind/src/conversions.rs
transaction/core/src/encrypted_fog_hint.rs
transaction/core/src/fog_hint.rs
transaction/core/src/tx.rs

Previously it was 128 bytes, because it needed to accomodate two
elliptic curve points in the payload in very early drafts.
In this commit we reduce it to 90 bytes, with explanation:
- 50 bytes for mc-crypto-box header
- 32 bytes for curve point
- 8 bytes of magic / extra padding for future use, filled with
magic number for now
This is a breaking change for the clients, but it doesn't break the software API I think, they will just have to recompile the SDK to get the new size constant

MCC-613 Reduce encrypted fog hint size to what is actually needed

---

crypto/box/src/fixed_buffer.rs
crypto/box/src/hkdf_blake2b_aes_128_gcm.rs
crypto/box/src/versioned.rs

There were four pieces of feedback:
(1) There was a subtle cryptogram malleability issue, where a
cryptogram could be modified to produce a new cryptogram which
would decrypt to the same message, but for a different private key.
It would be very difficult to exploit this without knowing the
private key that the original message targetted, but it is not very
hard to prevent this source of malleability.
(2) Use hkdf-expand step, not only the hkdf-extract step.
(3) Fix a possible numeric overflow in fixed-buffer
(4) Allow more flexibility in version negotiation than just "pick max version that is agreeable to both".
This commit addresses the first 3 issues, doesn't do anything with
version negotation, which we aren't really doing right now, the client
just always uses the latest version. …

MCC 692: Address NCC group cryptobox comments

---

consensus/enclave/impl/src/lib.rs
ledger/db/src/tx_out_store.rs
mobilecoind/src/sync.rs
transaction/core/src/lib.rs
transaction/core/src/onetime_keys.rs
transaction/core/src/ring_signature/key_image.rs
transaction/core/src/ring_signature/mlsag.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/tx.rs
transaction/std/src/transaction_builder.rs

Soundtrack of this PR: [Raio](https://www.youtube.com/watch?v=i3Z4isDQaiw)
onetime_keys.rs defines several functions used by a sender to create a transaction output, and used by the receiver to determine that they own the output and spend it. The code here has gone through a few a few stages, and so some names and doc comments are out of date or inconsistent. It is also thin on unit tests.
* Adds a module-level doc comment explaining how account keys, subaddresses, and output public keys are related.
* Removes an unused function.
* Moves a function that is not used when working with onetime keys.
* Lots of tweaks for clarity, brevity, and consistency.
* Adds unit tests
* Use proptest to increase testing coverage.

[MCC-695] Unit tests for onetime_keys

---

ledger/sync/src/test_app/main.rs
mobilecoind/src/bin/main.rs

mobilecoind is currently unable to verify a remote enclave, this logs a debug print of the verifier being used in the connection.
* Do a `log::debug!()` of the verifier being used.

MCC-1727 Log the verifier used when connecting to an enclave.

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

In order to spend a Transfer/Gift Code, we need to construct a `UnspentTxOut` for the referenced `tx_public_key` in the code.
* Adds a new `utxo` return field to the response `ReadTransferCodeResponse`
* wire this up to the terminal wallet client

add utxo to ReadTransferCodeResponse so Gift Codes can be spent

---

ledger/sync/src/test_app/main.rs
mobilecoind/src/bin/main.rs

Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=DuQ4WSF6MkQ)
This should fix issues with mobilecoind connecting to the consensus service
* Mark INTEL-SA-0034 as a hardening advisory, not a config advisory.

MCC-1726 - INTEL-SA-00334 is a hardening advisory, not a config advisory.

---

Cargo.lock
api/src/conversions.rs
consensus/enclave/impl/Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/service/src/validators.rs
ledger/db/src/tx_out_store.rs
transaction/core/Cargo.toml
transaction/core/src/membership_proofs/errors.rs
transaction/core/src/membership_proofs/mod.rs
transaction/core/src/range.rs
transaction/core/src/tx.rs
transaction/core/src/validation/validate.rs

The previous merkle proof has the following structure:
- index (indicates which number leaf this TxOut is in the merkle tree)
- highest_index (indicates how many TxOuts are in the merkle tree at time of proof)
- several TxOutMembershipElements, which include a hash corresponding to
an internal node in the tree, and a range explaining which leafs
are covered by this hash
The previous merkle proof validation routine assumes no particular structure
on the membership elements, it sorts them, throws them into hash maps,
etc. and as a result it is complicated and leaks information about the
path that the merkle proof is following over side channels. Because the
path determines the entire merkle proof, this means that we leak the
whole thing, in the SGX security model.
This PR does the …

MCC-959 side-channel resistant merkle proof validation

---

Cargo.lock
consensus/api/Cargo.toml
consensus/service/Cargo.toml
consensus/service/src/attested_api_service.rs
consensus/service/src/bin/main.rs
consensus/service/src/client_api_service.rs
consensus/service/src/consensus_service.rs
consensus/service/src/peer_api_service.rs
consensus/service/src/tx_manager/mod.rs
consensus/service/src/tx_manager/tx_manager_trait.rs
peers/src/connection.rs

We do not currently have unit test coverage for the consensus node's gRPC APIs, but we should. This service also relies on TxManager::insert to perform spent key image checks, which is incorrect and is blocking us from fixing TxManager.
* Replaces several uses of ConsensusEnclaveProxy (which can't be mocked) with ConsensusEnclave (which can).
* Checks for spent key images. Previously, this relied on TxManager::insert, which confused things because it mixed key image checking in with the is_well_formed check.
* Adds unit tests

[MCC-487] Unit test ClientApiService's gRPC endpoint

---

consensus/service/Cargo.toml
mobilecoind/Cargo.toml
transaction/core/src/constants.rs
util/keyfile/Cargo.toml
util/keyfile/src/bin/read_pubfile.rs

Add BetaNet Fee Account.
* Adds BetaNet fee pubkeys.
* Adds a super simple utility to read pubfile contents and print out bytes.
First part of [MCC-1733](https://mobilecoin.atlassian.net/browse/MCC-1733)
* Update to MainNet Fee Public Keys.

BetaNet fee account

---

admin-http-gateway/Cargo.toml
consensus/service/src/consensus_service.rs

The block signature may be empty when a node is behind, or if the node is configured as read-only (it is not trusted by any other quorum sets). The current info endpoint errors if this is the case, but that is not an error to be concerned about. I also took this opportunity to fix up the last_block_timestamp to be empty string if not found, rather than json null, and to make the format of the message signer pubkey something meaningful, rather than a bytevec.
* Processes the error and permits NotFound
* Updates last_block_timestamp to empty string
* URL-safe base64-encodes the message signer pubkey, to match the representation in the network.toml
* Fixes hex representation of last block hash
[MCC-1741](https://mobilecoin.atlassian.net/browse/MCC-1741) …

Info Endpoint Updates

---

attest/net/src/ias.rs
sgx/report-cache/untrusted/src/lib.rs

Currently the log level for IAS reports is trace, but we would like more visibility into the attestation evidence on startup.
* Adds info log for MrEnclave and MrSigner as hex strings
* Add debug log for IAS report
[MCC-1717](https://mobilecoin.atlassian.net/browse/MCC-1717)
* [FOG-180](https://mobilecoin.atlassian.net/browse/FOG-180) Reduce report caching frequency on Ingest. This will follow soon after, as this will flood the logs with info level logs for ingest on every cache update.

Elevate log

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

Address Codes are Payment Request codes that do not have an attached amount or memo (or implicitly, a zero amount and an empty memo). Rather than doom ourselves to explaining this thousands of times, we may as well add extra API to match user expectations.
The b58 string returned in the `GetAddressCodeResponse` message should match the preferred export for a "Public Address" within the mobile SDKs.
* Introduces "Address Code" to mobilecoind
* add mob-url construction and export to mobilecoind

b58 style Address Codes

---

consensus/service/src/tx_manager/mod.rs
consensus/service/src/tx_manager/untrusted_interfaces.rs
consensus/service/src/validators.rs

Some parts of transaction validation depend on the current ledger state (e.g. "has this key image been spent?"), while others don't (e.g. "is the transaction signature valid?"). In order to keep transaction validation efficient, we separate the two classes of checks, and only perform the checks that don't depend on the current ledger state once. For example, this means that if a transaction arrives circa block 7, and is considered by consensus for blocks 7, 8, and 9, that things like spent key images are re-checked for each block, but things like the transaction signature are only checked once.
We call a transaction "well-formed" if it passes all the checks that only need to be done once when the transaction is received. A transaction that passes these checks at one point in time must …

[MCC-1716] UntrustedInterfaces::is_well_formed

---

mobilecoind/clients/python/mob_client/mob_client.py

We added new public addresses endpoints to mobilecoind, this just adds them to the python wrapper 
* Adds `read_address_code` and `get_address_code` to `mob_client.py`

Adds new public address endpoints to Python client

---

consensus/service/src/tx_manager/mod.rs

Soundtrack of this PR: [Be Together](https://www.youtube.com/watch?v=GZSsOEqgm0c)
TxManager should maintain a cache of well-formed transactions. Previously, it also checked for validity (which is funky and unnecessary) because other things incorrectly required the transactions in its cache to be valid.
* Removes is_valid check when reinserting a transaction into the cache.

[MCC-1693] Removes is_valid check when reinserting 

---

mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs

Exposes the existing gRPC endpoint for removing a monitor in our JSON api.

add remove_monitor to mobilecoind-json [MCC-1736]

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

Exchanges want to match incoming deposits to user accounts by associating each user's account with a unique subaddress. 
Subaddresses could be matched based on index or based on the unique PublicAddress that each index creates. Since it is not possible to calculate the PublicAddress for a subaddress index without private keys, we want to include this information in our decrypted "ProcessedTxOut" message. This allows an exchange to match incoming deposits based on an association between users and deposit Address Codes rather than a map to subaddress indices.
* add field to proto, connect in service and add test

add Address Code to ProcessedTxOut [MCC-1755]

---

mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs

We recently introduced an explicit concept for an Address Code to avoid confusion over the meaning of a Payment Request with zero value and no memo. This PR connects `mobilecoind-json` to the gRPC endpoints.
* adds two new API endpoints
* cleans up some names to better match mobilecoind protobuf
* update API semantics for codes to create/parse [MCC-1760](https://mobilecoin.atlassian.net/browse/MCC-1760)

add Address Codes to mobilecoind-json [MCC-1757]

---

Cargo.lock
consensus/service/Cargo.toml
consensus/service/src/consensus_service.rs

The ByzantineLedger API is thread-safe, but a mutex was being used
in order to resolve a circular dependency issue.
The three major components of consensus service:
- `consensus_msgs_from_network` (background work queue taking messages)
- `broadcaster` (sends messages to our peers)
- `byzantine ledger` (processes messages and oversees SCP progress)
have needs to send messages in both directions, and so require handles
to eachother. That is, the two parts that are sending messages, sometimes
need to ask `byzantine ledger` about the state, but also, ByzantineLedger
needs to be able to push messages to the broadcaster etc.
Even though there are circular dependencies, one of them has to be
initialized last. Currently that is `ByzantineLedger`.
This means that the handles passed to those that …

Remove unnecessary mutex around ByzantineLedger

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/clients/python/mob_client/mob_client.py
mobilecoind/src/payments.rs
mobilecoind/src/service.rs

Soundtrack of this PR: [I'm Free](https://www.youtube.com/watch?v=S6InAX5IAQM)
Currently there is no way to generate a transaction in mobilecoind without first setting up a monitor which then must view-key scan the entire ledger. In certain instances, for example gift codes, a caller may already know which UTXO they wish to spend, making scanning unnecessary. This PR adds a new RPC endpoint allowing a client to spend UTXOs with an account key without creating a monitor.
* Adds and implements `GenerateTxFromTxOutList` to the gRPC endpoint
* Adds a new function `generate_tx_from_tx_list` to `payments.rs`
* Tests for the above
* update python library support these endpoints

Creates a new RPC endpoint for spending a TXO without a monitor

---

consensus/service/src/consensus_service.rs

Remove unnecessary mutex around peer_keepalive
This follows up on the commit that removes the mutex around
byzantine ledger. The peer_keepalive mutex is only there to allow
stopping the service. We change this from `Arc<Mutex<PeerKeepalive>`
to `Option<Arc<PeerKeepalive>>`, and replace to call to `lock().stop()`
in the stop function with `= None` which simply drops the value.
We also make the other Arc's that are holding this, in lambda functions,
into weak references. This prevents strong reference cycles which would
prevent the drop from happening and cause a resource leak.
We also put a code comment about why not to remove the mutex around
threaded broadcaster.

Remove more unnecessary mutex (based on #441)

---

consensus/scp/src/node/mod.rs
consensus/scp/src/node/node_impl.rs
consensus/scp/src/node/node_trait.rs

I often find that I want to quickly get to the ScpNode trait, which is 150 lines down into node.rs, or I want to hop back and forth between the Node implementation and its unit tests, in which case the ScpNode trait is just 50 lines of clutter.
- Moves the ScpNode trait into a separate file. It may just be personal preference, but I feel like this is more pleasant to navigate.

Moves ScpNode trait into separate file.

---

consensus/service/src/byzantine_ledger/worker.rs
consensus/service/src/tx_manager/mod.rs

One of the main jobs of the TxManager is to keep track of what
transcations have been validated or partially validated by the enclave,
and keep a cache mapping their hashes to the data that untrusted
has about them.
Any part of the system that needs to know something about a particular
Tx, or add new Tx's, or purge old Tx's, or form blocks, needs to talk
to this cache object. So ideally, this cache object would be like a
thread-safe map, similar to Java's concurrent hashmap, so that we
don't bottleneck essentially all the threads in the server on this.
We haven't gotten to the point of using a concurrent hashmap for this,
in part because there are several implementations of varying quality
and choosing one is not straightforward.
We also don't have infrastructure for measuring contention …

Don't tear-down and copy the entire Tx cache

---

Cargo.lock
consensus/service/Cargo.toml
consensus/service/src/byzantine_ledger/worker.rs
consensus/service/src/peer_api_service.rs
consensus/service/src/tx_manager/error.rs

Seems like we don't consider re-inserting into the cache to be an error, so we generally end up ignoring this error variant.
* Removes the AlreadyInCache error variant.
* Switches TxManagerError from `failure` to `displaydoc`

Removes TxManagerError::AlreadyInCache error variant [MCC-1707]

---

.circleci/config.yml

PR https://github.com/mobilecoinofficial/mobilecoin/pull/326 added `brew update` to all CI builds to resolve an issue with using an old version of Homebrew on CircleCI. Running `brew update` solved the issue by updating Homebrew before using it to install any dependencies. This added ~33s to each CI run.
This PR assumes that CircleCI is using a newer version of Homebrew by now. As such, this PR removes the call to `brew update` for all CI runs, and instead only runs it when building on master, which is done to ensure that the lastest versions of dependencies are saved to the cache (which is saved as part of the CI run on master).
This PR also fixes a minor yaml schema issue where parameters that are meant to be strings are considered by yaml to be integers because they are parsable as …

[MCC-1791] Resolve Homebrew issues in CI

---

Cargo.lock
mobilecoind-json/Cargo.toml
mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/README.md

Soundtrack of this PR: [Buttercup](https://www.youtube.com/watch?v=e2qG5uwDCW4)
Currently the GetUnspentTxOutList, GenerateTx, and Submit endpoints are not exposed on mobilecoind-json.
* Adds GetUnspentTxOutList to mobilecoind-json (needed to get inputs for constructing offline transactions)
* Adds GenerateTx to mobilecoind-json (needed for offline transactions)
* Adds Submit to mobilecoind-json (needed for offline transactions)
* Adds necessary json conversions
* Updates READMEs to reflect offline usage and new endpoints
[MCC-1751](https://mobilecoin.atlassian.net/browse/MCC-1751)

Add offline tx endpoints to mobilecoind-json

---

util/generate-sample-ledger/src/lib.rs

The origin block should not be created with fewer than 16 outputs. Technically 14 and 15 would work, but don't divide evenly into 250M MOB, so there would be fractional MOBs in the origin block. 
(250_000_000*1_000_000_000_000)/18_446_744_073_709_551_615 = 13.55
* Adds an assert, which enforces a comment in the docstring that it should panic if < 16 txs.

Ensure origin block contains at least 16 txos

---

tools/release-tests/mirror-json-test.py
tools/release-tests/requirements.txt

We have been checking our binary releases for various client-side components manually. This script automates downloading, extracting and running all the executables and verifies that they works as expected.
* Creates `mirror-test-json.py`
* Downloads specified tarball, defaulting to latest
* Launches mobilecoind, mirror-public, mirror-private and mobilecoind-json
* Runs a series of requests against the REST services to ensure they act as expected
* More tests on mirror service
* Set up to run against fresh builds for CI testing

Integration test for mobilecoind / json gateway / mirror

---

mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

Requested by a user.
* Add a new API call to `mobilecoind` that combines `ReadAddressCode` + `SendPayment`.
* Do the same to `mobilecoind-json`.

MCC-1756: Add convenience method to mobilecoind/mobilecoind-json for paying an address code 

---

mobilecoind/clients/python/lib/mobilecoin/__init__.py

A merge error for the PyPI package left an incorrect namespace, which this PR fixes
* Remove erroneous .api

Remove erroneous .api from GenerateTxFromTxOutListRequest

---

mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/clients/python/jupyter/wallet.ipynb
mobilecoind/clients/python/lib/mobilecoin/__init__.py
mobilecoind/clients/python/lib/setup.py
mobilecoind/src/service.rs
testnet-client/src/main.rs

The verbs related to b58 code stuff were "Get" for creating a b58 code and "Read" for parsing one - which are suboptimal. This PR moves to Create and Parse which are unambiguous.
* Whole bunch of renames

mobilecoind API: Get -> Create, Read -> Parse

---

mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

Requesting a printable public address currently requires two round-trips, we have a feature request to simplify this by including the b58 code in GetPublicAddress
This has been run through integration testing
* Adds b58-encoded Public Address in GetPublicAddress in mobilecoind
* Add to JSON interface
* Potentially allow b58 codes used directly in transaction creation functions, further reducing round-trips

Return b58 encoding of public address as part of public address endpoint

---

consensus/enclave/edl/enclave.edl
consensus/enclave/trusted/src/lib.rs

Fixes deserialization data-race uncovered by ioactive.
* Replace `[user_check]` with `[in]` in enclave EDL file.
* Invert the `sgx_is_outside_enclave` check of the inbuf in `mobileenclave_call`
* Update other enclaves which use this convention.

MCC-1822 Copy data into enclave before deserialization

---

Cargo.lock
consensus/enclave/build.rs
consensus/enclave/edl/enclave.edl
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml
consensus/enclave/trusted/build.rs
sgx/urts/Cargo.toml

The sgx_backtrace thing was an attempt to port Baidu's sgx backtrace
functionality so that it would work without making system calls.
We got it working in sim mode but never actually figured out about offsets
in SGX HW mode.
Since then we became worried that it's a security hole and turned it off,
we are building in panic=abort mode for sgx, so nothing is actually using
this OCALL.
We definitly aren't going to fix this before launch, it would need major
redesign. So there's no reason for it to be in the consensus edl at all.
Probably we should go further and just delete the sgx/backtrace crate entirely.
I'm putting up this smaller commit just for discussion first.

Removes sgx_backtrace and sgx_debug edl interfaces in consensus_enclave edl

---

ops/entrypoints/consensus_validator.sh

Soundtrack of this PR: [https://www.youtube.com/watch?v=EgT_us6AsDg](I keep hitting repeat repeat repeat)
The entrypoint starts several backgrounded processes. All of their output goes to the same stdout/stderr. This makes it very difficult to distinguish which messages go with which component.
Also, if any of these processes die, they are not restarted.
This patch sends logs to `NODE_LOG_DIR` if it is set, and restarts any process that exits after 10 seconds.
Log rotation is left to the user; recommend specifying`copytruncate` if using `logrotate`.
* `aesm-service` in our evironment exits immediately with no stdout/stderr message, so it is not handled like the rest of the services. `&` is not needed.
* With `--no-daemon` it does the more expected thing - it stays in foreground and …

Add bash function wrapper to log services and restart them if they die

---

mobilecoind/src/monitor_store.rs

A nice property of mobilecoind's monitor_id is that it is not secret material. This PR updates a comment to reflect this.

[Minor] Comment Change

---

mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
tools/release-tests/mirror-json-test.py

There were a few inconsistent names and values in the JSON gateway and the README was missing some useful calls.
* Change `amount` to `value` for all literal values
* Use strings for u64 amounts (JSON limitation)
* Add `pay-address-code` as a simple payment flow to README
* Update integration test with new fields / values / `pay-address-code`
* Make sure other documentation is in-sync
* Cut a new release

Fixes field names/type in json gateway, update README and test

---

consensus/service/src/byzantine_ledger/worker.rs

ByzantineLedgerWorker's catch-up logic has been hard to test, and generally hasn't been unit tested. 
* Splits the logic into a state transition and the action performed by each state transition.
* Creates a separate function for incrementally syncing the ledger.
* Unit tests for the above two things.
* A couple extra unit tests, thrown in for good measure.
The above should be an improvement in maintainability and testability, but shouldn't actually change much, if any, functionality. Once we have testing in place, changes in functionality should be easier. For example, I'd like to encapsulate more of the ledger sync logic in the LedgerSyncService.

[MCC-498] Catch-up unit tests

---

mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

* We needed a mobilecoind/mobilecoind-json endpoint that allows you to find the block index of a given tx out public key.
* Adding an endpoint that provides that functionality.
* Add it to mobilecoind-mirror

MCC-1856 - Get block index by txo pub key in mobilecoind[-json]

---

Cargo.lock
mobilecoind/Cargo.toml
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

Product spec includes QR codes for request codes in desktop clients, these should be encoded as mob_urls 
* Return mob_url  as part of CreateRequestCode in mobilecoind
* If we like this approach, also add to transfer codes?

Adds moburl to returned proto when creating a request code

---

attest/core/build.rs

A specially crafted certificate file could cause an integer overflow (in a `build.rs` script)
* Fix that

address potential integer overflow

---

Cargo.lock
Cargo.toml
common/src/lib.rs
common/src/time.rs
connection/src/thick.rs
connection/src/traits.rs
consensus/service/src/attested_api_service.rs
consensus/service/src/bin/main.rs
consensus/service/src/blockchain_api_service.rs
consensus/service/src/client_api_service.rs
consensus/service/src/config.rs
consensus/service/src/consensus_service.rs
consensus/service/src/grpc_error.rs
util/grpc-token-generator/Cargo.toml
util/grpc-token-generator/src/bin/main.rs
util/grpc/Cargo.toml
util/grpc/src/auth/anonymous_authenticator.rs
util/grpc/src/auth/mod.rs
util/grpc/src/auth/token_authenticator.rs
util/grpc/src/lib.rs
util/uri/Cargo.toml
util/uri/src/lib.rs
util/uri/src/traits.rs
util/uri/src/uri.rs

Soundtrack of this PR: [On and Off the Beaten Path 1](https://soundcloud.com/shoutingfire/oobp1?ref=whatsapp&p=i&c=0)
We'd like to have the option to require authentication when accessing some of our GRPC services. This could allow for things such as centralized rate limiting, or nodes that only accept client requests from specific entities. 
Add support for client request authentication in `mc-consensus-service`. Currently, the only supported authenticated method is a token-based one. A token-generating entity (currently a command line utility, but eventually some service) shares a secret with the token-validating entity (`mc-consensus-service`). The shared secret allows the validating entity to ensure tokens handed to it were signed by a trusted party. Generated tokens contain a unix …

MCC-1818: Optional authentication support in consensus-service

---

tools/release-tests/mirror-json-test.py

We have added some endpoints to the mirror, and this PR adds them to the integration test.
* Adds processed-block endpoint to the integration test
* Adds tx-out endpoint to the integration test
* Adds `--synced` flag to not resync the ledger on reruns of the test
* Adds `--services` flag to leave services up at conclusion of test for continued manual test iterations

Add processed-block and tx-out endpoint tests and testing flags

---

consensus/api/proto/consensus_peer.proto
consensus/service/src/client_api_service.rs
consensus/service/src/consensus_service.rs
consensus/service/src/peer_api_service.rs

Soundtrack of this PR: [Final Song](https://www.youtube.com/watch?v=WUcXQ--yGWQ)
PeerApiService provides the gRPC API that consensus nodes use to communicate with each other. It currently lacks unit tests. 
* Sets up PeerApiService to use mocked dependencies.
* Adds initial unit tests for send_consensus_msg, which handles incoming consensus messages.
* This PR mostly sets the pattern for unit testing and gets things ready for upcoming changes to PeerApiService, like MCC-1867, Modify send_consensus_msg to fetch transactions referenced by a consensus message.
* Additional unit tests.

[MCC-528] PeerApiService unit tests

---

Cargo.lock
mobilecoind/Cargo.toml

For the `target.x86_64-apple-darwin` build for mobilecoind, zlib (grpcio dep) throws an error. Specifying a higher zlib build dependency solves the issue.
* Sets zlib build dep for mobilecoind
[MC-1898](https://mobilecoin.atlassian.net/browse/MCC-1898)

Set zlib build dependency for mobilecoind

---

mobilecoind/clients/python/README.md
mobilecoind/clients/python/blockchain_explorer/README.md
mobilecoind/clients/python/blockchain_explorer/blockchain_explorer.py
mobilecoind/clients/python/blockchain_explorer/install.sh
mobilecoind/clients/python/blockchain_explorer/requirements.txt

We now have mobilecoin as a PyPi package, so we can update our blockchain explorer appropriately.
* Updates blockchain_explorer to use the mobilecoin module
* Adds README
* Removes install.sh script in favor of requirements.txt
[MCC-1889](https://mobilecoin.atlassian.net/browse/MCC-1889)

Update blockchain explorer for PyPi module

---

ledger/sync/src/ledger_sync/ledger_sync_service.rs
ledger/sync/src/ledger_sync/ledger_sync_service_thread.rs
mobilecoind/src/bin/main.rs
mobilecoind/src/service.rs
mobilecoind/src/test_utils.rs

Soundtrack of this PR: [Chino Moreno - Brief Exchange](https://www.youtube.com/watch?v=sBMGiHosRYk)
Slow ledger syncing is a suboptimal user-experience, and we'd like it to be faster.
* Increasing number of worker threads when fetching S3 blocks, as well as increasing the amount of block headers fetched from consensus. This results in bringing ledger sync time from several minutes to 40-60 seconds on my machines.
* Switch a mutex around `NetworkState` to an `RwLock` - this allows mobilecoind's `GetNetworkStatus` RPC call to not block when a ledger sync is taking place.
* Dig further into why attempts at changing the S3 fetching to use async code result in worse performance than creating 500 real threads.
* Consider post-processing blocks into larger chunks in order to reduce number of S3 …

Mobilecoind performance improvements

---

consensus/scp/play/src/main.rs
consensus/scp/src/msg.rs
consensus/scp/src/quorum_set.rs
consensus/service/src/config.rs
mobilecoind/src/config.rs

We'd like to have a sanity check around basic quorum set configuration when it is constructed from user input or external sources.
* Add an `is_valid()` method on `QuorumSet` that ensures the quorum set, and all of its inner sets have `threshold <= number of members`.
* Ideally we should have less panics around this and more `Result<>`, but that is a bigger change and the extra panics were added to places that would already panic on incorrect input.
* It would've been nice if the various `QuorumSet` constructors returned a `Result` and forced validation - but that means changing about 200 calls, mostly in test code. It also does not protect against deserializing a broken `QuorumSet`, which is where the real problem is and unfortunately `serde` does not have a good solution for that at the …

add QuorumSet::is_valid, call it when quorum sets are being parsed

---

mobilecoind-json/src/bin/main.rs
tools/release-tests/mirror-json-test.py

Currently, the processed-block endpoint is `processed-blocks` in mobilecoind-json, and `processed-block` on the mirror. This PR makes them consistent (processed-block).
* Updates mobilecoind-json `processed-blocks` -> `processed-block`
* Adds the mobilecoind-json processed-block endpoint to the integration test
[MCC-1910](https://mobilecoin.atlassian.net/browse/MCC-1910)

Update path for mobilecoind-json to match mirror

---

.circleci/config.yml

Apple release Xcode 12 recently which caused the repo to no longer compile on the latest macOS (see #488).
This PR sets up a build matrix for macOS testing using multiple Xcode versions, and adds testing using Xcode 12.0.0 in addition to the existing 11.7.0 testing.
* Parameterize macos executor in circleci config
* Add Xcode 12 testing to CI
Fixes [MCC-1911]
[MCC-1911]: https://mobilecoin.atlassian.net/browse/MCC-1911

[MCC-1911 Add Xcode 12 testing to CI

---

mobilecoind/clients/python/blockchain_explorer/blockchain_explorer.py
mobilecoind/clients/python/cli/benchmark.py
mobilecoind/clients/python/cli/check_balance.py
mobilecoind/clients/python/cli/cleanup_monitors.py
mobilecoind/clients/python/cli/get_public_address.py
mobilecoind/clients/python/cli/send_payment.py
mobilecoind/clients/python/lib/mobilecoin/client.py
mobilecoind/clients/python/lib/setup.py
mobilecoind/clients/python/mailchimp/allocate_mobilecoins.py
mobilecoind/clients/python/mailchimp/download_members.py
mobilecoind/clients/python/pizzamob_leaderboard/pizzamob_leaderboard.py

Soundtrack of this PR: [bg](https://soundcloud.com/pheel518/pheel-featherbed-sessions-vol1-mix)
If we add fields to messages in the protobuf API, it would be great for these to be available immediately in the python library.
* avoid unwrapping API responses in the python library [MCC-1904]
* since this is a breaking change, update the library to v0.3
[MCC-1904]: https://mobilecoin.atlassian.net/browse/MCC-1904

always return full API response from python library (MCC-1904)

---

Cargo.lock
consensus/service/Cargo.toml
consensus/service/src/api/grpc_error.rs
consensus/service/src/api/mod.rs
consensus/service/src/api/peer_api_service.rs
consensus/service/src/api/peer_service_error.rs
consensus/service/src/byzantine_ledger/worker.rs
consensus/service/src/consensus_service.rs

Soundtrack of this PR: [Kiss from a Rose](https://www.youtube.com/watch?v=G76nKGWRLPU)
I was getting bogged down by the error handling in PeerApiService. 
* Separates "logic" error handling from gRPC serialization/deserialization error handling.
* Extracts some logic into `handle_consensus_msg`.
* Creates an error type for PeerAPIService.
In total, I think this makes it easier to see what's going on.

Peer API error handling

---

api/src/convert/archive_block.rs
api/src/convert/error.rs
api/src/convert/mod.rs
ledger/db/src/ledger_trait.rs
ledger/db/src/lib.rs
ledger/db/src/test_utils/mock_ledger.rs
ledger/distribution/src/main.rs
ledger/from-archive/src/main.rs
ledger/sync/src/ledger_sync/ledger_sync_service.rs
ledger/sync/src/reqwest_transactions_fetcher.rs
ledger/sync/src/test_utils.rs
ledger/sync/src/transactions_fetcher_trait.rs
mobilecoind/src/bin/main.rs
mobilecoind/src/service.rs
transaction/core/src/blockchain/block_data.rs
transaction/core/src/blockchain/mod.rs
watcher/src/watcher.rs

Soundtrack of this PR: [Le pas du chat noir](https://open.spotify.com/album/1Vi1fmvatCuzuASdvUGTuf?si=nUDN47zaQ0qsN7pr-syBtg)
As part of work I am doing on merging blocks together for more efficient distribution, I ran into the lack of ergonomics around `Block`+`BlockContents`+`BlockSignature`. There are a few occasions where we want to get all three, and pass them around. Previously this was done in 3 separate calls to `LedgerDB`, and a bunch of tuples or custom but specific object (`ArchiveBlockData`). This PR cleans up this pattern, and provides a new and reusable`BlockData` object.
* Introduce `BlockData`, which is a `Block` + `BlockContents`+ optional `BlockSignature` and use it in places where appropriate. 
* The internal repo could benefit from this, so I will follow up with a PR …

New data type: BlockData

---

api/proto/printable.proto

"MobileCoinAPI" outer_classname is in use by external.proto, which creates conflict in java implementations.
Remove java_outer_classname option. 
With no outer class name specified, it will be generated by converting the file name to upper camel case

"MobileCoinAPI" is in use by external.proto

---

api/proto/printable.proto
api/src/display.rs
mobilecoind/src/service.rs

We should use concrete data when available, instead of byte arrays.
* Switching a bytes field into `CompressedRistretto`.
* Since this changes the proto APIs, the Python package will need to be updated (cc @rjwalters)

MCC-1881: TransferPayload.tx_out_public_key should use actual key data type

---

attest/core/Cargo.toml
attest/net/Cargo.toml
attest/trusted/Cargo.toml
common/Cargo.toml
connection/Cargo.toml
consensus/enclave/api/Cargo.toml
consensus/enclave/trusted/Cargo.lock
crypto/ake/enclave/Cargo.toml
crypto/box/Cargo.toml
crypto/keys/Cargo.toml
crypto/message-cipher/Cargo.toml
crypto/noise/Cargo.toml
ledger/db/Cargo.toml
ledger/distribution/Cargo.toml
ledger/sync/Cargo.toml
mobilecoind/Cargo.toml
peers/Cargo.toml
transaction/core/Cargo.toml
transaction/std/Cargo.toml
util/build/script/Cargo.toml
watcher/Cargo.toml

* This fixes the build in certain cases.
* Updating `failure` to its most recent version, and ensuring all crates refer to the same version.

bump failure to 0.1.8

---

sgx/epid-types/Cargo.toml

Dependabot is failing with the following error:
```
Dependabot couldn't parse the Cargo.toml found at /sgx/epid-types/Cargo.toml.
The error Dependabot encountered was:
Dependabot::DependencyFileNotParseable
```
(see: https://github.com/mobilecoinofficial/mobilecoin/network/updates/65925226)
Running it locally reveals the underlying issue:
```
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/citrus-3.0.2/lib/citrus.rb:669:in `parse': Failed to parse input on line 32 at offset 43 (Citrus::ParseError)
bytes = { version = "0.5", optional = true , default-features = false}
^
```
* Fixes a parsing issue with `sgx/epid-types/Cargo.toml`
Fixes [MCC-1977]
[MCC-1977]: https://mobilecoin.atlassian.net/browse/MCC-1977

[MCC-1977] Fix dependabot parsing issue

---

common/src/lib.rs

`cargo check -p mc-common --features std` should work
* Change `no_std` gating to use the correct feature

fix mc-common std feature usage

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

* We forked `RustCrypto-utils` because we need to disable its cpuid crate otherwise we get the `CPUID` instruction inside enclaves. They released a new version (to an unrelated crate in that repo), so I merged their changes in.
* Upreving `RustCrypto-utils` fork.

bump RustCrypto-utils revision

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml
crypto/box/Cargo.toml
crypto/box/src/hkdf_box.rs
crypto/box/src/lib.rs
crypto/box/src/traits.rs
crypto/box/src/versioned.rs
crypto/ct-aead/Cargo.toml
crypto/ct-aead/README.md
crypto/ct-aead/src/aes_impl.rs
crypto/ct-aead/src/lib.rs
crypto/ct-aead/src/traits.rs
transaction/core/src/fog_hint.rs

Soundtrack of this PR: [https://www.youtube.com/watch?v=TxrwImCJCqk](Hazy Shade of Winter)
We need constant time decryption to avoid side channel attacks.  Upstream aes-gcm did not have this, and it also kept its internals private so we could not implement this ourselves without a lot of code duplication.  So here we use a tiny patch on upstream, combined with a new trait for CtAeadDecrypt, and integrate it into cryptobox.
* Use upstream fork to allow access to aes-gcm internals
* Add CtAeadDecrypt trait and use it in cryptobox
Fixes #FOG-96 and FOG-155

Make a constant time aes-gcm decrypt and use in cryptobox

---

crypto/digestible/Cargo.toml
crypto/message-cipher/Cargo.toml
crypto/noise/Cargo.toml
transaction/core/Cargo.toml

The `generic-array` crate does not include `ArrayLength<T>` implementations for all the types in `typenum`, and in fact only does `U0` through `U32` by default. This adds the `more_lengths` feature to the use of `generic-array` in the `mc-util-repr-bytes` crate, and removes `default-features = false` where it appears, as it is not necessary.
* Cleanup cargo inclusion of `generic-array`
* Enable the `more_lengths` feature in `mc-util-repr-bytes` use of `generic-array`.

Cleanup generic array references, add more_lengths

---

BUILD.md
CONTRIBUTING.md
TESTNET.md
hooks/pre-push
mobilecoind/clients/java/mob_client/README.md
mobilecoind/clients/python/lib/README.md
mobilecoind/clients/python/lib/setup.py
mobilecoind/clients/python/start_mobilecoind.sh
sgx/ias-types/Cargo.toml
tools/release-tests/mirror-json-test.py
util/repr-bytes/README.md

We transferred ownership from mobilecoinofficial -> mobilecoinfoundation, and several references need to be updated. 
* updates references in documentation, the pre-push hook, and in scripts which look at release locations.
[MCC-2022](https://mobilecoin.atlassian.net/browse/MCC-2022)

mobilecoinofficial -> mobilecoinfoundation [MCC-2022]

---

Cargo.lock
api/Cargo.toml
api/build.rs
api/proto/external.proto
api/proto/watcher.proto
api/src/convert/mod.rs
api/src/convert/watcher.rs

Fog needs to communicate `TimestampResultCode` inside some of its proto objects. Currently the proto equivalent of `TimestampResultCode` lives in internal/fog, but the correct place for it is in this repository, next to all the other proto APIs bundled in `mc_api::external`.
* Add `TimestampResultCode` to `external.proto`
* Add appropriate `From`/`TryFrom` conversions. 
* Use this in internal fog code.

add TimestampResultCode to mc_api

---

connection/src/traits.rs
util/grpc/src/lib.rs

Restarting a node on the network deletes any peer session IDs they have. As a result, the next time the peer goes to perform an action, it will receive an enclave error. Unfortunately this is translated into the INVALID_ARGUMENT gRPC status code, which does not trigger a re-attestation. Without re-attestation, enclaves within the network cannot communicate with each other, leading to network collapse.
* Treat any RPC failure of an attested call as cause to re-attest.
* Explicitly return PERMISSION_DENIED for enclave errors.

MCC-2026 Make enclave errors always return PERMISSION_DENIED

---

common/src/logger/loggers/mod.rs

Sometimes, it isn't acceptable to log on stdout, because a CLI tool
may be required to return structured output on stdout.
Typically, the stderr channel is reserved for logging in unix, and
this is what glog does by default. I'm not sure why we log to stdout.
To avoid breaking any of our partners who may be depending on the stdout
behavior, this creates a configuration for stderr, but keeps the defaults
with the current behavior.
If we are sure that stderr is acceptable then ideally we would drop this and not log to stdout ever.

Make a stderr configuration of the logger module, and use it in tests

---

Cargo.lock
consensus/service/src/bin/main.rs

The `fs_extra` crate changed their API during the transition from 1.1 -> 1.2, specifically changing an `&Vec<u8>` parameter to an `&[u8]` parameter. This is not a semver break in the traditional sense, because a reference to a `Vec` can be coerced into a slice of the `Vec`'s contents, but this does trigger a new `clippy` warning, which breaks the build.
* Create a slice instead of a vector.

MCC-2050 Update fs_extra, fix for semver break-ish

---

Cargo.lock
consensus/enclave/measurement/Cargo.toml
consensus/enclave/measurement/src/lib.rs

This pattern was established in internal repo and avoids a bunch
of boilerplate
we should probably use these functions in mobilecoind also

Expose mrsigner/mrenclave verifiers in measurement crate

---

Cargo.lock
Cargo.toml
jenkins/Jenkinsfile
jenkins/packaging-pod.yaml
mobilecoind/src/service.rs
ops/Dockerfile-consensus
ops/Dockerfile-mobilecoind
tools/local-network/local_network.py
util/grpc-admin-tool/Cargo.toml
util/grpc-admin-tool/src/bin/main.rs

* The admin endpoint is useful for debugging and it's desirable to make it easy to use. This PR adds a small command line utility for making requests against an admin endpoint (e.g. `cargo run -p mc-util-grpc-admin-tool -- --uri insecure-mca://127.0.0.1:4444/ set-rust-log debug`
* It's desirable to be able to query a running `mobilecoind` for build information, and to change its log level. This can easily be achieved by having it package the grpc admin service into its rpc endpoint.
* Adding `mc-util-grpc-admin-tool`
* Adding `AdminService` to`mobilecoind`
* Including the `mc-util-grpc-admin-tool` binary in containers
* Cleaning up some whitespaces
* Include it in all the internal containers

GRPC Admin Utility + mobilecoind admin endpoint

---

api/proto/external.proto

The other one is in ` api/proto/watcher.proto`

remove duplicate TimestampResultCode

---

deploy/03-node1.yaml
deploy/03-node2.yaml
deploy/03-node3.yaml
deploy/03-node4.yaml
deploy/03-node5.yaml
ledger/distribution/README.md

Its standard practice to use environment variables to control AWS parameters. Previously we were using a custom, non-standard `?region=` query param. This PR replaces that with the more standard `AWS_REGION` environment variable.

Replace ?region= in favor of AWS_REGION

---

common/src/lib.rs
common/src/logger/mod.rs

`mc-common` incorrectly allowed compilation of custom panic handler code based on the `log` feature (which enables the logging infrastructure but not highlevel application logger implementations). It also allowed compilation of time-tracing utilities that depend on `std::time`.
This caused the issue in https://github.com/mobilecoinfoundation/mobilecoin/issues/548
* Change the feature gates so that std usage is being properly respected.

correctly gate time measurement and panic handlers

---

deploy/03-node1.yaml
deploy/03-node2.yaml
deploy/03-node3.yaml
deploy/03-node4.yaml
deploy/03-node5.yaml

Soundtrack of this PR: [My Favorite Things](https://www.youtube.com/watch?v=8d9cD_Es9k4)
The consensus node deployments previously used `spec.template.spec.containers[].securityContext.privileged: "true"` as a way of getting access to the underlying host SGX character device `/dev/isgx`.  Running in `privileged: "true"` mode is an unnecessary  security exposure, especially if an alternative type of access is available.
Using an sgx device plugin, we can let the `kubelet` map the SGX device into the container, without giving full privileged access to the container itself.
* remove privileged mode
* remove manual /dev/isgx character device volume mount
* Add intel.com/sgx resource requests.
* Explore running the processes within the containers as a non-root/non-privileged user

Update continuous deployment to use intel.com/sgx resource requests

---

mobilecoind-json/README.md
tools/release-tests/mirror-json-test.py

We recently added a feature to mobilecoind and mobilecoind-json that allows change from a split TXO to be returned to a subaddress other than the sender. This updates the README and the integration test to capture this feature.
* Update README to add `change_subaddress`
* Update integration test to pay twice with different change subaddresses

Update change readme

---

transaction/core/src/constants.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/core/src/validation/validate.rs

Soundtrack of this PR: [link to song that really fits the mood of this PR](https://youtu.be/Q5Yd2Io-g5c)
Currently, the pseudo_output commitments are included in the range proof, which increases the size of the range proof from "num_outputs" to "num_inputs + num_outputs". I originally included the pseudo_output commitments in the range proof out of caution, but since then we've concluded that it isn't necessary.
* Omits pseudo_output commitments from range proof.
* Simplifies the balance check in sign_with_balance_check.
* Various cleanup

[MCC-1969] Removes pseudo_outputs from range proof

---

.cargo/config

All crate in the `mobilecoin` repo should have their `authors` field set to `["MobileCoin"]`. This PR ensures that this value is prefilled automatically for any new crates created using `cargo new` .
* Sets the `name` and `email` properties within the `cargo-new` section of the repo's cargo config to `"MobileCoin"` and `""`, respectively.
Fixes MCC-447

[MCC-447] Set default author to MobileCoin for new crates

---

transaction/core/src/constants.rs
transaction/core/src/ring_signature/mod.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/core/src/validation/validate.rs

Reverts mobilecoinfoundation/mobilecoin#542
This will be included in a later enclave upgrade.

Revert "[MCC-1969] Removes pseudo_outputs from range proof"

---

consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

The enclave does not care about grpcio.

remove unused patch entry for grpcio

---

.circleci/config.yml

Our CI recently started failing on macOS CI runs (as seen [here](https://app.circleci.com/pipelines/github/mobilecoinfoundation/mobilecoin/2873/workflows/17d734ca-0734-4860-9413-4523e3d9e14e/jobs/7010/parallel-runs/0/steps/0-103)) because of an outdated Homebrew version. Previously we ran Homebrew update only when running CI from master, in order to cut down on CI run times for PRs. However, recently it has come to my attention that Homebrew doesn't support running without first updating (See https://github.com/Homebrew/homebrew-bundle/issues/840).
In order to resolve this issue while still minimizing CI times for PRs, this PR changes the CircleCI config to runs `brew update --preinstall` on every run of CI rather than just on master, while continuing to keep auto-update disabled …

Run Homebrew update on every macOS CI run

---

Cargo.lock
Cargo.toml

Currently, we hard code the console library. The relevant blame hints this was needed for patches at the time. This is needed to clean up the build and help reduce technical debt.
Removes the relevant duplicate console library.
I will probably continue to simplify the Cargo.toml

Simplify Cargo.toml

---

mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs

mobilecoind offers the option to encrypt the account_keys at rest in the DB on the backend. This PR exposes an endpoint in mobilecoind-json to pass the password_hash to mobilecoind.
* adds set-password endpoint and updates README
[MCC-2150](https://mobilecoin.atlassian.net/browse/MCC-2150)

Add password hash to mobilecoind-json

---

ledger/db/src/lib.rs

We sometimes have services that read the ledger db and report metrics to Prometheus, however they do not update the database themselves as that happens externally using `mobilecoind`. It's useful to have a way to force `LedgerDB` to update its gauges, so that these services could report correct data. The idea is that they will call the new `update_metrics` method periodically in the loop that polls the ledger that those services tend to have.
* Adding the `update_metrics` method to `LedgerDB`.

ledger-db: provide a utility method for updating prometheus metrics

---

docker/Dockerfile

https://github.com/mobilecoinfoundation/mobilecoin/issues/592
https://github.com/mobilecoinfoundation/mobilecoin/pull/589 is going to require linter tools to be installed before we can lint 
We install the newest black. This will mean that we will have to relint as new black updates come out
* Verify we only want to use the newest black
* https://github.com/mobilecoinfoundation/mobilecoin/pull/589

Add black for python linting

---

consensus/enclave/trusted/Cargo.lock

This is a followup PR to recent version bump PRs:
* https://github.com/mobilecoinfoundation/mobilecoin/pull/608
* https://github.com/mobilecoinfoundation/mobilecoin/pull/614
* https://github.com/mobilecoinfoundation/mobilecoin/pull/641
* https://github.com/mobilecoinfoundation/mobilecoin/pull/659
These PR were autogenerated by dependabot. They updated `Cargo.lock` but didn't perform the corresponding update to `consensus/enclave/trusted/Cargo.lock`, which is what this PR does.

Bump consensus enclave deps

---

.circleci/config.yml

One of our CI dependencies (`tokio`, on which `sccache` depends) recently updated and is no longer compatible with the version of Rust that our project is pinned to ([Failing CI log](https://app.circleci.com/pipelines/github/mobilecoinfoundation/mobilecoin/3143/workflows/380fc8d6-9fd3-42c4-8938-20d81aca333f/jobs/8100)). This is only a problem because we install our CI Cargo dependencies from our project dir, which in turn installs these dependencies using our project's pinned Rust version, rather than using stable.
This PR fixes that issue by `cd`'ing up 1 level whenever `cargo install` is invoked so that Cargo no longer detects the presence of the `rust-toolchain` file.

Don’t install Cargo deps from project dir in CI

---

tools/local-network/local_network.py

We need to be able to run a mobilecoind in release mode when running a local network.
* Ensuring the local network script builds it in a way that allows us to do so.

build mobilecoind with --no-default-features to allow running local network

---

transaction/core/src/fog_hint.rs

Soundtrack of this PR: [https://www.youtube.com/watch?v=CM3mB6WrhJ4](Aztec Camera - Oblivious)
My initial implementation of conditional_select for FogHint wasn't oblivious enough. Now I use conditionally assign each byte as per membership_proofs.  This makes it not only constant time, but also memory access oblivious.
* Rewrite FogHint::conditional_select
Fixes FOG-299
This should fix this with no need for future work.

Use byte-by-byte conditional_assign to implement conditional_select for FogHint

---

mobilecoind/strategies/accounts.py
mobilecoind/strategies/test_client.py

In #674 we fixed status as sender, but the test_client also needed to incorporate the fix for continuous deployment
* Fixes up GetTxStatusAsSender in the test_client
[MCC-2183](https://mobilecoin.atlassian.net/browse/MCC-2183)

Fix test_client usage of GetTxStatusAsSender

---

mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/payments.rs
mobilecoind/src/service.rs

Adds API endpoint for getting TxOuts for use as mixins.
* GetMembershipProofRequest and GetMembershipProofResponse use TxOut instead of UnspentTxOut.
* Add GetMixins endpoint 
* Update mobilecoind-json
* TODO: Add unit tests to mobilecoind-json

Add GetMixins to mobilecoind API

---

Cargo.lock
Cargo.toml
api/src/convert/tx.rs
consensus/service/src/validators.rs
fog/report/connection/src/lib.rs
fog/report/validation/Cargo.toml
fog/report/validation/README.md
fog/report/validation/src/ingest_report.rs
fog/report/validation/src/lib.rs
fog/report/validation/src/traits.rs
fog/report/validation/test-utils/Cargo.toml
fog/report/validation/test-utils/README.md
fog/report/validation/test-utils/src/lib.rs
mobilecoind/Cargo.toml
mobilecoind/src/bin/main.rs
mobilecoind/src/config.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
mobilecoind/src/test_utils.rs
transaction/core/Cargo.toml
transaction/core/test-utils/Cargo.toml
transaction/core/test-utils/src/lib.rs
transaction/std/Cargo.toml
transaction/std/src/error.rs
transaction/std/src/transaction_builder.rs

There are a few problems with the TransactionBuilder API in regards
to fog ingest public keys.
(1) It makes the API user match public addresses with ingest public keys.
If they do this wrong, the money will not be found by the recipient.
(2) It doesn't enforce that the ingest public keys that are used are
fully validated using the type system.
(3) It doesn't enforce the rule that the tombstone block of the transaction
may not exceed the pubkey_expiry of any of the fog public keys that used.
This change makes the TransactionBuilder take a set of FullyValidatedPublicKeys
object when building transactions. This object can be populated by taking
a FogPubkeyResolver and passing that, with each recipient PublicAddress,
to the object, which caches them for a short period of time.
The cache is …

MCC-710 Final changes regarded FullyValidatedFogPubkey and TransactionBuilder

---

Cargo.lock
fog/report/validation/Cargo.toml
fog/report/validation/src/lib.rs
fog/report/validation/src/traits.rs

this causes lookup to fail during fog conformance tests
this fixes up mcc-710 #581

fix: url from public address was not normalized before lookup

---

attest/ake/src/event.rs
attest/ake/src/initiator.rs
attest/core/src/ias/verify.rs

For upcoming `mc-watcher` improvements we want to be able to store the complete attestation verification report. For that, we the AKE state machine to expose the raw report + the signature over it + the certificate chain, in addition to the parsed report data.
* Change the AKE state machine to expose the full `VerificationReport` and not just `VerificationReportData` (which can be constructed from `VerificationReport`).
* I don't think this affects SDK or `internal` but due to other pending uprev issues am not currently able to verify that.

expose the full attestation report (that also includes the signature and certificate chain)

---

Cargo.lock
connection/src/thick.rs
connection/src/traits.rs
consensus/enclave/api/src/lib.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/src/lib.rs
consensus/enclave/mock/src/mock_consensus_enclave.rs
consensus/enclave/src/lib.rs
crypto/ake/enclave/src/lib.rs
peers/Cargo.toml
peers/src/connection.rs

For the upcoming `mc-watcher` changes we want to be able to expose the `VerificationReport` that is returned as part of the attestation process to the caller, so that they could store it, or look at the data it contains.
* Changing `AttestedConnection::attest` to return the `VerificationReport`.
* Changing `peer_connect` to return the `VerificationReport`.
* Upreving `internal`, I am working on that.

expose VerificationReport in AttestedConnection

---

consensus/service/src/api/peer_api_service.rs
mobilecoind/src/service.rs
util/grpc/src/lib.rs

In another PR we found use for the `FAILED_PRECONDITION` status code
of grpc.
While touching this code, we thought it would be a good idea to make
these conversion functions (which convert Error objects to appropriate
RpcStatus objects from grpcio crate), report the Error objects
using `Display` instead of `Debug`, because all of our Error objects
implement `Display` and it's usually more readable to a human than
the `Debug` formatting. This also makes the "context" thing use `Display`
as well instead of `ToString`, since in reality almost all `ToString`
implementations come from `Display` because of the blanket implementation.

Add rpc_precondition_error, and make these use Display instead of Debug

---

Cargo.lock
api/Cargo.toml
api/src/convert/block.rs
api/src/convert/block_signature.rs
api/src/convert/tx.rs
api/src/display.rs
api/tests/prost.rs
fog/api/Cargo.toml
fog/api/test-utils/src/lib.rs
ledger/sync/Cargo.toml
ledger/sync/src/reqwest_transactions_fetcher.rs

When trying to move android-bindings and libmobilecoin into their
own workspace (to allow configuration for smaller binaries), I got
errors in mc-api due to deprecation warnings added by protobuf 2.20.
This uprevs protobuf to 2.20 and fixes all deprecation warnings in
the public repo.

Fix deprecation warning (protobuf)

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
crypto/noise/Cargo.toml

This updates some dependencies and removes unnecessary duplicate versions where possible, as half of an effort to reduce version hysteresis among different repos. There is quite a bit more future work than work in this PR, as things are blocked on large updates (e.g. rusoto going full async, rocket not having a newer version, and sentry having some API breakage that needs accounting for).
* `mc-crypto-noise` now uses `zeroize = "1.1"` (removes last use of 0.10)
* Update `flate2` (removes old versions of other crates)
* Update `base-x`, `base64`, `const_fn` to versions used elsewhere.
* Upgrade rocket 0.4 -> ?, will fix stale deps:
- hyper 0.10
- base64 0.12
- cookie 0.11
- url 1.7.2
- idna 0.1.5
- log 0.3.9
- mime 0.2.6
- percent-encoding 1.0.1
- toml 0.4.10
* rusoto -> 0.46, will rev …

MCC-2204 Some dependency Cleanup

---

Cargo.lock

While updating the `arc-swap` crate in a different repo, it became evident that the version pinned in `Cargo.lock` has been yanked. This updates that crate to the latest version in the series.
* Update arc-swap to non-yanked version 
* See if there are any other yanked crates, integrate that test into CI.

MCC-2204 Redux Update arc-swap to non-yanked version.

---

Cargo.lock
watcher/Cargo.toml
watcher/src/bin/main.rs
watcher/src/config.rs
watcher/src/error.rs
watcher/src/lib.rs
watcher/src/verification_reports_collector.rs
watcher/src/watcher.rs
watcher/src/watcher_db.rs

We'd like `mc-watcher` to support more thorough watching of the network. The first step in a series of upcoming improvements is to have it fetch the `VerificationReport` each time a new block signer is encountered, and store that in its database.
* `mc-watcher` sources are now configured via a `sources.toml` toml file. This change was necessary because we needed to introduce a map of tx source url -> consensus client url (so that when a new block is fetched from the tx source url, if a new block signer is detected, we can contact the node that created the block and get its `VerificationReport`). Passing this map via command line was gnarly, so this moved to a configuration file (similar to `network.toml` in `mc-consensus-service`)
* The `WatcherDB` now includes additional databases …

mc-watcher keeps log of attestation verification reports

---

connection/src/thick.rs
consensus/api/proto/consensus_common.proto
consensus/service/src/api/client_api_service.rs
consensus/service/src/api/peer_api_service.rs

We switched to using `block_count` to indicate the number of blocks in the ledger (as opposed to block index which is the zero-based  number of the block).
* Rename ProposeTxResponse.num_blocks to block_count 
* At some point we might want to change `LedgerDB num_blocks` to `block_count` as well.

Rename ProposeTxResponse.num_blocks to block_count 

---

mobilecoind-json/README.md
mobilecoind-json/src/bin/main.rs

mobilecoind-json's status-as-receiver endpoint currently does not take monitor id into account, resulting in only partial receiver receipt validation. This is undesirable behavior.
* Include monitor id in the status-as-receiver endpoint.

mobilecoind-json: status-as-receiver must receive a monitor id in order to validate confirmation numbers

---

mobilecoind/src/bin/main.rs
watcher/src/bin/main.rs
watcher/src/block_data_store.rs
watcher/src/config.rs
watcher/src/error.rs
watcher/src/lib.rs
watcher/src/watcher.rs
watcher/src/watcher_db.rs

For accountability reasons we'd like to have the watcher support storing the entire `BlockData` received from polling each of the configured S3 sources. That would be useful in case the S3 buckets become inaccessible for some reason.
* Add a new `BlockDataStore` object that manages storing of `BlockData`s while taking care to de-duplicate data (under normal operating conditions all blocks should be identical (except the signatures) so there is no need to store each `Block`/`BlockContents` multiple times)
* Add a new command line argument `--store-block-data`

Watcher supports storing full block data for each block received

---

Cargo.lock
fog/report/connection/Cargo.toml
fog/report/validation/Cargo.toml
watcher/Cargo.toml
watcher/src/error.rs

`failure` is deprecated.
* replace `failure` with `displaydoc` inside the `mc-watcher` crate.

watcher: failure -> displaydoc

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

* We'd like to maintain as few forks as possible.
* Switch to a commit from the official bulletproofs repository

use official bulletproofs repo that has merged the version bump change we need

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml
crypto/box/Cargo.toml
crypto/box/src/fixed_buffer.rs
crypto/box/src/hkdf_blake2b_aes_128_gcm.rs
crypto/box/src/hkdf_box.rs
crypto/box/src/lib.rs
crypto/box/src/traits.rs
crypto/box/src/versioned.rs
crypto/ct-aead/src/aes_impl.rs
crypto/ct-aead/src/lib.rs
crypto/ct-aead/src/traits.rs
transaction/core/src/fog_hint.rs

Recent testing has shown that sometimes, errors are mishandled
when using the cryptobox API. The problem is:
(1) Mac check failure is returned using a `bool`, but this doesn't
have the `#[must_use]` annotation that `core::Result` does.
(2) Cryptobox itself was still using the `Error::MacFailed` which
was supposed to go away.
(3) Cryptobox itself was not using xoloki's CtAead trait, it was
still using the variable time thing, and only the return codes
were changing.
The solution proposed is:
(1) Introduce CtDecryptResult type which is a new-type wrapper around
`subtle::Choice` which has the must-use annotation. Put this
in `mc-crypto-ct-aead` crate and use it.
Previously I was worried to use `subtle::Choice` as an API type,
but now we have doen that elsewhere and it hasn't caused churn
or …

Fixes to cryptobox API

---

watcher/src/verification_reports_collector.rs

We want the watcher to connect to enclaves no matter what their configuration is
Remove the debug flag validation

watcher should not validate the enclave DEBUG setting

---

consensus/enclave/trusted/Cargo.lock
transaction/core/Cargo.toml

`mc-transaction-core` should be as portable as possible, but it had
a dependency on `mc-crypto-rand` which is not as portable.
Getting an RNG is very hard to do portably -- the approach we use
in `mc-crypto-rand` is like, use the standard library approach and
the getrandom crate, which still requires an OS, or if you have
RDRAND instruction, use that, and selecting between these
alternatives is what `mc-crypto-rand` does basically. But this will
not work on embedded devices that don't have an OS or intel chips.
It just happens to work for all our current enclave phone and server
targets. But it may pose a portability problem if someone wanted
to build `mc-transaction-core` for a more restricted device.
Fortunately the only thing that was creating an RNG directly in
`mc-transaction-core`, …

move mc-crypto-rand to be a dev-dependency of mc-transaction-core

---

Cargo.lock

This reverts unintended `Cargo.lock` dependency version bumps from the fog signatures PR.

Revert unintended dependency bumps

---

Cargo.lock
crypto/x509/test-vectors/Cargo.toml
crypto/x509/test-vectors/src/lib.rs
crypto/x509/test-vectors/src/main.rs

Integration tests need certificate chain and private key PEM files to do their work, this provides a simple binary that will print the build-time paths for the chains and certificates generated by our x509 test vectors crate. 
Adds `mc-crypto-x509-test-vectors` utility. This utility takes a `--type` arg, which is either `chain` or `key`, and a `--test-name`, which is typically going to be `ok_rsa_chain_25519_leaf`.
* Updating integration and client tests to work with this.

FOG-372 Add test-vector path-printing binary

---

mobilecoind-json/src/data_types.rs

Soundtrack of this PR: [Clone Wars](https://www.youtube.com/watch?v=cNO3aNksUzg)
For conversions to and from various json types, cloning is useful for certain fields when passing in the src object as a reference.
* Adds derive clone to Json types
* Updates `u64` fields in a map to a `usize` where it is referring to indices
[WS-78](https://mobilecoin.atlassian.net/browse/WS-78)

Cloneable json types

---

mob

Printing of commands in the mob script shows formatted lists, which don't copy and paste into the prompt. Quick fix to display dry-run commands better.
```
sudo ./mob --dry-run prompt                                                                                                                                 
Mapping SSH_AUTH_SOCKET into container                                                                                                                        
$ cd /home/christian/Tresor/work/mobilecoin_inc/mobilecoin                                                                                                    
$ docker image pull gcr.io/mobilenode-211420/builder-install:1_15                                                                                             
$ docker …
```

Clarify the printing of commands with the dry-run option.

---

Cargo.lock
account-keys/src/account_keys.rs
fog/report/validation/src/traits.rs
util/keyfile/Cargo.toml
util/keyfile/src/bin/sample_keys_main.rs
util/keyfile/src/keygen.rs
util/keyfile/src/lib.rs

In order to perform integration testing of fog authority signatures, keys generated with keyfile need to include the proper bytes from the chain to be used.
* Removes the `--fog-authority-fingerprint` and adds `--fog-authority-root` which will take a pem certificate and extract the relevant bytes necessary for the fog authority signatures.

FOG-373 Make sample-keys take a fog authority certificate PEM

---

watcher/src/block_data_store.rs
watcher/src/watcher_db.rs

During some watcher work I ran into the need to clear all the watcher data for a given source URL. This might be useful again in the future in case the watcher is accidentally started with incorrect configuration and manual fixes are needed.
* Add a way to remove all watched data for a given source URL
* Expose this through some CLI.

watcher-db: add remove_all_for_source_url

---

crypto/x509/test-vectors/generate.sh
crypto/x509/utils/src/lib.rs
fog/sig/src/public_address.rs

Kubernetes and nginx both expect TLS certificate chains to appear in order from leaf -> root, the fog authority chain should be in the same order.
* Reverse the order of the certificates created by the test-vectors crate.
* Fix the `X509CertificateChain::verify_chain()` method to verify certs in the new order.
* Add `X509CertificateChain::verified_root()` and '::leaf()` methods to pull certs from the expected place(s).
* Users outside the repos that may be fiddling with cert chains.

FOG-376 Reverse the expected order of certs in the chain.

---

attest/core/src/ias/verify.rs
watcher/README.md

This resolves ioactive audit #MC-03, which constraints the length of EpidPseudonym to exactly the size expected (128B). This size has been verified using a recent IAS report.
* not-equals instead of less-than.
* Fix doctest in watcher

MCC-1825 Fix ioactive MC-03

---

ledger/sync/src/lib.rs
watcher/src/error.rs
watcher/src/watcher.rs
watcher/src/watcher_db.rs

It's desirable to reduce the time in takes the watcher to sync blocks. Before the change proposed in this PR, the per-block fetching time would decrease linearly as a function of how many sources are configured.
Change fetching such that for each iteration all sources are polled in parallel.
Here are timings before and after for two consecutive runs of the watcher, with a limit of 100 blocks:
```
BEFORE:
real	1m23.908s
user	0m17.555s
sys	0m0.929s
real	1m10.915s
user	0m17.217s
sys	0m1.052s
AFTER:
real	0m20.911s
user	0m17.008s
sys	0m1.092s
real	0m21.182s
user	0m17.435s
sys	0m1.018s
```
* Poll each source in parallel but independently of others. Right now the fetching time is dictated by the slowest source URL, but a more elaborate change could work around that.

watcher: fetch from multiple sources in parallel

---

Cargo.lock
Cargo.toml
slam/Cargo.toml
slam/README.md
slam/src/config.rs
slam/src/lib.rs
slam/src/main.rs

The slam tool is a load testing tool for the consensus servers.
Generally, test code should be versioned with the code under test.
This moves the slam tool to the same repo as the consensus servers,
and will make it easier to run this test in CD and more easily use
it to validate changes to the consensus servers.

Add slam tool to consensus server repo

---

fog/report/validation/src/lib.rs
mobilecoind/src/config.rs

Currently, Fog resolver normalizes uris when looking up queries,
but not when taking the set of report responses. After this commit,
it normalizes the strings to URIs on both sides.
Arguably, we should just change the `BTreeMap<String, ReportResponse>`  to `BTreeMap<FogUri, ReportResponse>`, but I think that is a more disruptive change so i was reluctant to do it that way

FOG-361: Fog resolver should normalize URIs on both sides

---

util/uri/src/traits.rs
util/uri/src/uri.rs

I ran into a bug that printed the following error message:
`Tried to send our peer list to peer insecure-igp://localhost:4301/, but despite successful status the peer list is still wrong! Expected: [insecure-igp://localhost:4300/, insecure-igp://localhost:4301/], Found: [insecure-igp://localhost:4300/, insecure-igp://localhost:4301/]`
While the URLs appear to be identical, they were in fact not. The [Display implementation](https://github.com/mobilecoinfoundation/mobilecoin/blob/master/util/uri/src/uri.rs#L86) makes them appear as if they always have a trailing slash, but the underlying [url](https://github.com/mobilecoinfoundation/mobilecoin/blob/master/util/uri/src/uri.rs#L28) might be different (`scheme://host` vs `scheme://host/`). Since the only time a trailing slash is not desirable …

default to ensuring our URLs have have a trailing slash

---

Cargo.lock
Cargo.toml
sgx/css-dump/Cargo.toml
sgx/css-dump/README.md
sgx/css-dump/rustfmt.toml
sgx/css-dump/src/main.rs
sgx/css/src/lib.rs

Tracking down attestation failures during debug sessions typically results in discovering a mismatch between the expected MRENCLAVE or MRSIGNER and the enclave that is actually running, and most folks are compiling with a SIGSTRUCT file, not the `.signed.so` enclave binary itself. Intel provides no utilities to read this SIGSTRUCT file, so this will read it and output it using our SGX code.
* Implements `mc-sgx-css-dump` binary.
* Adds some missing accessors to the `mc_sgx_css::Signature` type to replicate the debug printf of Signature.
* Figure out a nice way to support debug print options in custom implementations, e.g. pretty-printing with hash...

MCC-2266 Utility to debug-print a signature

---

ledger/sync/src/ledger_sync/ledger_sync_service.rs

* We'd like to have a better understanding of where time is spent during some ledger sync operations.
* A minimal effort to trace some time durations at some key parts of the ledger sync process.

add some trace_time calls to ledger sync

---

consensus/service/src/consensus_service.rs

* consensus service should support processing client requests in parallel. For whatever reason, it is currently configured to have a worker pool of size 1.
* Remove the worker thread pool limitation
This passed deployment: https://deploybot.canadacentral.mobilecoin.com/blue/organizations/jenkins/mobilecoin-internal/detail/deploy%2Feran/184/pipeline

remove unnecessary cq_count

---

mobilecoind-json/src/data_types.rs

Soundtrack of this PR: [Right Now](https://www.youtube.com/watch?v=DLQawHJ38Sc)
The current block response in mobilecoind-json doesn't include the block contents.
* Adds txos and key_images to the block response in mobilecoind-json
#743 
[MCC-2251](https://mobilecoin.atlassian.net/browse/MCC-2251)

Add key images and txos to block response

---

account-keys/slip10/src/lib.rs
account-keys/slip10/src/mnemonic2slip.py
account-keys/slip10/src/testvectors.py

We currently allow the caller to use any BIP-32 path when deriving a SLIP-0010 ed25519 "private key" from a mnemonic seed. We should enforce proper BIP-44 with an account index, akin to how Stellar is doing this for their currencies (and seemingly how monero also does this stuff).
* Make `Slip10KeyGenerator::derive_slip10_key()` only take an account index.
* Make `Slip10KeyGenerator::derive_slip10_key()` infallible
* `impl From<Mnemonic> for Slip10Key` using a zero account-index.
* Update test-vector generation
* Add slip10's testvectors.py for reference.
* Spec integration

MCC-2284 Enforce proper BIP-44 path for slip10 derivation

---

Cargo.lock
api/proto/printable.proto
api/src/display.rs
mobilecoind-json/src/bin/main.rs
mobilecoind-json/src/data_types.rs
mobilecoind/Cargo.toml
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

We're moving away from root entropy and into using a string mnemonic and we'd like `mobilecoind` (and `mobilecoind-json`) to reflect this change.
* Update the `mobilecoind` and `mobilecoind-json` APIs to support generating a string mnemonic and deriving an `AccountKey` from it.
* Transfer codes ("gift codes") need to be migrated into using the new bip39 entropy.

Initial mnemonic support for mobilecoind

---

api/proto/printable.proto
api/src/display.rs
mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/service.rs

We're moving away from the old "root entropy" account key derivation to the new bip39/slip10 derivation. We'd like the transfer codes ("gift codes") generated by `mobilecoind` to use the new scheme. 
* Change `mobilecoind` to use the bip39/slip10 key derivation for gift codes while continuing to support old gift codes generated using the old root entropy scheme.

mobilecoind: Switch transfer codes to use bip39 entropy

---

Cargo.lock
ledger/sync/src/reqwest_transactions_fetcher.rs
mobilecoind/src/bin/main.rs
watcher/Cargo.toml
watcher/src/bin/main.rs
watcher/src/config.rs
watcher/src/error.rs
watcher/src/watcher.rs
watcher/src/watcher_db.rs

Make ReqwestTransactionsFetcher support caching of merged blocks when fetching by block index.
Use rayon to parallel fetch transactions.
Watcher performance is suboptimal and there are some low hanging fruits for speeding it up. Following this PR it takes `mobilecoind` with watcher enabled about 3.5 minutes to fully sync the ~155k blocks of test net.
* Make `ReqwestTransactionsFetcher` support using merged-blocks/caching when fetching blocks identified only by their block index (as opposed to the entire `Block` object). This substantially reduces the amount of S3 requests needed (in favor or fewer, larger object fetches)
* Switch to using `rayon` for parallel fetching instead of using a home-made solution.
* Turn …

Speed up watcher syncing

---

tools/local-network/local_network.py

The fog local network script is currently broken and this is part of the fix for it.
* Change the local network python script to build two utilities that are useful for local testing.

build mc-slam and mc-crypto-x509-test-vectors as part of local network script

---

mobilecoind/src/error.rs
mobilecoind/src/monitor_store.rs
mobilecoind/src/utxo_store.rs

A newer version of `clippy` is going to complain about `Error::LMDB`, saying that it should be `Lmdb`. In an attempt to reduce the number of changes needed when we upgrade rust, I PRing the backwards-compatible ones in advance.
* Search and replace `LMDB` with `Lmdb`
* Do the same in other repos.

LMDB -> Lmdb (since a newer rust version complains about the LMDB enum variant)

---

ledger/db/src/lib.rs
transaction/core/src/blockchain/block.rs
transaction/core/test-utils/src/lib.rs

Scheduled hardforks should be tracked on-chain (note: any change to validator enclaves requires a scheduled hardfork). Currently the only version number available is the block header version. Originally this was intended to represent the block header format version, however block header format version changes can be subsumed under the overall hardfork version (i.e. the protocol version). Since the current header version is `0`, repurposing the version number to represent the hardfork version is semantically harmless.
This PR prepares a new block version for whenever the hardfork that goes v0 to v1 occurs. Note that this PR is a breaking change (will alter the validator enclave MRENCLAVE).
This PR also adds a …

Increment block version for next scheduled hardfork (v0 -> v1)

---

consensus/scp/src/slot.rs
ledger/db/src/tx_out_store.rs
transaction/core/src/ring_signature/mlsag.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs
transaction/core/src/validation/validate.rs

New `clippy` identified a few places where we use `format!()` unnecessarily, so here's a PR to get rid of that.

remove unnecessary format! calls

---

attest/core/build.rs
consensus/scp/src/scp_log.rs
consensus/service/src/bin/main.rs
ledger/db/src/lib.rs
ledger/db/src/metrics.rs
ledger/distribution/src/main.rs
ledger/from-archive/src/main.rs
ledger/sync/src/test_app/main.rs
mobilecoind/src/bin/main.rs
mobilecoind/src/test_utils.rs
slam/src/main.rs
transaction/core/test-utils/src/lib.rs
util/generate-sample-ledger/src/lib.rs
util/keyfile/src/keygen.rs
watcher/src/bin/db-dump.rs
watcher/src/bin/main.rs
watcher/src/watcher_db.rs

The newer clippy prefers `Path` objects, as `PathBuf` implements `AsRef<Path>` and this allows to save a bunch of `.clone()`s and `.to_path_buf()` calls.
* Use `Path` where appropriate.

Prefer Path over PathBuf

---

attest/core/src/quote.rs
attest/trusted/src/lib.rs
connection/src/thick.rs
crypto/keys/src/ristretto.rs
util/repr-bytes/src/lib.rs
util/uri/src/traits.rs

Make future `clippy` happy.
* There are a few instances where we use the question-mark operator unnecessarily. This PR removes them.

remove unnecessary question-mark operator  

---

connection/src/manager.rs
consensus/service/src/byzantine_ledger/mod.rs
consensus/service/src/byzantine_ledger/worker.rs
consensus/service/src/config.rs
ledger/db/src/test_utils/mock_ledger.rs
ledger/sync/src/ledger_sync/ledger_sync_service.rs
ledger/sync/src/network_state/scp_network_state.rs
mobilecoind-json/src/data_types.rs
mobilecoind/src/conversions.rs
mobilecoind/src/payments.rs
peers/test-utils/src/lib.rs
util/build/script/src/env.rs

Future clippy prefers `.collect()` over `::from_iter()`.
* Switch to `.collect()` where possible.
* Some small misc changes (see specific comments)

replace from_iter with collect where possible

---

transaction/core/src/amount/mod.rs
transaction/core/src/lib.rs

This slightly refactors the `get_value_mask` function to return the u64
mask instead of a Ristretto scalar. This is because the u64 is what
all of the callers need and use, so there is less code duplication
if the function actually returns that.
This also makes the `get_value_mask` function exposed as part of the
public transaction-core API. This is because it is needed in fog,
to support a version of TxOut's where we don't store the compressed
commitment in Fog, and instead the user reconstructs that from the
other data in the TxOut.

Expose the `get_value_mask` function of `transaction_core::amount`

---

Cargo.lock
ledger/db/Cargo.toml
ledger/db/src/error.rs
ledger/db/src/lib.rs
ledger/db/src/tx_out_store.rs
ledger/sync/src/ledger_sync/ledger_sync_error.rs
ledger/sync/src/ledger_sync/ledger_sync_service_thread.rs
transaction/core/src/blockchain/block_id.rs

During some upgrade experiments we learnt that if LedgerSyncService repeatedly fails to append a block due to an incompatible version number, nothing useful is logged. This PR improves that situation.
* More explicit mc-ledger-db Error variants
* failure -> displaydoc
* Explicit logging of failed attempt_ledger_sync calls

Make ledgerdb errors more verbose, log ledger sync errors

---

consensus/enclave/measurement/build.rs
ledger/db/src/lib.rs
transaction/core/src/blockchain/block.rs

Bumping the block version represents a breaking change to clients, and the impetus to bump the block version is a semantic change to this field. This updates the release branch to revert this change.
* Revert the actual block version bump, while keeping the rest of PR 
* Re-designing the ledger to handle changes in an extensible way.

Undo block version bump

---

mobilecoind/api/proto/mobilecoind_api.proto
mobilecoind/src/payments.rs
mobilecoind/src/service.rs

The UTXO optimziation selection function was still using (and returning) a hard-coded fee, this makes it use a provided fee instead, and plumbs that fee back out to gRPC
* Makes `TransactionManager::select_utxos_for_optimization()` take a fee amount, rather than return it.
* Adds a `fee` argument to `TransactionManager::generate_optimization_tx()`.
* Adds a `fee` field to the `GenerateOptimizationTxRequest` gRPC message.

Fix fees in TransactionManager::select_utxos_for_optimization

---

ledger/from-archive/src/main.rs

Soundtrack of this PR: [I love it](https://www.youtube.com/watch?v=UxxajLWwzqY)
Ledger-from-archive is painfully slow, especially on TestNet at 160K blocks currently
* Leveraging merged blocks and caching in ReqwestTransactionsFetcher to speed up fetching

make ledger-from-archive faster by utilizing the merged block/caching support in ReqwestTransactionsFetcher

---

mobilecoind/src/payments.rs
slam/src/main.rs

The fallback fee for mobilecoind and slam should be the current fee, not the (newly lowered) fee, fix current clients sending tx to old networks.
* Add a FALLBACK_FEE constant to the relevant apps, and make that the one that's used.
* This can be removed after the 1.1 enclaves have been released.

Use 10mMOB as a fallback fee

---

.circleci/config.yml

Dont do cargo check, because it doesn't link anything. We want
to test in CI that linkage actually works, particularly, linking
against the various C libraries that we use, like mbedtls.

When we test that the code builds, actually build

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

Unfortunately `mbedtls` contains some piece of code we don't need that will not compile on 32-bit targets (that we need to support). This PR uprevs `mbedtls` to include a [workaround](https://github.com/mobilecoinofficial/rust-mbedtls/commit/c7fa3f0c737f36af8f437e147131d1f5c8a90b0e).
Edit: @jcape also noticed that the `grpcio` fork we switched to unnecessarily downgraded `boringssl-src`, so I fixed that as well.

update mbedtls again to work around 32 bit build issues

---

attest/core/src/lib.rs

Intending to support clients connecting to a "Pre-Production" environment, we were setting `DEBUG_ENCLAVE` conditionally, based on whether or not debug assertions were enabled. This has the surprising effect of allowing verifiers compiled in debug mode with `IAS_MODE=PROD` set to allow debug-mode enclaves to verify.
Additionally, now that IAS DEV and "LIV" (PROD) environments both use the same root authority, DEV vs. PROD is sufficient to distinguish whether debug enclaves are supported or not.
We should just remove the conditional and simply make PROD builds always reject debug enclaves, because it removes a footgun.
* Make `DEBUG_ENCLAVE` always `false` when not built with the `sgx-sim` or `ias-dev` features.

Always set DEBUG_ENCLAVE to false in IAS prod mode.

---

crypto/box/README.md

This wasn't updated properly when we switched to AES-256-GCM
Fixes #789

update cryptobox readme to refer to AES-256-GCM

---

consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

The master branch is currently producing a `SIGILL` when trying to verify the quote given by a quoting enclave. None of the CPUs we expect to run an enclave on will support the SHA-NI instructions anyways.
* Disable the `asm` feature from the `sha2` crate (should never be used anyways)

Consensus enclaves don't run on sha-ni chips right now.

---

consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml

Due to issues with cargo feature unification, which is seemingly only exposed (sadly) when running on an actual enclave, we need to make our patches to `cpufeatures` just use `target_features` directly.
* Update our crates.io patch of `cpufeatures` to one which works in our environment.
* Create test case and report issue to cargo
* Get a reasonable patch for cpufeatures upstreamed after cargo issue is fixed.

Update cpufeatures fork

---

.circleci/config.yml

PRs to master are still failing, due to a bug / change in `cargo trim` (the `--directory` argument doesn't appear to function)
* Run `cargo trim init` in the top-level and trusted enclave directories directly.

Work around broken cargo trim -d

---

mobilecoind/clients/python/cli/benchmark.py
mobilecoind/clients/python/cli/check_balance.py
mobilecoind/clients/python/cli/get_public_address.py
mobilecoind/clients/python/lib/mobilecoin/client.py
mobilecoind/clients/python/mailchimp/allocate_mobilecoins.py

Since protocol added mnemonic entropy.
Soundtrack of this PR: [Skeleton](https://www.youtube.com/watch?v=-dl2JmOLwtI)
Python client library crashes with current version of API, since #779 
* A simple update to the Python code to reference the current mobilecoind protocol.
* Backwards-compatible with jupyter example.
* Probably belongs in #592 
* Update jupyter notebook example to use mnemonics by default.

Update Python client library to reflect changes to protocol.

---

deploy/00-node-grpc-ingress.yaml

Soundtrack of this PR: [RJD2: The Proxy](https://www.youtube.com/watch?v=LjYo0cwXLWM)
Ingress objects are very opinionated in CD.  This change allows for either an nginx or haproxy ingress controller.
* Updated annotations to configure an HAProxy ingress controller to use HTTP-2/gRPC
* Nothing planned.

Update ingress manifest to include HAProxy annotations

---

consensus/service/src/tx_manager/mod.rs
transaction/std/src/transaction_builder.rs

The tombstone block is defined in the transaction-core on transaction object docstring to mean:
"The block index at which this transaction is no longer valid."
https://github.com/mobilecoinfoundation/mobilecoin/blob/766f4078e000314a2ff9e8ea44a76f1c36fe7853/transaction/core/src/tx.rs#L162
However, in some places in the code it instead means, the block index
*after* which this transaction is no longer valid.
The TxManager prunes a Tx if the tombstone block exceeds the current block index, but not if it equals the current block index:
https://github.com/mobilecoinfoundation/mobilecoin/blob/103aa92bb0c8934d26de01b16c2ef1cbeebe3c95/consensus/service/src/tx_manager/mod.rs#L155
The `TransactionBuilder` (before this commit) documents
```
/// The tombstone_block value, a block index after which …
```

Documentation and minor bug fix around tombstone block

---

transaction/std/src/transaction_builder.rs

This helps SDKs which may want to support using multiple
MemoBuilder types, because they can have one (e.g. java) type that represents
a type-erased `MemoBuilder`, which is then passed to the java constructor
for representation of `TransactionBuilder`. Then different java functions
can create differently typed instances of `Box<dyn MemoBuilder>`

Add a constructor for TransactionBuilder which takes Box<dyn MemoBuilder>

---

consensus/service/src/byzantine_ledger/worker.rs

This is a merge and update of https://github.com/mobilecoinfoundation/mobilecoin/pull/770
The API of the `PendingValues` object changed since that PR was created, but this test is pretty important and we need to land it.
This merges that PR and then fixes up the issues.

Merge mfaulk 2247

---

Cargo.lock
Cargo.toml
consensus/enclave/trusted/Cargo.lock
consensus/enclave/trusted/Cargo.toml
fog/ingest/enclave/trusted/Cargo.lock
fog/ingest/enclave/trusted/Cargo.toml
fog/ledger/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.toml
fog/view/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.toml

See commit message:
https://github.com/mobilecoinofficial/rust-mbedtls/commit/d0c2aea8700bf151951bf48daa9ac4724df924a0
This is an alternative to the hackier fix that was removing object
code manually from the `libmobilecoin_stripped.a` in the libmobilecoin
makefile

Use rust-mbedtls that has linker fix backported from upstream

---

fog/test_infra/src/lib.rs

Soundtrack of this PR: [https://www.youtube.com/watch?v=zF5gcEQVxL4]()
This test: cargo test -p mc-fog-ingest-server --test tx_recovery 
was failing on my machine saying 'test_ingest_sql' panicked at 'users did not converge to ledger_db.num_blocks before we ran out of retry attempts', and it seems to be due to a race condition where there are insufficient retries. It seems sufficient to resolve this by increasing the number of retries.
I increased the number of retries.
Potentially useful to configure for the machine if this varies between devices.

Increasing the number of retries to get tx_recovery test to pass.

---

Cargo.lock
common/Cargo.toml
consensus/enclave/trusted/Cargo.lock
fog/ingest/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.lock

There have been multiple revisions to `hashbrown`, this updates our usage to 0.11, and therefore our `HashMap`/`HashSet` in enclaves. This also removes the last user of `autocfg` 0.1.7, which means we only have to compile one version of that crate now.
* Update `hashbrown`

Bump hashbrown to 0.11.

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
consensus/service/Cargo.toml
fog/ingest/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.lock
fog/report/cli/Cargo.toml
fog/view/enclave/trusted/Cargo.lock
util/encodings/Cargo.toml
util/grpc/Cargo.toml
util/uri/Cargo.toml

This upgrades our usage of base64 to use v0.13, which reduces the users of the older 0.12 crate to just `reqwest`.
* Upgrade `base64` crate to 0.13.

Update base64 to 0.13.

---

Cargo.lock
util/logger-macros/Cargo.toml
util/logger-macros/src/lib.rs

This PR updates the `mc-util-logger-macros` crate to use the 1.0 releases of `proc-macro2`, `quote`, and `syn`.
* Update `proc-macro2`, `quote`, and `syn`

Update proc-macro2, quote, and syn to 1.0

---

Cargo.lock
crypto/keys/Cargo.toml

The tests in `mc-crypto-keys` depend on a beta release of the `semver` crate, this bumps the dependency to 1.0.
* Bump `semver` dependency to 1.0

Update semver to 1.0

---

Cargo.lock
attest/core/Cargo.toml
attest/net/Cargo.toml
common/Cargo.toml
consensus/enclave/trusted/Cargo.lock
crypto/digestible/Cargo.toml
crypto/rand/Cargo.toml
fog/ingest/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.lock
sgx/compat/Cargo.toml
sgx/slog/Cargo.toml

This updates all our direct usage of the `cfg-if` crate to the 1.0 stable release. This leaves `rusoto`, `serial_test`, and `slog` as remaining users.
* Update all our direct `cfg-if` uses to 1.0

Update all our usages of cfg-if to 1.0

---

Cargo.lock
common/Cargo.toml
common/src/logger/loggers/mod.rs

This PR updates the `hostname` dependency of `mc-common` (used when constructing loggers in untrusted space) to 0.3.1. This removes the last user of hostname 0.1, which means we only need to build one version of that crate.
* Update `hostname` to 0.3.1

Update hostname to 0.3.1

---

consensus/enclave/impl/src/lib.rs
fog/ledger/server/src/merkle_proof_service.rs
ledger/db/src/tx_out_store.rs
transaction/core/src/onetime_keys.rs
transaction/core/src/tx.rs

The documentation in `onetime_keys.rs` explains that the term
`onetime public key` comes from cryptonote papers, and is also called
the "target key". However, in the `TxOut` object, we have gone with
the name `target_key`, while in many functions in `onetime_keys.rs`,
it is still called `onetime_public_key`.
This makes it much more difficult to read and use this code, because
there is no type safety that ensures that `onetime_public_key` is not
used with `tx_out.public_key` rather than `tx_out.target_key`, and
searching for `onetime_public_key` only gives very few hits in the
source code, so you have to read all of the documentation to figure
out how to use any of these functions correctly.
By changing the function names, and input parameter names, to things
like `tx_target_key`, we make …

Make transaction-core code call it "tx_target_key" and not "onetime_public_key"

---

Cargo.lock
libmobilecoin/Makefile

We want to build `libmobilecoin` for the new M1 targets.
* Bump version of `cc` crate because we need https://github.com/alexcrichton/cc-rs/commit/178fd031e74f643721605e25110ee6abce8dbe05
* Add new targets and stop using `lipo` in `libmobilecoin/Makefile`
Note that currently the build only works for all targets on an Intel Mac. `x86_64-apple-ios` and `x86_64-apple-darwin` fail on an M1 due to weird linker issues.
* Make all targets buildable on an M1 mac

Libmobilecoin M1 fixes

---

android-bindings/src/bindings.rs
libmobilecoin/libmobilecoin_cbindgen.h
libmobilecoin/src/transaction.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
slam/src/main.rs
transaction/core/src/tx.rs
transaction/core/src/validation/validate.rs
transaction/std/src/lib.rs
transaction/std/src/memo_builder/mod.rs
transaction/std/src/memo_builder/rth_memo_builder.rs
transaction/std/src/transaction_builder.rs

In testing, we discovered that old clients are unable to submit
transactions to new servers, even if the MRENCLAVE value is up to date.
This is because the entire TxPrefix is under the ring signature in the
transaction math, and the TxPrefix is different whether or not a memo
is there. An old server has protobufs that don't include the memo field,
so they compute the hash of the TxPrefix differently from clients that
included an empty memo.
To make this go, we decided to release this change in two steps.
First, we make versions of the servers that tolerate the presence of
the memo and compute the TxPrefix hash in the same way as the clients,
but also accept the state of affairs that there are no memos.
Existing clients can thus continue to work with this server simply by
updating the …

Make Encrypted memo changes releasable

---

Cargo.lock
attest/core/Cargo.toml
consensus/enclave/trusted/Cargo.lock
fog/ingest/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.lock

See: https://github.com/mobilecoinfoundation/mobilecoin/pull/953

Bump chrono to 0.4.19.

---

Cargo.lock
attest/core/Cargo.toml
consensus/enclave/trusted/Cargo.lock
fog/ingest/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.lock

This reverts commit f56a1020f176bc6fe6c3dcf4e8db08686214b20c.
The most recent merge introduces a dependency conflict, because nix 0.22.1 depends on bitflags < 1.3, for MSRV reasons. This reverts the bitflag bump, which we can re-introduce after [nix 0.23 is released](https://github.com/nix-rust/nix/issues/1510), hopefully within the next few days.

Revert "Bump bitflags from 1.2.1 to 1.3.2 (#1016)"

---

.github/dependabot.yml

At the moment, dependabot will create a maximum of 10 PRs in each of the enclaves and the root. This often results in multiple broken PRs, as changes to an enclave need to touch the upstream Cargo.lock as well. Originally, this resulted in us saying "oh, well, don't scan the enclaves," but this causes issues with dependencies that *only* exist in the enclave never getting updated.
This will change that so updates which will trigger PRs in multiple workspaces will be more likely to have a PR against the "root" that we can work in (and close the others).
* Bump root limit to 25, reduce enclave limit to 5

Fiddle with dependabot PR limits

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
crypto/keys/Cargo.toml
crypto/keys/src/ristretto.rs
fog/ingest/enclave/api/src/lib.rs
fog/ingest/enclave/impl/src/lib.rs
fog/ingest/enclave/src/lib.rs
fog/ingest/enclave/trusted/Cargo.lock
fog/ingest/server/src/controller.rs
fog/ledger/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.lock

[FOG-180](https://github.com/mobilecoinfoundation/fog/pull/116/files#diff-1bd75fa7d4e53379b9fe76ed5de3edd920c698f1d188a08ae34d2ba9fb414247R212) introduced logic to check if a user's private key had changed. This check introduced additional calls across the enclave border, which increases latency. 
* fog-ingest-enclave `set_ingress_private_key` function returns bool that indicates if the key changed or not.
* fog ingest server controller uses this returned value to decide whether or not to seal the private key to disk.
The `set_ingress_private_key` function runs inside the enclave, so the logic that decides if the key changed or not needs to be constant time. As such, I implemented `subtle::ConstantTimeEq `for `RistrettoPrivate`. 
Fixes this …

Make fog-ingest-enclave `set_ingress_private_key` function return bool

---

Cargo.lock
fog/sample-paykit/Cargo.toml
fog/sample-paykit/src/cached_tx_data/mod.rs
fog/sample-paykit/src/client.rs
fog/sample-paykit/src/error.rs
fog/test-client/src/test_client.rs
mobilecoind/src/utxo_store.rs

The current implementation of the sample paykit makes the incorrect assumption that all TxOuts are on the default subaddress index (0). However, at some point, we started sending change outputs to subaddress index 1.
For this to work properly the sample paykit needs to support tracking of which subaddress index each TxOut it is aware of belongs to, and use that information when generating transactions (and key images).
* Make the sample paykit support tracking subaddress indices, similar to how mobilecoind and full-service do it.
* Make sample paykit use that information to properly construct transactions.
* The Swift and Android SDKs have the same problem and need to incorporate similar changes. I will reach out to @voloshyn to coordinate the work on this.
* Even after this …

Fix sample-paykit subaddress index handling

---

.gitignore
libmobilecoin/Makefile

Add support for Apple's `Bitcode` and reduce the size of our SDK & its dependencies. With this enabled the compressed "downloadable" size **shrinks by ~25%.**  
```
App Thinning Size Report for All Variants of Example
App + On Demand Resources size: 7.2 MB compressed, 19.7 MB uncompressed
App size: 7.2 MB compressed, 19.7 MB uncompressed
```
```
App Thinning Size Report for All Variants of Example
App + On Demand Resources size: 9.6 MB compressed, 35.6 MB uncompressed
App size: 9.6 MB compressed, 35.6 MB uncompressed
```
Shallow clone [`rust-bitcode`](https://github.com/mobilecoinofficial/rust-bitcode) to compile `rustup` toolchains that include LLVM compatible with Apple's Xcode build system.
Remove "symbol" stripping step from the `Makefile` because it's not compatible with enabling …

[🍒  pick] Bitcode for `release-1.2.0`

---

fog/ingest/client/tests/sync_keys_from_remote.rs

The "sync_keys_from_remote" test, which was added in #1139, intermittently fails during CI runs. The error message is: `process didn’t exit successfully: /root/project/target/debug/deps/sync_keys_from_remote-df5d33ac3e128cd9 (signal: 11, SIGSEGV: invalid memory reference)`. 
* Retain the db test context after the test's set up method. This ensures that the underlying SQL db won't be dropped.
We think that retaining this DB will mitigate the chance of this segfault, but if it doesn't then we'll consider adding (a) logging or (b) investigate using gdb on the CI machines.

Ensure underlying SqlRecoveryDb is not dropped during sync_keys_from_remote test

---

.circleci/config.yml

When a flaky fog tests fail due to segfaults, there is no easy way to grab the core dumps from the CircleCi machine. To complicate matters further, even if you ssh into the CircleCi machine, the test may not fail during multiple runs. 
* Stores core dumps produced by the "Run fog tests" action as a CircleCi build artifact. Follows this implementation [guide](https://circleci.com/docs/2.0/artifacts/#uploading-core-files).
Fixes [ticket](https://app.asana.com/0/1200353042931237/1201321243869915/f).

Store fog test core dumps as CircleCi build artifacts

---

Cargo.lock
util/keyfile/Cargo.toml
util/keyfile/tests/b58-length.rs

Some exchanges use `VARCHAR(255)` for cryptocurrency public addresses, and it is difficult for them to migrate their SQL DBs.
We want that the mobilecoin b58 printable wrapper address strings are always within 255 bytes.
This imposes a limit on how long the fog report url can be.
The purpose of this test is to experimentally determine exactly what the limit is.
The test uses repetition because b58 encoding length isn't determined completely by payload length, it depends on what bytes are in the payload. So we try it with several choices of the mobilecoin private keys.
The test ensures that:
* Any domain less than the limit leads to a public address less than the 255 limit, trying private keys ten times
* Any domain at or more than the limit does violate the 255 limit at least sometimes, …

add tests for maximum fog domain vs. 255 b58 pub address limit

---

fog/test-client/src/counters.rs

it looks that we don't have to modify `OpMetrics` to do this, we can just use the prometheus macros `register_histogram`, which was already exported from `mc-util-metrics`. because they are registered with prometheus library when we use the macro, calls elsewhere to `prometheus::gather` will pick up these histograms

set custom buckets for test-client tx time histograms

---

Cargo.lock
fog/api/proto/ingest.proto
fog/ingest/client/Cargo.toml
fog/ingest/client/src/config.rs
fog/ingest/client/src/lib.rs
fog/ingest/client/src/main.rs
fog/ingest/client/tests/get_ingress_key_records.rs
fog/ingest/server/src/controller.rs
fog/ingest/server/src/ingest_service.rs
fog/recovery_db_iface/src/lib.rs
fog/sql_recovery_db/src/lib.rs
fog/view/server/src/db_fetcher.rs

The ops team has requested a "fog_ingest_client" CLI API that allows them to list all of the ingress public keys for the fog system. 
* Exposes this API. Ingress keys can be filtered by start block, lost status, and retired status.
Fixes this [ticket](https://app.asana.com/0/1200353042931237/1200512973791588/f).
* Potentially exposes more CLI options that filter the ingress keys even more.

Expose "get_ingress_key_record" API in the "fog_ingest_client" CLI

---

.circleci/config.yml

the tests run locally in 1 minute instead of 29 minutes when we
use --release, so this may improve performance in CI also. the
reason for the performance gain is that all the ORAM servers are
much faster when compiled in release mode
(see stats here: https://github.com/mobilecoinfoundation/mobilecoin/pull/1157)

run fog conformance tests in release mode

---

Cargo.lock
fog/enclave_connection/Cargo.toml
fog/enclave_connection/src/error.rs
fog/enclave_connection/src/lib.rs
fog/ledger/connection/Cargo.toml
fog/ledger/connection/src/error.rs
fog/ledger/connection/src/key_image.rs
fog/ledger/connection/src/merkle_proof.rs
fog/sample-paykit/src/cached_tx_data/memo_handler.rs
fog/sample-paykit/src/cached_tx_data/mod.rs
fog/view/connection/Cargo.toml
fog/view/connection/src/lib.rs

This addresses many old tickets, and I developed this while trying
to figure out why the test client failed with seemingly retriable errors
There is a large amount of tech debt to resolve the discrepancy
between mc-connection and mc-fog-enclave-connection. They are mostly
supposed to be doing the same thing, but `mc-fog-enclave-connection`
is generic over a protobuf client object that could be ledger key image, merkle proof, or view
(or consensus user tx conceivably). OTOH the mc-connection objects
have been used in production and support more features like the credentials
provider, and before now, doing retries with the retry crate for
connection / attestation issues.
This does not attempt to resolve that issue for now, but it does port
forward the retry aspect of this from …

Add retries to many fog enclave connections using retry crate

---

common/src/logger/mod.rs

these macros, `log_assert`, `log_assert_eq`, etc. are not used
anywhere in the codebase.
these macros are harmful because the panic handler already logs
the panic to the logger, so using these macros means that you
actually log the assert failure twice. I believe that this may
be why no one is actually using this.
Since this is dead code we should delete it.

remove unused logging macros

---

common/src/logger/mod.rs
fog/ledger/server/src/key_image_service.rs
util/grpc/src/lib.rs

Log messages with the level Error (e.g. `log::error!`) get forwarded to Sentry. The way we handle returning GRPC errors involves logging, and that used the error level for all scenarios, even ones that are common and not actionable. This results in many thousands of events being submitted to Sentry unnecessarily.
* Degrade a bunch of grpc-related log messages to a less severe level, causing them not to go out to Sentry.
* Fix an error handling case to return the correct grpc error code

Less aggressive grpc logs

---

consensus/service/src/tx_manager/mod.rs

Being `error!`, this log message finds its way to Sentry, but there is nothing to do about it. Its useful for debugging so I want to keep it, and I am not 100% sure why we're seeing it but still no need to have it ship to Sentry.
* `error!` -> `warn!`
* Investigate the cause of this (it is likely fine)

Downgrade a noisy log that is not currently actionable

---

fog/ingest/server/src/controller.rs
fog/recovery_db_iface/src/lib.rs
fog/sql_recovery_db/src/error.rs
fog/sql_recovery_db/src/lib.rs
fog/test_infra/src/db_tests.rs
fog/view/server/tests/smoke_tests.rs

As described in this [ticket](https://app.asana.com/0/1200353042931237/1201342064475415/f), "when ingest creates a new ingress key, it can specify any start_block value, and it currently does this using ledger_db.num_blocks(). But if its ledger_db is slow (because of a race), then this value may be very low, much older than the actual current number of blocks."
* At the DB level, enforce that a new ingress key can't specify a start block that's higher than the highest known block index
Fixes requirement 1 of this [ticket](https://app.asana.com/0/1200353042931237/1201342064475415/f). 
* Investigate if fog view should retrieve the highest known block count from the DB

Prevent ingress keys from using start block higher than highest known

---

Cargo.lock
util/build/info/Cargo.toml
util/build/info/build.rs

the build info crate records build info, like environment variables
that configure the build, so that targets can log them and such
however, i notice that oftentimes the info can be wrong, especially
in local testing, e.g. SGX_MODE or IAS_MODE not matching the actual
build.
it turns out the build.rs did not emit cargo's rerun-if-changed
directives, so cargo doesn't regenerate the file if one of these
variables changes
this commit may reduce confusion

try to fix build info crate

---

util/grpc/src/lib.rs

Currently, both Error and Critical get forwarded to sentry and cause
sentry alerts. However, most attestation errors are logged at Error
level, as well as other client-triggered "errors" that usually
represent the normal operation of the system.
This commit makes attestation errors and "invalid arg" errors (that
don't necessarily indicate a server problem) logged at debug level.
It makes general "enclave errors" which get mapped to permission denied
normally, logged as warn level only. We should revisit this in the future
and try to break down those error levels in a more granular way.
This commit is intended for 1.1.2 maintenance release and is based off
the v1.1.0+ tag.

Use less severe log levels for server levels that aren't usually actionable

---

consensus/service/src/tx_manager/mod.rs

While doing some research work on extending the type of transactions we can run consensus on I encountered this piece of code that was repeated in two places and was a bit un-ergonomic due to resulting in `Vec<Option<CacheEntry>>` instead of `Vec<CacheEntry>`.
Add a utility method to perform the `TxHash` -> `CacheEntry` resolution and use it in the two places that currently do that.

DRYs up resolving TxHashes into CacheEntries inside TxManager

---

Cargo.lock
connection/src/thick.rs
connection/src/traits.rs
fog/test-client/Cargo.toml
fog/test-client/src/bin/main.rs
fog/test-client/src/config.rs
fog/test-client/src/counters.rs
fog/test-client/src/test_client.rs

* it is helpful to have the `--ingest-enclave-css` arguments
in the admin server json blob, so we can't use `Option<Signature>`
in structopt with `serde(skip_serializing)`, we have to go back to `Option<String>`.
But this is still nicer after we get load_css_file from another crate.
* It is confusing to have the flag be `--fog-ingest-enclave-css`
and the env be `INGEST_ENCLAVE_CSS`, they should match
* We want to have a really easy metric to alert on, so we use
`IS_HEALTHY`, which is 1 when things are working and 0 when any
of the accounts failed its last transfer. (This means that
the "time window" after we which we consider ourselves healthy
is determined by num_clients * transfer_period.)
* When a transfer fails, but the tx was accepted to the chain,
log the block and the public keys …

More fixups from discussion with jason

---

fog/ingest/client/src/main.rs
fog/ingest/server/src/worker.rs

* ingest server says "Checking up on peer..." instead of
"peer checkup period exceeded" because the latter sounds like
an error
* fog ingest client pretty prints its json results instead of
dense json, because this is usually what an operator wants, and
currently people are piping things to jq, but then you also have
to filter out the log statements that the client emits

minor quality of life improvements in fog

---

consensus/service/src/api/peer_api_service.rs
fog/ingest/server/src/ingest_peer_service.rs
fog/ingest/server/src/ingest_service.rs
util/grpc/src/lib.rs

This commit starts from the idea that `rpc_enclave_err` is wrong.
Usually, an enclave error is a complex enum containing numerous
possible failure modes. Some of these may be SGX errors that are
not retriable and may represent internal errors. However,
attestation errors must be mapped to "permission denied" to trigger
re-attestation on the clients. Deserialization errors might represent
invalid arg, or might represent an error internal to the server
depending on which payload couldn't be deserialized.
Moreover, each enclave error is a separate enum for each enclave API.
It's not possible to have a single blanket function that does the
right thing for each one of these types, particularly because of
dependency issues -- the enclave api crates which export these
errors must build in …

remove rpc_enclave_err, fix a bunch of error -> rpc conversions

---

transaction/core/README.md

The `CryptoNote Whitepaper` has moved, so has the `CryptoNote One Time Addresses` but I can't find its new location
Soundtrack of this PR: [Ivy Lab - Stacked](https://www.youtube.com/watch?v=XOD4WFhTrSg)
Reading docs and found an out of date link
Update whitepaper link.
- Find location of the `CryptoNote One Time Addresses`

Update link in `transaction/core/README.md`

---

fog/test-client/src/bin/main.rs
fog/test-client/src/config.rs

this allows more control over what happens when a transaction
hangs and the test client gets blocked, in the continuous mode

add another option to test client config

---

fog/sample-paykit/src/cached_tx_data/mod.rs

this divides key image requests with more than 100 key images into
several requests, to avoid hitting any grpc maximums etc.

make the fog sample paykit avoid making massive requests for key image checks

---

crypto/digestible/README.md
crypto/digestible/derive/README.md
crypto/digestible/derive/src/lib.rs
crypto/digestible/derive/test/tests/schema_evolution.rs
crypto/digestible/src/lib.rs

We'd like to support adding integer fields to existing `Digestible` structs such that existing hashes are not affected when the new fields are set to zero. This plays nicely with structs that are also backed by Protobuf, since integer fields default to zero when not explicitly set to something else.
* Add support for a `#[digestible(omit_on_zero)]` directive that can be applied to struct fields, resulting in the field not being digested if it is set to zero.

Allow configurating Digestible to omit fields equal to zero

---

fog/api/proto/ingest.proto
fog/ingest/server/src/controller.rs
fog/ingest/server/src/ingest_service.rs
fog/recovery_db_iface/src/lib.rs
fog/sql_recovery_db/src/lib.rs
fog/view/server/src/db_fetcher.rs

This PR enables us to filter ingress keys based on their expiry status. A key is considered expired if its pubkey_expiry is less than or equal to the key's last scanned block. This prepares for the Fog Overseer implementation (see [sam/fog-overseer](https://github.com/mobilecoinfoundation/mobilecoin/tree/sam/fog-overseer/fog)), which requires us to find any keys that are unexpired, meaning they still have work to do. 
Note that I chose to create a new term "unexpired" to signify the state in which a key's pubkey_expiry is less than or equal to last scanned block because we can't use any existing terms to signify this state. For example, we can't just use "retired" to signify this state because a key can be marked as retired but still have work to do on any blocks (IFF its pubkey_expiry is …

Add ingress key DB filter that enables selecting only unexpired keys

---

ledger/sync/src/ledger_sync/ledger_sync_service.rs
ledger/sync/src/ledger_sync/mod.rs
ledger/sync/src/lib.rs

The `identify_safe_blocks` function contains useful logic that can be re-used by alternative implementations of ledger syncing and I'd like to make that possible.
* Making `identify_safe_blocks` public.

expose identify_safe_blocks since it is useful for full-service

---

Cargo.lock
util/uri/src/lib.rs
util/uri/src/uri.rs

Fixes #828: `--peer` accepts `mcp://` URLs.

Fix peer flag accepting mcp URLs

---

connection/test-utils/src/blockchain.rs
consensus/enclave/api/src/fee_map.rs
consensus/enclave/api/src/lib.rs
consensus/enclave/api/src/messages.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/src/lib.rs
consensus/enclave/mock/src/mock_consensus_enclave.rs
consensus/enclave/src/lib.rs
consensus/service/src/config.rs
consensus/service/src/consensus_service.rs
fog/distribution/src/main.rs
fog/sample-paykit/src/client.rs
fog/test-client/src/test_client.rs
mobilecoind/src/payments.rs
mobilecoind/src/service.rs
transaction/core/src/constants.rs
transaction/core/src/lib.rs
transaction/core/src/token.rs
transaction/core/src/tx.rs
transaction/core/src/validation/validate.rs
transaction/core/test-utils/src/lib.rs
transaction/std/src/memo_builder/rth_memo_builder.rs
transaction/std/src/transaction_builder.rs

The `MINIMUM_FEE` constant we use everywhere does not make sense in a multi-token world. This PR proposes to deprecate it in favor of a new trait, `Token`, that will hold useful information about arbitrary tokens.
Right now this is limited to a `TokenId` and the minimum fee.
In the future this can be extended to support human-readable names, an `Amount<T: Token>` trait, a `TransactionBuilder<T: Token>` that contains token-specific logic, etc.
* Moving `TokenId` into a new `token.rs` file
* Introducing the `Token` trait
* Replacing `MINIMUM_FEE` with `Mob::MINIMUM_FEE`.

Introduce new `Token` trait and use it for specify constants relating to a given token.

---

Cargo.lock
consensus/enclave/trusted/Cargo.lock
fog/ingest/enclave/trusted/Cargo.lock
fog/ledger/enclave/trusted/Cargo.lock
fog/view/enclave/trusted/Cargo.lock

Goal is to try to get the same versions for all this stuff in and out of the enclave, before branching for release
this PR was made by doing `cargo update -p aead` in each workspace, then building and confirming it still works

update aead to 0.4.3 everywhere

---

account-keys/src/account_keys.rs
android-bindings/src/bindings.rs

To process TxOuts sent to an account's change subaddress, we need to enable the android-sdk to retrieve the account's change subaddress keys
* AccountKey functions to compute the change subaddress view and spend keys
* Android binding updates to retrieve the change subaddress view and spend keys

Updating android bindings and account key for subaddress fix

---

fog/overseer/server/src/worker.rs

Fixes CI failure introduced by PR #1298.

Make ingress key filter a reference

---

Cargo.lock
connection/src/traits.rs
connection/test-utils/Cargo.toml
connection/test-utils/src/blockchain.rs
consensus/api/proto/consensus_common.proto
consensus/enclave/api/src/fee_map.rs
consensus/service/src/api/blockchain_api_service.rs
consensus/service/src/config.rs
consensus/service/src/consensus_service.rs
fog/distribution/src/main.rs
fog/sample-paykit/src/client.rs
mobilecoind/src/payments.rs
slam/src/main.rs
transaction/core/src/token.rs

* Now that we support a mapping of token -> minimum fee, we need to make that information available to clients.
* Update `LastBlockInfoResponse` to contain a new field, `minimum_fees`, that holds the map of token id -> minimum fee.
* Rename the existing `minimum_fee` field to `mob_minimum_fee`. This is a backwards-compatible change (the tag number remains the same), but it makes it easy to catch client code that uses the now-deprecated field
* Update client code to use the new field
* Minor cleanups

Update LastBlockInfoResponse to include the new fee map

---

Cargo.lock
ledger/distribution/Cargo.toml
ledger/distribution/src/main.rs

Reverts mobilecoinfoundation/mobilecoin#1038, due to errors.
The `ledger-distribution` binary panics with `Could not read ledger DB: MetadataStore(Lmdb(ReadersFull))`, suggesting the uploads are not happening quickly enough.

Revert "Bump rusoto_s3 from 0.42.0 to 0.47.0"

---

util/build/enclave/src/lib.rs

Minor enhancement for build output.
`cargo build` output now looks like:
```
warning: Signed enclave consensus-enclave not provided, trying to sign it...
warning: Unsigned enclave consensus-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of consensus-enclave
warning: Signed enclave view-enclave not provided, trying to sign it...
warning: Unsigned enclave view-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of view-enclave
warning: Signed enclave ingest-enclave not provided, trying to sign it...
warning: Unsigned enclave ingest-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of …
```

Include enclave name in generated warnings

---

fog/overseer/server/src/bin/main.rs
fog/overseer/server/src/error.rs
fog/overseer/server/src/worker.rs

There are some scenarios that Fog Overseer may encounter in which we want human operators to be alerted. MobileCoin uses [Sentry](https://sentry.io) to handle alerting, so we need to implement Sentry for Fog Overseer. 
The two scenarios for which we'll notify are when there are multiple inactive outstanding keys found, and when there are multiple active nodes found. For the former, we stop overseer and then send the error log (which in turn Sentry transforms into a PagerDuty alert). For the latter, we don't stop overseer and just send the error log.
While this PR implements Sentry logging for the app, we still need to configure alerting via the Sentry UI. 
* Enables the sentry guard in the Fog Overseer binary
* Cleans up logging messages and how errors encapsulate the messaages.
#1416

Enable sentry error logging for Fog Overseer

---

fog/ledger/test_infra/src/lib.rs
ledger/db/src/ledger_trait.rs
ledger/db/src/lib.rs
ledger/db/src/test_utils/mock_ledger.rs

Our blocks keep track of the root hash of membership proofs that were used when validating transactions: https://github.com/mobilecoinfoundation/mobilecoin/blob/master/transaction/core/src/blockchain/block.rs#L45
In a future version we might introduce new transaction types that go into the blockchain that do not involve verifying any proofs of existing input TxOuts, and as such the enclave will not have a root_element to place inside the block (see [form_block](https://github.com/mobilecoinfoundation/mobilecoin/blob/master/consensus/enclave/impl/src/lib.rs#L471-L473)).
For such cases, where the block only contains new transactions, we still want to provide a root element that captures the state of the ledger at the time the block was formed. This PRs adds a new method to `LedgerDB` that …

add get_root_tx_out_membership_element

---

consensus/enclave/impl/src/lib.rs

With the introduction of new token types, we expect to add functionality to the consensus enclave that allows minting TxOuts for these token types. The enclave currently contains code to predictably mint new outputs and that is how we handle the aggregated fee output that gets generated for each block.
The code that does it can be generalized so that it is easy to reuse for other future minting purposes.
* Change `mint_aggregate_fee` to a more generic `mint_output`.

Make enclave TxOut minting code reusable

---

.github/dependabot.yml

The motivation for the changes in this PR is to have the `@eng` group auto-assigned by the `dependabot`
< Ticket status, e.g. "fixes #issue number" > 
fixed ticket #1407

Added a new configuration entry to auto assign the @eng group

---

account-keys/src/account_keys.rs
attest/core/src/ias/verify.rs
common/src/responder_id.rs
crypto/digestible/derive/src/lib.rs
crypto/digestible/derive/test/tests/schema_evolution.rs
crypto/digestible/src/lib.rs
fog/report/types/src/lib.rs
mobilecoind/src/monitor_store.rs
transaction/core/src/ring_signature/rct_bulletproofs.rs

In digestible crate, part of the design is to allow that new `optional`
and `repeated` fields can be added to structs corresponding to protobufs,
without changing the hashes of old objects. By making the hash algorithm
similar to protobuf in this regard, we make it easier to evolve the
blockchain without breaking backwards compatibility.
Unfortunately, there are some gaps still in what kinds of schema
evolution digestible allows vs. what protobuf allows. Protobuf allows
that new bytes and string fields can be added to a struct without a
breaking change, but digestible doesn't, because it doesn't currently
omit empty bytes or string fields when omitting them would be allowed.
We didn't think about this when implementing the allow_omit stuff,
because we were focused on containers -- but …

In digestible crate, allow that `string` and `bytes` can be omitted

---

fog/test-client/src/test_client.rs

As described in #1445, we want the continuous run of the test client to submit a consistent number of transactions per day. This makes it easier to analyze transaction volume for "real" network participants rather than those executed on behalf of MobileCoin tests.
* Configures the sleep statement in the continous run's transfer loop to account for how long the previous transfer took. This means that a consistent number of transfers will be executed per day.
Fixes #1445

Make test client submit a consistent number of transfers per day

---

fog/ledger/server/src/config.rs
fog/view/server/src/config.rs

I put this in the PR that we backported to 1.1.3 branch, I think
the ENV configuration is sometimes nicer, and I wouldn't want it
to disappear in 1.2 release.

Make omap_capacity configurable by environment variable

---

consensus/api/proto/consensus_common.proto
consensus/api/src/conversions.rs
transaction/core/src/validation/error.rs
transaction/core/src/validation/validate.rs
transaction/core/test-utils/src/lib.rs

Per James, I actually got the release plan wrong for the RTH stuff.
The idea was supposed to be, update all readers first, in 1.2.0,
and only in the next release may writing memos be allowed.
This means that, transaction validation should enforce for now
that memos do not exist in the chain.
In [MCIP 26](https://github.com/mobilecoinfoundation/mcips/pull/26) we may introduce a mechanism to allow turning on the
memos. That is not yet implemented. We will continue to work on that
but by merging this to master now, we make it possible to branch
for release conceivably, and create clients capable of reading memos, while
we could later make a release that accepts writing memos in the
future.
We can discuss separately if the scope for 1.2.0 should be to
include a `block_version`-aware …

Fixup transaction validation for 1.2.0

---

fog/api/proto/ledger.proto
fog/ledger/enclave/api/src/lib.rs
fog/ledger/enclave/impl/src/lib.rs
fog/ledger/server/src/db_fetcher.rs
fog/ledger/server/src/key_image_service.rs
fog/ledger/server/src/merkle_proof_service.rs
fog/ledger/server/src/server.rs
fog/ledger/test_infra/src/lib.rs
fog/types/src/common.rs
fog/types/src/ledger.rs
fog/types/src/lib.rs
fog/types/src/view.rs
ledger/db/src/ledger_trait.rs

This makes fog-ledger pass `latest_block_version` to clients in
its responses when they do `KeyImage` checks or get merkle proofs.
This will mean that they will get an update on this value when
they do a balance check or before they submit a transaction,
giving them a chance to potentially:
* Pass the `latest_block_version` to the transaction builder, as
envisioned in MCIP https://github.com/mobilecoinfoundation/mcips/pull/26
* Maybe signal the need for an update if in the course of a balance
check we learn that the block version has advanced beyond what
our software was built to support.
This is not a breaking change, this is just the part where fog
communicates the `block_version` which is backwards compatible,
so it is safe to merge at any time.
The non-fog clients can already ask the …

Fog passes `latest_block_version` to clients in its responses

---

Cargo.lock
libmobilecoin/Cargo.toml
libmobilecoin/include/transaction.h
libmobilecoin/libmobilecoin_cbindgen.h
libmobilecoin/src/transaction.rs

Soundtrack of this PR: [Duke Hugh - 2017 Heatwave](https://www.youtube.com/watch?v=-MB4UzSsHmM&list=RD__8L_E9ije0&index=2)
The iOS SDK needs a way to calculate the crc32 checksum from Compressed Commitment data
* New function `mc_tx_out_commitment_crc32` in transaction.rs
* Unit tests for functions in /libmobilecoin

Add function to calculate the `crc32` from Compressed Commitment data

---

connection/src/sync.rs
fog/ingest/client/src/lib.rs
fog/ledger/connection/src/key_image.rs
fog/ledger/connection/src/merkle_proof.rs
fog/ledger/server/src/db_fetcher.rs
fog/load_testing/src/bin/ingest.rs
fog/sql_recovery_db/src/lib.rs
fog/view/connection/src/lib.rs
ledger/sync/src/network_state/polling_network_state.rs
peers/src/threaded_broadcaster_retry.rs

When we have multiple instances of a program that includes retries, there is a risk of having many retries synchronize, creating a kind of thundering herd problem when attempting to recover from transient errors. 
* Add a `.map(delay::jitter)` call to all call sites that create a delay iterator for `retry` calls with a remote connection.

Add jitter to most retry iterators

---

consensus/enclave/api/src/error.rs
crypto/keys/src/ed25519.rs
crypto/keys/src/lib.rs
fog/sig/report/src/ed25519.rs
transaction/core/src/blockchain/block_signature.rs

It is literally just reexporting `signature::Error`

Rename misleading Ed25519SignatureError -> SignatureError

---

consensus/enclave/api/src/error.rs
consensus/enclave/api/src/lib.rs
consensus/enclave/api/src/messages.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/src/lib.rs
consensus/enclave/mock/src/mock_consensus_enclave.rs
consensus/enclave/src/lib.rs
consensus/enclave/trusted/src/lib.rs
consensus/service/src/tx_manager/mod.rs
consensus/service/src/tx_manager/untrusted_interfaces.rs
consensus/service/src/validators.rs

Our blocks contain the [`root_element`](https://github.com/mobilecoinfoundation/mobilecoin/blob/95d2ceff8a3a08704f981f99ef9455185c2c128b/transaction/core/src/blockchain/block.rs#L45) (Root hash of the membership proofs provided by the untrusted). At the moment, when a block is formed using `form_block`, this value is calculated from the proofs-of-membership passed alongside the transactions (see [here](https://github.com/mobilecoinfoundation/mobilecoin/blob/95d2ceff8a3a08704f981f99ef9455185c2c128b/consensus/enclave/impl/src/lib.rs#L463)). This is great when the block contains transactions that are coupled with membership proofs, however we are about to enter a world where a block might only contain minting transactions or configuration change transactions and no regular Txs.
When that …

Include the merkle tree root element in consensus enclave form_block

---

Cargo.lock
Cargo.toml
crypto/multisig/Cargo.toml
crypto/multisig/src/lib.rs

We are going to want some basic M-out-of-N signature primitives for the upcoming new transaction types.
* A new crate, `mc-crypto-multisig`, which contains primitives for a multisig implementation.

Multisig utility crate

---

consensus/service/src/config/mod.rs
consensus/service/src/config/network.rs

As `consensus-service` evolves its configuration gets more complicated. An upcoming PR is going to add a `tokens.yml`/`tokens.json` file for token-specific configuration (such as fees per token). I want to prevent `config.rs` from growing indefinitely as more stuff is added, so I am proposing to split standalone chunks into their own files.
* Split out `NetworkConfig` into its own file.
* No logic/tests changes - only code moving from one place to another.

break out consensus NetworkConfig into its own file

---

util/build/info/build.rs
util/build/info/src/lib.rs

We ran into an issue where `mc-util-build-info` would pick the wrong value for GIT_COMMIT when `mobilecoin` is being included as a submodule in another repository. Since the build script runs inside the crate's directory, `git describe` would grab the commit id of the `mobilecoin` submodule, wheer the expected behavior was that it would grab the commit id of the root repo. 
This PR addresses that with a hack that looks for the top-most git repository and grabs the commit id from there. It also adds `MOBILECOIN_GIT_COMMIT` for getting the commit of the actual `mobilecoin` repository, since that information might come in handy.

provide correct GIT_COMMIT when mobilecoin is a submodule of another repository

---

crypto/keys/src/ed25519.rs
crypto/multisig/src/lib.rs

The new objects in `mc-crypto-multisig` are going to end up inside SCP transactions. As such, they need to implement all the traits requires by [`mc-consensus-scp::Value`](https://github.com/mobilecoinfoundation/mobilecoin/blob/0bbca35d7eba7db7a38ccd6dc1591c70fd3c62d5/consensus/scp/src/core_types.rs#L59).
This PR adds the necessary implementations.

derive the traits necessary for implementing scp Value

---

Cargo.lock
consensus/service/Cargo.toml
consensus/service/src/config/tokens.rs
crypto/multisig/src/lib.rs
transaction/core/src/token.rs

This is a first step in implementing a proof-of-concept minting scheme. It is currently based on https://github.com/mobilecoinfoundation/mobilecoin/pull/1491 (which is still blocked on reviews). It will not get merged to `master` at this point, but instead be the base for a minting feature branch to present a potential approach.
* Adding the option to specify a list of master minter signing keys, which are Ed25519 keys that are hex-encoded DER representation.

Add master minters configuration to TokensConfig

---

.github/dependabot.yml

This should link the PRs with [the milestone](https://github.com/mobilecoinfoundation/mobilecoin/milestone/2), per [docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#milestone)

Tag dependabot PRs with the 'Reduce supply chain attack surface' milestone

---

fog/overseer/server/src/bin/main.rs
fog/overseer/server/src/server.rs

Currently, the fog overseer shuts down soon after being started because the server's `rocket` instance is not kept in scope. This issue was surfaced locally using a local network and on the CD deployment. Fixing this should make overseer run successfully on CD.
Contributes to #1482.
* Keeps the `rocket` instance in scope and calls launch.

Keep Fog Overseer Server alive when started via binary

---

.circleci/config.yml

The run mc-fog-tests job currently takes 40 minutes
This does two things:
* Move fog ingest tests to their own job in circle ci, and make
the fog tests job exclude fog ingest
* Use `--release` when running the fog ingest tests. This is because
I think it will make the integration tests that run little fog
ingest clusters a lot faster, since it will make the ORAM and
all that much faster. Those integration tests probably make more
sense to run in release mode anyways since then it will more
closely resemble what we actually deploy.

try to improve circle ci times by splitting fog ingest to its own job

---

watcher/src/bin/main.rs
watcher/src/watcher.rs

These logs do
indeed exist, but the log level was below that of what the log
shipper was able to pickup. Has been raised to "error"
In the 2021-12-25 mainnet outage, no watcher logs were found indicating trouble syncing attestation signatures. The only indication was that watcher info messages stating it was 1000 blocks behind.
* Proper logging statements to log node having difficult + the underlying cause existed, but the log level was debug and thus was not being shipped. Simple elevation of log level provides these log statements 
* Make the watcher sync nodes independently so they don't get stuck if one node can't sync
* Create Prometheus logging that give per-node sync stats in order to develop an idea of …

Elevate watcher log level for sync errors

---

consensus/enclave/trusted/src/lib.rs
fog/ingest/enclave/trusted/src/lib.rs
fog/ledger/enclave/trusted/src/lib.rs
fog/view/enclave/trusted/src/lib.rs

Flagged in [our TOB audit report](https://github.com/trailofbits/publications/blob/master/reviews/Mobilecoin.pdf) (page 32).
* Consolidate `.or(Err(sgx_status_t::SGX_ERROR_UNEXPECTED))?` statements in the various `ecall_dispatcher` methods, and remove an unnecessary variable.

DRY up enclave dispatch calls.

---

consensus/api/proto/consensus_common.proto
consensus/api/src/conversions.rs
transaction/core/src/validation/error.rs
transaction/core/src/validation/validate.rs

Transaction outputs should be deterministically ordered. A required ordering removes an unneeded "degree of freedom" in the transaction structure, and prevents a possible source of information leakage (e.g. client software that always orders transaction outputs from largest value to smallest value).
* Adds `validate_outputs_are_sorted` to transaction validation.

[MCC-1994] Adds validate_outputs_are_sorted

---

fog/overseer/server/src/service.rs
fog/overseer/server/tests/get_ingest_summaries.rs
fog/overseer/server/tests/inactive_outstanding_key_idle_does_not_have_key.rs
fog/overseer/server/tests/inactive_outstanding_key_idle_has_key.rs
fog/overseer/server/tests/one_active_node.rs
fog/overseer/server/tests/prometheus_produces_metrics.rs
fog/overseer/server/tests/retired_key_not_outstanding_idles_have_different_keys.rs
fog/overseer/server/tests/retired_key_not_outstanding_idles_have_same_key.rs

Previously, Fog Overseer started up in the "enabled" state, which means that it monitors the Fog Ingest cluster for incorrect state. This was an issue because Overseer was started right when Fog Ingest started, and the ingest nodes didn't have time to activate. In this state, where no active nodes exist, Overseer initiated automatic failover, which is not desirable because ingest node was in the process of activating.
* Starts Fog Overseer in the disabled state. The new deployment flow will involve activating Overseer after the Fog Ingest cluster has reached the active state.

Make Fog Overseer disabled on start up

---

watcher/src/bin/main.rs
watcher/src/watcher.rs

Watcher in previous form would update all nodes at once, leading to updates from
all nodes getting stuck if a single node failed or was unreachable. This was determined by the 12-25-2021 FOG mainnet outage. A solution for this suggested that watcher sync each node independently and referenced in [#1296](https://github.com/mobilecoinfoundation/mobilecoin/issues/1296)
- A thread is created for each watcher node so that they can sync independently when launched from mobilecoind. If it's desired the binary should launch separate threads, this can be achieved as well.
- The ability to sync all nodes at once is preserved
- Future commits might consider using an async/futures model to avoid the overhead of OS threads. However this work should probably be coordinated with other async efforts as …

Allow watchers to sync independently

---

.circleci/config.yml
fog/distribution/src/main.rs
fog/sample-paykit/src/client.rs
fog/test-client/src/test_client.rs
tools/fog-local-network/README.md
tools/fog-local-network/fog_local_network.py
tools/local-network/local_network.py

As Chris wrote in the previous PR (#1173): 
This adds fog local network to CI, with fog distro using very few transactions. The point is to get test coverage that ensures that test client is able to spend change outputs.
Fixes #1572 
- Fixes previous issue with Fog Test Client. The local_network.py script used the old network fee of 10,000,000,000. The test client gets the fee from consensus, but when it failed to retrieve the fee it defaulted to the new network fee of 40,000,000.
- This manifested as an incorrect balance because the amount used for the expected balance used the new fee while the actual transaction used the old fee. This occurred because the fee was getting retrieved in two places. I fixed this by reusing the fee from the transaction in the balance check.
- I also had to …

Add Fog Local Network and Test Client to CI

---

api/proto/blockchain.proto
api/proto/external.proto
api/src/convert/block_contents.rs
api/src/convert/mint_config.rs
consensus/enclave/impl/src/lib.rs
fog/ledger/test_infra/src/lib.rs
ledger/db/src/error.rs
ledger/db/src/ledger_trait.rs
ledger/db/src/lib.rs
ledger/db/src/mint_config_store.rs
ledger/db/src/mint_tx_store.rs
ledger/db/src/test_utils/mock_ledger.rs
ledger/migration/src/lib.rs
transaction/core/src/blockchain/block_contents.rs
transaction/core/src/domain_separators.rs
transaction/core/src/mint/config.rs
transaction/core/src/mint/mod.rs
transaction/core/src/mint/validation/config.rs

No need for the `Set` prefix, it's overly verbose and results in weird method names like `get_se_mint_config_txs`.

SetMintConfigTx -> MintConfigTx

---

start-testnet-client.sh

The output binary from that package was renamed from mc-mobilecoind-json
to mobilecoind-json in commit b709b734.

Fix exec call to mobilecoind-json binary in start-testnet-client.sh.

---

consensus/enclave/api/src/lib.rs
consensus/enclave/api/src/messages.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/src/lib.rs
consensus/enclave/mock/src/mock_consensus_enclave.rs
consensus/enclave/src/lib.rs
consensus/enclave/trusted/src/lib.rs
consensus/service/src/tx_manager/mod.rs

The consensus enclave's `form_block` method currently receives the list of encrypted transactions paired with membership proofs in one of its arguments, and uses that to form a new block. As we add more transaction types, the list of arguments will start to grow and require a tedious change across the various enclave crates. I am encountering this in the minting branch, and figured this is a small enough change to bring in immediately which will help keep minting-related PRs shorter.
* Add a new `FormBlockInputs` struct that can easily be extended to add more transaction types that will be fed into the enclave
* Break out a bunch of transaction validation code `form_block` was doing into its own method, so that `form_block` can be easier to read and maintain.

introduce FormBlockInputs and break out some code from form_block into its own method

---

consensus/service/src/byzantine_ledger/mod.rs
consensus/service/src/byzantine_ledger/pending_values.rs
peers/src/consensus_msg.rs

… since is makes it impossible to add transaction types that cant implement it.
I ran into a problem when I extended `ConsensusValue` to include a struct that has a `Vec<>` (can't implement `Copy`). 
* Removing the `Copy` trait derive on `ConsensusValue` and dealing with the aftermath of that (fairly minimal).

remove the Copy trait from ConsensusValue 

---

Cargo.lock
Cargo.toml
util/seeded-ed25519-key-gen/Cargo.toml
util/seeded-ed25519-key-gen/src/main.rs

We want to include some predictable Ed25519 keys in our internal dev deployments, and there's currently no way to do that.
* A little utility that can generate a predictable Ed25519 key.

add a utility for generating predictable Ed25519 private keys

---

util/metrics/src/op_counters.rs

Several situations have arisen where Prometheus counters that track (mostly misbehaving) peers would be very useful, this small PR addresses that need.
* Addition of peer counters
* Addition of helper methods for peer counters
Part of issue #1370

Add Prometheus int counters that track peers

---

Cargo.lock
consensus/scp/Cargo.toml
consensus/scp/src/slot.rs

there was no need for the pretty-assertions dependency
removed the dependency
fixes #1437

removed pretty-assertions dependency from SCP

---

Cargo.lock
consensus/enclave/impl/Cargo.toml
consensus/enclave/impl/src/lib.rs
transaction/core/src/blockchain/block_version.rs
transaction/core/src/mint/validation/common.rs
transaction/core/test-utils/src/lib.rs
transaction/core/test-utils/src/mint.rs

Wanting to have more unit test coverage is pretty self explanatory :)
* Unit tests to exercise the new code flows in `form_block` that deal with `MintTx`s and `MintConfigTx`s.
* Add a unit test for checking that invalid `MintTx`s get rejected. That is blocked by having the active mint configurations fed into the enclave.

form_block unit tests for MintTx/MintConfigTx

---

libmobilecoin/Makefile

Soundtrack of this PR: [Bok Bok - Papaya Lipgloss](https://youtu.be/MsIBb8IhF6Q)
`mobilecoin/libmobilecoin` will make static libraries that return `BadSignature` errors if "compiled with Xcode 13". Adding a check in the Makefile stops the problem early.
* Check that the version of Xcode `xcode-select`  is pointing to is version 12
Output if the user has Xcode 13 selected
```bash
$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer                                                                                                                                                                                                                                              
$ make …
```

Add Xcode 12 Check

---

.circleci/config.yml
Cargo.lock
consensus/enclave/mock/Cargo.toml
consensus/enclave/mock/src/lib.rs
consensus/service/src/api/client_api_service.rs
consensus/service/src/byzantine_ledger/mod.rs

This PR adds a few unit tests  to `mc-consensus-service` to exercise some of the new minting transaction flows.

mc-consensus-service: add unit tests for new minting transaction flows

---

mobilecoind/src/bin/main.rs

by setting `MC_TELEMETRY=0` when jaeger is not running
pulling this out of https://github.com/mobilecoinfoundation/mobilecoin/pull/1696
for ease of review

make a way to disable the mc telemetry stuff

---

fog/sample-paykit/src/cached_tx_data/mod.rs

this should be defaulting to zero, this was missed during the
decrement block versions everywhere project
will cherry-pick this to master after

fix fog-sample-paykit initial block version (release-1.2.0)

---

fog/sample-paykit/src/cached_tx_data/mod.rs

this should be defaulting to zero, this was missed during the
decrement block versions everywhere project

fix fog-sample-paykit initial block version (release-1.2.0) actually

---

consensus/enclave/impl/src/lib.rs
transaction/core/src/validation/mod.rs
transaction/core/src/validation/validate.rs
transaction/std/src/transaction_builder.rs

this also refactors the transaction validation a bit,
so that there is a function which tests all "structural tx out rules",
and then re-uses this function in tests elsewhere, which will help us
going into the future to maintain all this

make the fee output conform to block version rules

---

.circleci/config.yml
connection/src/traits.rs
connection/test-utils/src/blockchain.rs
consensus/api/proto/consensus_common.proto
consensus/service/src/api/blockchain_api_service.rs
consensus/service/src/consensus_service.rs
fog/distribution/src/config.rs
fog/distribution/src/main.rs
fog/distribution/tests/bootstrap.rs
fog/sample-paykit/src/cached_tx_data/mod.rs
fog/sample-paykit/src/client.rs
mobilecoind/src/payments.rs

We realized that there is a chicken and egg problem for many clients around
the block version:
* For mobilecoind and for fog clients, they were getting block version
from their local copy of the ledger, or fog-ledger's copy of the ledger
* However, when we upgrade consensus and increase block version, the
first transaction takes place when the ledger has the old block version
but the consensus config is the new block version.
* There has to be at least one client capable of determining the configured
block version and making a transaction according to those rules.
To fix this, James suggested that we use the `GetLastBlock` call, where
most clients are getting the minimum fees right now. We added a field
on this response that returns the configured block version, so this is
a good source …

Make GetLastBlockInfo return the configured block version, and use it

---

mobilecoind/strategies/drain-accounts.py
mobilecoind/strategies/test_client.py

Adding this because it works around in issue in CD:
Normally we fund fog accounts using fog-distro. However, fog-distro can only work with the bootstrapped tokens, but we did not succeed in building a way to bootstrap the custom token ids without breaking other things. The only way to get custom token ids is to mint them right now, but this happens after bootstrap and fog-distro can't see them.
Instead, we add a mobilecoind script that drains the funds of one account to another. We only have to do this for a few accounts so it doesn't matter if it is slower than slam. The idea is that the second address is fog keys.

add drain-accounts.py python script

---

connection/src/traits.rs
connection/test-utils/src/blockchain.rs
consensus/api/proto/consensus_common.proto
consensus/service/src/api/blockchain_api_service.rs
fog/distribution/src/main.rs
fog/sample-paykit/src/client.rs
mobilecoind/src/payments.rs

This is expected to reduce confusion, because a reader could reasonably
think that the LastBlockInfo.block_version refers to the version of the
last block, and not the current configured version of the network
(cc James)

rename GetLastBlockInfoResponse.block_version -> network_block_version

---

mobilecoind/strategies/drain-accounts.py
mobilecoind/strategies/test_client.py

error in deployment was:
```
+ python3 drain-accounts.py --key-dir ./keys --dest-key-dir ./fog_keys --max-accounts 4 --fee 10 --mobilecoind-host 127.0.0.1 --mobilecoind-port 3229
Namespace(dest_key_dir='./fog_keys', fee=10, key_dir='./keys', max_accounts=4, max_seconds=40, mobilecoind_host='127.0.0.1', mobilecoind_port='3229')
Traceback (most recent call last):
File "drain-accounts.py", line 121, in <module>
for k in sorted(glob.glob(os.path.join(args.key_dir, '*.json')), key=filename_key)
File "drain-accounts.py", line 121, in <listcomp>
for k in sorted(glob.glob(os.path.join(args.key_dir, '*.json')), key=filename_key)
File "/home/jenkins/agent/workspace/mobilecoin-internal_deploy_build/strategies/accounts.py", line 58, in load_key_and_register
with open(keyfile, 'r') as f: …
```

fix python mistakes

---

Cargo.lock
api/proto/blockchain.proto
api/proto/external.proto
api/src/convert/block_contents.rs
api/src/convert/mod.rs
api/src/convert/validated_mint_config.rs
consensus/enclave/impl/src/lib.rs
consensus/enclave/mock/Cargo.toml
consensus/enclave/mock/src/lib.rs
consensus/service/src/byzantine_ledger/mod.rs
consensus/service/src/mint_tx_manager/mod.rs
ledger/db/src/lib.rs
ledger/db/src/mint_config_store.rs
ledger/db/src/mint_tx_store.rs
ledger/migration/src/lib.rs
mint-auditor/Cargo.toml
transaction/core/src/blockchain/block_contents.rs
transaction/core/src/mint/config.rs
transaction/core/src/mint/mod.rs
transaction/core/test-utils/src/lib.rs
transaction/core/test-utils/src/mint.rs

`MintConfigTx`s are validated by checking their signatures against the master minters configured on consensus nodes. We'd like to allow independent auditors to validate those as well, and have a record of which master minter keys were active when a `MintConfigTx` was accepted into the ledger.
The solution proposed here is to store the master minters used to validate a given `MintConfigTx` alongside the `MintConfigTx`.
Down the road we intend on signing the master minters with a key owned by the foundation, and at that point we will store this signature as well.
* Create a new `ValidatedMintConfigTx` struct that holds a `MintConfigTx` and the `SignerSet` that was used to validate its signature.
* Replace `mint_config_txs` in `BlockContents` with `validated_mint_config_txs`. This results in …

Store validation data alongside `MintConfigTx`s in the ledger

---

mint-auditor/src/bin/main.rs
mint-auditor/src/counters.rs
mint-auditor/src/db.rs

We'd like the mint auditor to validate as many mint-related things as possible. This PR adds a check that validates whether `MintTx`s in a block match the currently active `MintConfigTx` for the minted token.
* Add the check mentioned above + a counter to keep track of any discrepancies found.

Make the mint auditor validate MintTxs against MintConfigTxs

---

consensus/enclave/impl/src/lib.rs
transaction/core/src/amount/mod.rs
transaction/core/test-utils/src/lib.rs

Prior to this PR, `mint_output` generated the same tx private key for all minted fee outputs. This PR addresses that by adding the `Amount` into what gets hashed to produce the key. It also adds a unit test (that was originally failing and then passed once the fix was applied).
Thank you @garbageslam for flagging this!

Fix a bug in fee output minting and add a test
